### ISSUE TITLE
Search form does not load when Picklist Config has not yet loaded in HPI Context

### ISSUE THREAD

**Issue by aviking** [tsgrp/hpi#1000]
Mostly an issue with portal projects. The getPicklistConfig call in context is not an async call but references Context.currentPicklistConfig() observable which may or may not be defined when the method is called. 

Context.currentPicklistConfig() gets initialized in the success callback of a fetch call in Context.getPicklistServices. Which means nothing should be able to call getPicklistConfig until the fetch call is finished. 

getPicklistConfig is called from formsupport assuming it is not an async call, if this is called before the async fetch is finished the error is thrown.

The fix is to make the getPicklistConfig an async call. When we do that we will need to "bubble" that async call all the way up. We would need to dig into formsupport and add deferreds in all methods that rely on this call to getPicklistConfig.

Talk to @dgrumieaux before starting this one.

**Comment by grahamsinger** [comment]
Might be worth tackling this at the same time: #918.

**Comment by gsteimer** [comment]
@aviking - can you post a GIF and/or screenshots of what's going on with this?

**Comment by ladams13** [comment]
![image](https://cloud.githubusercontent.com/assets/5861266/12956277/d9ead3fa-cfec-11e5-9def-eaef9e83ff98.png)

**Comment by ladams13** [comment]
At this point, Context.currentPicklistConfig() is undefined

**Comment by aviking** [comment]
Closed with HPI Commit: 14308
Code Review: Joe Hof
