### ISSUE TITLE
HBASE - script/tooling for deleting Wizard folders and their documents

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1001]
With the current implementation of the Wizard on HBase, we run into interesting problems in deleting a Page Set Definition. In Alfresco and Documentum we have Share and DA for cleaning up or unlocking Wizard forms but no such tooling when working with HBase. Right now the only primitive solution is to drop the entire HBase table - which works in DEV but won't work for QA and Production environments. I'd like to add an endpoint to RESTWizard2Admin that takes in a Page Set Name (like Simple CR) and deletes the page set. I think we could write this generically for re-use across Documentum and Alfresco.

**Comment by gsteimer** [comment]
@mikeblum - don't we already have that?  `RESTWizard2Admin#deletePageSetDefinition`

**Comment by mikeblum** [comment]
So we do. Do you think we could work this into the Page Set Archiver? That way we can just have deletePageSet and pass in the name `Simple CR`

**Comment by gsteimer** [comment]
Maybe?  But why not just run this through the AW admin?

Perhaps what we really need is a "force" option that will run cancel checkout code as admin if there are any checked out objects...

**Comment by gsteimer** [comment]
Closing this one - per @aviking it's possible to use the AW Admin as normal to delete a Page Set Def.  If locked files are a problem, you can configure an admin trac in HPI to give admins the ability to release locks.
