### ISSUE TITLE
Stage Config should not duplicate Trac Name

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1002]
Since the stage admin was built before the Trac Config existed, it made sense to have the Config Label field here:

![image](https://cloud.githubusercontent.com/assets/1377228/12956783/4f126740-cfef-11e5-8068-52274eae7f9a.png)

This controls the Trac label in the stage here:

![image](https://cloud.githubusercontent.com/assets/1377228/12956794/63eff984-cfef-11e5-9b7e-76093a778dcf.png)

However, now that we can configure tracs in the admin, the Config Label in stage is no longer necessary unless we need to override the trac name.  We should:

- [x] Update the Stage Info module - if the Config Label is blank, use the Trac Label.  If it has a value, then use that value. 
  - Doing it this way allows clients more flexibility when using one search config across multiple tracs
- [x] Add help text to the Config Label reflecting the above

**Comment by camrooks** [comment]
FIX: Updated the Stage Info module - if the Config Label is blank, use the Trac Label. If it has a value, then use that value.  Also added localized help text to the Config Label and updated the unit test accordingly

Revision: 15633

CRd by Graham
