### ISSUE TITLE
Complete Wizard Approval Route - Admin updates not saving

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#1003]
The new configurations available in HPI admin with the Complete Wizard Approval Route action don't seem to be saving properly.  Here's what see on edge2:

![aw-admin-save-fail](https://cloud.githubusercontent.com/assets/1377228/12958669/6b2ba5f0-cff8-11e5-8cd5-fb4658c81803.gif)

Here's the signoff screen:

![image](https://cloud.githubusercontent.com/assets/1377228/12958704/9ed82a4a-cff8-11e5-91c2-1fdff859040f.png)

Things to look into:
- The approval action doesn't show the username and password (seems obvious if the config didn't save)
- The Submit button is active.  Seems like it should be disabled until I at least choose either "approve" or "reject"
- If I do select Approve and try to submit, the form does nothing.  No request is sent to OC.

@nwoodbine @dgrumieaux

**Comment by nwoodbine** [comment]
Fixed in HPI rev 14331

**Comment by nwoodbine** [comment]
Fix update in HPI rev 14336
