### ISSUE TITLE
Document Link Resolving in Bulk Upload Config Not able to be turned "off"

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#1008]
In contextless bulk upload, if you enable document link resolving, then turn the slider to off:

![screenshot](https://cloud.githubusercontent.com/assets/547941/13013636/1f986416-d165-11e5-9f21-cc285607ac51.gif)

The document links continue to go to the trac that was previously selected. There is no way to turn the feature "off".

**Comment by grahamsinger** [comment]
@nwoodbine Seems like you can close this from rev 14319.

**Comment by nwoodbine** [comment]
Closed, HPI revision 14319
