### ISSUE TITLE
Cannot Checkin an Approved Controlled Doc

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#1012]
When attempting to checkin a checkin new version of Approved controlled document, the following errors occur upon attempting to checkin:

![image](https://cloud.githubusercontent.com/assets/1377228/13085533/56ab04bc-d4a4-11e5-8b7b-87da47a431fb.png)

Detail for the last error:
![image](https://cloud.githubusercontent.com/assets/1377228/13085560/6ed917f4-d4a4-11e5-8278-0b79d7c570a9.png)

From looking at the OC error, it seems that something is not correct with the document numbering:
```
11:53:04,841 ERROR [com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice] [ajp-apr-8009-exec-8] Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: checkin
org.alfresco.service.cmr.model.FileExistsException: Existing file or folder TSG-133-1_cbb8e2e5-3bef-480e-8c1e-fad8fcf84150.0 already exists
	at org.alfresco.repo.model.filefolder.FileFolderServiceImpl.moveOrCopy(FileFolderServiceImpl.java:1127)
	at org.alfresco.repo.model.filefolder.FileFolderServiceImpl.copy(FileFolderServiceImpl.java:974)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Note - the other 500 errors in there will be handled by a separate issue

**Comment by ZachGerth** [comment]
Fixed with OC Revision # 13856.
