### ISSUE TITLE
Check In, Check Out and Cancel Check Out actions not working in List View

### ISSUE THREAD

**Issue by RudraVishweshwar** [tsgrp/HPI#1014]
HPI freezes when you configure check in, check out and cancel check out in List View for the Search configs. 

The error is popping up in action.js in line 183.

![listview3](https://cloud.githubusercontent.com/assets/14186904/13116277/e7af6216-d560-11e5-8ccf-bfd52cdc9956.gif)

**Comment by gsteimer** [comment]
We should check grid view as well...

**Comment by gsteimer** [comment]
De-prioritizing since grid and list view are being overhauled

**Comment by gsteimer** [comment]
Closing since we've redesigned grid view and dropped list view in HPI 2.6.
