### ISSUE TITLE
Icons for Header Links and Actions

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1016]
For usability purposes, especially non-native English speaking users would be aided by utilizing icons associated with the header links.

For header actions, this will be as easy as utilizing the existing glyphicon configured icon for the action. For other links, we will need to revamp the application config to allow the selection of an icon for that link (dashboard, collections, search, etc).

Considerations:
- intelligent defaults
- presentation (does the icon look associated with the corresponding link?)
- upgrading configs to work appropriately
- synchronizing with existing icons (for instance the magnifying glass next to Search text)
- core question: should icons always be on? or should there be a config to turn them on/off? If so, what should that default to? @gsteimer - thoughts?

**Comment by gsteimer** [comment]
@dgrumieaux we can talk through it more once you figure out the admin design, but my initial thought is that it should default to no icon, since old HPI implementations aren't going to have an icon configured....

**Comment by dgrumieaux** [comment]
@gsteimer makes sense to me.

**Comment by ZachGerth** [comment]
Implemented with HPI Revision #14498. Default is for icons to be disabled, and if none are configured, none are displayed.
