### ISSUE TITLE
OTC - Adding Types Doesn't Maintain Filter

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/hpi#1018]
If were going to hang on to the text from the previous add, we need to run the filter. Otherwise we need to clear out the text.
![otcaddtype](https://cloud.githubusercontent.com/assets/8796489/13226433/02994430-d957-11e5-9d4d-4dfd23f57e3e.gif)

**Comment by gsteimer** [comment]
Also - when adding a type, the box should not disappear (this was the original design).  Keeping the box up makes it much easier to add more than one type quickly.

**Comment by RudraVishweshwar** [comment]
fixed with revision #14384. 

CR-GS
