### ISSUE TITLE
Value in full text search box is not recognized

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#1019]
Found during HPI weekly STS run - if you only enter text into the quick search box, the search does not run.  It looks like it thinks that the user hasn't entered any parameters.  See the screencam below:

![fts-no-run](https://cloud.githubusercontent.com/assets/1377228/13255415/b7071c94-da0b-11e5-8e23-66d4243a1fbd.gif)

I tried both clicking the search button as well as hitting [Enter] - both do the same thing.  Seen on edge1 and edge2.

**Comment by gsteimer** [comment]
Quick update - it looks like the text entered isn't being registered at all.  See below - if I search on some text that should return no results, it's returning all documents that have `TSG` in the doc number:

![image](https://cloud.githubusercontent.com/assets/1377228/13255606/79715664-da0c-11e5-8e84-4560e9410b2b.png)

**Comment by ZachGerth** [comment]
Fixed with Revision # 14388. CR - nwoodbine
