### ISSUE TITLE
Back Button after editing an ActiveWizard form creates a branched version in Documentum

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1021]
If a user clicks the "back" button in their browser after creating or editing a wizard form, it will open the previous version for editing. When the user finishes the form, it creates an:
a) whole new form or b) a branched version,

2 ways to reproduce:

## Way 1

1. Create a new form.
1. Finish the Form.
1. Notice the form on the stage displays 0.1 as the version.
1. Click the 'back' button
1. Somehow the form is 'reopened' for editing with the previous answers
1. When this is saved, notice how there are now two different forms that have been created

I would expect that the back button would not take the user back to create a new form. Workaround would be to just skip the fact that they were on the "Create" page and take them to the place that they were previously at (like the stage, or search, or wherever they were).

## Way 2

1. Edit an existing form.
1. Change an answer to one of the questions.
1. Finish the Form. Notice how the stage shows the correct objectId for the CURRENT version
1. Click the 'Back' button. Notice how the Wizard is "editing" the previous version with the old objectId in the URL.
1. Finish the form again. There is now a "branched" version of the form.

I would expect that the back button again would not take the user back to edit that form, but instead skip back to where they were prior to this happening.

![vers](https://cloud.githubusercontent.com/assets/4850976/13265162/326bf14a-da37-11e5-8f1f-96eb9a267436.gif)

@dgrumieaux @mikeblum any thoughts? This is what is happening at a current client.

**Comment by mikeblum** [comment]
Creating a new form leads to the case of a brand new form being created when a user hits the back button.

http://edge1.tsgrp.com/hpi/Stage/wizard/09000002800111ef%2Bcurrent%7C09000002800111ef%2Bcurrent

User clicks the back button:

![image](https://cloud.githubusercontent.com/assets/3905463/13363211/db88ba12-dc8d-11e5-860c-4fe55e692bfd.png)

**Comment by alieblich** [comment]
fixed with hpi rev 14423 - When forms are loaded, check and make sure that the current version of the form is loaded and if not then allow user to be redirected to the current version
