### ISSUE TITLE
Form Admin - Don't hide attribute list immediately after adding an attribute to a form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#1022]
Similar to #1018 - it's super annoying that when editing a form, the attributes box disappears every time you add one to a form.  See screencam below:

![attr-form-add](https://cloud.githubusercontent.com/assets/1377228/13268601/0edcc422-da49-11e5-8608-07b5b71ee88b.gif)

The original design had this box staying active until the user either clicked the X or somewhere else on the page.  Can we add this back in?  The current functionality is really annoying when you need to add 10 properties to a form.

**Comment by RudraVishweshwar** [comment]
Fixed with revision #14403. 

CR-GS
