### ISSUE TITLE
Wizard form PDF generated with HTML characters on a WYSIWYG

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#1023]
Form:
![2016-02-24 12_01_55-hpi](https://cloud.githubusercontent.com/assets/4850976/13295475/aa9ef4a2-daee-11e5-9049-716888675a67.png)

PDF Generated:
![2016-02-24 12_03_08-hpi](https://cloud.githubusercontent.com/assets/4850976/13295481/aff03808-daee-11e5-887c-3a452cb5a718.png)

**Comment by mikeblum** [comment]
r13937 | mblum | 2016-02-25 13:38:34 -0600 (Thu, 25 Feb 2016) | 1 line

WIZARD + WYSWIG - we now refrain from re-escaping already escaped HTML from a WYSIWIG question. refactored the question types to constants and using StringUtils for null safety. CR ballen. Closing https://github.com/tsgrp/hpi/issues/1023
