### ISSUE TITLE
Start Workflow Action should not use /allUsers endpoint

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1024]
The Start Workflow action uses the `/allUsers` OC endpoint to populate the available users for workflow:

```Javascript
$.get(app.serviceUrlRoot + "/users/allUsers?", function(users) {
                _.each(users, function(user) {
                    self.allUsers.push({
                        id: user.loginName,
                        name: user.displayName
                    });
                });
            });
```

The `/allUsers` endpoint is very slow and I'd like to remove it completely from OC.  The problem is that the method contract says to return all users in the system as a UserResult along with *all of the user's groups* populated.  This is extremely slow for all but the smallest client environments.

Here's what we need to do:

- [ ] Update the Start Workflow action admin - ask the user to specify a group for approvers for each configured workflow template
- [ ] Update the javascript code to use the `IUser#searchAuthorities` endpoint.  The criteria should say to to a user search on the admin defined group, returning users in sub-groups
- [ ] Remove the `IUser#allUsers` method and all references to it
- [ ] Remove the `RestEndpointConstants.USERS_ALL_USERS` constant in both HPI and OC

**Comment by gsteimer** [comment]
Note - even with the current "get all the users" design in the HPI code, we do not need to use the `/allUsers` endpoint.  The code in `delegateWorkflowTask.js` does the same thing, but uses the more modern `/authorities/search` endpoint.

As a first stopgap, we could update the Start Worfklow action to use the authority search method to get the available users.

From talking to @cmlewis we may not want this to be an admin defined group in the admin.  Instead, her client may end up building functionality where the available users are defined by the workflow template chosen (not by the action itself).

If someone gets to working on this issue before that client project, it would be good to just simply stop using the (horribly slow, especially on Documentum) `/allUsers` endpoint.

**Comment by dgrumieaux** [comment]
I believe delegate searches only for users in the wizard_contributors group.

**Comment by gsteimer** [comment]
@dgrumieaux - you're thinking of the Delegate *Wizard* Worfklow Task action.  The generic one (used in simple workflow) searches for users using the `/allUsers` endpoint.

**Comment by dgrumieaux** [comment]
Whoops, makes sense.

**Comment by RudraVishweshwar** [comment]
Fixed with rev no. 14438.
 
CR-GS
