### ISSUE TITLE
Remove usage of /allGroups endpoint

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1031]
Similar to #1024, we should discontinue usage of the `/allGroups` endpoint in HPI

**Comment by RudraVishweshwar** [comment]
Fixed with revision no. 14445.

CR-AK

**Comment by grahamsinger** [comment]
Doesn't work on edge2 @RudraVishweshwar

**Comment by grahamsinger** [comment]
Typeaheads don't populate.

**Comment by RudraVishweshwar** [comment]
Fixed with revision no. 14468. 

CR-AK
