### ISSUE TITLE
AW Workflow Canceled Email - Document list not displaying properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1033]
When you route a wizard form with attached workflow documents for approval and then cancel the workflow, the email looks like this:

![image](https://cloud.githubusercontent.com/assets/1377228/13506246/d5afd526-e142-11e5-9376-7036b87bc5ca.png)

Notice that the sections where it lists the documents aren't getting populated properly.  As an example, here's what the rejected email looks like:

![image](https://cloud.githubusercontent.com/assets/1377228/13506273/ff067e66-e142-11e5-88aa-a24eef47b419.png)

In my above example, I only have one document attached.  When fixing this issue, be sure to test no documents attached as well as more than one.

**Comment by aviking** [comment]
Fixed with OC Commit: 14349
Code Review: Ben A.
