### ISSUE TITLE
Full-Text Search Doesn't Trigger on Login from URL

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1038]
Upon logging in to HPI from a URL with only a full-text search, the search does not automatically trigger; the form is correctly populated with the full-text search value, but it does not happen until the user selects search. If other attributes are selected, the search still automatically triggers, and correctly uses the full-text search value.

Steps to reproduce on edge:
Perform a search only using the full-text search box.
Bookmark the search results page.
Logout of HPI.
Use the bookmark to navigate back to the search results page.
Login.

**Comment by nquillin91** [comment]
When going to a bookmark rerouted through the login functionality. The function self.setAdvSearchParams in attributesearch.js was not properly checking for the full-text search box (paramType="allproperties") when looping through the query.searchParameters. Resulting in query.paramsPopulated being undefined and causing the IF statement to fail in tableview.js (afterRender()) which results in no results being shown.

**Comment by ZachGerth** [comment]
Now, no search seems to automatically take place on logging in. The parameters appear to be correctly populated. This is on edge2.

**Comment by renesaladrigas** [comment]
Again, this seems to not be an issue anymore in any of our edge instances, so I will close this issue.

Below are two screencams proving that full text search (only) and full text search with other attributes work properly following Zach's initial "steps to reproduce"

FTS only
![ftstriggeringfromlogin2](https://cloud.githubusercontent.com/assets/14186921/19002093/10d3367a-8710-11e6-90d5-71ff53540f21.gif)

FTS + attrs
![ftstriggeringfromlogin](https://cloud.githubusercontent.com/assets/14186921/19002094/10d85ae2-8710-11e6-9fa4-e4d9c5bce267.gif)
