### ISSUE TITLE
Add on hover help text for form support controls

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1039]
Add an optional (?) label that shows up next to field names, and that when hovered over, shows configurable text.

- Need to consider other (?) controls (thinking of date search)
- Consider how to render rich HTML if configured in the Admin (nice to have)

See #1036.

**Comment by ZachGerth** [comment]
Implemented with HPI revision # 14557. To differentiate from controls such as date search's (!), we use a (?) icon, to indicate "help" rather than "info".
