### ISSUE TITLE
Execute Saved Search via REST endpoint

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1041]
Inputs:

- user login name
- saved search name

Outputs:

- Excel Saved Search that contains results run from the specified user's saved search.

Error cases:

- user does not exist: Throw an exception saying user does not exist.
- user's user prefs do not exist: Throw an exception saying user's user prefs do not exist (user does not have any saved searches)
- user's saved search does not exist: Throw an exception saying user does not have a saved search by that name.

TEST CASES:

- above error cases
- special characters in saved search

Should most likely utilize executeWithAttachment action

**Comment by ZachGerth** [comment]
Implemented with OpenContent Revision #14068.
