### ISSUE TITLE
GridView and List View - saying 0 results returned and pagination broken

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1042]
On edge 2 when I search for all Case Documents in the Incident trac, I see this in table view:

26 results:

![image](https://cloud.githubusercontent.com/assets/1377228/13791688/4e938a1e-eabc-11e5-8691-d8adda4f5677.png)

However, when I search in grid view or list view, the results return correctly, but the "search returned" module shows 0 results, and only one page (even when 10 per page is selected) is visible:

![image](https://cloud.githubusercontent.com/assets/1377228/13791728/7e4352c6-eabc-11e5-8ce3-1713531a4029.png)

![image](https://cloud.githubusercontent.com/assets/1377228/13791738/873a1bda-eabc-11e5-8b15-07add267dddc.png)

Interestingly, if I search with table view first, and then switch to grid view, it works fine:

![image](https://cloud.githubusercontent.com/assets/1377228/13791754/9ad8d424-eabc-11e5-94e1-f0eef8813378.png)

**Comment by aviking** [comment]
Fixed with Commit: 14823
CR: Dan G.
