### ISSUE TITLE
Approval email from Alfresco Wizard Mentions the wrong version number in the email that is sent

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1043]
The email that is sent is pulling the "objectName" of the document at the time the email is sent. It would appear we first send the email, then promote the document to approved, therefore, the Alfresco controlled document mechanism of us putting the "-1.1" at the end of the object name is causing confusion from some QA folks on what is really being approved.

Option 1: Switch the timing to first promote and send the email after the promote happens. There may be more involved that just switching the order though...

Option 2: Switch the FTL template to use the docNumber rather than the objectName, so that we don't even bother to show the version in the email since Documentum doesn't show this and it isn't key info that needs to be in the email.

![image](https://cloud.githubusercontent.com/assets/4850976/13851681/0ce847c2-ec2d-11e5-8c68-a0026b6a915d.png)

**Comment by dgrumieaux** [comment]
I think both options make sense to do. The easiest would be Option 2, and is not a bad fix.

**Comment by aviking** [comment]
Fixed with OC Commit: 14349
Code Review: Ben A.
