### ISSUE TITLE
Form Config - Clean up Options View

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1045]
See the screenshots below - this view needs to be cleaned up:

![image](https://cloud.githubusercontent.com/assets/1377228/13924236/8bb7ce02-ef51-11e5-8fe9-50aa4ccb59db.png)

![image](https://cloud.githubusercontent.com/assets/1377228/13924248/92790fd0-ef51-11e5-9afc-f65c9b8e7409.png)

![image](https://cloud.githubusercontent.com/assets/1377228/13924252/97150044-ef51-11e5-8159-60a29cf56198.png)

We mainly need to clean up the scrollbars, especially the horizontal scrollbar that only shows up when you hover over long help text.  When fixing this, note that the options view is different depending on the type of control.

**Comment by joehof** [comment]
Fixed we HPI revision 14826.
