### ISSUE TITLE
Search and Create Folder - Firefox issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1047]
STS test scripts found some issues with Firefox:

*All Search views not working*
![ff-search-issues](https://cloud.githubusercontent.com/assets/1377228/13958934/fab6ce38-f01f-11e5-8270-455612c3dadf.gif)

The error in the console is:
![image](https://cloud.githubusercontent.com/assets/1377228/13958957/0dd223be-f020-11e5-9c63-f25cc2679d0d.png)
![image](https://cloud.githubusercontent.com/assets/1377228/13958968/1d78d984-f020-11e5-936d-5969074f7929.png)

*Create Folder action not displaying forms*
![create-folder-ff-issues](https://cloud.githubusercontent.com/assets/1377228/13959019/46a99da2-f020-11e5-9313-88012da213b4.gif)

The error in the console is the exact same as the above issue

**Comment by ZachGerth** [comment]
Fixed with Revision # 14577. Issue was the way Firefox handles getting values from events; refactored so we stopped getting the value from the event at all.
