### ISSUE TITLE
Default doesn't display for Picklists with repeating control

### ISSUE THREAD

**Issue by ladams13** [tsgrp/HPI#1048]
Currently when a picklist is configured to be Autocomplete and repeating in the form, and a default value is set, it does not display the default option in search (see screen shots below)

Form Config (status is AutoComplete control and repeating is checked):
![image](https://cloud.githubusercontent.com/assets/5861266/13962354/89fe6e1c-f02e-11e5-8de5-9d18379a8651.png)

Status Picklist with default selected:
![image](https://cloud.githubusercontent.com/assets/5861266/13962377/a52d1a58-f02e-11e5-829e-670db6fd4be6.png)

Search Field Status does not display default:
![image](https://cloud.githubusercontent.com/assets/5861266/13962413/da7560ee-f02e-11e5-8795-52884ab07386.png)

I can select multiple values and search successfully on them.  There don't appear to be any HPI errors trying to display the default and failing.

**Comment by gsteimer** [comment]
@ladams13 - so is this really two items?

- [ ] Make default work properly on repeating controls (with the current admin radio button for default)
- [ ] Change the admin to make the default setting a checkbox
  - [ ] Process repeating controls to provide for multiple defaults
  - [ ] Handle single controls with more than one default (probably just select the first?)

Please reply if your project plans on doing all of the above, or just a portion.

**Comment by ladams13** [comment]
I created a second item (https://github.com/tsgrp/HPI/issues/1048) - currently labeled as enhancement, but we can change to issue if you see fit, for noting the default setting to a checkbox instead.

We have a status call with the client this afternoon, I will note after we confirm with them if we are completing all or just a portion.

**Comment by renesaladrigas** [comment]
Enhancement completed.  HPI supports multiple default item selections and will display these for repeating attributes in forms.

Closed with HPI revision - 14901

CR - Natalia Woodbine
