### ISSUE TITLE
Can't select multiple default values in Picklist

### ISSUE THREAD

**Issue by ladams13** [tsgrp/HPI#1049]
Due to the default value selector in Picklist Admin being a radio button, an administrator is unable to select multiple defaults (which could be desired if the picklist is repeating on the search page).

For instance, our client will want Approved and Effective status to selected by default.

**Comment by renesaladrigas** [comment]
Enhancement completed. HPI supports multiple default item selections and will display these for repeating attributes in forms.

Closed with HPI revision - 14901

CR - Natalia Woodbine
