### ISSUE TITLE
Application Config Issues with Groups for HPI Administrators

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1050]
There are some issues with the app config section where groups are selected for HPI administrators:

- Alfresco
  - [ ] It looks like all the groups are returned, but the code is incorrectly keying off of the group description vs. the group name.  It incorrectly lists *HPI Administrators* twice and if I save the pretty name version, the group description is incorrectly saved to the JSON, causing the admin button to disappear.
- Documentum
  - [ ] On edge1, groups aren't even returned properly.

![admin-groups-fail](https://cloud.githubusercontent.com/assets/1377228/13966815/3b62ffca-f042-11e5-9fd3-68e144c13d8c.gif)

@dgrumieaux @RudraVishweshwar

**Comment by RudraVishweshwar** [comment]
Alfresco - Fixed with revision no. 14467 in HPI
DCTM - Fixed with revision no. 14117 in OC. 
Groups now load correctly for both.

CR- GS
