### ISSUE TITLE
Session Expiration control in HPI

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1053]
Up to this point, we have simply assumed that if the OC ticket is valid, the user's session is also valid.  In other words, it's up to the back end repository to say when a user session has timed out.  For some clients, we would like to override this behavior in HPI.  Here's what we would need to do:

- [ ] Admin Configuration in App Config - number of minutes of inactivity before timing out a user.
  - No value here would mean "let the repository determine session timeout" and would cause HPI to behave like it does today.
- [ ] If the setting above is non null and `> 0`, then:
  - [ ] When setting the session cookie, set it to expire in X minutes, as determined by the admin config
  - [ ] Every time the user does something in HPI, reset the cookie expiration date to X minutes from that point in time
    - How do we know when a user does something in HPI?  We need a good common place to put this code (don't just put it in 1,000 places).  Can we do something whenever OC is called?  Or when the code goes through a router?  Something else?

Thoughts?

**Comment by dgrumieaux** [comment]
http://stackoverflow.com/a/20014416

**Comment by aviking** [comment]
Fixed with Commit: 14821
CR: Dan G.
