### ISSUE TITLE
Saved Search Urls Cannot be Used to Execute Searches

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1058]
Expected behavior is that a url grabbed from a Saved Search can be pasted at any time to execute the search. Currently HPI just hangs.

**Comment by gsteimer** [comment]
@nwoodbine - I just tried this on edge2 and it worked fine.  Does it have something to do with facets?  The trac I was using did not have facetes.

[Here's my saved search URL.](http://edge2.tsgrp.com/hpi/search/controlleddocs/Quality%20Document/_id=UserPreferences.gsteimer.savedSearches_2.searchParams_0&paramValue%5B%5D=&paramName=aw_status&paramType=facet/_id=UserPreferences.gsteimer.savedSearches_2.searchParams_1&paramValue%5B%5D=&paramName=modifier&paramType=facet/_id=UserPreferences.gsteimer.savedSearches_2.searchParams_2&paramValue=TSG&paramName=documentNumber&paramType=property/_id=UserPreferences.gsteimer.savedSearches_2.searchParams_3&paramValue=Draft&paramName=aw_status&operator=OPERATOR_EQUALS&paramType=property/paramName=Quality+Document&paramValue=Quality+Document&paramType=type&pageNumber=1&sortAttr=documentNumber&sortOrder=-1)

**Comment by gsteimer** [comment]
@nwoodbine - is this potentially not an issue?

**Comment by nwoodbine** [comment]
@gsteimer here is an example saved search that does not work:

[Saved Search](http://edge2.tsgrp.com/hpi/search/controlleddocs/Quality%20Document?_id=UserPreferences.nwoodbine.savedSearches_0.searchParams_0&paramValue=/paramType=property&_id=UserPreferences.nwoodbine.savedSearches_0.searchParams_2&paramName=aw_status&operator=OPERATOR_EQUALS&paramValue%5B%5D=Draft/paramName=Quality+Document&paramValue=Quality+Document&paramType=type&pageNumber=1&sortAttr=documentNumber&sortOrder=-1)

**Comment by gsteimer** [comment]
@nwoodbine - works for me;

![saved-search-link](https://cloud.githubusercontent.com/assets/1377228/26409006/f544dfee-4064-11e7-9eb8-54dd49832f26.gif)

**Comment by nwoodbine** [comment]
Closing as the only incorrect behavior seen is related to [this issue](https://github.com/tsgrp/HPI/issues/1399).
