### ISSUE TITLE
Collection Grid View displays duplicates on refresh

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1062]
When you are viewing a collection with grid view and you refresh the page, the collection displays however it shows every asset twice (if the collection has 2 items the grid shows 4 items).

See Gif below: 
![collectionsgridviewissue](https://cloud.githubusercontent.com/assets/2895070/14397657/47e900ea-fda4-11e5-8524-348646c3e1d5.gif)

**Comment by gsteimer** [comment]
When fixing this, we should test list view as well...

**Comment by aviking** [comment]
Fixed with Commit: 14824
CR: Dan G.
