### ISSUE TITLE
Advanced Combine to PDF - Admin toggle issue and action styling

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1064]
See the screencam below - I'm guessing something is conflicting with element IDs:

![advcombineadmin](https://cloud.githubusercontent.com/assets/1377228/14504099/ecac8426-0178-11e6-8103-9a65e3603dc5.gif)

Also - if possible, can we clean up the styling when one of the tables has more fields than the other?  It seems like making the title columns wrap would solve the issue:

![screenhunter_715 apr 13 10 58](https://cloud.githubusercontent.com/assets/1377228/14504125/08d49ce2-0179-11e6-84af-0849819e0e2c.jpg)

**Comment by alieblich** [comment]
Admin toggle issue fixed with HPI rev# 14820

**Comment by gsteimer** [comment]
Closing this issue since the views have been completely updated on current client projects.
