### ISSUE TITLE
Disabling Notifications in Application Config Does Not Remove Bell Icon

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/HPI#1065]
If notifications are disabled, the user should no longer see the bell icon.

![image](https://cloud.githubusercontent.com/assets/4128978/14511526/9d63889a-019d-11e6-84dc-a09dd13bbfb7.png)

**Comment by gsteimer** [comment]
from @benallenallen - even if notifications are off, the header still constantly asks OC for notifications.  We should make sure to remove this as well if notifications are disabled.

**Comment by camrooks** [comment]
Revision #15318 in the log.
log message: NOTIFICATION BELL- issue fix: fixed the notification bell icon not disappearing when disabling header notifications

CR: Graham
