### ISSUE TITLE
Saved Searches Don't Allow Other Searches and searching after changing tracs breaks

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1066]
Upon navigating to a search form and selecting your saved search, the saved search runs successfully. However, attempting to change parameters and run a new search after this results in searches which fail to execute.

The following gif is on edge1:

![savedsearchissue](https://cloud.githubusercontent.com/assets/14186924/14535947/d4cedbc0-0235-11e6-9184-28d5576b7bfc.gif)

The following network call is errored out with each search:

![image](https://cloud.githubusercontent.com/assets/14186924/14536024/0d914ede-0236-11e6-8cc1-fab5f1297a05.png)

**Comment by gsteimer** [comment]
@ZachGerth I just tried this on edge and it doesn't work.  However it does work on release2.  That means something must've changed in the past couple weeks that caused this bug to crop up.

**Comment by gsteimer** [comment]
Also - this works on edge1, so I'm marking this as Alfresco.  If that turns out to be a coincidence, please remove that label...

**Comment by gsteimer** [comment]
Also - on both edge1 and edge2 if you search on a trac (doesn't matter if you have a saved search) it works fine.  But if you change tracs and try to search again, the search fails to execute:

![image](https://cloud.githubusercontent.com/assets/1377228/14536481/2c2abb26-0238-11e6-861e-624f1d7ad803.png)

**Comment by peterkk** [comment]
Fixed with hpi revision #14843
