### ISSUE TITLE
Picklist Config - Title should remain when selecting type of picklist

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1067]
The user should not have to re-type the name after selecting a type: it's annoying.

![picklistretype](https://cloud.githubusercontent.com/assets/8784597/14573911/e9f0cf5c-031d-11e6-8a3e-696e2383759d.gif)

**Comment by camrooks** [comment]
Revision #15313 in the log, CRed by Graham
log message: PICKLISTCONFIG: issue fix: https://github.com/tsgrp/HPI/issues/1067
now the text does not disappear when selecting a picklist type
