### ISSUE TITLE
Query Restrictions Update - search logic isn't hit for Solr portals in searchsidebar.js

### ISSUE THREAD

**Issue by ladams13** [tsgrp/HPI#1071]
The root of this issue comes from Solr not having groupNames for users.

So when in queryrestrictionservice.js, it tries to get groupNames (line 19-27) and doesn't find any, the deferred.resolve() is never getting hit.

This causes the def.promise() at the end of the function to not be resolved, resulting in the search logic in searchsidebar.js (lines 443-499) to not be called within a Solr portal.

To quickly fix this locally to be able to execute searches for other testing, @renesaladrigas added a flag (hasSearchLogicBeenExecuted) initially set to false, and flips to true at the end of the hasSearchLogicBeenExecuted done function.  If after that logic, it is still set to false, then we have it go through the search logic (basically copy/pasted logic from within callback function inside of an if block).

@joehof any thoughts on a better implementation/fix for Solr instances?

**Comment by gsteimer** [comment]
@peterkk @renesaladrigas @aviking - do you know the status of this?  I'd think our recent Solr projects would have needed this.  Was this fixed for any of those projects?

**Comment by renesaladrigas** [comment]
This issue was corrected with OC revision 14909 (and 14910).

To correct this issue we implemented the findGroupsWithUser method of the SolrUserImpl.java with a dummy implementation; the method will return a blank UserResult that HPI can work with and execute the search logic with.
