### ISSUE TITLE
SearchConfig Default to Table View for Search Results

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1072]
Can we make table view the default search results view that is enabled?

Creating a new search config from scratch would be easier if we didn't have to always disable the list view and enable the table view since that is the one that 99% of our clients use.

We would want it to only enable one by default, and have that be table view.

**Comment by camrooks** [comment]
FIX: Updated search config to default to table view when creating a new search config

Revision #15609

CRd by Graham
