### ISSUE TITLE
Weird Alignment with DropDown

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1074]
See screenshots:

![dropdownalignment](https://cloud.githubusercontent.com/assets/8784597/14747538/5c3ac76e-087a-11e6-9f86-a09a8a53d792.PNG)

![dropdownalignment2](https://cloud.githubusercontent.com/assets/8784597/14747573/90db43e0-087a-11e6-9569-cbf10ce5e92a.PNG)

**Comment by jharkins2** [comment]
Closed at Revision:16896
Fixed https://github.com/tsgrp/HPI/issues/1074. Form dropdown styling cleaned up in formsupport.html and formSupport.styl

CR: Marc
