### ISSUE TITLE
Deleting a Controlled Document does not Move the LATEST flag to prior version

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1078]
In the controlled document scenario, if a minor version of a document is deleted (which typically isn't allowed) the LATEST flag should move to the next highest version. Currently, the TBOs for controlled documents don't move the LATEST flag when a document is deleted, but it should.

**Comment by eschwarzbeck** [comment]
I committed a fix for this on October 7th. Didn't realize there was an outstanding bug for it.

#16155
