### ISSUE TITLE
Saved Search Dashlet - pagination dropdown broken

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1088]
See the screencam below.  On saved search dashlets, you can change the number of objects that are displayed per page, but the dropdown never changes from 10 per page.  Aside from being confusing, this also makes it impossible to change back to 10 per page without navigating away from the page.

![saved-search-per-page](https://cloud.githubusercontent.com/assets/1377228/15018631/047bc87e-11e0-11e6-84d4-c6025e11b854.gif)

**Comment by vachanta93** [comment]
Fixed with rev #15062 in HPI trunk. 

Added a new serialized variable `currentPageSize`, similar to how `currentPage` is used. 

CR - Marc
