### ISSUE TITLE
Group Actions - right click menu item in table view only recognizes the current page

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1092]
See the screencam below.  Using Export Search Results as an example - when I run Export Search Results from the Group Actions menu at the top, all results are correctly exported.  However, when I use the right click menu, only the current page of results is exported.

Once this is fixed, we should test this with other group actions (ex: export to zip, bulk properties, etc).

![group-action-right-click-fail](https://cloud.githubusercontent.com/assets/1377228/15085075/912f6320-139d-11e6-801b-cc2c34a8e766.gif)

**Comment by vachanta93** [comment]
Fixed with rev #15086 in HPI trunk.

When a user selects the total number of search results (more than what is on the first search results page), the `selectedIds` wasn't being updated before the user opens the context menu by right-clicking. 

CR - Avi
