### ISSUE TITLE
Create Folder Header Action - Admin broken

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1093]
See the screenshot below.  Create folder is working on edge, but something is messed up in the admin.  On edge2, there should be 11 tracs set up.  However, it looks like only one messed up trac is displaying:

![image](https://cloud.githubusercontent.com/assets/1377228/15085209/7291ff62-139e-11e6-84e2-dab8ed2ad1c8.png)

Deleting the phantom trac or adding new tracs is impossible.

**Comment by b-k-white** [comment]
Fixed.
HPI - 15066
CR - Graham
