### ISSUE TITLE
Workflow and Workflow Form Config Enhancements

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1105]
**Complete Workflow Task Action (Stage)**
- [x] The info icon appears, even when there is no help text configured:
![image](https://cloud.githubusercontent.com/assets/1377228/15578801/816ad08e-2327-11e6-8924-7c70378276e6.png)
- [x] It seems that required attributes are not evaluated.  For example, in the screenshot below, Review Outcome is required, but the complete task button is still available:
![image](https://cloud.githubusercontent.com/assets/1377228/15578875/d8a702a0-2327-11e6-80ee-cd5d394b0fe7.png)

**Workflow Form Config (Admin)**
- [x] Workflow forms are currently stored all in one default json.  We shuold make each form a separate object in the repo, similar to how Form Config works.
![image](https://cloud.githubusercontent.com/assets/1377228/15577549/9f1087e6-2322-11e6-83f3-60ffcaed224a.png)
- [x] Once the item above is added, the delete config button should delete only the form you're looking at, not all forms
- [x] Ability to label attributes - currently, there's no way to change the labels of any form fields.  Can we simply make the textbox editable?
![image](https://cloud.githubusercontent.com/assets/1377228/15577579/b743f1d6-2322-11e6-84ae-05cd5e9a6a08.png)
- [x] Once you add a custom attribute, there's no way to edit it.  If you want to make changes, you have to delete the property and re-add it.
- [x] When adding an attribute, default editable to true

**Workflow Config (Admin)**
- [ ] Do not display automatic tasks in the interface.  Ex: this task in the HPI Simple Workflow template just sends an email and moves on (there's no user interaction, so no form is necessary)
![image](https://cloud.githubusercontent.com/assets/1377228/15577438/2c47edbc-2322-11e6-81d6-64111dc41ddd.png)

- [x] Order workflow templates by the label, not ID
![image](https://cloud.githubusercontent.com/assets/1377228/15577386/ef1995bc-2321-11e6-8298-a068c6a4b20b.png)

- [x] Order forms in alphabetical order:
![image](https://cloud.githubusercontent.com/assets/1377228/15577375/e3842014-2321-11e6-97f3-f55fb79c5d9b.png)

**Comment by cmlewis** [comment]
These items look good to me. One note - for "Do not display automatic tasks in the interface. Ex: this task in the HPI Simple Workflow template just sends an email..." - this may only be possible if we can get Activiti to tell us it's a service task instead of a user task. Just depends on the API.

**Comment by gsteimer** [comment]
Another one I found:

- [ ] Give the user the ability to delete certain custom attributes, rather than being forced to delete all custom attributes:
![image](https://cloud.githubusercontent.com/assets/1377228/15611463/12ec2ab2-23f0-11e6-8bc2-846b519cbe0f.png)

**Comment by grahamsinger** [comment]
Closed all but the one outstanding with rev15264.  @gsteimer let me know if you would like me to close this out—separating the one outstanding one into it's own issue.

CR: BW

**Comment by gsteimer** [comment]
@grahamsinger - yeah let's split the item around hiding automatic tasks into it's own item.  Thanks!
