### ISSUE TITLE
Advanced Combine to PDF - OA Select Pages Integration issues and other random items

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1109]
Some issues with the OA "select pages" integration with the Advanced Combine to PDF action:

- [x] Upon starting the action, the new interface appears, but the "File to be created" field should be automatically populated.  This box was defaulted to a value in the old interface.
- [x] When opening up OA, the action modal height should be sized appropriately.  With the way it is now, the save button hangs off the bottom of the screen.  Users will not know to scroll down to see the action:
![image](https://cloud.githubusercontent.com/assets/1377228/15617749/ee404304-240f-11e6-97bd-91306ac21403.png)

- [x] After saving pages in OA, the pages are listed out of order when more than 10 pages exist on the document.  I'm guessing this is because the pages are sorted in alpha-order vs. numeric order.  Note - I tested this, and it's not just a display issue.  The pages are actually out of order on the generated PDF.
![image](https://cloud.githubusercontent.com/assets/1377228/15617811/1d5053dc-2410-11e6-91b1-844c710ceb2a.png)

**Comment by gsteimer** [comment]
- [ ] Another issue - it seems like the spacing on the "selected documents table" is inconsistent.  When you add documents, it's squished.  If you re-order, the spacing changes.

![combined-pdf-spacing](https://cloud.githubusercontent.com/assets/1377228/15714977/6350853e-27e2-11e6-8dc8-0291a8a283cc.gif)

**Comment by gsteimer** [comment]
Ok - I see what the problem is... It looks like the following settings were not tested:

![image](https://cloud.githubusercontent.com/assets/1377228/15715523/5e4a8448-27e4-11e6-86ff-b32b9b04c29c.png)

If set to "both", it's fine.  If "selected" it looks fine (although it's wrong - attributes show up on both tables.  If set to "available", then you see what I saw in my last comment.

Question - with the new layout, do we even need this setting anymore?  Should we just assume the selected attributes will appear on both?

**Comment by gsteimer** [comment]
@nquillin91 @mikeblum - will the OA page select order issue affect the AW page select as well?

**Comment by gsteimer** [comment]
- [ ] Action does not work at all from search results:

![image](https://cloud.githubusercontent.com/assets/1377228/15748634/405a0780-28a5-11e6-9a97-10cbf4228683.png)

![image](https://cloud.githubusercontent.com/assets/1377228/15748654/477f71ee-28a5-11e6-941d-46d08d5ecec0.png)

When using the action from search, the available documents section shouldn't show at all (since you already selected the docs).  All the user should be able to do is work with the bottom table.

**Comment by alieblich** [comment]
The third bullet point (the order of the selected pages on a doc with more than 10 pages coming back from OA) has been fixed with OA rev 3293

**Comment by gsteimer** [comment]
Also - if the action is in a modal, the select page button does not work.

![modal-inception](https://cloud.githubusercontent.com/assets/1377228/16088869/98005194-32ee-11e6-8582-f253b6b7889e.gif)

**Comment by alieblich** [comment]
Fix for the select page button when the action is in a modal is commit in HPI rev #15457

**Comment by gsteimer** [comment]
Just trying this out again on edge2.  It seems to work much better, but the select pages from OA isn't changing the page range.  See below:

![combined-pdf-select-pages-fail](https://cloud.githubusercontent.com/assets/1377228/17146040/72606650-5322-11e6-9370-ccb2a7f315c4.gif)

@nquillin91 @dhartman25

**Comment by alieblich** [comment]
Looks like the event OA triggers when the user selects a page isn't getting fired off anymore. Testing with an older version of OA still works.

**Comment by gsteimer** [comment]
These issues seem to be fixed on edge,
