### ISSUE TITLE
Search Restrictions not configurable in core HPI/OC

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1110]
See screen shot below, no groups are displaying when navigating to Search -> Restrictions config. Groups need to be selected before any configuring can take place.

![search-restrictions-issue](https://cloud.githubusercontent.com/assets/2895070/15679357/3c7db786-2717-11e6-9bce-80c22897d072.png)

**Comment by gsteimer** [comment]
From talking to @aviking, it seems like the culprit may be that the code is expecting the `/allGroups` endpoint to exist, which we removed.  See #1031.  Instead, the code should use the `/authorities/search` endpoint to find groups.  Talk to @RudraVishweshwar, who updated other areas in HPI to do something similar.

**Comment by gsteimer** [comment]
Also - @aviking noticed that there were not many OC updates merged in for this.  Are there changes that need to be merged into trunk to get search restrictions to actually work?

**Comment by b-k-white** [comment]
Updated HPI to use the new endpoint, as well as merged in the OC code.

HPI - 15223
OC - 14564
