### ISSUE TITLE
Cannot set note type for new folder note

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1111]
For folder notes, we typically configure a `Note Type` picklist.  However, on both release and edge (1 & 2), the note type picklist is always uneditable:

![image](https://cloud.githubusercontent.com/assets/1377228/15690071/6cfe9076-2747-11e6-80d2-cb0409674195.png)

However, in the admin, the field is configured to be editable:

![image](https://cloud.githubusercontent.com/assets/1377228/15690094/89ad7c00-2747-11e6-86fe-6ae6b4d3c22b.png)

**Comment by b-k-white** [comment]
Fixed. 
HPI - 15231
CR - Graham
