### ISSUE TITLE
Cannot attach a controlled document past version 1.0 to a form and route for approval

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1112]
Now that a chron id structure has been developed for our Alfresco implementation, findFirstVersionId returns the chron id instead of simply the passed in objectId (see OC revision 14034). Workflow documents are getting attached incorrectly past 1.0.

**Comment by ZachGerth** [comment]
Fixed with OC Commit # 14566.

**Comment by gsteimer** [comment]
Ok - so now I can attach a 1.1 document to a form, but starting the route fails with the same error that's displayed in #1120.

I'm guessing something happened with the conditions, perhaps something that was masked before #1113 was implemented.

**Comment by gsteimer** [comment]
Just tried this on a 0.x version and I'm getting the same error - cannot start the route

**Comment by gsteimer** [comment]
Fixed with OC Rev 14640
