### ISSUE TITLE
User preferences not saving

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1116]
Something must have changed with user preferences recently.  All user preferences are not saving on both edge1 and 2.  I've tried saving searches and changing table view columns, but nothing saves after a logout / login.  See below:

![user-prefs-not-saving](https://cloud.githubusercontent.com/assets/1377228/15869967/382b2db0-2cb4-11e6-99b9-40061046babd.gif)

In the OC log, I see this, but I'm not sure if it's related:

```
13:27:49,170 ERROR [com.tsgrp.opencontent.rest.RESTService] [ajp-apr-8009-exec-6] The user does not have READ permissions on object workspace://SpacesStore/dc434baf-cb7c-4372-870c-f082ae9ffa49
com.tsgrp.opencontent.core.exception.OCForbiddenRuntimeException: The user does not have READ permissions on object workspace://SpacesStore/dc434baf-cb7c-4372-870c-f082ae9ffa49
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:529)
	at sun.reflect.GeneratedMethodAccessor764.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)

```

**Comment by mikeblum** [comment]
------------------------------------------------------------------------
r15339 | mblum | 2016-06-14 11:28:13 -0500 (Tue, 14 Jun 2016) | 2 lines
Changed paths:
   M /trunk/code
   M /trunk/code/app
   M /trunk/code/app/main.js
   M /trunk/code/app/modules/common/security.js
   M /trunk/code/app/modules/hpiadmin/preferences/userpreferences.js
   M /trunk/code/app/modules/search/savedsearch.js
   A /trunk/code/app/modules/services/exitservice.js (from /feature_branches/exit_service/app/modules/services/exitservice.js:15289)
   M /trunk/code/app/modules/wizard/activeformrouter.js
   M /trunk/code/project
   M /trunk/code/project/iron-mountain-employee-onboarding/app/modules/common/security.js
   M /trunk/code/test/tests
   M /trunk/code/test/tests/modules/search/savedsearchSpec.js
   A /trunk/code/test/tests/modules/services (from /feature_branches/exit_service/test/tests/modules/services:15289)
   M /trunk/code/test/tests/modules/services/exitserviceSpec.js

Exit Service: support for multiple window.onbeforeunload events. See how to configure an event in main.js, security.js, and activeformrouter.js. Further explanation can be found on Github: 
https://github.com/tsgrp/HPI/wiki/Exit-Service  CR @dgrumieuax
------------------------------------------------------------------------

**Comment by gsteimer** [comment]
After rebuilding edge1 and edge2, saved searches are still not saving properly using the Exit Service.

**Comment by mikeblum** [comment]
r15417 | mblum | 2016-06-21 10:32:10 -0500 (Tue, 21 Jun 2016) | 1 line
Changed paths:
   M /trunk/code/app/modules/common/security.js
   M /trunk/code/app/modules/hpiadmin/preferences/userpreferences.js

User Preferences - Saved Search - synchranously save user prefs upon logout instantly CR @jhof
