### ISSUE TITLE
View properties submit button duplicates the doc viewer

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1118]
Steps to recreate:
1. View a document in the stage
2. Click View Properties action (document action)
3. Edit an attribute (or don't) then click submit
4. See gif below there are two viewers showing the same document

Gif:
![viewpropsduplicatesdocview](https://cloud.githubusercontent.com/assets/2895070/15945011/ebe45cc6-2e55-11e6-8c0f-974316372085.gif)

**Comment by gsteimer** [comment]
This has been around for a while with bulk import.  If you import a document and then view it right away without refreshing the page, it duplicates the viewer.  See -  #324.  Not sure how this has been introduced to view properties

**Comment by ZachGerth** [comment]
Fixed with HPI Commit # 15366.
