### ISSUE TITLE
Workflow Config Admin - Reset Config button does nothing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1119]
Clicking the reset config button in workflow admin does not actually reset the form or give any feedback to the user.  We should verify that the button:

- [x] Asks the user if he/she really wants to reset the workflow config
- [x] Actually resets the config
- [x] Gives the user some sort of success message once it finishes

See the screencam below:

![reset-config-nothing](https://cloud.githubusercontent.com/assets/1377228/15968234/b6161b48-2ef0-11e6-81fc-60bb2628c4f9.gif)

**Comment by camrooks** [comment]
FIX: Updated the workflow config to allow the reset button to work properly.  Added a confirmation popup and the reset button is disabled unless a workflow is selected from the dropdown.

Revision #15608

CRd by Graham
