### ISSUE TITLE
Alfresco Manage Controlled Documents - Improper OR search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1121]
When the user searches for controlled documents to attach in the Manage Workflow Documents action, the query is determined by the `manageWFDocSearchConfig` in HPI's `config-project`.  Typically the search results should match:

- Controlled Documents
- Document number containing the search term entered by the user
- Draft status
- Not a working copy

However, it looks like the query is generated as:

**Note - improper OR**
```
(@tsg\:documentNumber:\*TSG\-133\* OR @tsg\:status:\*DRAFT\*) AND TYPE:aw\:controlledDocument AND -ASPECT:cm\:workingcopy
```

Since the query is `OR`ing, it ends up pulling back improper results:

![image](https://cloud.githubusercontent.com/assets/1377228/16051440/82f8b706-3225-11e6-9b0b-f40a3df16e91.png)

From what I can tell in the config-project for edge2, it's trying to `AND` the criteria:

```
searchConfig: [
		{
			paramName: "documentNumber",
			paramValue: "none",
			paramType: "property",
			//operator: "LOGIC_LIKE",
			andOr: " and "
		},
		{
			logic: "OPERATOR_EQUALS",
			paramName: "aw_status",
			paramType: "property",
			paramValue: "DRAFT",
			relatedObjectOperator: " and "
		},

		{
			logic: " and ",
			paramName: "Controlled Document",
			paramType: "type",
			paramValue: "Controlled Document",
			relatedObjectOperator: null
		},

		{
			paramName: "limit_results",
			paramValue: 25,
			paramType: "options"
		}

	],
```

Note that on Documentum, this query is properly generated as:

```sql
Select ... FROM aw_controlled_doc  (ALL)   WHERE  UPPER(document_number)  like '%TSG-105%'  and   UPPER(a_status)  like '%DRAFT%' ORDER BY object_name DESC ENABLE(NOFTDQL, RETURN_TOP 25)
```

**Comment by gsteimer** [comment]
@mikeblum @joehof - any ideas on if I can change my `config-project` to get this query to `AND` properly?

**Comment by ZachGerth** [comment]
Fixed with HPI Commit # 15460.
