### ISSUE TITLE
Cross-site scripting in HPI alerts

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1122]
From the previous discussion, there are cross-site scripting vulnerabilities in the way we show HPI alerts. Mainly in our use of the Handlebars {{{ }}} that does not escape malicious JS.

I've added browser support for this selective escaping module (from npm): [sanitize-html](https://github.com/punkave/sanitize-html)

Out of the box this will omit `onerror` attrs and `<script>` tags. Here's a full list of what is escaped by default: [sanitize-html defaults](https://github.com/punkave/sanitize-html#what-are-the-default-options)

I propose we shim in the browserify-ied sanitize-html and create a Handlebars helper like this one in leiu of using {{{ }}} Handlebars for rendering HTML:

```javascript
    //defend against <script> tags in {{{ attr }}} situations
    Handlebars.registerHelper('sanitize-html', function(html) {
        return sanitizeHtml(html);        
    });
```

example use in html:

```html
<p>{{sanitize-html message}}</p>
```

**Comment by camrooks** [comment]
FIX: Cross-site scripting error in User Preferences admin #1141

#1141

CRd by Graham

revision# 15594
