### ISSUE TITLE
Checkout Causes Double Scrollbars

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1123]
When checking out/checking in a document, the way the stage refreshes seems to cause double scrollbars to appear in the stage on edge2.

Before checking out:
![image](https://cloud.githubusercontent.com/assets/14186924/16121801/479f2f24-33aa-11e6-97a9-5397cf081878.png)

After checking out:
![image](https://cloud.githubusercontent.com/assets/14186924/16121819/5abd2e44-33aa-11e6-89c9-c6486b549704.png)

Note the double scroll bar remains after moving around the window/tab, resizing the window/tab, etc.

**Comment by gsteimer** [comment]
@ZachGerth - Looks like this is working on edge.  Can we close?

**Comment by ZachGerth** [comment]
Just replicated it on edge 2 again.

**Comment by gsteimer** [comment]
@ZachGerth - yep, not sure what I was working with before, but I do see this now on edge2

**Comment by rosenoam** [comment]
Revision #16694 
Fixed issue where checkout causes double scrollbars. Within checkout.js I changed the iframe.style.display="none" if iframe === null. This seems to fix the issue.
