### ISSUE TITLE
Workflow Config Admin - Selected form not displaying in admin all tasks

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1127]
See the screencam below.  For some reason, on my Policy Contract Annual Review form, when I try to select a form for the Underwriter Review task, it looks like nothing is selected.  However, when the user processes the task, the correct form is displayed.  So it seems that it's setting the value properly, but not displaying it in the admin.

This happens on both edge and release, but only for this one task.

Admin:

![wf-config-form-select](https://cloud.githubusercontent.com/assets/1377228/16320863/aa23039a-395f-11e6-9651-41347b63c363.gif)

Stage Action:

![image](https://cloud.githubusercontent.com/assets/1377228/16320859/a0b873da-395f-11e6-9f69-d82a554a597c.png)

**Comment by camrooks** [comment]
FIX: Workflow Config Admin - Select form not displaying in admin for certain tasks

Revision #: 15583

CRd by Graham

**Comment by gsteimer** [comment]
@camrooks @grahamsinger - Am I doing something wrong?  Now on both edge and release, when I go to an existing workflow config, *none* of the tasks are populating in the dropdowns.  See below:

![workflow-admin-select-form](https://cloud.githubusercontent.com/assets/1377228/17146411/0273b228-5324-11e6-9477-2e207c039cc9.gif)

**Comment by camrooks** [comment]
FIX: Workflow config tasks not populating in the dropdowns, needed to update the way the IDs were generated when loading tasks

Revision# 15698

CRd by Bradley White
