### ISSUE TITLE
Back Button from Stage to Search doesn't work when search term contains a "%" (percent sign)

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#113]
Encountered on Edge1 on 1/14/2014

![search](https://f.cloud.github.com/assets/4850976/1912481/c0a5fbec-7d3a-11e3-856b-17adcb3bfbaf.gif)

Reproduce - 
- Click on "Search" tab
- type in a "Name" that contains a % character
- press "Enter"
- click on a search result
- click on the back button

The first click of the back button seems to change the URL in the address bar, but nothing seems to happen. A second click of the back button does take you back to the search page, but it doesn't remember the search that was run.

**Comment by vachanta93** [comment]
Fixed in rev #15065. 

If a user entered a '%' character in the search parameter, it would fail because $.deparam doesn't work if the '%' is un-encoded. Added encodeURI to encode special characters except , / ? : @ & = + $ # (http://www.w3schools.com/jsref/jsref_encodeURI.asp).

CR - Marc
