### ISSUE TITLE
Google client library 404ing upon loading HPI

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1131]
It appears the shim'd-in `google-client-api` library that we shim into Bulk Upload is throwing a 404 since it gets loading when require loads the JS:

![selection_122](https://cloud.githubusercontent.com/assets/3905463/16427685/05a91542-3d34-11e6-8de0-bd4709a78a28.png)

Can we get the un-minified copy of `google-client-api.js` for debugging purposes and only load this module if the cloud upload / Google drive settings are configured for Bulk Upload / wherever else we have this configured?

**Comment by gsteimer** [comment]
@aviking - Is this no longer an issue now that we've fixed #1234 ?

**Comment by gsteimer** [comment]
closed per #1234
