### ISSUE TITLE
If one item checked in table view, the actions dropdown should list single doc actions matching right click

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1132]
Right now on edge2, when a single document is selected in TableView, the right-click action list shows both the `grouped` actions as well as `single` actions. The actions dropdown only shows the grouped actions. This should be corrected so that the dropdown and right click actions show the same actions.

Test Scenarios:
- Configure Advanced Combine to PDF as both a TableView action and a grouped action
- configure View Properties in TableView
- [ ] Select a single action - right-click and actions dropdown should show Combine to PDF and View Properties
- [ ] Select multiple documents -  right-click and actions dropdown should show Combine to PDF ONLY

see me before starting this one.

**Comment by b-k-white** [comment]
@gsteimer - This functionality already exists.
