### ISSUE TITLE
SearchAuthorities Alfresco Implementation does not support EVERYONE

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1133]
Turns out EVERYONE is a special type of authority, not a GROUP or a USER in Alfresco parlance (see https://forums.alfresco.com/forum/general/non-technical-alfresco-discussion/how-add-all-users-group-emailcontributors-03102011 and AuthorityType.java in Alfresco). As such, returning all users in an Alfresco system from EVERYONE is not supported through searchAuthorities.

This enhancement would enable this functionality in Alfresco implementations at a minimum.

Could we/should we add this as another AuthorityType in OC code to our existing User and Group types?

interface com.tsgrp.opencontent.core.user.IUser| name: searchAuthorities
org.alfresco.repo.security.authority.UnknownAuthorityException: 06010008 An authority was not found for GROUP_EVERYONE

**Comment by ZachGerth** [comment]
We now support utilizing GROUP_EVERYONE in our SearchAuthorities functionality in OC Revision # 14817.
