### ISSUE TITLE
Datebox Visibility Dependence on Autocomplete Breaks Form

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1137]
When an attribute which is a Datebox is configured to have visibility dependence on another attribute which is an Autocomplete control, the form itself is no longer able to render. An example is given below.

![image](https://cloud.githubusercontent.com/assets/14186924/16701406/297aba7c-4525-11e6-90e5-995b13bd21a8.png)

The following error is printed in the console:

`Uncaught Error: Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.`

**Comment by gsteimer** [comment]
@ZachGerth is this really just a Documentum thing?  If this would fail on other ECMs as well, we should remove the Documentum label.  Can you check with @joehof to see if this is actually an issue?  It could be a config problem...

**Comment by ZachGerth** [comment]
I haven't tested it on HBase, but where it happens consistently and reproducable on edge1, I couldn't get it to occur on edge2.

**Comment by ZachGerth** [comment]
@joehof and I dug into this and the issue appears to be caused by configuring an attribute as a datebox, and that Datebox has Visibility Dependence on a picklist-enabled Autocomplete control. I'll update the title.

**Comment by Kovacinski** [comment]
HPI REVISION: 16695
