### ISSUE TITLE
Facets Breaking on Raw Types that are not Strings

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#1139]
Facets are breaking when an attribute other than a String is configured. When a facet is selected, the search URL is updated to filter the values selected. When we attempt to compare the value in this URL to the value retrieved from each document in the search results, the comparison fails and doesn't display the document. See the screen cam below for a visual.

![facetsbreakingonrawvalues](https://cloud.githubusercontent.com/assets/14186921/16809774/1fa2f828-48e7-11e6-83b0-a4884c9c66fa.gif)

**Comment by gsteimer** [comment]
@joehof - was this a known thing when you revamped facets or did it just crop up?

**Comment by renesaladrigas** [comment]
FACET SEARCH : Facets were not working for raw types such as integers, doubles and booleans. Now all values retrieved from the results collection will be stringified to be compared properly to the values from the URL that filters the results.

Fixed with HPI commit 15605
CR - Joe Hof
