### ISSUE TITLE
Config stability issue with Search Icons

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1140]
Clicking on a type in TableView doesn't show the attribute icons for a type:

![selection_130](https://cloud.githubusercontent.com/assets/3905463/16811811/bc3bf88a-48ef-11e6-8707-d9f52fa87bdb.png)

Intermittently, the operator (`regex, equals, contains`) becomes undefined and breaks the code pulling on the icon config.

**Comment by grahamsinger** [comment]
Fixed with revison 15586.  Document types with spaces weren't tested originally (by me).
