### ISSUE TITLE
Cross-site scripting error in User Preferences admin

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1141]
This issue affects how Handlebars renders `{{{ }}}` in the DOM. It doesn't properly escape malicious scriupt tags hidden in HTML.

![upload_6_15_2016_at_8_32_09_am](https://cloud.githubusercontent.com/assets/3905463/16812130/5cea850c-48f1-11e6-851c-b427f4c21d6e.png)

In the per-user User Preferences admin we can see the issue from maliciously named saved searched.

I've added an enhancement to the following library for intelligent sanitation of HTML before we show it to the user in `alert.js`:

[sanitize-html](https://github.com/punkave/sanitize-html)

To solve this, integrate the new sanitize-html dependency into HPI and create a Handlebars helper in `app.js` called `Handlebars.registerHelper('sanitize', function(){});`

**Comment by camrooks** [comment]
FIX: Cross-site scripting error in User Preferences admin #1141

https://github.com/tsgrp/HPI/issues/1141

CRd by Graham

revision# 15594
