### ISSUE TITLE
Saved Searches will not execute - complaining about missing entry in full text search box

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1145]
See the screencam below - something is preventing the saved search from running.  It's complaining that I need to enter a value in the full text search box, but my search does not contain a full text value.

![saved-search-run-fail](https://cloud.githubusercontent.com/assets/1377228/16845194/aec43758-49ad-11e6-93c4-16862424160d.gif)

**Comment by camrooks** [comment]
FIX: changed the behavior of adding a saved search to saveNow() instead of save(), which was preventing the saved search from running and asked for parameters, even though the parameters were visible.  Also updated a unit test to spyOn saveNow instead of save 

Revision: 15639

CRd by Graham
