### ISSUE TITLE
View Properties action auto-appends the file extension to the object name

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1150]
See the screenshot below.  If I edit properties of a wizard form, the `.json` extension gets appended to the object name, which should not occur for wizard forms.

![edit-form-props](https://cloud.githubusercontent.com/assets/1377228/17341003/416ade4a-58b8-11e6-9dba-68af64ddf080.gif)

_Notes_
- This also happens for other document types like insurance docs.  If you take `something.pdf` and try to rename it as `something`, it actually saves as `something.pdf`.  That's fine, and what most Alfresco clients would probably want, but isn't what we want for AW forms.
- The extension doesn't get appended for controlled docs.  My guess is that the code is actually trying to append the extension, but our behaviours under the covers rename the document to the proper format: `{doc.number}-{version.num}`.
- Current workarounds:
  - The extension being there does't hurt anything.  Just deal with it.  
    - Note - I'm _pretty_ sure this isn't a problem.  If this turns out to be wrong, bump the milestone on this issue.
  - Use autonumbered forms and do not allow form properties to be edited outside of the form itself.  This is how most clients have AW forms set up, hence the 2.x milestone.

**Comment by grahamsinger** [comment]
@gsteimer For project Turntables, I added in a "blacklist" of types not to add the extension to.  If this is a reasonable solution for trunk, should we add this to the `project.config()` or make it configurable in the admin?

**Comment by gsteimer** [comment]
@grahamsinger - for now, let's just move it to trunk as something in the project config.  We can add it to the admin later if needed.

**Comment by grahamsinger** [comment]
Fixed with Committed revision 21482 in HPI
