### ISSUE TITLE
Workflow Form Admin Broken

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1154]
See the screencams below.  It looks like creating a new workflow form and editing existing forms are completely broken.

The error in the console for both scenarios is: 
![image](https://cloud.githubusercontent.com/assets/1377228/17439182/7179183c-5aec-11e6-9df4-2c4080164012.png)

Create new form - cannot add fields
![workflow-form-create](https://cloud.githubusercontent.com/assets/1377228/17439226/9f5f3a92-5aec-11e6-810b-04c1ca176c9e.gif)

Edit form - does not load forms
![workflow-form-edit](https://cloud.githubusercontent.com/assets/1377228/17439228/a2d5b002-5aec-11e6-81d6-9c1ded957926.gif)

**Comment by renesaladrigas** [comment]
Forms can now be created or edited in the Workflow Form tab since the code correctly passes in the attrHelper when creating a new form.

Closed with HPI revision 15780.
