### ISSUE TITLE
Advanced Combine to PDF - Page Selection

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#1159]
Currently, AdvancedCombineToPDFActionExecuter holds each PDF that it is combining in memory until the whole action has completed. This will cause a heap memory issue very easily if the document count gets high enough. We ought to only grab the content of each PDF a single time and close the stream to that document when finished using it.

**Comment by b-k-white** [comment]
Advanced Combine to PDF also has an error on the javascript side. If you use the "Add All Documents" button, and quickly press the Combine, it will give you an error in javascript code because it hasn't finished loading all of the page selection text boxes. There needs to be some sort of feedback loop or disabling of that button until those are all loaded.

**Comment by b-k-white** [comment]
@alieblich did anything go into trunk to fix what I describe in the second comment?

**Comment by gpolonus** [comment]
Fixed with commit #16912
