### ISSUE TITLE
Create Doc from Template Fails in Firefox

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1165]
On both edge1 and edge2, when creating a doc from a template in Firefox, the upload fails with this error:

![image](https://cloud.githubusercontent.com/assets/1377228/17869751/5356aa68-687a-11e6-92a4-f2032db44400.png)

![firefox-create-from-template](https://cloud.githubusercontent.com/assets/1377228/17869756/57800f1c-687a-11e6-91f8-edfeb2bb6439.gif)

**Comment by gpolonus** [comment]
Resolved with revision number #16061.

CR: Zach Gerth
