### ISSUE TITLE
Create Wizard Form - Typeahead does not allow mouse scroll

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1173]
See the screen capture below.  If you try to use the mouse to scroll the list of available forms, the list disappears:

![create-wizard-form-no-scroll](https://cloud.githubusercontent.com/assets/1377228/18056991/d07926de-6dd3-11e6-89e0-059b6cbb2b0e.gif)

**Comment by tbrandstatter** [comment]
TYPEAHEAD:  Added a mousedown event in typeahead.js and prevented default. No logic branches so not unit tests necessary.
CR: Avi King

Completed at Revision: 16023

**Comment by aviking** [comment]
See Attached Screen Capture, Issue is still happnening
![wizardformscrollissue](https://cloud.githubusercontent.com/assets/2895070/24296661/fd0a0c80-106d-11e7-8f15-9b86e2b96e49.gif)

**Comment by aviking** [comment]
Re-closing this issue because it was correctly fixed. The reopening was because of issue #1341, however #1341 only occurs in IE (potentially due to a windows update).
