### ISSUE TITLE
Video.js causes javascript error in IE when Windows Media Player is not installed

### ISSUE THREAD

**Issue by joehof** [tsgrp/HPI#1174]
We are seeing this at a client with IE11. Starting up HPI on a box that doesn't have Windows Media Player installed causes a javascript error in our require.js where video.js is embedded. Looks like this has been fixed in a later version of video.js:

https://github.com/videojs/video.js/issues/984

We should update video.js and test.

**Comment by b-k-white** [comment]
Installed Windows Experience into server and issue went away. Looking into upgrading to a more recent release that has a fix for this problem.

**Comment by gsteimer** [comment]
@b-k-white - is this fixed now?

**Comment by b-k-white** [comment]
@gsteimer video.js has been updated, but I haven't tested this issue to verify. Do we have a server where we can test?

**Comment by gsteimer** [comment]
@b-k-white - I just tried on an old Windows 2003 server that doesn't have WMP installed and it seems to be working fine.  Can you reference the commit Rev and close?

**Comment by b-k-white** [comment]
Closed. Upgraded version.
HPI - 17419
