### ISSUE TITLE
Chained "Send Email" + "Folder Note" Action does not set an Object Name on the Note

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1176]
When the "Send Email" + "Folder Note" action is used, the note object that is created does not set an object name. It seems like Alfresco just generates some dummy name when it gets created, and Documentum leaves objectName blank. We'll probably want to name this object something. In HBase this actually fails since we need an object name to be set.

![image](https://cloud.githubusercontent.com/assets/4850976/18107275/e6932ed4-6ecc-11e6-9367-92a4b398fb35.png)

![image](https://cloud.githubusercontent.com/assets/4850976/18107287/f80a3fae-6ecc-11e6-800a-aa3e64ed079e.png)

**Comment by gsteimer** [comment]
This was a problem a while back with normal Folder Notes.  See #170.  Not sure why chaining send email with folder notes would cause an issue.  It should just be picking up the subject of the email...

**Comment by Kovacinski** [comment]
Revision : 16403
