### ISSUE TITLE
Immediately after importing document, clicking any other document in folder contents loads the wrong document

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1178]
Steps to recreate
- [ ] Import a document using bulk import
- [ ] Immediately after the document imports, try to load any other document into the stage using the link in Folder Contents
- [ ] The document imported in step 1 loads, not the document you clicked on.

See the screencams below.  In the first case (normal import), the doc info module in the top right shows the correct document, but the contents are wrong.  In the second case (create doc from template), both are incorrect:

![bulk-import-click-doc-fail](https://cloud.githubusercontent.com/assets/1377228/18213968/57d290e0-7110-11e6-8410-e105f7b594f5.gif)

![bulk-import-template-click-doc-fail](https://cloud.githubusercontent.com/assets/1377228/18213969/5a1576f6-7110-11e6-865a-375182a12bde.gif)

For reference, the report document should look like this loaded in the HPI stage:

![image](https://cloud.githubusercontent.com/assets/1377228/18214022/9462f0f4-7110-11e6-8225-acceffc44cc4.png)

**Comment by jharkins2** [comment]
Completed at Revision: 16063
RIGHTSIDEACTIONHANDLER: Fixed bug in rightsideactionhandler.js where opening a file from the folder tree would cause the file currently in the rightsideactionhandler to load instead. Added unit test file rightsideactionhandlerSpec.js

#1178

CR - Marc
