### ISSUE TITLE
Removing a Group in the Group Admin causes a JS error after the group is Removed

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1182]
See the screencap, but removing a group does work, it just bombs the JS when attempting to remove the item from the list it would seem. The group is gone when you refresh (and gone in the repo), so the issue is def on the client side with handling the success case to remove it from the list.

![vers2](https://cloud.githubusercontent.com/assets/4850976/18388589/d260398c-7667-11e6-999c-8b9a781b0fcb.gif)

**Comment by Kovacinski** [comment]
Revision number 16040
