### ISSUE TITLE
Right click cut-off at bottom of Search Results

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1183]
Line 561 tableview.js seems like we are just absolutly positioning the element, so can we update this to not be cut off if the menu is going to spill off the bottom of the page?

![image](https://cloud.githubusercontent.com/assets/4850976/18521123/867b130e-7a70-11e6-8378-a3de07e8bdce.png)

**Comment by Kovacinski** [comment]
This was closed with commit revision #16028, Updated the tableview.js and tableviewSpec.js files. CR by Avi King and Zach Gerth
