### ISSUE TITLE
Manange Relations Config Unable to Delete Relation Name

### ISSUE THREAD

**Issue by eschwarzbeck** [tsgrp/HPI#1184]
![image](https://cloud.githubusercontent.com/assets/6668298/18589011/60797d24-7bee-11e6-8bfa-00a56ad0080d.png)

Unable to remove the relation type when clicking on the X next to the relation name in Manage Relations.

**Comment by tbrandstatter** [comment]
Completed at Revision: 16029
MANAGE RELATIONS: Fixed github issue https://github.com/tsgrp/HPI/issues/1184. Can now delete relation names added.
CR: zgerth and aviking
