### ISSUE TITLE
Auto-Complete Configuration Names Doesn't Complete

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1185]
When using Autocomplete in Google Chrome to fill out the name of a configuration, the name does not actually update.

The screenshot below shows an autocomplete suggestion.

![image](https://cloud.githubusercontent.com/assets/14186924/18602668/a76221cc-7c30-11e6-96ce-390f6d74a6a1.png)

Selecting it via. "Enter" and hitting Complete causes the name to be the one prior to the suggestion.

![image](https://cloud.githubusercontent.com/assets/14186924/18602675/bae6faba-7c30-11e6-9dfd-d07792c19dc0.png)

**Comment by jharkins2** [comment]
Completed at Revision: 16045
ADMINSWITCHER: Fixed bug in hpiadmin-switcher.js where config names would not be set correctly when using your browsers auto-complete. Added unit test file hpiadmin-switcherSpec.js

https://github.com/tsgrp/HPI/issues/1185

CR - Devin S

**Comment by jharkins2** [comment]
Completed at Revision: 16045
ADMINSWITCHER: Fixed bug in hpiadmin-switcher.js where config names would not be set correctly when using your browsers auto-complete. Added unit test file hpiadmin-switcherSpec.js

#1185

CR - Devin S
