### ISSUE TITLE
Document Notes - Private Visibility Displayed When Disabled

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1188]
Note Visibility Slider displays even though admin has it configured to be disabled

![image](https://cloud.githubusercontent.com/assets/13734523/18759334/abe48006-80c1-11e6-815f-9f57a912d205.png)

![image](https://cloud.githubusercontent.com/assets/13734523/18759350/bacad8fe-80c1-11e6-9b72-c439ebdb0617.png)

**Comment by nquillin91** [comment]
Config seems to be coming back false correctly but comes back as a string, resulting in an if statement that incorrectly evaluates to true

**Comment by gpolonus** [comment]
Completed at revision: 16128

Folder Notes: Fixed by adding a new observable and differentiating names between the config and HTML bindings.

#1188

CR: Zach Gerth
