### ISSUE TITLE
Advanced Combine to PDF - Document order incorrect in final PDF

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1189]
See the screenshots below - it seems that the Combine PDF is reversing the order of the documents on the final PDF:

*Example with two documents*
![screenhunter_1061 sep 23 14 13](https://cloud.githubusercontent.com/assets/1377228/18798501/6fce6500-8198-11e6-8c79-7fc45cbbefad.jpg)

Final PDF:
![image](https://cloud.githubusercontent.com/assets/1377228/18798517/7e09d47e-8198-11e6-90a8-73641b7ce817.png)

*Example with three documents*
![screenhunter_1062 sep 23 14 15](https://cloud.githubusercontent.com/assets/1377228/18798523/847d1a3c-8198-11e6-8179-e8101c3e27c3.jpg)

Final PDF:
![image](https://cloud.githubusercontent.com/assets/1377228/18798538/93203344-8198-11e6-85fa-96dc05e80563.png)

**Comment by peterkk** [comment]
Fixed with HPI commit #16069

**Comment by gsteimer** [comment]
Just tried this - it's working in stage, but not from search.  See the screencam below:

![combine-pdf-order](https://cloud.githubusercontent.com/assets/1377228/19053191/6d8dd368-897f-11e6-85ec-e40fceaf9cb9.gif)

**Comment by Kovacinski** [comment]
Fixed with commit #16152
