### ISSUE TITLE
Cannot Create Wizard Form in IE

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1190]
See screen shot and screen cam below. When creating a form (either auto numbered or not) in IE (9 or 10 works on 11), the user sees a loading screen and the URL is incorrect. 

Screen Cam:
![createwizardformissueie](https://cloud.githubusercontent.com/assets/2895070/18834609/7b395226-83bc-11e6-8c7e-026cacc6287a.gif)

Screen Shot of bad URL:
![createwizardformissueie](https://cloud.githubusercontent.com/assets/2895070/18834582/5d31207e-83bc-11e6-8202-ffddbd32435f.png)

**Comment by mikeblum** [comment]
r16050 | mblum | 2016-09-26 11:32:12 -0500 (Mon, 26 Sep 2016) | 1 line
Changed paths:
   M /trunk/code/app/modules/actions/createwizardform.js

Create Wizard Form IE 9, IE 10, IE 11 support - issue was window.location.origin doesn't exist in IE 9 or 10. CR @dgrumieaux

Unit tests were misbehaving - slew of commits after this one to fix them.
