### ISSUE TITLE
Email address isn't added to list when suggested and typed out and then the user hits Tab

### ISSUE THREAD

**Issue by gpolonus** [tsgrp/HPI#1191]
![emailrecipientbug](https://cloud.githubusercontent.com/assets/9874402/18922094/f13bf56c-856c-11e6-81e6-ea3c5e6d12cf.gif)

If the email that the user is trying to input already exists in the address book for that folder, and the user types the entire email address out and then hits Tab, the email is not added to the list of recipients below.

**Comment by nquillin91** [comment]
Closing older issue - refer to https://github.com/tsgrp/HPI/issues/1800
