### ISSUE TITLE
App Config - Header Icons slider does not populate current setting

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1196]
See the screencam below - should be an easy one.  The functionality is working properly, but the admin doesn't seem to display the currently set value:

![header-icons-admin](https://cloud.githubusercontent.com/assets/1377228/19051901/4747fad0-897a-11e6-8a9f-ba84fe67e854.gif)

**Comment by renesaladrigas** [comment]
APP CONFIG HEADER ICONS -- Fixing the slider behavior that was not displaying properly even though the functionality was there.

CR - Bradley White

Fixed with HPI revision 16368
