### ISSUE TITLE
Back Button to Search with Folder Path Security Switches Types

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1197]
When you perform a search with folder path security and an object type that is not the "default" object type, you can select a search result. By clicking the "Back" button after selecting a search result, you would expect the same search results you navigated from; however, instead the search form and results are wiped out, and the object type switched back to the first object type.

Note that this issue is fixed on a client branch.

**Comment by gsteimer** [comment]
@ZachGerth - can you make sure this gets merged back to trunk at some point?

**Comment by ZachGerth** [comment]
Fixed with SVN Revision # 16666.
