### ISSUE TITLE
"Select All" Updates Incorrectly when Form Pre-Populated

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1198]
When navigating to a search form using the "Back Button", or re-rendering a form with all options selected, and using the "Select All" feature for auto-complete properties, the "Select All" button appears to still be "Select All" rather than "Remove All". The functionality is correct, but the icon is incorrect.

This is fixed on a client branch.

**Comment by gsteimer** [comment]
@ZachGerth - can you make sure this gets merged back to trunk at some point?

**Comment by ZachGerth** [comment]
Fixed with SVN Revision # 16641.
