### ISSUE TITLE
OneDrive Cancel-Checkout Synchronization Not Honoring Admin Configuration

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1203]
Users cannot cancel a .doc checkout, even after disabling OneDrive on the action. To reproduce, configure "OneDrive Configuration" to be "No" on a Cancel Checkout action:
![image](https://cloud.githubusercontent.com/assets/8784125/19168297/2f062fd4-8bd5-11e6-85b6-d3a8e1dae95f.png)

Checkout a .doc and attempt to cancel the checkout. The action modal should allow the user to do this, but instead the Submit button is disabled (this is expected when OneDrive is enabled).
![image](https://cloud.githubusercontent.com/assets/8784125/19168314/3bf332d2-8bd5-11e6-8dac-777289459701.png)

See @aviking for details before approaching this issue.

**Comment by gsteimer** [comment]
Is the issue that it's calling out to OneDrive even when that setting is configured to 'No'?  Wondering because this works for me on release2 and edge2.  On edge2, the Microsoft login popup appeared even when the config was set to 'No'.

**Comment by gsteimer** [comment]
@aviking - you mentioned this was an easy fix.  Can you make that fix or post something here?

**Comment by Kovacinski** [comment]
fixed with revision 16234
