### ISSUE TITLE
HPI configs no longer portable to other Alfresco environments

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1207]
Currently on edge2, HPI configs contain a reference to its edge2 nodeRef:

"id":"workspace://SpacesStore/0cccb221-9d29-4fbb-9354-d5c52063a13d"

within the JSON of the config. This affects Application config (easiest to replicate) as well as other configs like Stage and Search.

This might also be an issue for DCTM since Backbone looks to the id attribute in its JSON to preform a save.

error trace:

``` javascript
"Error creating config object: org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: workspace://SpacesStore/d29aad65-c0f1-4de9-a97c-98f2e12f7669 (status:null)

{"status":500,"message":"Error creating config object: org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: workspace://SpacesStore/d29aad65-c0f1-4de9-a97c-98f2e12f7669 (status:null)\n\tat org.alfresco.repo.node.db.DbNodeServiceImpl.getNodePairNotNull(DbNodeServiceImpl.java:182)
```

If your configs are affected, you'll find the nodeRef in the JSON of your configs. The simple fix right now is to remove the id attribute from the JSON and version the config.

It appears that upon initial creation we're storing the nodeRef on creation of the config. Edits to the config appear to NOT add back the problematic `id` attribute.

Docbases to confirm:
- [ ] Alfresco (edge2)
- [ ] Documentum (edge1)
- [ ] HBase (edge3)

Test cases:
- [ ] Create a new Application config
- [ ] Verify no `id` attribute is in the JSON  of the config
- [ ] Edit and save the Application config
- [ ] Verify no `id` attribute is in the JSON  of the config

**Comment by gsteimer** [comment]
I feel like this was always in there, but we were still always able to port configs.  Did something change recently in the save?  I've always assumed that the ID was updated to the new repo value the first time it was saved. 

For Documentum, this would be an issue even without moving configs, since the ID changes on every version.  However, saving app config on edge1 works fine...

**Comment by gsteimer** [comment]
@mikeblum - I've been able to do the with no problems going from the 4.2.3.1 to 5.1.2 environments for edge2/release2.  I think we can close this.  Do you agree?

**Comment by gsteimer** [comment]
Closing this issue - I've had no issues moving configs from the Alfresco 4.x environment to the 5.x environment.
