### ISSUE TITLE
FormSupport - Date comparison not working correctly

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1214]
Currently, if you use the controlType DateBox as a field on a form and select one of options for enforcing a date range such as "Date must be later than today"

![capture](https://cloud.githubusercontent.com/assets/13734523/19449651/19bf372a-946c-11e6-9516-692beabfb5b4.PNG)

The comparison seems to be looking at the dates as strings. Resulting in failed validation at times. In the example below, Thursday is validated correctly that it is after the current date but any chosen Friday is invalid.

![formsupportbug](https://cloud.githubusercontent.com/assets/13734523/19449540/9bf6cf92-946b-11e6-9cc9-746c38d9e74c.gif)

**Comment by nquillin91** [comment]
It should be noted that this probably hasn't been seen as much in the past because of which date format has been chosen in the app configuration. For instance, USA (Monday, October 17, 2016) causes this problem. Whereas LONG (10-17-2016) does not.

**Comment by jharkins2** [comment]
Completed at Revision: 16896
Fixed https://github.com/tsgrp/HPI/issues/1074. Form dropdown styling cleaned up in formsupport.html and formSupport.styl

CR: Marc
