### ISSUE TITLE
Search Traversal - Current document input box not working on firefox

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1217]
When typing in a number into the current doc input textbox, nothing happens. The blur event fails. Only happens on firefox.

![image](https://cloud.githubusercontent.com/assets/13734523/19773343/d43e920c-9c2e-11e6-85a1-3ea3124caf32.png)

**Comment by rosenoam** [comment]
Revision #16894
Standardized the property to target instead of 'srcElement'
