### ISSUE TITLE
View All Documents / OCQuery Issues

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1218]
Add any issues you find as a part of the trunk View All Documents merge below:

**Updates necessary before pushing to release**
- [x] Table view's "Quickview streaming option" doesn't work - undefined object id.  Note - this isn't an action, just something we build up a link for and launch in a new tab
- [x] Issue https://github.com/tsgrp/HPI/issues/1082 is now back, only it's really consistent

Once the above are complete, we can remove the High Priority tag from this issue

**Other updates**
- Unit Tests
- [x] View All Documents
- [x] OCQuery
- [x] Search Result Controls (Backbone-ified)
- [x] TableView
- [ ] Grid View
- [ ] List View
- [x] Facet Search
- [x] Related Objects
- [x] Folder Tree
- [ ] Folder Browser

- Search
- [x] HBASE -  Searching in HPI is broken. OC is returning the results but it is not being displayed on the HPI side

- [x] Search blanking out on long-executing queries > 200 results

- FolderTree
- [x] Controlled Documents- When viewing a folder the related objects field does not display the contents. The error thrown in the chrome debugger is "Uncaught TypeError: OCQuery.Children is not a constructor(…)" at line 578 in foldertree.js

- [x] Controlled Documents- When a document is a part of a work flow an error occurs when viewing the documents related objects. The error thrown is "modalactionhandler.js:190 Uncaught TypeError: Cannot read property 'View' of undefined(…) " at foldertree.js line 153

- [x ] Related objects on Documentum - seems not to be working properly on edge1 with Controlled Docs and AW forms (both have repo relation based relationships)

**Comment by gsteimer** [comment]
Marking this as High Priority since we want to hold back the release build until the big items are resolved

**Comment by mikeblum** [comment]
Solr / HBase search fixed.
------------------------------------------------------------------------
r15386 | mblum | 2016-10-28 12:02:55 -0500 (Fri, 28 Oct 2016) | 1 line

SOLR / SCHEMALESS QUERIES - added server page calculations for Solr and HBase (solr, cough) queries. TODO - move this critical maths into a generic method for all the implementations to call : DCTM, Alfresco, Solr, Solr Schemaless
------------------------------------------------------------------------

**Comment by mikeblum** [comment]
r16429 | mblum | 2016-11-04 16:34:16 -0500 (Fri, 04 Nov 2016) | 1 line

Issue #1223 Searching on Folder in Documentum and Alfresco shows a blank screen - problem was when OCQuery sent ocos to be formatted, context.js would never return a response on the deferred or callback if no OTC was found for a particular type. This would make the query hang indefinately.  app.context.configService.getAdminTypeConfig now always resolves, regardless of a type being configured in the master admin OTC.

**Comment by mikeblum** [comment]
For most of the unit tests involved (Folder Tree, Related Objects, Facet Search) - we simply need to update the contract the unit tests have with OCQuery as opposed to a wholesale re-write.

**Comment by gsteimer** [comment]
@mikeblum - added a few new issues to the list.  Looks like edge1 isn't showing related objects properly.  Also the quick view streaming option in table view no longer works

**Comment by gsteimer** [comment]
@mikeblum - here's the error.  It's actually happening on edge2 as well.  Seems to be a problem with repo-relationship sections:

![image](https://cloud.githubusercontent.com/assets/1377228/20149215/f09b1b4a-a675-11e6-8eaf-960ed06b5516.png)

**Comment by mikeblum** [comment]
------------------------------------------------------------------------
r16494 | mblum | 2016-11-09 14:38:47 -0600 (Wed, 09 Nov 2016) | 1 line

INFO BLOCKS: fix for related objects involving workflow documents and other query-based relations that have info blocks configured. Since OCQuery now formats all OCOs, foldertree no longer needs to worry. CR @jhof. Closing issue flagged in https://github.com/tsgrp/HPI/issues/1218
------------------------------------------------------------------------

**Comment by gsteimer** [comment]
@mikeblum - see the changes I made to the original post.  Also - it looks like that on some tracks, we're getting the issue where you can't navigate back to the search screen.  This happens on edge2 for the Engineering and Engineering Sales tracs:

![back-to-search](https://cloud.githubusercontent.com/assets/1377228/20363170/db7d945c-ac03-11e6-887b-e15995d5a309.gif)

Is it just a config thing or is something else going on?

**Comment by gsteimer** [comment]
@mikeblum here's another issue, probably related to the one above.  If VAD uses a generic doc config, going back to search hoses the type switcher:

![back-to-search2](https://cloud.githubusercontent.com/assets/1377228/20363738/10586a7e-ac06-11e6-8f53-6bbbe9a49d4f.gif)

**Comment by nwoodbine** [comment]
Fixed VAD vs. Search configs in HPI Revision 16681

**Comment by gsteimer** [comment]
Removing High Priority here - we're going to start tracking any VAD/Table view issues separately going forward

**Comment by b-k-white** [comment]
@gsteimer Should we close this if we're tracking new issues separately?

**Comment by gsteimer** [comment]
agreed - closing.
