### ISSUE TITLE
HBase HPI Admin - can't add an attribute

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1220]
Clicking "Add Attribute" throws a knockout binding error.  Currently can't add  attributes to a  type in the HBASE HPI admin.

![selection_150](https://cloud.githubusercontent.com/assets/3905463/19945527/8af55e20-a10e-11e6-85af-ba5a356cb2cd.png)

paging  @nwoodbine

**Comment by renesaladrigas** [comment]
HPI TYPE CONFIG ATTR -- Restoring missing if block that caused OTC attributes to break when searching for the isRepoEditable binding.

CR - Avi King

Fixed with HPI revision 16424
