### ISSUE TITLE
Searching on Folder in Documentum and Alfresco shows a blank screen

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1223]
Searching on `*` or single-character criterias is resulting in a slew of:

__Documentum__

    No type configured on trac for: dmc_java_library

__Alfresco__

    No type configured on trac for: dl_dataList
    No type configured on trac for: cm_systemfolder
    No type configured on trac for: bpm_package

and a blank search screen:

![selection_152](https://cloud.githubusercontent.com/assets/3905463/20019685/7d40f864-a29b-11e6-8820-7fc73b867ffe.png)

**Comment by mikeblum** [comment]
Possibly related too?

- [ ] Search blanking out on long-executing queries > 200 results

**Comment by mikeblum** [comment]
r16429 | mblum | 2016-11-04 16:34:16 -0500 (Fri, 04 Nov 2016) | 1 line

Issue #1223 Searching on Folder in Documentum and Alfresco shows a blank screen - problem was when OCQuery sent ocos to be formatted, context.js would never return a response on the deferred or callback if no OTC was found for a particular type. This would make the query hang indefinately.  app.context.configService.getAdminTypeConfig now always resolves, regardless of a type being configured in the master admin OTC.

**Comment by gsteimer** [comment]
@mikeblum - as we discussed, it looks like the fix to this exposed an issue where the Related Objects section is not showing anything:

![image](https://cloud.githubusercontent.com/assets/1377228/20078416/127db900-a506-11e6-9404-8da8ad86caae.png)

Seems to be an error in the javascript:
![image](https://cloud.githubusercontent.com/assets/1377228/20078430/21fb96fe-a506-11e6-9f22-2169ee554140.png)

**Comment by mikeblum** [comment]
r16455 | mblum | 2016-11-07 17:02:58 -0600 (Mon, 07 Nov 2016) | 1 line

FOLDERTREE -  fix for https://github.com/tsgrp/HPI/issues/1223. Now that getAdminOTC always resolves, need an update to no-op if the otc is undefined
