### ISSUE TITLE
isAnnotated, isRedacted, hasNotes support for Table View

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1226]
As of the latest changes to View All Documents and Search, we no longer have the ability to show certain relationship-based queries in Table View. Originally, View All Documents made separate relationship-based queries to OpenContent to discover whether a particular document has annotations, redactions, or folder notes. 

Going forward, these *meta* attributes will be configured as a part of Search Config - since Search, View All Documents, and Collections all use a centralized search config now. In the HPI Admin we'll have a panel like so:

![selection_154](https://cloud.githubusercontent.com/assets/3905463/20312378/df770ee4-ab18-11e6-816e-5dfd1301dbbc.png)

In  `searchrouter.js` we'll want to pass in a configuration into OCQuery itself that mirrors the settings in the search config:

```javascript
var query = new Ocquery.Collection([],{
                            mode : "client"
                            isAnnotated: true,
                            isRedacted: false,
                            hasNotes: true
                        });
```

This will be resolved into constants that we place in OCQuery's URL that we send to OC. OC will then be responsible for preforming the, at times, expensive relational queries and applying a *meta* attribute to the OCO being sent back to HPI.

**Comment by gpolonus** [comment]
Revision: 16587
Author: gpolonus
Date: Wednesday, November 16, 2016 2:24:16 PM
Message:
VIEW ALL DOCUMENTS ACTION - Removed all custom configurations from the View All Documents configuration in admin except for Select Document Type. Javascript is left in for future possible uses in search. Github Issue #1226 CR : Mike Blum
----
Modified : /trunk/code/app/templates/hpiadmin/actions/customconfig/viewalldocumentsconfig.html

**Comment by gsteimer** [comment]
@gpolonus @mikeblum We want to leave this around until the functionality has been replaced in the new table view, correct?

**Comment by nquillin91** [comment]
We will also be including hasWorkflow as another option that the original View All Documents action executer was performing even though there was no configuration for it

**Comment by dsubramanian92394** [comment]
VIEW ALL DOCUMENTS - added the functionality to display the icons associated with redacted, notes, annotations and workflows for documents configured in VAD. 

CR - Nick
Honorary CR - Ben

At revision:17506
