### ISSUE TITLE
Streamline Mode Confirmation Page not appearing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1231]
On edge2, if I try to complete a form in streamline mode, the confirmation page does not appear.

It looks like it's failing for some reason with DWT.  @CodyWatson15 - can you work with James to see what's going on here?

![image](https://cloud.githubusercontent.com/assets/1377228/20365373/4b74726e-ac0c-11e6-9fc6-57c261185fa4.png)

**Comment by gsteimer** [comment]
Looks like @CodyWatson15 committed some updates and the DWT code is no longer complaining.  However, the confirmation page still no longer appears.  I see no errors in the console, but do see the following warnings:

![image](https://cloud.githubusercontent.com/assets/1377228/20848233/cbe01e3a-b896-11e6-91bd-83c8f055dbda.png)

**Comment by gsteimer** [comment]
Figured out what's going on with @jharkins2.  It looks like the problem is that the code isn't finding the object id properly.  The confirmation page route includes the object ID as the last parameter, so in Documentum, it would look something like this:

`/hpi/activeform/streamline/Simple%20CR/confirmation/090000028001db91`

However, in Alfresco, the ID has slashes - so the route will look something like this:

`/hpi/activeform/streamline/Simple%20CR/confirmation/workspace://SpacesStore/acd7f254-277c-4332-8ee9-763907f1f555`

We can fix this in one of two ways:

- URL encode and decode the ID value
- Do whatever the stage does today

The stage somehow correctly handles a URL like this:
`/hpi/Stage/controlleddocs/workspace://SpacesStore/f1787181-40a6-4728-a166-1597949ea66d%7Cworkspace://SpacesStore/b3da63d6-1210-4cc1-bf1c-4d74f97d58a3`

**Comment by rosenoam** [comment]
Revision: 16749
Fixed the issue where the confirmation page no longer appears. Decoded the objectId in activeformrouter.js and encoded the objectId in psieventmanager.js.
