### ISSUE TITLE
Externalize Google API from HPI

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1234]
The Google Client API that is used for the gmail action get's updated by google without us knowing. This causes the gmail action to break. To fix this issue, we can externalize the Google Client API. This can be accomplished by putting the following line in HPI's index.jsp (right above the script to import the require).

`<script src="https://apis.google.com/js/client.js" type="text/javascript"></script>`

You are then able to remove the google-api-client.js file from the following location:
`HPI_HOME/code/assets/js/libs`

This isn't going into trunk (yet) because we don't like to externalize files. This can be implemented for individual projects.

**Comment by gsteimer** [comment]
Fixed with @RudraVishweshwar's commit for #1299
