### ISSUE TITLE
Delete Collection - any way we can stop refreshing the entire page?

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1235]
With the recent updates to table view, if you delete a collection it needs to refresh the entire page.  On fast environment, this isn't a huge pain, but in slower environments this can be really confusing.  Here's how it looks on edge1:

![collection-delete-slow-env](https://cloud.githubusercontent.com/assets/1377228/20536695/9adf225c-b0af-11e6-87d1-855ae0bdff0f.gif)

Some questions / Notes:

- [ ] Rather than refreshing the entire page, can we just hide the collection item in the list on the left after it's deleted?
- [ ] when loading collections, it's super annoying to see the view below.  Can we replace this with some sort of loading message or something else rather than the edit collection name view and the "no collections" view, which should never display at the same time.

![image](https://cloud.githubusercontent.com/assets/1377228/20536741/d2f83534-b0af-11e6-8732-4912dfb45778.png)

**Comment by rosenoam** [comment]
Fixed issue with revision #16994
