### ISSUE TITLE
Table View - if no icons are configured, the link jumps to the left

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1236]
See the screencam below.  If no icons are configured in table view, the link looks to be leaving room to the left for it, but the whole link jumps over on mouse over:

![table-view-jump](https://cloud.githubusercontent.com/assets/1377228/20683105/4ecfc824-b570-11e6-9f44-507efac237b5.gif)

We should test that that link doesn't jump on hover in table view, including:

- [x] Search Results
- [x] Collections
- [x] View All Docs

**Comment by rosenoam** [comment]
Revision #16709:
Fixed tableview issue where if no icons are configured in table view, the link looks to be leaving room to the left for it, but the whole link jumps over on mouse over.  Added if check to see whether configuredIcon is not empty. Added two new unit tests for this as well.
