### ISSUE TITLE
Complete Task Action - No need for form to display config in the admin

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1238]
The Complete Task Action includes a "Select Form to Display" config:

![image](https://cloud.githubusercontent.com/assets/1377228/20714719/75040f8a-b612-11e6-80c4-17b05e481588.png)

This should be completely ignored in the code now that we have workflow config and workflow form config.  We should:

- [ ] Verify this config is not used
- [ ] Remove it from the admin to prevent confusion

**Comment by rosenoam** [comment]
Revision #16890 
Removed the unnecessary code so it the "Form to Display" will no longer be visible in the admin
