### ISSUE TITLE
View All Documents with different search configs - breaks back button going back to search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1240]
Similar to #1082, this is now consistent behavior when the new View All Documents action is configured to use a different search config vs. HPI Search:

On edge2 if I make the insurance trac use the `insurance` search config, going back works fine.  However, if I change it to use the `genericVADSearch` config, I see this:

![back-to-search](https://cloud.githubusercontent.com/assets/1377228/20730720/bf80a70a-b64c-11e6-82a4-26668a2ff563.gif)

**Comment by rosenoam** [comment]
Revision # 16721: 
Fixed the issue where the new View All Documents action is configured to use a different search config vs HPI Search. The fix was to change the getSearchConfig if check within tableview.js.
