### ISSUE TITLE
Lookup Values for Bulk Upload doesn't work if tracs are mismatched

### ISSUE THREAD

**Issue by eschwarzbeck** [tsgrp/HPI#1244]
If the trac for Search is for example "Insurance" and you go to Bulk Upload and look up values for a "Controlled Document" it will try to find a suitable Search Config for the "Insurance" trac and display a blank tableview.

![lookupvalues2tracs](https://cloud.githubusercontent.com/assets/6668298/20816109/67260064-b7e6-11e6-94ba-7032fe22402a.gif)

**Comment by peterkk** [comment]
closed with hpi commit #16740
