### ISSUE TITLE
Remove From Collection - Impossible to remove just one

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1245]
Like a single potato chip, it is now impossible to remove just one doc from a collection:

**Multiple Docs Selected**
![image](https://cloud.githubusercontent.com/assets/1377228/20840052/869d75ba-b874-11e6-8e71-52b1862e2b38.png)

**Single Doc Selected**
![image](https://cloud.githubusercontent.com/assets/1377228/20840076/9631ceea-b874-11e6-8bc5-63f3196e6c83.png)

This is because the `removeFromCollection` action is a group action:

```xml
	<bean id="action-removeFromCollection" class="com.tsgrp.opencontent.universal.action.executer.RemoveFromCollectionActionExecuter" parent="AbstractActionExecuter" scope="prototype">
        <property name="requiredConditionEvaluatorList">
            <list>
                <value>condition-read-conditionevaluator</value> <!-- read items -->
                <value>condition-collectionwrite-conditionevaluator</value> <!-- write to collection-->
            </list>
        </property>
        <property name="group" value="true"></property>
        <property name="collectionRelation" value="${collection.relation}"></property>
		<property name="description" value="Remove one or more objects from a collection." />
    </bean>
```

So the above makes it impossible for HPI to even allow the admin to configure the action on a single doc.

We need to create a new OC action (same code, just xml config) for a `removeFromCollection-singleDoc` option.  This should allow the admin to configure the `removeFromCollection` action as a single doc action

See `addToCollection` and the badly named `addToCollection-DocViewer` actions as an example.

**Comment by peterkk** [comment]
Closed with HPI commit # 16750
