### ISSUE TITLE
Remove from Collection - Does not show up in right click action when multiple are selected

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1246]
On edge2 collections, currently RemoveFromCollection is configured as a group action only (see #1245).

When I click more than one document in the collection, the remove from collection action correctly appears in the actions menu.

However, when I right click, the group action list is displayed, but the Remove from Collection action does not appear:

![image](https://cloud.githubusercontent.com/assets/1377228/20843372/b4c11eb8-b880-11e6-9425-7144c570ff9f.png)

**Comment by peterkk** [comment]
Closed with HPI commit # 16750
