### ISSUE TITLE
Complete Task - Fails when configured to add folder note

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1247]
When the Complete Task action is configured to allow the user to add a folder note, the form correctly displays the Add Note box:

![image](https://cloud.githubusercontent.com/assets/1377228/20844773/175f19a2-b887-11e6-8cd8-dabb986773c3.png)

However, if I add a note and sign off, I see a javascript error:

![image](https://cloud.githubusercontent.com/assets/1377228/20844809/40f72b42-b887-11e6-9139-5b163d562133.png)

Interestingly enough, I am able to submit the form and the note is correctly created.

**Comment by rosenoam** [comment]
Revision #16804 
 Fixed issue with rendering of CKEDITOR Box as well as took out references to folderNoteRequired since we no longer utilize it.
