### ISSUE TITLE
Table View - Filtering is Slow

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1249]
With the updates to table view, the filtering functionality has gotten unacceptably slow:

**Release2**
This is from before the table view updates - you can see a slight delay in the filtering, but it's acceptable:
![table-view-filter-release2](https://cloud.githubusercontent.com/assets/1377228/20846507/9a9d7216-b88f-11e6-9d40-e69a20768ddc.gif)

**Edge2** 
The filtering is unacceptably slow.  You can't see in this screencam, but even typing in the box is really slow:
![table-view-filter-edge2](https://cloud.githubusercontent.com/assets/1377228/20846515/a63eeb72-b88f-11e6-9163-5be226676313.gif)

This is not a problem with slickgrid.  See here for an example with 50,000 rows and lightning fast filtering:
![table-view-filter-sickgrid](https://cloud.githubusercontent.com/assets/1377228/20846521/ab171aac-b88f-11e6-9b67-7884c857270c.gif)

Above screencap taken from here: http://mleibman.github.io/SlickGrid/examples/example4-model.html

**Comment by peterkk** [comment]
Fixed with HPI commit #16766

**Comment by grahamsinger** [comment]
Reverted fix for this.  IMO, this needs to be branched if multiple are going to work on it.  I've seen a handful of instances where "fixing" something results in breaking something else.

**Comment by grahamsinger** [comment]
Closed with rev16821
