### ISSUE TITLE
Tableview Filter Does Not Work Outside of Search

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/HPI#1255]
The tableview filter in the View All Documents action does not filter down the result set. See example below:

![view all documents filter](https://cloud.githubusercontent.com/assets/4128978/20978969/8911e862-bc70-11e6-8534-1915b5727554.gif)

**Comment by gsteimer** [comment]
Filter doesn't work in:

- [ ] View All Documents
- [ ] Collections
- [ ] Grid View
- [ ] List View

**Comment by nwoodbine** [comment]
HPI Revision 16778

**Comment by gsteimer** [comment]
This works, but not if you have one trac using a generic search config and another trac that uses it's search config.

See edge2 - most tracs use a "generic" config, but the Insurance trac uses the insurance config.

![image](https://cloud.githubusercontent.com/assets/1377228/21103913/17589de6-c04a-11e6-8463-65b563bae2d8.png)

**Comment by grahamsinger** [comment]
Closed with rev16821
