### ISSUE TITLE
Issues and Enhancements for Grid and List View

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1258]
There are various issues with Grid and List view that we need to fix.  Some of these may be Alfresco specific issues

**Issue List**
- Pagination is broken
  - [ ]  Number per page displayed is incorrect
  - [ ] Previous and Next buttons don't work correctly
- [ ] The wrong number of results is returned
- [ ] Duplicate results are returned
- [ ] List view - error for thumbnails
- [ ] List view - property list overlaps thumbnails

**Enhancement List**
- [ ] Thumbnail support on HBase
- [ ] Filter support (like table view)

Search for `Case Document`s with Incident ID `12` in the Incident trac:
![grid-list-view](https://cloud.githubusercontent.com/assets/1377228/21015831/08559f70-bd29-11e6-8c62-de71ea1c3725.gif)

**List View thumbnail error**
![image](https://cloud.githubusercontent.com/assets/1377228/21015870/2d05c28c-bd29-11e6-90cf-940d83a661d8.png)

**List View text overlap**
![image](https://cloud.githubusercontent.com/assets/1377228/21015897/4285bf9a-bd29-11e6-8119-98f9bf614991.png)

For some of the pagination issues, I'm guessing things are really complicated here because Grid and List Views assume server side pagination, whereas Table View assumes client side.  This could also be affecting #1253.  Would it simplify things if we just made Grid and List Views work with client side pagination as well?  If I remember correctly, the reason Grid and List Views used server side pagination was because of the thumbnails.  Given that Documentum and HBase don't currently support server side pagination in HPI, would it be better to just move them all to client side and load the thumbnails on demand based on when the item is visible on the page?

**Comment by gsteimer** [comment]
As with all things search results, we should test any fixes for the above items in Collections as well as Search.  Any updates to Table View must be tested in View All Docs as well.

**Comment by grahamsinger** [comment]
Quick note: Backbone.Paginator is no longer used by TableView as of revision16821.  This undoubtedly confirms that pagination/results per page, will not work with GridView and ListView.

If we want to go back to using a generic paginator/result controls that can be used across all three (a good idea in my mind) then some careful planning will need to be done before hand.

**Comment by gsteimer** [comment]
Closing since we've redesigned grid view and dropped list view.  See #1422
