### ISSUE TITLE
Generic VAD Config typeahead failing for Insurance documents

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1259]
When Generic VAD Config is used for the Insurance trac's View All Documents action., the typeahead does not work. This must be caused by something unique to the Insurance trac, as Engineering and Accounts Payable do not encounter this issue when Generic VAD Config is used.

**Comment by gsteimer** [comment]
@nwoodbine - Once @grahamsinger commits a fix for #1249, do you think this will be fixed?

**Comment by gsteimer** [comment]
This was fixed with @grahamsinger's commit for #1249 - verified on edge2
