### ISSUE TITLE
Table headers and button labels are duplicated

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1260]
See the screenshot below in the View Versions action.  Perhaps something with the localization code in the template is duplicating these labels?

![image](https://cloud.githubusercontent.com/assets/1377228/21110468/e4f2031a-c062-11e6-9268-efea6a930108.png)

**Comment by gsteimer** [comment]
Similar problem in the Send Notification action:

![image](https://cloud.githubusercontent.com/assets/1377228/21110529/2c71a6a0-c063-11e6-9057-1509032783df.png)

**Comment by rosenoam** [comment]
Revision: #16808
Removed the duplicate labels
