### ISSUE TITLE
ocQuery error preventing query-based relationships from returning after stage action

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1261]
See the screencam below.  When a trac has a query-based relationship, it loads fine when entering the stage.  However, after executing an action, this error occurs:

![image](https://cloud.githubusercontent.com/assets/1377228/21110656/ad3504bc-c063-11e6-86ea-d57e4b433544.png)

Some notes:

- [ ] This was found on the Insurance Trac of edge2
- [ ] For some reason, I only see this for the Related Claims relationship.  The Related Policies relationship is also query-based, but I don't see that one fail.
- [x] I've seen this happen after executing any action.  I've tried:
  - Edit Properties (folder or doc)
  - Complete task
  - Add folder note
- It doesn't fail after executing
  - Download Doc
  - Send Notification
  - Start Workflow
- Perhaps it's only happening for actions that tell related objects to refresh?

**Comment by grahamsinger** [comment]
Fixed with rev16835
