### ISSUE TITLE
Start Workflow Admin - no longer have the ability to configure which workflow templates should appear

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1262]
See the screenshots below:

Release2:
![image](https://cloud.githubusercontent.com/assets/1377228/21112188/712cb274-c06a-11e6-86ad-61ea4bf5241f.png)

Edge2:
![image](https://cloud.githubusercontent.com/assets/1377228/21112203/7acbf470-c06a-11e6-821b-8a6d5a234dd9.png)

**Comment by gpolonus** [comment]
Could not replicate bug.
