### ISSUE TITLE
Bulk Upload - Issues with Lookup Functionality

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1264]
Even when the lookup functionality is off in the admin:

![image](https://cloud.githubusercontent.com/assets/1377228/21116890/03cbd8aa-c07d-11e6-91c9-ea5f89a20d24.png)

The button still shows:

![image](https://cloud.githubusercontent.com/assets/1377228/21116926/3775bef0-c07d-11e6-8b73-92e82ac874a0.png)

Also - see above.  The button to finish and upload is not showing at all when in indexing mode:

![image](https://cloud.githubusercontent.com/assets/1377228/21116946/58f25ec6-c07d-11e6-8f3c-1fa1ff92a087.png)

**Comment by gsteimer** [comment]
@b-k-white - odd... So I was able to get the Finish and Upload button to appear on edge after filling out all required fields.  I swear that wasn't happening though when we were looking at it with @cmlewis...

**Comment by cmlewis** [comment]
@gsteimer @b-k-white It was random when it happened. I got it to upload subsequent times, but the Look Up Values button always shows, no matter what is configured in admin.

**Comment by rosenoam** [comment]
Switching the on and off button in admin will now enable and disable the "Look Up" button in both header and folder actions, however now there is a different error when clicking on the "Look Up" button. See GIF below.  
![look up values](https://cloud.githubusercontent.com/assets/22036850/22029272/a22565be-dc9f-11e6-97bc-65add2d12837.gif)

**Comment by RudraVishweshwar** [comment]
Cannot replicate. Closing as non issue.
