### ISSUE TITLE
Notifications - Bell icon does nothing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1265]
Clicking the bell icon should bring up the notifications panel when it's highlighted:

![image](https://cloud.githubusercontent.com/assets/1377228/21155871/6c2040d2-c139-11e6-9c0b-6c195e71e234.png)

However, on edge2 it does nothing.  Here's the javascript error:

![image](https://cloud.githubusercontent.com/assets/1377228/21155898/816e9902-c139-11e6-9039-4bb27b72dc4b.png)

Looks like it has something to do with localization?

**Comment by rosenoam** [comment]
Revision # 16824
Fixed this issues as well as other localization issues
