### ISSUE TITLE
Collections - Dates not formatting

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1266]
See the screencam below.  For some reason, dates in table view for collections are not formatting properly:

![image](https://cloud.githubusercontent.com/assets/1377228/21160079/313b1342-c149-11e6-95d9-05455f4bf3fc.png)

Note that for some reason, I only see this on edge2.  Edge1 works fine.

Note - in the OTC for the type `Document` (which is configured for Collections on edge2), I have the proper filter set up for both of these attributes:

![image](https://cloud.githubusercontent.com/assets/1377228/21160122/53527ee8-c149-11e6-81bb-55f0039a49d9.png)

![image](https://cloud.githubusercontent.com/assets/1377228/21160130/585824c4-c149-11e6-9245-8a1aa443fcd6.png)

**Comment by rosenoam** [comment]
Revision : 16850

Fixed Collection Date format issue.
