### ISSUE TITLE
Query Based Relationships - Should not display self

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1268]
I think some functionality may have been lost with the fixes for #1261 - When a query-based relationship runs, if an object is returned that matches the current object, it should be ignored. 

So - for example - the related policies on edge2:

![image](https://cloud.githubusercontent.com/assets/1377228/21275265/9a35abce-c391-11e6-9348-a6bf8c95ffc6.png)

Since we're looking for folders with matching metadata from the current Folder, the current folder will always be returned.  Therefore, it should be filtered out on the HPI side.  Here, I'm in the 121212 - 2016 policy, but it's listed in the related policies section as well:

![image](https://cloud.githubusercontent.com/assets/1377228/21275305/c8fcedc8-c391-11e6-8a41-65a8512aace9.png)

If the current object is the _only_ one in the list, it should be filtered out and the relationship should be treated in HPI like it's empty.

**Comment by grahamsinger** [comment]
Fixed with rev16849
