### ISSUE TITLE
Advanced Search - NOT EQUALS does not work

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#1270]
My results I got on this query or the opposite of what they should be.

![screen shot 2016-12-21 at 9 28 38 am](https://cloud.githubusercontent.com/assets/8796489/21395963/21e3cea4-c764-11e6-9c04-119e24b85ec2.png)

**Comment by gsteimer** [comment]
tried this on edge1 and it seems to work.  Alfresco query issue?

**Comment by jharkins2** [comment]
Closed at Revision: 15730
OC Alfresco Query Fix: Fixed issue https://github.com/tsgrp/HPI/issues/1270. NOT EQUALS queries against alfresco with only one property now work. Also made general improvements to the building of the alfresco query.

CR: Dan, Peter
