### ISSUE TITLE
Advanced Search - Any/All logic issues

### ISSUE THREAD

**Issue by jharkins2** [tsgrp/HPI#1274]
When performing an attribute search after an advance search, the logic from the advanced search is used in the attribute search (ie if you perform an advanced search using "ANY of these values", then perform an attribute search, the attribute search is performed using OR logic):
![capture2](https://cloud.githubusercontent.com/assets/22036857/21614834/c09c2afa-d1a0-11e6-8bc2-88febbd1082c.PNG)

Also when advance searching with the "ANY of these values" radio option, the option becomes unchecked after performing a search:
![capture1](https://cloud.githubusercontent.com/assets/22036857/21614645/e2c8c6de-d19f-11e6-8865-24a7398bc278.PNG)

**Comment by b-k-white** [comment]
@peterkk This sounds like something we might have fixed, can you check if we merged this to trunk?

**Comment by jharkins2** [comment]
Closed at Revision 16900.
ADVANCEDSEARCH: Fixed issue https://github.com/tsgrp/HPI/issues/1274. Correctly check if we are advanced searching before sending logic, and correctly populate logic based on previous search.

CR: Dan
