### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#128]
Currently, if you leave HPI idle for a long period of time (ex: one hour), the session does not time out.  Most clients that do not use Single Sign On (SSO) have a timeout period.  Most are something like 30 or 60 minutes, but we've had clients that wanted a 15 minute timeout period.

Ideally, this would be done on the OC level.  OC would have the timeout configuration and timeout the OC ticket after X minutes of inactivity.  When HPI (or any other app) tries to use a timed out ticket, they would get a 401 and be redirected to the login page.  After login, the user should be taken back to where he/she left off.

**Comment by b-k-white** [comment]
@gsteimer is this fixed with the hpi timeout in app config?

**Comment by gsteimer** [comment]
@b-k-white - it is, but it's implemented as an HPI timeout vs. something in OpenContent.  I think it's probably fine to close this though.  What we have now is sufficient for client needs.

Thanks for pointing this out!
