### ISSUE TITLE
Bulk Property Edit - Validation ignored on Bulk Screen

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#1282]
Currently, Bulk Property Edit doesn't care if you abide by the form's validations. You can simply press the "Save" button instead of "Next", and it will update the values. See the below screen shots.

**Bulk Screen**

![screen shot 2017-01-16 at 2 31 29 pm](https://cloud.githubusercontent.com/assets/8796489/21998146/b31799a2-dbf8-11e6-90eb-8317467d91cf.png)

**Single Edit Screen (after pressing next)**

![screen shot 2017-01-16 at 2 32 55 pm](https://cloud.githubusercontent.com/assets/8796489/21998174/d16aa200-dbf8-11e6-8701-f6c8a7034a0c.png)

**Comment by gsteimer** [comment]
@b-k-white - merge in change from client?

**Comment by b-k-white** [comment]
Fixed.

HPI - 17232
