### ISSUE TITLE
View All Documents/Search - Repeatedly Sorting on a Date Field Changes the Date Values when HPI's Configured Timezone is Different than User's Local Timezone 

### ISSUE THREAD

**Issue by alieblich** [tsgrp/HPI#1283]
Date values are trying to be converted to the user's local timezone on each sort in Tableview, causing the date values to change on each sort.

Steps to reproduce
- Configure HPI to use a timezone (ex: Central Time - America/Chicago)
- Change the timezone on your machine to a timezone other than what you configured in HPI (ex: Eastern Time America/New York)
- Go to either Search and search on a trac that has a date attribute configured to be shown
- Repeatedly sort on the date field and the date values will change

![changing-dates](https://cloud.githubusercontent.com/assets/14186936/22000230/0ccb122c-dc0c-11e6-9171-aa68b70f6cae.gif)

**Comment by ZachGerth** [comment]
This is related to issue #1206, albeit not obviously.

**Comment by rosenoam** [comment]
Fixed with revision #17065
