### ISSUE TITLE
Pressing escape does not close a modal 

### ISSUE THREAD

**Issue by rosenoam** [tsgrp/HPI#1294]
Even when the keyboard feature is enabled in the admin clicking escape does not close the modal. 
![escape_bug](https://cloud.githubusercontent.com/assets/22036850/22436374/58e53a06-e6e9-11e6-9250-0df4efb1ec1e.gif)

**Comment by gsteimer** [comment]
For reference - this is the admin config that should allow the `Esc` button to close the modal:

![image](https://cloud.githubusercontent.com/assets/1377228/22437964/c59bddc0-e6ef-11e6-8a9a-66823b21c128.png)

**Comment by Swence32** [comment]
@rosenoam We just fixed this for GB last April and I believe I merged it back in. Here is what was causing the issue you are seeing and what we did. Check to see that we have the following changes made in trunk:


> There are two configurations we are interested in:
> 
> backdrop - 'static' prevents clicking outside of the modal from closing it
> keyboard - 'true' allows modal to be closed when pressing Esc
> 
> In Chrome, pressing Esc did nothing. In IE 11, pressing Esc closed the modal.
> 
> Taking a look at the base modal configuration in modalactionhandler.js, keyboard is set to true by default:
> 
> that.$modal.modal({
>                 backdrop: 'static',
>                 keyboard: true,
>                 show: false
>             });
> 
> We override backdrop via hpi admin (modalOptions.backdrop = config.get("modalBackdrop");) but we do not override keyboard, so it is always true.
> 
> So why does IE 11 close on Esc (as it is configured to) but it does not in Chrome?
> 
> http://stackoverflow.com/questions/12630156/how-do-you-enable-the-escape-key-close-functionality-in-a-twitter-bootstrap-moda?answertab=votes#tab-top
> 
> Turns out, we need to set tabindex="1" on the modal div in modalactionhandler.html: 
> 
> <div class="modal" tabindex="-1">
> 
> Now, when keyboard is set to 'true', pressing Esc closes the modal in Chrome.
> 
> We should probably make this property configurable as well. It just takes 'true' or 'false'

.

**Comment by gpolonus** [comment]
MODAL ACTION HANDLER - Made it possible to press Esc to close a modal. Reverted line 1 of revision #16912. Fixed by revision #17281 CR: Devin Swenson
