### ISSUE TITLE
Alfresco Asynchronous Picklists Don't Provide Feedback When Querying

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1295]
With large user bases, the query can still take a noticeable amount of time, even with the 3 character limit. In addition to increasing the characters required before querying, it would be helpful to disable the input and show a spinner when the query is running. 

This should resolve the following issues:

- Losing scope when clicking away during query
- Allowing input to be changed during query, causing returned results to not match input
- Poor UX due to lack of feedback

Talk to me or @dgrumieaux before working on this.

**Comment by RudraVishweshwar** [comment]
Fixed with revision 17231. Async picklists now when the query is loading the results the input box will be readonly and there will a loading spinner next to it. This will help the user understand that his results are being populated.

CR-BW
