### ISSUE TITLE
Search/View All Documents - Sorting on an empty result set causes search result controls to disappear

### ISSUE THREAD

**Issue by mholwey** [tsgrp/HPI#1296]
If the user types in a bogus filter to return no results in search or view all documents, then proceeds to sort by clicking a column heading, the search result controls disappear. We are seeing a similar issue with our client. If this trunk issue requires the same fix as the issue for our client, we will merge the fix into trunk.

![tableview_sort_empty_result_set](https://cloud.githubusercontent.com/assets/22036889/22607908/9f655662-ea1f-11e6-89aa-a259ada04edd.gif)

**Comment by alieblich** [comment]
Fixed with HPI rev#17279
