### ISSUE TITLE
Gmail Integration broken

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1299]
I tried turning on the Gmail integration on edge2 (and release2).  When clicking the button I see:

![image](https://cloud.githubusercontent.com/assets/1377228/22665785/aab42f4e-ec7b-11e6-89f5-ac8beb35142c.png)

![image](https://cloud.githubusercontent.com/assets/1377228/22665796/b58b9f56-ec7b-11e6-8ac4-032d60cedcf8.png)

**Comment by rosenoam** [comment]
Fixed with revision# 17186

**Comment by gsteimer** [comment]
This is happening again.  Let's fix this by addressing #1234

**Comment by RudraVishweshwar** [comment]
Fixed issue in revision 17545 using the externalization fix from  issue 1234. So now we just inject the script in the index.jsp and index.html for it to work as a war and html.

CR-Avi K

**Comment by b-k-white** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revisit this - Gmail API](https://trello.com/c/aodxkemt/665-revisit-this-gmail-api)

**Comment by gsteimer** [comment]
We thought we fixed this with #1234, but it seems to be happening again on edge2:

![image](https://cloud.githubusercontent.com/assets/1377228/24364608/eafbfc52-12d8-11e7-83ae-5cdc61b0574b.png)

**Comment by gsteimer** [comment]
It looks like certain extensions causing the request to 307 and redirect to blank.  See: http://stackoverflow.com/questions/27945501/307-redirect-when-loading-analytics-js-in-chrome .  

After whitelisting the domain in the problem extensions (for me: ABP, Disconnect), it started working again.
