### ISSUE TITLE
Facet Search does not yield new results when there is a null or undefined

### ISSUE THREAD

**Issue by rosenoam** [tsgrp/HPI#1301]
Facet search breaks when there is a null or undefined value. See the attachment below for more detail. 

![department facet search](https://cloud.githubusercontent.com/assets/22036850/22788393/56bfb440-eea5-11e6-9b9e-72b2223e501a.gif)
![image](https://cloud.githubusercontent.com/assets/22036850/22788519/a9e60ac0-eea5-11e6-9c9c-6f93b26f0019.png)

**Comment by gsteimer** [comment]
Note - this seems to only be a problem on alfresco environments.  I don't think the problem is alfresco specific, but the OC DCTM code may be saving us here by changing `NULLSTRING` values to empty string.

**Comment by gsteimer** [comment]
@RudraVishweshwar @peterkk - can those unit tests be committed now?  I don't think the branch you mentioned is coming back to trunk

**Comment by RudraVishweshwar** [comment]
@peterkk can you get your unit tests in today and then I can add my addition

**Comment by gsteimer** [comment]
@RudraVishweshwar @peterkk - any update on this?  I don't want to lose track of it.  I still see this happening on edge2...

**Comment by peterkk** [comment]
Fixed with HPI commit #18110
