### ISSUE TITLE
Searching on repeating fields is broken

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1302]
See gif:

![repeating_attrs](https://cloud.githubusercontent.com/assets/8784597/22790847/1d19809c-eead-11e6-86a0-4d83a9a16aef.gif)

**Comment by gsteimer** [comment]
This fails on Documentum searching on a repeating field too (so this isn't just an issue with a repeating form control on a single valued attr like status)

I'm seeing the same thing - after clicking search, the value changes to `undefined`

**Comment by grahamsinger** [comment]
Fixed with committed revision 17250.
