### ISSUE TITLE
Generate Combined PDF "Remove All Selected Docs" button does not work in the modal

### ISSUE THREAD

**Issue by rosenoam** [tsgrp/HPI#1306]
The remove all selected documents does not remove all the documents when using generate combined pdf in the modal. 
![removealldocumentsbutton](https://cloud.githubusercontent.com/assets/22036850/22844815/8a418e28-efa5-11e6-91d6-9468412e0758.gif)

**Comment by rosenoam** [comment]
Also an issue when you launce combine to pdf from tableview in view all documents

**Comment by rosenoam** [comment]
This is the fix
 if(this.myHandler !== "modalActionHandler") 
wrap this guy around 1914 in advancedCombineToPDF.js

**Comment by gpolonus** [comment]
ADVANCED COMBINE TO PDF - The 'Remove All Selected Documents' now removes all selected documents in all manifestations of this action, because previously the jQuery was having issues with being a modalActionHandler. Also added unit tests for addition. Fixed with revision #17277. CR: Zach Gerth
