### ISSUE TITLE
Group actions not using correct action Id when determining action executor to use in OC

### ISSUE THREAD

**Issue by alieblich** [tsgrp/HPI#1312]
When executing an action, HPI builds up an Action Model with an `ocActionId`. That `ocActionId` is then used as the id for the bean for the corresponding Action Executor. Grouped actions are using the incorrect id when setting the `ocActionId` property. 

For example when registering an action in HPI, you do something like the following:
![actionsids](https://cloud.githubusercontent.com/assets/14186936/23042132/15c492f4-f45d-11e6-9fcf-9de40f9e8101.PNG)
where the `actionId` (circled in blue) should be used as the `ocActionId` in the Action Model. But for grouped actions, the "key" name for the registered action (circled in red) is actually used for the `ocActionId`. Therefore when executing this group action, `customAdvancedCombineToPDF-group` will be the id for the Action Executor bean, and not `advancedCombineToPDF-group` like it should be.

This isn't a show-stopping issue because as long as the "key" name for the registered action corresponds to the Action Executor bean id, everything works as intended, and most of the time both the `actionId` and the "key" name for the registered action are the same so you never notice the issue. 

This issue mainly is that separate values are used for the `ocActionId` for single doc actions vs group actions leading to confusion.

Another issue when fixing this issue is that current actions that have configured around this issue will break.

**Comment by mholwey** [comment]
Fix is in, commit 17350. As mentioned in @alieblich 's comment, current actions that have been configured around this issue will break, so they will need to be reconfigured.
