### ISSUE TITLE
Search Results Always show 10/page - ignore the "Default Search Results Page Size"

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1313]
It seems like the Admin config for choosing the default number of results in table view are ignored. I haven't seen a case that it ever shows anything other than 10 results per page. Is there some other configurations or caching that are preventing this global default from working?

![lice](https://cloud.githubusercontent.com/assets/4850976/23074979/6937834e-f500-11e6-9eae-f8a4fbf4400a.gif)

**Comment by grahamsinger** [comment]
I think I might know why this is happening.  Whoever picks this up, talk to me and I can point you in the right direction.

**Comment by renesaladrigas** [comment]
The default value for search results was hard-coded to always use 10 results per page. We are now retrieving the App Config and using the value found there as the default results, or if not found, still defaulting to 10.

CR - Graham Singer

Fixed with revision: 17352

**Comment by gsteimer** [comment]
Release2 hasn't rebuilt since 12/1, and this functionality seems to be working there

**Comment by dhruvvora94** [comment]
Closed with HPI commit #19645
