### ISSUE TITLE
Zero Configured Folder Actions

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1314]
Our client currently doesn't have any need folder actions.  Currently, if there are 0 folder actions configured, an error is thrown in OC and HPI.

Should we show something like this: 
![image](https://cloud.githubusercontent.com/assets/8784597/23132470/541ab0bc-f753-11e6-9258-7f1f1974338e.png)

Or hide the pane altogether?

**Comment by gsteimer** [comment]
I'd say to just not show the pane at all

**Comment by gsteimer** [comment]
Or - maybe even better, something like this:

- If there are no configured folder actions, hide the pane
- If there are configured actions, but the user has no permissions to see any, show `No Actions Available`

Would that be doable?

**Comment by grahamsinger** [comment]
Yeah, that's how I have it working right now.  That makes sense to me!

**Comment by grahamsinger** [comment]
Committed revision 17343.
