### ISSUE TITLE
Saved Search Dashlets - cannot configure attributes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1316]
It's impossible to configure attributes on saved search dashlets:

![saved-search-admin-fail](https://cloud.githubusercontent.com/assets/1377228/23231005/b8052c9c-f90b-11e6-8747-5130b9b73fc3.gif)

It looks like instead of pulling attributes into the toss across, it pulls only the object name

**Comment by gsteimer** [comment]
Note - it looks like the problem also extends to the search criteria for already set up dashlets:

![image](https://cloud.githubusercontent.com/assets/1377228/23231142/533d5888-f90c-11e6-9cff-556e9efdf41f.png)

**Comment by grahamsinger** [comment]
Committed revision 17344.
