### ISSUE TITLE
Allow the "results per page" selection to persist during a session

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#1317]
Currently, any search run in table view will default the results to the Application's default value in the config. If the user changes the number of results he wants in a page, any future searches will default back to the value of Application Config which might be tedious for the user.

We should implement an enhancement that saves the selected number of results per page for the user (in app.userSearchResultsPP for instance), making sure to weave this selection into the renderings of tableview. This value should be cleared out when the user logs out, just in the same fashion we clean tickets and login names.

**Comment by peterkk** [comment]
Fixed with HPI commit #18077
