### ISSUE TITLE
HPI Solr Portal does not store User Preferences File in Solr

### ISSUE THREAD

**Issue by cadcock** [tsgrp/HPI#1326]
In an HPI Solr Portal fail over environment, not storing the user preferences file within solr causes an issue with a user having to set up a preferences file on each server HPI is running on. This can cause confusion with saved searches and user preferences as they will differ when the user is on one server or the other. A client has requested the user preferences file be stored within Solr to prevent this condition.

**Comment by benallenallen** [comment]
User Preferences can now be stored in a browser's local-storage, so this is the way that I would expect we should store these going forward - As long as saved search works using the localstorage mode as per the below I say we can mark this as "won't fix"

```
  "modules/hpiadmin/preferences/userpreferences": {
    location : "localstorage"
  }
```

**Comment by gsteimer** [comment]
agreed @benallenallen
