### ISSUE TITLE
Custom "Meaning Of Signature" Not Appending Signature page correctly

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1329]
If you configure a "Meaning Of Signature" picklist for the Complete Wizard Approval Task action and a user completes a workflow task selecting one of the "Meaning Of Signature" picklist, The Signature page is not applied to the Document or Workflow Form.

Issue looks to be from overriding the "Role" on the signature event and it not matching the workflow definition.

**Comment by peterkk** [comment]
Fixed with OC commit #16616
