### ISSUE TITLE
Folder Tags and Document Edit Properties

### ISSUE THREAD

**Issue by zkeller** [tsgrp/HPI#133]
Folder tags are based off an attribute's values on documents in the current folder. When someone edits that property, currently the folder tags relation doesn't refresh. To refresh that relation, we would need to do a container refresh on the stage, which would reset all of the relations. Is this something that we want to do? Or should we leave it as it is right now? Should we try to come up with a way to just refresh folder tag relations when we edit document properties?

**Comment by gsteimer** [comment]
Not sure when this was updated, but changing properties now refreshes the Folder Tags listing
