### ISSUE TITLE
Cannot Create AW Form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1335]
Looks like something changed where the create AW form action is displaying nothing:

![image](https://cloud.githubusercontent.com/assets/1377228/24121748/69671178-0d87-11e7-8523-37cfbcb348ca.png)

![image](https://cloud.githubusercontent.com/assets/1377228/24121731/5a5e437c-0d87-11e7-8a73-c101185b14da.png)

@Kovacinski @aviking - I'm guessing that the update to check for accepted object types for form template creation doesn't handle the case where there are no configurations.  We should check for `null` and if so, just do what we did before.

**Comment by Kovacinski** [comment]
Fixed with revision 17575
