### ISSUE TITLE
Download Document action should run PDFs through OpenOverlay

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1337]
When configuring the download document action, it's possible to choose whether the Native rendition or PDF rendition is downloaded:

![image](https://cloud.githubusercontent.com/assets/1377228/24202490/299dac7c-0ee1-11e7-89a7-c90359e3eb99.png)

When downloading the PDF rendition, the current code does not send the PDF through open overlay before streaming it back to the browser.

When making this enhancement, if it's possible to place the code to do this in a generic spot that would be preferable.  I.e. - whenever OC retrieves a PDF rendition, automatically send the document through OpenOverlay.

In either case, we may want to check to see if there are any overlays configured in OO before sending the doc through.  In other words, don't spend the time running the doc through OO if there's no overlays configured.

**Comment by Kovacinski** [comment]
OC Revision: 16189

**Comment by Kovacinski** [comment]
The change was to default overlay to be true when calling content/content
