### ISSUE TITLE
External Form Rules Container does not go away

### ISSUE THREAD

**Issue by peterkk** [tsgrp/HPI#1342]
This issue is in the Form Config in HPI Admin. Within an object type, there is a button labelled 'External Form Rules' that opens up a container that, when clicked away from or when the 'X' is clicked to minimize it, it doesn't do so.

**Comment by peterkk** [comment]
![formconfig](https://cloud.githubusercontent.com/assets/14186903/24303890/a01020ba-1085-11e7-97b3-c3111f376066.PNG)

**Comment by b-k-white** [comment]
You should be able to click the button again as a current work around. That will minimize it.

**Comment by henryerzinger** [comment]
FORM CONFIG - The external form rules container now closes when the 'x' button is clicked or when clicked outside of the container. 

CR - Rene

revision: 18740
