### ISSUE TITLE
Advanced Combine to PDF Page Selection Breaks the Index Page

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1343]
When a user chooses to include/exclude specific pages in the PDF when creating a combined PDF, the "links" incorrectly point to pages that were deleted and the links are broken. 

Observations: It appears that the links are only broken if you remove the first page as one to include in the combined pdf. If you exclude pages 2-x, everything works as you would expect. It is only when page 1 of one of the documents is excluded that the issue occurs.

![loading](https://cloud.githubusercontent.com/assets/4850976/24304126/5cbc9a18-1086-11e7-9ebd-499cd2c38aae.gif)

**Comment by gpolonus** [comment]
Fixed with commit #16571. CR: Bradley White
