### ISSUE TITLE
View All Documents allow for Side-by-side launching of two documents

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1347]
To use side-by-side view within HPI, users have to use the "Related Objects" pane to be able to launch a document in the 2nd pane. For clients that don't use related objects, or prefer to do everything from view all documents, it may be nice to allow "View all Documents" to have either a right click action, or an icon in each row that would replace the "View All Documents" pane with the 2nd document.

**Comment by gsteimer** [comment]
This was implemented in OCMS 3.1
