### ISSUE TITLE
Object Type Config—"Add Attr and Close" doesn't close modal

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1349]
See below:
![otc_add_close](https://cloud.githubusercontent.com/assets/8784597/24516292/b66e3216-153f-11e7-8f22-ac7212b9b117.gif)

**Comment by abrown45** [comment]
Confirming issue exists as of today 8/24/2020

**Comment by mwojno-tsg** [comment]
Commit was resolved with OCMS commit at revision: **25986**. There was a timing issue between a render being called and the app trigger to close the modal. Code was switched around to resolve that timing issue. Unit tests updated. 

CR: aking, gsinger
