### ISSUE TITLE
Trac Config—don't allow tracs with spaces to be created

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1350]
![image](https://cloud.githubusercontent.com/assets/8784597/24524548/9b979442-155c-11e7-90c1-d0a7336b1cb9.png)

Disable the `Create` button if there are spaces in the desired trac name.

**Comment by gsteimer** [comment]
Bumping the priority - this is most likely really easy, and spaces cause problems

**Comment by grahamsinger** [comment]
@gsteimer I have the fix for spaces, but wanted to know if there are any special characters that we could prevent as well.  Should we be preventing certain special characters?

**Comment by gsteimer** [comment]
We probably should prevent any char that has to be URL encoded.  I.e. - unless it comes out of URL encoding as the exact same char, we should block it.

I'm fine though if we just want to say it has to match `[a-zA-Z]` and call it a day

**Comment by grahamsinger** [comment]
Committed revision 17656.

When creating a new trac, only letters and numbers are allowed in the input.  Also, no spaces.
