### ISSUE TITLE
Saved Search Dashlet—message for zero results?

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1351]
Should we have a different UI for saved search dashlets when there are zero results, rather than empty columns?

As seen below, workflow reporting dashlets have a message saying "You have no active workflows". 

One idea would be a configurable message in the admin that will display when there are zero results since saved search dashlets functionality is quite broad compared to workflow reporting.

![image](https://cloud.githubusercontent.com/assets/8784597/24717583/9bd44f18-19f8-11e7-9e84-63ce46949934.png)

**Comment by gsteimer** [comment]
@grahamsinger - putting the wording in the admin would work, but it may work better as two separate L10N keys.  That way, a client could easily have the messages in different languages...

**Comment by gsteimer** [comment]
Also - I'm not sure what happened to saved search dashlets with 0 results, but those did display some sort of "no results" text at one point.

**Comment by LoganLaFollette** [comment]
Fixed at revision: 18133

Zero result saved search queries now say "No results available." instead of a blank table.

**Comment by gsteimer** [comment]
Reopening this one - we can't assume that the collection is empty this way:

```javascript
if (this.collection.length === 1)
            {
                return;
            }
```

Otherwise, if there's only one document in the list, the container will display "No Documents"

**Comment by LoganLaFollette** [comment]
Fixed at revision: 18146
