### ISSUE TITLE
If signin fails, clear warning message after user starts typing a new password

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1353]
After failing a signin, the login UI shows a warning message like:

![image](https://cloud.githubusercontent.com/assets/1377228/24768568/ac15d5a6-1ac8-11e7-89b4-a2d09ebc1fb5.png)

Once the user starts typing in the password field again, it would be nice to hide the "sign in failed" message.  This way, it's easier for the user know when/if the signin fails again.  It also helps the scenario where the signin works (but could be slow) and the failure message is still on the screen.

**Comment by dhruvvora94** [comment]
Closed with HPI commit #18107

**Comment by gsteimer** [comment]
Looks like this works fine in IE11, but isn't behaving properly in Chrome and Firefox.  It looks like it's showing the message, but then immediately clearing it (rather than waiting until the user starts typing a new password).  I'm guessing this is because Chrome and Firefox (correctly) try to put the focus on the password field, whereas IE (incorrectly) does not.

Working in IE:
![ie-correct](https://user-images.githubusercontent.com/1377228/26982512-3f4586de-4cfe-11e7-9882-bcf895970fa7.gif)

Incorrect in Chrome/Firefox:
![chrome-incorrect](https://user-images.githubusercontent.com/1377228/26982519-45f883aa-4cfe-11e7-9560-5d0f83b39d71.gif)

**Comment by dhruvvora94** [comment]
Closed with HPI commit #18116
