### ISSUE TITLE
Creating a new trac strips off the last character in the trac ID

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1354]
I think this is related to the fix for #1350, but it looks like the last character is getting cut off when creating a new trac.  See below:

![image](https://cloud.githubusercontent.com/assets/1377228/24771167/250d98be-1ad2-11e7-8d29-53ae7f52cf68.png)

After creating the trac, notice the trac ID:

![image](https://cloud.githubusercontent.com/assets/1377228/24771191/36240e6c-1ad2-11e7-87b2-a29dcd6849de.png)

**Comment by grahamsinger** [comment]
Committed revision 17690.

When only allowing letters and numbers, we had to check on a keydown event.  This, however, caused the name to always be one letter behind.  Now we have a keydown to only allow letters and numbers, and the key up to properly set what the new trac name should be.
