### ISSUE TITLE
Required Documents - not checking off required tags on Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1356]
See below - on edge1, it looks like it's properly setting the `completed_required_tags` attribute after adding a document:

![image](https://cloud.githubusercontent.com/assets/1377228/24774156/838594b8-1add-11e7-8c81-5e331d8d215a.png)

But the required documents action doesn't reflect that the tag is completed:

![image](https://cloud.githubusercontent.com/assets/1377228/24774175/983c8d76-1add-11e7-9786-e03e7bbd4542.png)

**Comment by gsteimer** [comment]
After talking to @grahamsinger, it seems like a problem with how the front end is figuring out what the tags attribute is (we use `keywords` by default in Dctm)

**Comment by grahamsinger** [comment]
OC revision 16283.
HPI revision 17697.

**Comment by gsteimer** [comment]
@grahamsinger - seems like this one is back after testing for #1369

**Comment by gsteimer** [comment]
This may be slightly different now.  The front end knows that the documents exist:

![image](https://cloud.githubusercontent.com/assets/1377228/26175906/e89139e6-3b19-11e7-84e3-9b921fccbb6b.png)

But the attributes aren't being updated properly:

![image](https://cloud.githubusercontent.com/assets/1377228/26175924/fb11c824-3b19-11e7-9501-8c58784b9682.png)

**Comment by grahamsinger** [comment]
This issue was related to the fact that Alfresco and DCTM use different properties for the "same thing" in the required documents/tags solution.  Real issue is: https://github.com/tsgrp/HPI/issues/1363

**Comment by gsteimer** [comment]
@grahamsinger - after edge updated last night, I'm still not seeing any of the attributes updating when I upload a document to the folder

**Comment by gsteimer** [comment]
My bad @grahamsinger - it was just bad data from a previously created folder.
