### ISSUE TITLE
Force Fit Columns Breaks Pagination

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1362]
The "Force Fit Columns" configuration feature in HPI seems to be a requirement to be configured if users want to be able to click on anything after the first page. In the screencam below you can see:

1. Search
2. Links on page 1 work, links on page 2 also work
3. Disable the "Force Fit Columns" checkbox
4) Re-run the search
5) Links on page 1 WORK, links on page 2 DO NOT work.

![issuegif3](https://cloud.githubusercontent.com/assets/4850976/25106082/4fb00480-238d-11e7-87ec-fccf9425b092.gif)

It seems like this feature is required to be on, which is not the desired solution. 

@Kovacinski and @aviking did some looking into this, so if you start on this bug, they are the primary folks that know the most about what is going on here.

**Comment by eschwarzbeck** [comment]
Closed in #18059
