### ISSUE TITLE
Required Docs - Folder being marked as not complete incorrectly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1364]
Steps to recreate:

1. Create an Employee folder on edge1/2.
1. Add all required documents to make the Employee Complete:
![image](https://cloud.githubusercontent.com/assets/1377228/25141017/cbcb1088-2427-11e7-8d6c-c051b6858b70.png)
1. Add another document in any category (required or not).  The folder incorrectly resets to the original state after step 1:
![image](https://cloud.githubusercontent.com/assets/1377228/25141069/f94e448a-2427-11e7-9f51-a2e6ace5abe2.png)

I tested this on both edge1 and edge2 and saw the same behavior.

**Comment by grahamsinger** [comment]
Fixed with committed revision 16523.
