### ISSUE TITLE
Saved Search Dashlets - Better text when no results found

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1365]
At one point the saved search dashlets displayed some text when 0 results are returned.  It looks like that's no longer happening:

![image](https://cloud.githubusercontent.com/assets/1377228/25151654/f9ff44be-244b-11e7-89b4-badbd6f67de0.png)

We should make it look something like the other dashlets.  For example, here's the Inbox dashlet with no tasks: 
![image](https://cloud.githubusercontent.com/assets/1377228/25151678/0c5e53d4-244c-11e7-8acf-efef38c682e8.png)

**Comment by grahamsinger** [comment]
dupe of https://github.com/tsgrp/HPI/issues/1351?

**Comment by gsteimer** [comment]
Yep, I thought we already had this.. My bad
