### ISSUE TITLE
Bulk Upload - Allow for Synchronous Upload of Documents

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1369]
There are some cases where forcing Bulk Upload into a Synchronous Mode would solve some concurrency issues.  For example see #885 and #1363 

This is currently completed on a client branch, pending merge back to trunk.

**Comment by gsteimer** [comment]
Couple of things to test:

- [ ] One document Upload
- [ ] Multiple document upload
- [ ] Test upload of email MSG and attachments (EX: `HPI\trunk\demo-docs\InsuranceQuote for Public DNO.msg`)
  - Not sure if Intel accounted for this scenario or not...
- [ ] Similar to the last one - other integrations that only send OCOs.  Ex: upcoming Box integration

**Comment by grahamsinger** [comment]
Implemented with rev17911.

**Comment by gsteimer** [comment]
@grahamsinger noticed some inconsistencies with this behavior.  Updates are forthcoming...

**Comment by grahamsinger** [comment]
Re-fixed with committed revision 17960 in HPI
