### ISSUE TITLE
Annotation Link in Document Viewer shouldn't launch "Read Only Mode"

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1371]
Right now, there is logic that launches OpenAnnotate from the "Document Viewer" that seems to always launch OpenAnnotate in "Read Only Mode." If this wasn't a specific requirement from some specific client use case, we should really just let OpenAnnotate decide if the user has actual permissions to annotate the document and not have it always launch in "Read Only Mode". 

This may have been necessary before OA had the ability to resolve permissions, but now that OA checks the user's permissions on the document and decides if they can annotate or not, we shouldn't need to have this hard coded anymore.

The URL that it is launching should be the same URL that is launched by the embedded OA viewer or the launching of OA in a separate tab. It shouldn't include the "mode=readOnly" parameter.

![image](https://cloud.githubusercontent.com/assets/4850976/25397750/0c0336a8-29af-11e7-9b9f-1b3839f5f427.png)

**Comment by acastor** [comment]
Closed by HPI Revision 19198
