### ISSUE TITLE
Send Email Action - Admin not displaying selected attributes when editing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1375]
In the send email action, there's a section of the config that lets the admin choose what attributes to display when listing out documents.  The configuration seems to save properly when going through the admin (and works fine in the actual action), but when returning to the admin, there are inconsistencies.  In the example below, I've already configured Claim Document, Underwriting Document and HPI email message:

![send-email-admin](https://cloud.githubusercontent.com/assets/1377228/25454476/2c533398-2a92-11e7-8d47-282d5b4ffeff.gif)

Some things I've seen:

- [ ] When changing to a type, the selected attributes list is blank, even though some are configured and working properly in the action
- [ ] When coming back, it defaults to one of the configured types, which is fine, but the available attributes are blank (sometimes - this didn't happen in the video)

**Comment by gpolonus** [comment]
Fixed with commit #17994
