### ISSUE TITLE
ShareFile - Do not reuse the same cloud folder for each email

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1379]
Currently, the client that built ShareFile has a customization that controls what folder is created in ShareFile when sending documents.  In trunk, however, we simply look at the `sharefile.upload.folder.name` property to know what folder to upload to.  This presents a problem, because the following scenario happens:

1. I send Document 1 to person A.  Everything's great - they see the doc.
1. I send Documents 2 and 3 to person B.  When person B logs in to ShareFile, he/she sees all three documents

To fix this problem, we should update the functionality so that it creates a new folder (perhaps with `sharefile.upload.folder.name` as the root folder?) each time an email is sent.  Before implementing this, we'll have to discuss how to make the folder name unique.

**Comment by gpolonus** [comment]
Fixed with commit #16652
