### ISSUE TITLE
Search result types should have a default icon

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#138]
![image](https://f.cloud.github.com/assets/4850976/2023584/c1c8d610-885d-11e3-8ab5-9cf67ac15f3e.png)

I don't know the names of icons off the top of my head, and I'm sure clients won't either, so we should set the icons by default to show for table/grid/list to a sensible default rather than just showing blank icons.

This also needs to be done for the "Collections Config" admin.
- [ ] Collections Config Admin
- [ ] Search Admin

![image](https://f.cloud.github.com/assets/4850976/2023615/1d8d33ba-885e-11e3-9890-fa2b6974c59f.png)

**Comment by gsteimer** [comment]
Closing since we've redesigned grid view and dropped list view.  See #1422
