### ISSUE TITLE
View All Docs - Table View sometimes doesn't list columns

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1380]
For some reason, view all documents sometimes produces a view that looks like this:

![image](https://cloud.githubusercontent.com/assets/1377228/25583285/c37968e2-2e56-11e7-8810-aa59c91e83c5.png)

When this happens, clicking the action again generates a view that looks good:

![image](https://cloud.githubusercontent.com/assets/1377228/25583338/fa4c8f3e-2e56-11e7-96ef-3d60a0759156.png)

This issue happens inconsistently (timing issue?) but seems to occur most often after executing a document action.  In the case above, my steps were:

1. View a Doc
1. Delete the doc
1. Click on VAD folder action

**Comment by gpolonus** [comment]
Fixed with commit #18049

**Comment by gsteimer** [comment]
I'm still consistently seeing this on edge2 today:

http://edge2.tsgrp.com/hpi/Stage/insurance/workspace://SpacesStore/3d7ebc7b-36d1-493c-9966-14598134c02e

Same steps - add a doc, delete it, then click on VAD

**Comment by gpolonus** [comment]
Refixed with commit #18071
