### ISSUE TITLE
Get Notifications - Called multiple times after visiting search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1381]
![image](https://cloud.githubusercontent.com/assets/1377228/25585921/92a508be-2e62-11e7-935d-090c709f461b.png)

See the screencam below.  Steps to recreate:

1. Make sure Header Notifications are enabled
1. Open the F12 developer tools and monitor the network tab
1. If you stay out of HPI search, the `getNotifications` call is executed once.  This call is used so that the bell icon knows whether or not to light up.  In my screencam, I'm looking at the `getNotification` requests on Collections, but you can really use any page except search
1. Navigate to search.  `getNotifications` will execute twice
1. Navigate somewhere else (ex: Collections), `getNotifications` will execute three times
1. Every time you go go back to search, `getNotifications` will execute N+1 time
1. Go from Search -> Collections -> Dashboard.  Get notifications will go back to only executing once

Based on the above, it seems that the problem is somehow originating with the search screen.

![notifications-spamming](https://cloud.githubusercontent.com/assets/1377228/25585896/718c3af8-2e62-11e7-80ad-7b66f9dc9444.gif)

**Comment by gpolonus** [comment]
Problem comes from an existing layout being returned to a router in main.js if the layout name parameter is the same as the existing layout's name instead of a new layout being created.

**Comment by gpolonus** [comment]
Fixed with commit 17980
