### ISSUE TITLE
Bulk Upload - Pulls content from previous uploads

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1386]
See the screencam below - from discussions and testing with @benallenallen and @grahamsinger we think this has something to do with the Indexer failing to load the document and then running bulk upload again.

Note - this is on edge2 in the Insurance trac working with a claim and claim documents.  For some reason, this doesn't happen with Policy folders and policy documents.  Timing issue?

![double upload](https://cloud.githubusercontent.com/assets/1377228/25751533/facd57fa-317a-11e7-98fb-93f927e06320.gif)

@benallenallen has also gotten this to happen with large PDFs:

1. Upload Large PDF A - works great, although something in the PDF (bookmarks?) cause OA to fail when trying to display it in the indexer ( @benallenallen - correct?)
1. Without refreshing, upload large PDF B.  It flashes with Alfresco's "dupe node name" error, but then flashes again with a success screen.  The user thinks it worked
1. View PDF B.  It has the content of PDF A.

Some notes based on current research ( @benallenallen and @grahamsinger - feel free to add if I've missed anything)

- This only happens when Bulk Import has the Indexer turned on
- This only seems to happen when the first document fails to load in the Indexer.  Perhaps something isn't getting cleaned up when the indexer view fails?
- This seems to be a timing issue.  With small files on a fast connection, you won't reproduce the error

FYI - @iwhitingTSG

**Comment by grahamsinger** [comment]
Fixed with committed revision 17888.  Hopefully, we can modularize and cleanup bulk upload so that this fix isn't always there.
