### ISSUE TITLE
Create document note HTML malformed

### ISSUE THREAD

**Issue by tbrandstatter** [tsgrp/HPI#1387]
The HTML is malformed when creating a document note in both the right side pane and full pane view. Possibly related to the isDocumentNotes observable.
![capture](https://cloud.githubusercontent.com/assets/6662242/25920866/ea336d68-3598-11e7-8f4b-69f4e8d367a0.PNG)
![capture1](https://cloud.githubusercontent.com/assets/6662242/25920867/eba322c4-3598-11e7-93d2-07a11bf70b4f.PNG)

**Comment by gpolonus** [comment]
Fixed with commit #18004
