### ISSUE TITLE
Advanced Search - Date Format Incorrect

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#1389]
The date format in Advanced Search does not match the configuration. 
![advancedsearchdateformat](https://cloud.githubusercontent.com/assets/8796489/25967579/4b0bd7cc-3654-11e7-961a-7252642e61b1.gif)

**Comment by gsteimer** [comment]
@b-k-white - this is also referenced here as well #1103.  If there are other things there that have been resolved since it was opened, feel free to check them off.

**Comment by b-k-white** [comment]
Fixed with hpi revision 18051
