### ISSUE TITLE
View All Documents - Table View Link Breaks on Firefox and IE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1390]
When clicking on a document link in table view on View All Documents, the following happens in Firefox:

![firefox-vad](https://cloud.githubusercontent.com/assets/1377228/26014119/ee7ae3b8-3720-11e7-8b42-82f768cc57b8.gif)

It does work on IE, but throws up a screen like this on my Window 10 machine:

![image](https://cloud.githubusercontent.com/assets/1377228/26014143/08d61d36-3721-11e7-8add-fb877769cd1f.png)

After clicking `Allow`:

![image](https://cloud.githubusercontent.com/assets/1377228/26014168/1786fdfa-3721-11e7-8e0a-ed7806ba2b5a.png)

Since the page does not refresh, I'm guessing this is a simple update where we don't want the link to actually be an `href` with the URL set to the object ID.  Interestingly enough, on edge1 (Dctm), the link isn't just the ID, it's something like: `http://edge1.tsgrp.com/hpi/090000028000a5b0`.  It looks like it works, but if you were to refresh, that URL throws an error since the trac is missing.

**Comment by grahamsinger** [comment]
Happens on Safari, too, FYI.

**Comment by gsteimer** [comment]
Just a heads up - table view in Search seems fine.  I'm guessing that's because we generate the URL differently to force the user on the trac the search uses.

**Comment by gsteimer** [comment]
I'm not sure how this is happening, but the STS scripts also see something similar when in Send Email (as document action) and Combine PDF.  Let's start with the error we can reproduce and perhaps it will fix the issues the STS scripts are running into.

**Comment by grahamsinger** [comment]
Fixed with committed revision 17949.
