### ISSUE TITLE
BHUDI Bulk Upload Success Leaves Controls Intact

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1391]
When finished bulk uploading a document with the Bulk Heads Up Document Indexing(BHUDI), the Previous/Next/Finish and Upload buttons remain visible, and Finish and Upload remains clickable, but will spin indefinitely.

![image](https://cloud.githubusercontent.com/assets/14186924/26067256/2aa555b8-395f-11e7-9095-a3d30b819763.png)

**Comment by gsteimer** [comment]
@ZachGerth - this is only applicable when Head's Up Indexing is on, correct?

**Comment by ZachGerth** [comment]
Yeah, that's right. I'll update title and description.

**Comment by grahamsinger** [comment]
@gsteimer @ZachGerth  I'm seeing it still show when HUD is off... Based on what I'm seeing, I'd be surprised if that would make a difference.  I wanted to be sure as to what you were seeing so I'm not addressing a different issue.

**Comment by gsteimer** [comment]
@grahamsinger - I think you're right.  Something must've changed recently with the confirmation page, because before with HUD on, it would show the controls while the upload was processing, but they would disappear when the upload finished.  Now, they stick around even after the upload is finished.

**Comment by grahamsinger** [comment]
@gsteimer ok awesome, fix should be in soon!

**Comment by grahamsinger** [comment]
Fixed with committed revision 17929.
