### ISSUE TITLE
Bulk Upload - Throws silent javascript error when more than one document selected and folder attribute inheritance on

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1392]
This only happens on tracs such as the Insurance Trac where Bulk Upload is configured:

1. To inherit folder properties AND
1. More than one type is on the create form

If you try to upload more than one document, you get the following error on the Bulk Properties screen _before_ selecting the object type:

![image](https://cloud.githubusercontent.com/assets/1377228/26076637/04392fba-397f-11e7-86ad-69cf733596e5.png)

Most of the time, this is a silent error that the user never notices (see below).  From talking to @aviking, he thinks its because the code is unnecessarily trying to get the form for the undefined object type.  It makes sense that the object type is undefined at this point because the user hasn't selected it from the dropdown.  We should just catch this case and skip the logic.

I can't be sure, but I have a sneaking suspicion that this is what's causing the issue where _sometimes_ the Bulk Properties screen fails to display (it just sits there grayed out).

**Comment by eschwarzbeck** [comment]
Closed in #17974
