### ISSUE TITLE
Combine PDF - Cannot change downloaded file name

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1394]
See the screencam below.  Combine PDF works fine if you do not change the file name, but as soon as you change the name, a blank error appears and you cannot click the `Create PDF` button:

![combine-pdf-fail](https://cloud.githubusercontent.com/assets/1377228/26159599/a1c555e0-3ae4-11e7-91d6-84299293dcc2.gif)

This happens on edge1 (accordion mode) and edge2 (tabbed mode).

**Comment by CodyWatson15** [comment]
Fixed with commit 17950
