### ISSUE TITLE
Search - Default Sorting Attribute

### ISSUE THREAD

**Issue by mbowen000** [tsgrp/HPI#14]
Clients have expressed interest in having a default sortable attribute for search results (grid view / list view).  Instead of seeing "Not Sorted" it would default to say, the first one in the list... Typically Object Name.

This is an enhancement, since I think by default SOLR is going to give us some kind of ordering to the results based on score / boosting.

This could also be configurable in the search configuration -- do you want to have a default sorting field / which one.

**Comment by mikeblum** [comment]
On a feature branch against trunk for the time being

**Comment by gsteimer** [comment]
marking this as UCR since Grid and List view are targeted for redesign

**Comment by gsteimer** [comment]
Closing since we've redesigned grid view and dropped list view. See #1422
