### ISSUE TITLE
Large videos are not scaled down and extend off the screen

### ISSUE THREAD

**Issue by iwhitingTSG** [tsgrp/HPI#1402]
When large videos are uploaded - they are not resized on the screen to fit the window causing the interface to break and scrollbars to appear.
![video-blowout](https://cloud.githubusercontent.com/assets/18294569/26499562/c089a9fc-41f8-11e7-8a06-8a44a5ee823d.gif)

**Comment by peterkk** [comment]
Closed with HPI commit #18079
