### ISSUE TITLE
Table View - Names too long aren't displayed

### ISSUE THREAD

**Issue by gpolonus** [tsgrp/HPI#1405]
Giving a document a name that is longer in width than the Name column in tableview makes the name disappear:

![image](https://cloud.githubusercontent.com/assets/9874402/26588184/2e69f9a8-451a-11e7-8083-75017594e8db.png)

This might have something to do with the 'tableViewLink' class on the span containing the name, since removing it makes the name come back.

**Comment by gpolonus** [comment]
This bug does not occur in search tableview.

**Comment by gsteimer** [comment]
@gpolonus - I tested this on edge2 search - Insurance trac searching for Underwriting Docs and I see the bug there

**Comment by joehaynes** [comment]
Fixed with SVN commit 18028

CR- Graham

**Comment by gsteimer** [comment]
@grahamsinger @joehaynes - it looks like this is happening again today on edge2, but oddly not on edge1.  Here's what I see on edge2:

![image](https://user-images.githubusercontent.com/1377228/26932345-da600170-4c28-11e7-9966-a30b608a177b.png)

Here's edge1:

![image](https://user-images.githubusercontent.com/1377228/26932377-ef3a93d0-4c28-11e7-82d7-9453f640a6c4.png)

I've tried across multiple tracs on edge2 with the same results

**Comment by gsteimer** [comment]
Not sure what edge2 was doing before, but now I can't get this to happen again.  Perhaps something was cached improperly?
