### ISSUE TITLE
Unncessessary whitespace included below table view in search  

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1406]
After the table view updates for thumbnails were added last week, it seems that there is a ton of unnecessary whitespace included below the table.  See screenshots below:

**release2**
![image](https://cloud.githubusercontent.com/assets/1377228/26594124/1c4f2ab0-452c-11e7-822f-9a11e9dd1f86.png)

**edge2**
The same div extends below the entire visible screen
![image](https://cloud.githubusercontent.com/assets/1377228/26594197/5b74d60e-452c-11e7-917d-c624caed80af.png)

This issue is causing scrollbars to appear unnecessarily and it's breaking the STS scripts (it thinks it needs to scroll even though it doesn't, and the mouse gets off track and clicks where it shouldn't)

Notice the scrollbar on VAD:

![image](https://cloud.githubusercontent.com/assets/1377228/26594269/9c847834-452c-11e7-9dc6-62b87b8ddd1a.png)

**Comment by joehaynes** [comment]
Fixed with svn commit 18039. Links will now work the same way they did before if thumbnails are disabled.

CR- Graham
