### ISSUE TITLE
Table view no longer showing file format icons

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1407]
On edge2, Controlled Docs trac, I have this configured in the admin:

![image](https://cloud.githubusercontent.com/assets/1377228/26594510/7e3d904e-452d-11e7-9638-dcf7d49093a8.png)

But the format icons are not appearing:
![image](https://cloud.githubusercontent.com/assets/1377228/26594521/90130240-452d-11e7-818a-77e70f7e083a.png)

Here's what it looks like on release2:
![image](https://cloud.githubusercontent.com/assets/1377228/26594535/a04a9c36-452d-11e7-9ddb-b744115d1456.png)

Not 100% sure if this is related to the #873 fix last week or the thumbnail update

**Comment by joehaynes** [comment]
Fixed with svn commit 18039. Icons will work the same way as before if thumbnails are disabled. If thumbnails are enabled, they will be formatted within the cell that contains the thumbnail and the link

CR- Graham
