### ISSUE TITLE
Alfresco - Collections not displaying the number of items

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1408]
For some reason, the Collections list on the left side does not show the number of items in the collection anymore.  See below:

**Edge2 - Collection with 3 items**
![image](https://cloud.githubusercontent.com/assets/1377228/26646439/39d5d84c-4601-11e7-8820-ab39ec96ad23.png)

**Edge1 - Collections have number of items populated**
![image](https://cloud.githubusercontent.com/assets/1377228/26646509/8be92eae-4601-11e7-9d44-81fd106815d4.png)

**Comment by gsteimer** [comment]
@ZachGerth - this does seem to be working today...

![image](https://cloud.githubusercontent.com/assets/1377228/26691418/a492bb3e-46c2-11e7-929c-2f71cc85c7e1.png)


Can this be closed?  If so, what changed?  You mentioned something about a commit by @peterkk ?

**Comment by ZachGerth** [comment]
No commit, it was related to edge2 failing to start without errors due to the issue with the Audit bean. It should be able to be changed. I can swing by to explain.

**Comment by ZachGerth** [comment]
Fixed by @joehaynes with OC Revision # 16577.
