### ISSUE TITLE
Bulk Upload Admin - Cloud Configuration Overload

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1409]
Bulk Upload has two "cloud" configuration sections:

![image](https://cloud.githubusercontent.com/assets/1377228/26696597/b5dbee44-46d4-11e7-8bc0-da4d4910cd1f.png)

And then farther down at the bottom:

![image](https://cloud.githubusercontent.com/assets/1377228/26696614/c4a17020-46d4-11e7-945f-b69fa5864c33.png)

This should be combined into one section.  Also - the `Select Multiple` option should say `Allow Select Multiple` and have an info icon that describes what this slider controls

**Comment by peterkk** [comment]
Fixed with HPI commit #18604
