### ISSUE TITLE
Search Indicator Icons - Minor Updates

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1412]
The indicator icons have a few things that could be cleaned up:

- [x] The `Select Icon` box does no pop pup a help bubble like other icon select fields in HPI.  For example:
![image](https://user-images.githubusercontent.com/1377228/26851065-605a4dc2-4acf-11e7-8e0d-0541840ac48c.png)

- [x] Clicking on an indicator icon shouldn't delete it:
![indicator-icon-click](https://user-images.githubusercontent.com/1377228/26851110-8bf5010c-4acf-11e7-82a0-e6fff58559c5.gif)

**Comment by LoganLaFollette** [comment]
Fixed with revision 18108.  Added popup and fixed indicator icon deletion
