### ISSUE TITLE
Table View thumbnails are not type specific

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1415]
In table view admin, you can configure thumbnails per type.  For example:

Underwriting Document - show thumbnails checked
![image](https://user-images.githubusercontent.com/1377228/27049961-8c3717a8-4f76-11e7-9e60-c9285ad9e086.png)

Policy folder - **not checked**
![image](https://user-images.githubusercontent.com/1377228/27049985-a1067e26-4f76-11e7-8268-f3584b730f2e.png)

However, when executing a search on Policy (or any other type in that trac), the table view is still attempting to show thumbnails:

![image](https://user-images.githubusercontent.com/1377228/27050024-c0b2bfdc-4f76-11e7-9975-f729e54d8e38.png)

**Comment by grahamsinger** [comment]
Fixed with revision 18224 in HPI.
