### ISSUE TITLE
Advanced Combine PDF Config—Duplicated Text

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1417]
When Folder Notes are On, the dropdown contains some seemingly duplicated text.

![image](https://user-images.githubusercontent.com/8784597/27201871-ea16efc2-51e4-11e7-9154-547d8e4797ad.png)

**Comment by dsubramanian92394** [comment]
ADVANCED COMBINE TO PDF - I removed hard coded text in the html file in order to avoid duplication. 

CR:Rene 

Fixed with revision 18730 .

**Comment by dsubramanian92394** [comment]
OPEN NEW TAB - added the functionality to open documents in a new tab from the action dropdown. It works for extensions such as .pdf, .docx, .xlsx. 


CR:Michael
