### ISSUE TITLE
Option Disable Open in New Tab on Stage

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1419]
Some clients have "Controlled Print" requirements, which perform special functionality when a document is printed from the ECM system.  These clients would typically disable actions like "Open in New Tab" and "Download Document".  However, there's currently no way to disable the open in new tab arrow in the stage:

![image](https://user-images.githubusercontent.com/1377228/27291984-75859f0a-54d7-11e7-955e-a8b1961c83f5.png)

To support controlled print clients, we should add an option in doc viewer config to disable this arrow.  This option should default to "on" - tracs that need controlled print will be in the minority.

**Comment by gpolonus** [comment]
Accomplished with commit #18302.

**Comment by gsteimer** [comment]
@gpolonus - looks like no matter what the setting is set to in the admin, the arrow is not displaying in the stage.  Tested on edge2 and edge3.

**Comment by gpolonus** [comment]
Fixed with commit #18327.
