### ISSUE TITLE
Consistency across header icons

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1420]
Something small I noticed: 
—the notification bell gets shaded on hover, but the cursor stays the same
—however, the user preferences icon _doesn't_ get shaded on hover and _does_ show the `pointer` cursor

There also is hover text for notifications, but not for User Preferences.

These should be consistent.

![header_icons](https://user-images.githubusercontent.com/8784597/27353216-e851e56a-55c8-11e7-96a4-804c35af5147.gif)

**Comment by henryerzinger** [comment]
HEADER - User preferences button tooltip was not working.  Also the button now highlights when hovered over.

CR- Rene

revision:18731
