### ISSUE TITLE
Collections - Results View does not load

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1425]
It looks like the update to update Table View Config to Search Results Config is causing Collections to fail to load:

![collections-load](https://user-images.githubusercontent.com/1377228/27595311-f48a2b7c-5b21-11e7-926c-8e071ba37416.gif)

It looks like in the admin that the Collections view is still showing the old options for Grid, List and Table Views:

![image](https://user-images.githubusercontent.com/1377228/27595368-114d2f84-5b22-11e7-8a49-8ec740317b1b.png)

**Comment by grahamsinger** [comment]
Fixed with committed revision 18250 in HPI.

**Comment by grahamsinger** [comment]
Re-opening for a sec to address `It looks like in the admin that the Collections view is still showing the old options for Grid, List and Table Views:` part of above issue.

**Comment by grahamsinger** [comment]
Fixed second part with committed revision 18258 in HPI.
