### ISSUE TITLE
Table View links are not clickable

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1427]
When executing a search, the following error occurs numerous times:

![image](https://user-images.githubusercontent.com/1377228/27643212-047d4c02-5be6-11e7-80ab-a30988b9a554.png)

This is causing any link that uses the stage resolver to be unclickable.  Marking as high priority since we cannot push this to release1/2.

**Comment by grahamsinger** [comment]
Fixed with committed revision 18258 in HPI.
