### ISSUE TITLE
Textbox Default Value setting doesn't default

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1431]
Tested on edge2 - the `createObjectControlledDocs` form has the title field set with a default value:

![image](https://user-images.githubusercontent.com/1377228/28074519-632c74e8-661e-11e7-8ca6-508f14f1cc82.png)

However, in Bulk Import, the value does not default:

![image](https://user-images.githubusercontent.com/1377228/28074428-29d20dca-661e-11e7-8d1e-ec0bac81c635.png)

I double checked and BU is configured with the expected form:

![image](https://user-images.githubusercontent.com/1377228/28074592-92d9e888-661e-11e7-902f-5466c27e1482.png)

**Comment by peterkk** [comment]
Closed with HPI commit #18311
