### ISSUE TITLE
Indexer Admin - Javascript issues and clearer instructions

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1433]
- [x] In the indexer admin, there are javascript errors occuring 90% of the time when clicking the "Add Attributes" buttons.  Interestingly, if you continue to click the button, it will work maybe 1 out of 10 times.  No errors occur in the console when clicking the button, but I do see this in the console when the page loads:

![image](https://user-images.githubusercontent.com/1377228/28078673-47f6829c-662b-11e7-829d-52f1a5ba1836.png)

- [x] This is a minor issue, but clicking on the Indexer collapses the `Views` menu completely:
![image](https://user-images.githubusercontent.com/1377228/28078740-737ac0ea-662b-11e7-81ee-7026459fa5e3.png)

- [x] The section that says "Any Properties being Auto-set should also be set on the Form" doesn't seem to be true.  I have the Indexing Status value being auto set in the pre and post sections, but that attribute is not on the form at all.  Most likely will need to follow up with @m-brouillette to see if/how this should be changed.

- [x] The indexer admin in general needs better instructions and text wording.  The interface is confusing and requires knowledge of how the indexer works to configure it properly.  Talk to @m-brouillette and me to come up with a plan on how it should be updated.

**Comment by gsteimer** [comment]
Related to the clearer instructions section - for this configuration:

![image](https://user-images.githubusercontent.com/1377228/28085787-66ad6086-6642-11e7-8e01-983cde295567.png)

This is confusing because:

- When the checkbox isn't checked, the value is what the attribute should be set to when the user saves.  Which makes sense.
- But - if it is checked, then the value changes to what the attribute is set to when the form _isn't_ valid, with the extra textbox set to the value when it's  _valid_

This would make much more sense if we flipped it:

1. The top textbox is what the value should be set to if the form is valid
1. If if checkbox is checked, the bottom checkbox should be what the value is set to if the form is invalid

This way, the top value is always the "default", with the bottom box being the "exception" case.

**Comment by grahamsinger** [comment]
fixed with rev16784 HPI

**Comment by gsteimer** [comment]
The admin looks a lot better, but there are still issues saving configs.  If I fill out some post-indexing properties, save, navigate and come back into the config, all the post-indexing properties are blank:

![image](https://user-images.githubusercontent.com/1377228/35990358-5dcd54fc-0cc9-11e8-8c05-7c48499a568c.png)

**Comment by grahamsinger** [comment]
Forgot to close this, but it was resolved with HPI revision 19807 on Feb. 9th
