### ISSUE TITLE
Indexer - Save with invalid form not changing status as configured

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1434]
Based on this in the Indexer Config:

![image](https://user-images.githubusercontent.com/1377228/28085628-ea93d46c-6641-11e7-9568-12f66c6ee223.png)

The indexing status should be set to `Done` if the form is completed and is valid, and set to `New` if the user exits the form without a valid form.

However, after saving and exiting without a valid form, the status is set to "Done" incorrectly:

![image](https://user-images.githubusercontent.com/1377228/28085733-3b7b2e7a-6642-11e7-926a-9e00902750be.png)

See the screencam below.  If you go into a document and save without a valid form, the document should not drop out of the queue:

![indexer-invalid-form-wrong-status](https://user-images.githubusercontent.com/1377228/28086443-a20c3042-6644-11e7-94ed-cc26e782c5ef.gif)

**Comment by gsteimer** [comment]
Note - this is also happening when you split off a page from a document and finish without the page having all it's properties.  However, in this case, the attribute stays as `Indexing`

**Comment by tbrandstatter** [comment]
INDEXER: the isValid variable is coming in through an object now so updated the way we set the this.isValid variable. 
HPI Revision: 18366

CR: Zach
