### ISSUE TITLE
Admin menu should float so users don't have to scroll back up to navigate

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1436]
It would be nice if the admin menu floated so that you can always navigate to another section, no matter where you are on the page. This would be particularly useful for large admin pages such as Application or Forms.

Image: Admin menu cut by scrolling.
![image](https://user-images.githubusercontent.com/8784125/28185540-5ee47adc-67dd-11e7-84a9-935b00dde248.png)

**Comment by nreiman** [comment]
HPI Revision: 19635 
CR: CC
