### ISSUE TITLE
Active Wizard - displaying answer value instead of display text on Summary Page and in PDF

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1439]
It seems that the summary page and PDF are displaying the answer value and not the display text for certain input types.

**AW Admin - TS Leading Actions - Edge1**

*Question 1 - Checkbox*
![image](https://user-images.githubusercontent.com/1377228/28373284-96108bfc-6c67-11e7-8245-ffd20c04a358.png)

*Page 1 - Summary page - First time through - Correct*
![image](https://user-images.githubusercontent.com/1377228/28373427-f087910c-6c67-11e7-9d30-d8018f9523cd.png)

*Page 1 - PDF - First time through - Displaying value, not display text*
![image](https://user-images.githubusercontent.com/1377228/28373491-1bb24a70-6c68-11e7-8805-19b1ef16bd0b.png)

*Page 1 - Summary Page - After edit and navigate to Summary page - Displaying value, not display text
![image](https://user-images.githubusercontent.com/1377228/28373586-536ecad8-6c68-11e7-8deb-feaf76573666.png)

From what I can tell, this is most prevalent for checkbox and radio button questions, but we should test the other question types as well.

**Comment by grahamsinger** [comment]
Closed with revision 22203.
