### ISSUE TITLE
Start Workflow action after form completion not triggering when groups are tripped for workflow

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1443]
In the Active Wizard Forms section of the admin, the interface gives you the ability to launch an action after form completion.  The two options are:

![image](https://user-images.githubusercontent.com/1377228/28470745-6f3bd578-6e00-11e7-9af8-f363e99fd7ec.png)

When a user is tripped for the first AW priority, this works fine.  However, if a group is selected, the system can't find any approvers and fails with this displayed to the user:

![image](https://user-images.githubusercontent.com/1377228/28470908-e6f7048e-6e00-11e7-9869-542e7444bb2d.png)

However, this is incorrect.  Once you get to the stage, you can successfully kick off the approval route to the group using the Start Approval Route stage action:

![image](https://user-images.githubusercontent.com/1377228/28470946-06306e8a-6e01-11e7-96da-0b0aabb2b1a4.png)

**Comment by gsteimer** [comment]
Not sure what changed, but this seems to be working now.

**Comment by gsteimer** [comment]
@nwoodbine - I may have spoken too soon on this

**Comment by nwoodbine** [comment]
@gsteimer Unable to replicate with a wizard_contributors group task (Priority 1) on release1
![image](https://user-images.githubusercontent.com/8784125/32383045-de12334e-c084-11e7-81e4-271761d354cc.png)

**Comment by gsteimer** [comment]
@nwoodbine - do you think we can close this one?
