### ISSUE TITLE
Grid View - Cannot click on document from search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1445]
If you run a search and switch to grid view, clicking on a document does nothing:

![search-grid-view](https://user-images.githubusercontent.com/1377228/28534104-2b67a04a-7065-11e7-99b4-9a1cb79f3ade.gif)

Clicking on a document should behave the same in grid view as it does in table view.

**Comment by dhruvvora94** [comment]
Closed with HPI commit #19048
