### ISSUE TITLE
Search Tool — Button text cut off

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1447]
See screenshot:
![image](https://user-images.githubusercontent.com/8784597/29079738-9336a530-7c23-11e7-99b1-5f2c1dbbfc35.png)

**Comment by gsteimer** [comment]
Not sure when this happened, but the buttons seem fine now on edge2:

![image](https://user-images.githubusercontent.com/1377228/30609593-6ee4c498-9d41-11e7-8e83-224bdadaec25.png)
