### ISSUE TITLE
OpenAnnotate Supporting Non-TSG-Controlled Documents

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1449]
Currently OpenAnnotate/OpenContent will carry over the annotations if a document is versioned and NOT using that TSG-Controlled behaviours. We'll want to enhance OpenAnnotate/OpenContent's behaviours for annotations to ensure that annotations are not carried over when a normal cm:content object has annotation associations.

Things to ensure work:

- [x] Annotations should not be carried over onto new versions
- [ ] Viewing annotations of previous versions should only show the annotations for that version

**Comment by benallenallen** [comment]
@m-brouillette this is done, correct?

**Comment by m-brouillette** [comment]
The annotations should only appear on the newest version, and the getRelatedChildren call should not return annotation associations not tied to that version. 

In short, yes we should be able to.
