### ISSUE TITLE
User tasks not properly loading on IE11

### ISSUE THREAD

**Issue by mkolas** [tsgrp/hpi#145]
When running HPI on IE11, a client is reporting that inbox tasks are not loading on the Dashboard. In the meantime, they've switched the offending user to a better browser ;)

**Comment by gsteimer** [comment]
@mkolas - I just tried viewing tasks in the Active Wizard inbox and the normal inbox dashlet in IE11 on edge2 and tasks appear fine in both.  I'm going to mark this one as closed unless you disagree.
