### ISSUE TITLE
Toggle missing in Stage —> DocViewer Config

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1451]
There used to be an Enable/Disable slider for "Browser Stream", no?

![image](https://user-images.githubusercontent.com/8784597/29287301-93450d10-80fa-11e7-88b8-5f0053cf8006.png)

**Comment by gsteimer** [comment]
@grahamsinger - yes.  Someone must have accidentally removed it from the interface.  We should add it back, but honestly I've never seen it configured to be off

**Comment by gpolonus** [comment]
Fixed with commit #18481.
