### ISSUE TITLE
Complete Task action allowing complete with invalid form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1452]
See the screenshot below - the form is not valid, but `Complete Task` is enabled:

![image](https://user-images.githubusercontent.com/1377228/29292472-beccf6ca-810c-11e7-88f8-609a2f3ee971.png)

Clicking the button produces an error in OC, as you'd expect.

@cmlewis @nquillin91 - I'm guessing your project will need this fixed.

**Comment by kforbes** [comment]
COMPLETE TASK - Replace button variable names to disable button when required fields not filled. User interface so no unit tests 

CR: Rene
HPI Revision 19175
