### ISSUE TITLE
View All Documents - sort not working properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1453]
On edge2, the insurance trac uses the `insurance` search config for the View All Documents action.  Note - all other tracs that use VAD use the `genericVADSearch` search config.  

In the `insurance` search config, all document types are set to sort like:

![image](https://user-images.githubusercontent.com/1377228/29319830-eec25346-819a-11e7-91cd-fb170fb961b9.png)

This seems to work fine in normal search:

![image](https://user-images.githubusercontent.com/1377228/29319855-087d82d8-819b-11e7-8007-3665bdf74b67.png)

But VAD for policy 121212 is not sorted properly:

![image](https://user-images.githubusercontent.com/1377228/29319869-20bd9da6-819b-11e7-8909-f92fbab6e17d.png)

**Comment by b-k-white** [comment]
Whoever works on this, first check to see if the network tab is returning the results in the correct order. If HPI's Backbone Pagination stuff is the one causing the issue, I may have a fix.

**Comment by gsteimer** [comment]
After looking at this during the HPI/OC weekly meeting, we figured out that it must be looking at the _first_ object in the search config's Attribute Search section to find the sort.  However, in our `insurance` trac, the first one is for Policy Folder, and it's set to `Policy Number`.  

So this fix for this should be to find the sort attribute for the first **non-container** type configured in Attribute Search.

**Comment by wrudnickTSGRP** [comment]
HPI Revision: 19106
