### ISSUE TITLE
Bulk Upload UI For Waiting/Uploading/Finishing

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1454]
Currently there is no indication to the end user that their upload is in progress... They click on the "Finish and Upload" button and suddenly the HUD goes away but the screen is still not grayed out nor are the buttons disabled/hidden. Then while the upload is happening there is no spinner, so if they had multiple documents and are waiting, there is no good indicator that something is happening and/or preventing the user from attempting to click upload again.

![issuegif3](https://user-images.githubusercontent.com/4850976/29384728-c64d62e2-829a-11e7-9a4a-57cfddc72087.gif)

**Comment by gsteimer** [comment]
I'd argue this should be an issue since it's really easy to mess something up, especially if you have a large upload.  

Also, I swear this was already logged somewhere, but I can't find it...

**Comment by henryerzinger** [comment]
BULK UPLOAD - On a bulk upload, the properties view is now removed and a progress bar shows the status of the upload. 

CR-Bradley

revision: 18932
