### ISSUE TITLE
Advanced Combine To PDF Not Working in Search

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1457]
When in search and selecting documents, attempting to select Advanced Combine To PDF via the toolbar results in no response (as well as no console errors). If you right click in the table itself and attempt to click on it, no response. Other actions seem to be responding correctly. 

![advancedcombine](https://user-images.githubusercontent.com/13734523/29567617-74e32ec8-8713-11e7-9992-70d1a29f2de3.gif)

**Comment by nquillin91** [comment]
Config issue - action configured for search group actions can't be configured to use right side action handler. Has to be configured to use modal.

**Comment by gsteimer** [comment]
Note - if you did want this type of functionality (modal in search, right side in VAD), then you'd need a separate search config for each.
