### ISSUE TITLE
Combine PDF - Executing Twice from Search Results Displays Blank Modal

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1458]
See the screencam below - if you run Combine PDF a second time without re-running the search, it shows a blank modal

![combine-pdf-twice-from-search](https://user-images.githubusercontent.com/1377228/29639108-3995ee52-881f-11e7-8b45-d72e4e04de00.gif)

Interestingly, there are no errors or other feedback in the console.  Note that if you run a new search it works fine (no need to hard refresh).

**Comment by henryerzinger** [comment]
COMBINE PDF - Resolved issue where the combined PDF modal was blank when Combine PDF was ran a second time without re-running the search.

CR - Zach

revision: 18789

**Comment by henryerzinger** [comment]
COMBINE PDF - Resolved issue where the combined PDF modal was blank when Combine PDF was ran a second time without re-running the search.

CR - Zach

revision: 18789
