### ISSUE TITLE
Update HPI so mp3 mimetypes are viewed with OpenAnnotate Video Player

### ISSUE THREAD

**Issue by iwhitingTSG** [tsgrp/HPI#1459]
Stage config update to handle mp3 mimetype - they should be opened in the OpenAnnotate Video player - right now they are just presented as a download link in HPI.

**Comment by gsteimer** [comment]
We should have mp3's available in Video.js as well.  I.e. - use OpenAnnotate Video as the highest priority, then Video.js if it's enabled, and finally fall back to download.

**Comment by gsteimer** [comment]
@iwhitingTSG @cchau-tsgrp - is this in trunk?  I opened an `mp3` on edge2 and it looks like it's opening in the OAV player now.

**Comment by cchau-tsgrp** [comment]
@gsteimer Yes it's in HPI trunk already.
We pushed it into HPI trunk on 09/18/17 #18679
Thanks

**Comment by cchau-tsgrp** [comment]
I believe we can close this ticket.

**Comment by gsteimer** [comment]
@cchau-tsgrp - sounds good.  Please close this after committing.  Thanks!
