### ISSUE TITLE
Allow the BUHUDI to be configured to use OpenViewer

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1460]
Right now, the BUHUDI (Bulk Upload Heads Up Document Indexer) always goes to OpenAnnotate in "Annotation Mode". For clients that don't want to use the ability to select text from the document to fill in attribute, but just want to see a preview of the document they are uploading, it might be nice to add a toggle to the admin of the BUHUDI that launches OpenAnnotate in "Open Viewer" mode. This view is nearly 200% faster, so it may give a much better experience to users that just want to preview the document while uploading.

**Comment by m-brouillette** [comment]
I believe currently it goes into "Indexing Mode" which allows the capturing of text.   User would still see documents quick than with "Indexing Mode".  If the documents are mostly non-OCR'd this option would be ideal.

Another potential avenue to get the best of both worlds, would be to optimize Indexing Mode of OpenAnnotate. We could strip out most of the annotation architecture and still get the lion's share of the performance benefit seen with OpenViewer.

**Comment by benallenallen** [comment]
@acastor / @m-brouillette this is done, right?

**Comment by m-brouillette** [comment]
@benallenallen Should be!  - @acastor Could you close this and list the revision number(s)?

**Comment by acastor** [comment]
Yeah this is closed by Revision 19035
