### ISSUE TITLE
Sort Repeating Attributes for more than one document type in Search

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1461]
Currently there is no way to be able to use the "Sort Repeating Attributes" feature on a search config that has more than one type. The admin seems to have a bug that you can only toggle the "Yes/No" slider on the first one in the list:

![issuegif3](https://user-images.githubusercontent.com/4850976/29733897-0581f09c-89b5-11e7-9c5e-28e307006475.gif)

The desired functionality is that if the two documents below both have the "Accounting" and "Finance" attribute values in a repeating field (but not in the same "order"), in Search results and in view all documents, the sorting should make sure that these two documents are next to each other, rather than bubbling the 2nd document to be treated like it starts with "Finance".

Document A:
 - Department
   + Accounting
   + Finance

Document B:
 - Department
   + Finance
   + Accounting

**Comment by aviking** [comment]
Made it a checkbox instead of a slider.
Fixed with HPI commit 18609
CR: Nick Q.
