### ISSUE TITLE
Open Content doesn't handle Alfresco long and NodeRef properties

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1464]
When properties on a node are updated in Open Content, the properties which have types long and NodeRef are set to null. 

When we turn an Alfresco node into an Open Content Object, properties of this type aren't appropriately handled, and so a null value is assigned by default.

**Comment by ZachGerth** [comment]
@dhruvvora94 This can be closed out now right?

**Comment by dhruvvora94** [comment]
Closed with OC commit #17217

**Comment by dhruvvora94** [comment]
Closed with OC commit #17217
