### ISSUE TITLE
Export with Annotations no longer works

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1466]
See the screencam below.  On the insurance trac in edge2, both the email document action is configured to export with annotations:

![image](https://user-images.githubusercontent.com/1377228/29939761-97104706-8e52-11e7-8ef2-264915457d71.png)

In the screencam below, the document I'm emailing has annotations present, but the user is not presented with the page that allows them to choose whether or not to include annotations in the emailed document.

![email-no-export-annotations](https://user-images.githubusercontent.com/1377228/29939787-afd110cc-8e52-11e7-8b7b-62e41524b2c7.gif)

I've tested that this working incorrectly for the following actions:

- [x] Email (As a folder or doc action)
- [x] Combine PDF

**Comment by joehof** [comment]
Fixed with HPI revision 18753 - getAnnotations endpoint changed and short circuited the export annotation logic. Updated the code to know where to look for the annotations that are returned.
