### ISSUE TITLE
Manage Workflow Documents no longer works properly with Chain Versionable Amp Installed

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1467]
When the Chain Versionable Amp is deployed, the search in Manage Workflow Documents is not working properly with documents past version 1.0.  Here's the scenario I set up on edge2:

The following documents exist in the system:

![image](https://user-images.githubusercontent.com/1377228/29974023-2a5ce31c-8ef7-11e7-971d-219e3c1b52a9.png)

In manage workflow documents, if I search for `TSG`, I would expect the following documents to be retrieved: TSG-101 v1.2, TSG-102 through TSG-104 v0.1.  Instead, only the 0.x versions are returned:

![image](https://user-images.githubusercontent.com/1377228/29974059-52519b56-8ef7-11e7-854e-9920fb8b8a44.png)

If I search for `TSG-101` directly, I see this:

![image](https://user-images.githubusercontent.com/1377228/29974074-5f438266-8ef7-11e7-89cd-cc2035fd7b3d.png)

The omission of TSG-101 in the first search for `TSG` makes sense.  This action works by configuring the search in the `config-project.js`.  The `hpi-demo-alf` has this setup:

```javascript
var manageWFDocSearchConfig = {
	searchConfig: [
		{
			paramName: "documentNumber",
			paramValue: "none",
			paramType: "property"
		},
		{
			operator: "equals",
			paramName: "aw_status",
			paramType: "property",
			paramValue: "DRAFT"
		},
		{
			paramName: "Controlled Document",
			paramType: "type",
			paramValue: "Controlled Document"
		},
		{
			paramName: "limit_results",
			paramValue: 25,
			paramType: "options"
		}
	],
```

So it makes sense since there's nothing to specify that it should search on all versions, and TSG-101 v.1.0 is Effective, not Draft.

At a high level, here's how it should work:

- Search for documents as configured on a single property
- Only return documents that are:
  - Draft
  - The latest version (If this is not possible and we have to return multiple versions, it's not ideal, but also not the end of the world - because... see below)
- When selecting a document to be attached, conditions are evaluated.  The document must meet the following conditions in order to be attached to the form.  The document must be:
  - In the Draft state
  - The Latest veresion
  - Not already attached to another AW form

**Comment by ZachGerth** [comment]
This issue seems to be related to the searchAllVersions enhancement for Alfresco search. No results are returned in the query, seemingly because no Active version is returned in the search (since it does not become Active until it's Effective). The fix may be as simple as adding the "searchAllVersions" flag to true.

**Comment by nwoodbine** [comment]
Fixed in HPI revision 18981 and OC revision 17598
