### ISSUE TITLE
Login screen shown in new tab though user is already logged in

### ISSUE THREAD

**Issue by AubreyZielinski** [tsgrp/HPI#1470]
When a user opens a new tab at /hpi and they are already logged into HPI in the same browser, the login screen is displayed. The session is still valid behind the scenes because navigating to anything else (ex. /hpi/search) loads as expected. 

Additionally, there is nothing stopping the user from entering different credentials in the new tab and logging in (QA users were doing this to test functionality for different accounts).

**Comment by gsteimer** [comment]
Sounds like @b-k-white has this fixed on a client branch

**Comment by gsteimer** [comment]
FYI @AubreyZielinski

**Comment by b-k-white** [comment]
Fixed with hpi revision 19,070.
CR - Rene
