### ISSUE TITLE
OpenAdmin Searches Fail After Very First Run

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1474]
When running a search in OpenAdmin, the initial search is built up fine and runs correctly, returning the correct result set.

However, upon any subsequent search, with different parameters, the OpenAdmin instead has a CORS issue, and does not provide any indication that it didn't perform the search.

Worse, this problem is not fixed by a single refresh; it can take multiple refreshes to "clear" the errored state before OpenAdmin can perform searches again.

See the error below.

![image](https://user-images.githubusercontent.com/14186924/30217352-7e06ac1c-947b-11e7-957e-15b4ab54544f.png)

Notably, when it fails on an initial page load, this error does not occur, it simply fails to execute and return the search.

**Comment by ZachGerth** [comment]
It looks like there are actually two separate issues going on. When it initially fails, OpenContent outputs a null pointer error and fails to execute a search. 

With the CORS issue, OpenContent never gets so far as running a search on subsequent runs. 

I'll track both of these on the issue for now but update the header.

**Comment by grahamsinger** [comment]
fixed in client branch

**Comment by grahamsinger** [comment]
Fixed with HPI commit 18708
