### ISSUE TITLE
OpenAdmin Delete Fails to Run

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1475]
See the screenshot below. Note that no nodes are actually returned by that bulk delete search, so the failure probably occurs before any search is executed. 

![image](https://user-images.githubusercontent.com/14186924/30220710-0b97870e-9486-11e7-849f-5925521e305a.png)

**Comment by grahamsinger** [comment]
fixed in client branch, awaiting merge with #1474

**Comment by grahamsinger** [comment]
Fixed with HPI commit 18708
