### ISSUE TITLE
Adding MSG File to Bulk Upload Fails in IE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1476]
Found by STS scripts - if you select a MSG file for Bulk Upload, IE crashes.  It seems to work fine in Chrome and FireFox.

Error in the console is:

![image](https://user-images.githubusercontent.com/1377228/30330579-177dac70-979b-11e7-91ec-8d83dcb6a6eb.png)

Seems to be pointing to this line:

![image](https://user-images.githubusercontent.com/1377228/30330606-2abd881e-979b-11e7-8d5f-7befdb173816.png)
](url)

**Comment by cchau-tsgrp** [comment]
I am not sure if there has a quick fix on "Add .msg file under IE".
For the time being, adding a try-catch, then window.navigator users to something else might be better off.

**Comment by RudraVishweshwar** [comment]
Fixed with commit no. 18779. Made headsup Indexing work for IE when bulkuploading msg files.

CR-Graham S.

**Comment by gsteimer** [comment]
@RudraVishweshwar - this fix works, but it assumes that the BHUDI is turned on.  For tracs that don't have the indexer turned on, you see this:

![image](https://user-images.githubusercontent.com/1377228/31132577-ba7026d2-a822-11e7-99ff-783591bf1877.png)

Which makes sense because the code is blindly assuming it can upload to the configured indexer folder.  We need to first check to make sure Heads Up Indexing is on before executing this logic

**Comment by RudraVishweshwar** [comment]
Fixed with commit #17451 to OC and #18811  in HPI. Heads up indexing works and bulk upload works when it is turned off as well.

CR- George S

**Comment by gsteimer** [comment]
@RudraVishweshwar - I checked edge2 and edge1 and it's failing with the same 'cannot find folder `undefined`' error.  I verified that your changes were deployed overnight and both webapps (OC and HPI on both TCs) were updated.  Additionally, it looks like unit tests are failing as well.

**Comment by RudraVishweshwar** [comment]
Fixed The issue the heads up indexing for bulkupload. It is just that true and false is a string and so the boolean check need to be with === "true". Unite tests pass. Rev no. 18822
