### ISSUE TITLE
Open in New Tab Doesn't Work from actions list in toolbar

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1477]
When right clicking on a document in the table and clicking on "Open in a new tab" the document successfully opens. When going to the toolbar, clicking actions, and then clicking "Open in a new tab" the action fails to execute. 

![opennewtab](https://user-images.githubusercontent.com/13734523/30341952-a392138c-97bd-11e7-8217-f2041a7e8511.gif)

**Comment by dgrumieaux** [comment]
Should the Open In New Tab action show up from the dropdown at all?

**Comment by gsteimer** [comment]
That dropdown is supposed to show single doc actions when only one document is selected in the table, right?  I'd think it should work

**Comment by gsteimer** [comment]
@dgrumieaux - you may be remembering back when that "Open in New Tab" was a pseudo action.  @b-k-white committed an update a couple months ago that makes it a real action

**Comment by gsteimer** [comment]
FYI - this is the error:

**Comment by dgrumieaux** [comment]
Yep, that's what I was thinking of. Thanks for the clarification.

**Comment by dsubramanian92394** [comment]
OPEN NEW TAB - added the functionality to open documents in a new tab from the action dropdown. It works for extensions such as .pdf, .docx, .xlsx. 


CR:Michael

**Comment by b-k-white** [comment]
@dsubramanian92394 If this action isn't working for .jpg or other image files, then please open an issue explaining this.

**Comment by dsubramanian92394** [comment]
Yeah @b-k-white just about to.

**Comment by dsubramanian92394** [comment]
Added a fix for opening new tab when opening a single doc from the actions search result control list

Revision :18805
