### ISSUE TITLE
OpenAnnotate does not autosave when Navigating within HPI

### ISSUE THREAD

**Issue by m-brouillette** [tsgrp/HPI#1478]
If OpenAnnotate is configured to autosave on close, this option currently works even when OA is embedded within HPI.  It works when the window is closed, refreshed, or the user navigates away from HPI completely.  

If the user instead navigates **within** HPI however, no autosave is performed.  This difference is due to the fact that a Backbone navigate is does not currently trigger the same cleanup on the OA iframe that a true browser nav / close would.  

In order to fix this, HPI needs to trigger a cleanup event on its nested OA before a Backbone navigate occurs, ideally in a generic `beforeNavigate ` function in the router.

![noautosaveonnav](https://user-images.githubusercontent.com/8784115/30349162-971eee26-97d7-11e7-96e4-7d93ea0046b8.gif)

**Comment by gsteimer** [comment]
Marking this as 2.6 since I think this is something a client would expect to be there...

**Comment by acastor** [comment]
Closed by Revision 18780

**Comment by gsteimer** [comment]
@acastor @m-brouillette - can you guys test this out on edge2 and see if it's working for you?  I tried a few times and had varying levels of success.  It did work a few times, but other times did not.  See below:

![oa-autosave](https://user-images.githubusercontent.com/1377228/31087974-aac83f08-a764-11e7-9242-56a1aba6378b.gif)

**Comment by m-brouillette** [comment]
Closing for now, tested with IE and Chrome with a 95% success rate between the two.
