### ISSUE TITLE
When Heads Up Indexing is configured for Bulk Upload, only one document at a time can be scanned

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1483]
If you've configured Bulk Upload for Heads Up Indexing as well as OpenCapture, the following files are added to the list:

![image](https://user-images.githubusercontent.com/1377228/30601806-791c796a-9d28-11e7-8d58-2bfe76b6010d.png)

When using Alfresco as a back end, the subsequent upload to the indexing folder causes this error:

```
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "parent_node_id"
  Detail: Key (parent_node_id, type_qname_id, child_node_name_crc, child_node_name)=(1636, 33, 420204962, 104908scanned_document.pdf) already exists.
; SQL []; ERROR: duplicate key value violates unique constraint "parent_node_id"
  Detail: Key (parent_node_id, type_qname_id, child_node_name_crc, child_node_name)=(1636, 33, 420204962, 104908scanned_document.pdf) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "parent_node_id"
  Detail: Key (parent_node_id, type_qname_id, child_node_name_crc, child_node_name)=(1636, 33, 420204962, 104908scanned_document.pdf) already exists.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245)
```
This could be fixed by adding an index value to the name of the document.

One question however - it looks like the `IndexerTemp` on release2 has file names like this: `105744Loss Report.pdf`.  So it seems like we're adding some sort of "dupe node" prevention logic already.  Why isn't this working for scanned documents?

**Comment by nwoodbine** [comment]
Fixed in HPI revision 19188
