### ISSUE TITLE
VideoJS Styling Issues with Audio Files

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1485]
Currently, if you view an mp3 file or another audio file in the HPI Video Viewer, you see the below styling.

![image](https://user-images.githubusercontent.com/14186924/30651763-408fec7a-9dec-11e7-8bb1-8dc58b8f2649.png)

We would ideally want the audio viewer piece to be below the document actions, in line with other document viewers, where it appears clearly delineated as a document.

**Comment by acastor** [comment]
Closed by Revision 19483
