### ISSUE TITLE
Viewing a previous version in stage causes the containerId to change

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1489]
See the screencam below - viewing an old version in the stage updates the container ID, which throws off everything else in the stage that relies on it (like Stage Info). 

![view-previous-version](https://user-images.githubusercontent.com/1377228/30988235-505cc398-a45f-11e7-9bc2-f9beb696e28a.gif)

**Comment by joehaynes** [comment]
Fixed with HPI commit 19007

CR- Zach G
