### ISSUE TITLE
TableView icons off when column is too small in IE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1490]
When the table view column containing the object link and icons (typically `objectName`) is too small, the view is off in IE.  It looks fine on Chrome and Firefox:

**Chrome**
![image](https://user-images.githubusercontent.com/1377228/31020184-da437c30-a4f7-11e7-99d7-001262759305.png)

**Firefox**
![image](https://user-images.githubusercontent.com/1377228/31020206-e73fa0a8-a4f7-11e7-82f6-63beb50ce3a2.png)

**IE**
![image](https://user-images.githubusercontent.com/1377228/31020222-f1ac6c9c-a4f7-11e7-8a7f-357bc6c93251.png)

**Comment by kgarelli** [comment]
Revision 18851 
CR: Nick
