### ISSUE TITLE
Remember last value entered for search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1492]
Per client request, it would be nice if there was an option to tell form support to remember the last selected value(s) in a form field when searching.  For example, if a client has a form field for `Facility` and I only care about one facility, it would be nice if I just had to pick it once and then the value would stick across searches and sessions.

**Comment by gsteimer** [comment]
@CRdouglas - looks like you've committed this - can you comment with the REV numbers of the commit?

Also - it looks like this isn't working on edge2.  It remembers _every_ value entered into search rather than relying on the checkbox in the admin.

**Comment by CRdouglas** [comment]
REV - 19030
