### ISSUE TITLE
Controlled Documents remember Power Promote signatures across major versions incorrectly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1493]
When a document is power promoted, an approval details association is attached to the document (normal routes with an AW form have the association on the form).  

After the document is promoted to 1.0, this association should be frozen and not carried over to 1.1.

**Comment by gsteimer** [comment]
Note - the downstream effect of this is that if you power promote 1.1 -> 2.0, the 2.0 signature page will also include the power promote from 0.x -> 1.0.

**Comment by gsteimer** [comment]
@ZachGerth - looks like this one is not related to #1501 and #1488.  The fixes to the chain versionable amp seem to fix those two, but this one remains:

![image](https://user-images.githubusercontent.com/1377228/31466337-700d932e-ae9c-11e7-91b3-f51416665944.png)

**Comment by ZachGerth** [comment]
Resolved with CVN commit # 9346.
