### ISSUE TITLE
Related Objects - If no relations are configured "Loading..." indicator stays on

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1500]
If somebody doesn't want to use "related objects" there is a misleading "Loading..." section that shows up in Related Objects. It stays with the word "Loading..." and doesn't appear to be tied to any ajax event attempting to resolve anything.

I would expect that the entire "related objects" header shouldn't show up if there aren't any configurations to show anything 

![image](https://user-images.githubusercontent.com/4850976/31396608-7b5b09e4-ada9-11e7-9655-5829aaeaa223.png)

Admin:

![image](https://user-images.githubusercontent.com/4850976/31396623-868b52b0-ada9-11e7-87a4-5a0acc18f6ea.png)

**Comment by henryerzinger** [comment]
STAGE - Resolved issue where a misleading "Loading..." text appeared in the related objects panel when there were no related object configurations.  Instead, a "No Related Objects" label appears. 

CR - Nick

Revision: 19454

**Comment by henryerzinger** [comment]
STAGE - Resolved issue where a misleading "Loading..." text appeared in the related objects panel when there were no related object configurations. Instead, a "No Related Objects" label appears.

CR - Nick

Revision: 19454
