### ISSUE TITLE
Non-Chain Versionable Documents lose information on prior versions

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1502]
We were hoping that we could stop using the `AlfrescoEmbUtil#updateVersionHistory` method with the update to using Chain Versionable for Controlled/Quality documents.  As part of that effort, we did this:

```java
public static void updateVersionHistory(final ServiceRegistry serviceRegistry, final NodeRef nodeRef) {
    	
    	if(!isLegacyType(serviceRegistry, nodeRef)){
		return;
	}
    ...
```

Essentially - only run the method for legacy controlled doc types.  However with that in place, you now run into the following scenarios:

1. Create Insurance document (non-chain versionable) with Word at version 1.0.  See PDF Rendition
1. Version document to 1.1, see new PDF
1. Try to view 1.0 in the stage.  You'll get the download link, not the PDF rendition for 1.0

For example - 1.1 is on the left, and 1.0 is on the right (which used to have a PDF rendition before 1.1 existed)

![image](https://user-images.githubusercontent.com/1377228/31519255-7efa4604-af67-11e7-914f-f11e0623a278.png)

http://edge2.tsgrp.com/hpi/Stage/insurance/workspace://SpacesStore/3d7ebc7b-36d1-493c-9966-14598134c02e%7Cworkspace://SpacesStore/f6153153-7c20-42d6-b780-c16aaecc007e

The same thing is going to happen if you checkin as same version.  This will happen:

1. Create 1.0 doc with content A
1. Checkin content B as the same version, 1.0
1. Checkin content C as version 1.1
1. View version 1.0.  You'll get content A, not content B

**Comment by benallenallen** [comment]
Updated to make everything call updateVersionHistory again.
OC Commit 17535: ALFRESCO VERSIONSTORE :( The versionStore node is created at the same time that the node is created in spacesStore. This is fine if you never update a property on a node without versioning it, but lots of things allow us to alter a shiny new "snapshot" of the node with the correct properties whenever a node is changed. It is up to you to know that you are updating a property/association after the versionStore node has been created and manually calling this method.
CR Zach
