### ISSUE TITLE
VAD Indicator Icons - Default to Off

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1506]
When you create a new View All Documents action, some of the indicator icons default to on:

![image](https://user-images.githubusercontent.com/1377228/31909776-cf6f4980-b800-11e7-94c2-f703ba5ea307.png)

Since these icons are all a performance hit, we should default them to off so they're opt in.  We should also include some text on that screen in the admin to alert the admin that each of these options are a performance hit.  Using the Indicator Icons in Search Results will perform much better.

**Comment by gsteimer** [comment]
It may also be helpful to add some help text for the "is annotated" option - there's a faster/better way to do the same thing, but it only works on Alfresco on HPI with NMAC config:

1. Add the `oa_annotated` aspect as a non-mandatory aspect for your type
2. Set up the icon to be driven off of the `Is Annotated` attribute via the normal search results indicator icon config.

Something like:

```
If you are using Alfresco, consider configuring the 'oa:annotated' non-mandatory aspect on your type and then configure this icon using search results indicator icons instead of here.  This approach will perform much better.
```

**Comment by dsubramanian92394** [comment]
Revision - 19445
CR- Nick
