### ISSUE TITLE
BehaviorFilter Utility Bean

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1508]
At present, whenever working with Alfresco and needing to disable certain behaviors (most notably, auditable behaviors, to prevent modifier/modified changing erroneously), you only have two options available:

1. Do this work inside a bean that can have the BehaviorFilter injected into it. This works fine for things like webscripts, but when working with general OC code can be difficult to move logic into.
2. Be called from a bean that has already disabled the relevant behaviors.

Instead, making the BehaviorFilter bean available similar to the current ServiceRegistryProxy and CoreContext would allow a more flexible way to disable behaviors in custom or core logic, and clean up a lot of the boilerplate surrounding behaviors. This is similar to how we have a OCBaseBehavior class.

**Comment by acastor** [comment]
Closed by OC Revision 17934
