### ISSUE TITLE
Annotations are not visible on previous version in Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1510]
The Golden Snitch project added the ability for annotations to "stick" to a certain version in alfresco when _not_ utilizing the Chain Versioning module.  It looks like some parts work.  For example, I did the following:

1. Annotated a version 1.0
1. Versioned the document to 1.1

When viewing versions on 1.1, it correctly indicates annotations on 1.0, but not 1.1:

![image](https://user-images.githubusercontent.com/1377228/31967948-1a37f5dc-b8d5-11e7-8a3c-75d4b6e44d81.png)

But, when viewing 1.1 and 1.0 side by side, the annotations are not appearing on the 1.0 version.  Note the lit up annotation icon, but no annotations visible (this is a 1 page document):

![image](https://user-images.githubusercontent.com/1377228/31967981-43d35bb6-b8d5-11e7-9496-dba56a5c9cf1.png)

**Comment by gsteimer** [comment]
note that because of #1502, we _do_ need to keep in the call to `updateVersionHistory` for non-chain versionable documents.

**Comment by joehaynes** [comment]
Fixed with OC commit 17589

CR- Zach G
