### ISSUE TITLE
Annotation Search indicator icon does not correctly flip to false upon versioning document

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1511]
Another related issue to #1510 .  When using the `oa_annotated` non mandatory aspect with search indicator icons, the icon incorrectly indicates that the 1.1 version is annotated when it's actually version 1.0 that was annotated.  

Notice that the indicator icon in table view is there, but the document isn't actually annotated (it's 1.0 that was annotated):

![image](https://user-images.githubusercontent.com/1377228/31968980-8eecb734-b8d8-11e7-8af3-5b7ed614e8c8.png)

@benallenallen - will your project need this?

**Comment by RudraVishweshwar** [comment]
Have a fix in. Will get a CR tomo.

**Comment by RudraVishweshwar** [comment]
Fixed with rev no. 17663 in OC. The icon now disappears when new version is created.

CR-Ben A
