### ISSUE TITLE
OpenViewer opened in dual pane mode retains the dual pane size

### ISSUE THREAD

**Issue by eschwarzbeck** [tsgrp/HPI#1512]
If you open up OpenViewer in dual pane mode and then close the second pane the view only retains the half size. It also retains the half size if you try to open up OpenAnnotate from the half size OpenViewer. 

![dualviewopenviewer](https://user-images.githubusercontent.com/6668298/32041780-02239736-b9fb-11e7-9983-867989688075.gif)

**Comment by m-brouillette** [comment]
Could you open an OA issue for this as well?  It just seems like the window resize logic isn't happening properly, which would affect even standalone OA.

**Comment by joehaynes** [comment]
Fixed with OA commit 4275

CR- Marc
