### ISSUE TITLE
ImageViewer Doesn't resize image upon leftbar open in dual pane

### ISSUE THREAD

**Issue by eschwarzbeck** [tsgrp/HPI#1514]
It seems as those we are just missing a hook to re-size the image with dual panes and the left side bar.
![imageviewerleftside](https://user-images.githubusercontent.com/6668298/32108465-63bbd1c8-baf7-11e7-9961-43c1ec254601.gif)

**Comment by joehaynes** [comment]
Fixed with HPI commit 19007. Needed to trigger an event that the panes resized when closing the leftbar.
