### ISSUE TITLE
User Preference to Hide Search Criteria Not Working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1520]
For clients that have small screens (ex: a tablet), horizontal space is at a premium.  So, we built a feature into user preferences that directs HPI search to hide the criteria after a search is run:

![image](https://user-images.githubusercontent.com/1377228/32279972-42c08c8a-bee8-11e7-8e10-f53c344d155a.png)

However, it doesn't seem to be working anymore:

![search-autohide-criteria](https://user-images.githubusercontent.com/1377228/32279977-4cca902c-bee8-11e7-898e-0146b364be3a.gif)

Also - notice how when you manually minimize the criteria, the table width is not correct.  For whoever looks at this, I seem to remember @Kovacinski fixing something similar a while back.

**Comment by nquillin91** [comment]
@gsteimer I briefly looked into this and if I remember correctly the issue is the search triggers a full refresh so it loses context to the fact that the sidebar was just collapsed and then immediately reopens it

**Comment by gsteimer** [comment]
This may be fixed when #1438 is committed.  @henryerzinger - can you test this issue after you commit your updates for public saved search?

**Comment by henryerzinger** [comment]
SEARCH REFRESH - Search side bar now hides after a search is ran when the option is selected in user preferences.

CR - Joe Hof

Revision: 19462
