### ISSUE TITLE
Updating Remembered Search term field to blank breaks search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1521]
If you have a search field that is configured to remember the last search term selected, it fails if you try to remove the value.  See below:

![remember-last](https://user-images.githubusercontent.com/1377228/32293365-d910f51c-bf10-11e7-9a65-6cad53ce00ca.gif)

Error in the console is the same as #1517 

![image](https://user-images.githubusercontent.com/1377228/32293371-de6627d0-bf10-11e7-863a-1654786dcce2.png)

**Comment by nquillin91** [comment]
Fixed with rev 19044
