### ISSUE TITLE
Interacting with Search on All Versions Slider should not allow searching on all documents

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1522]
See the screencam below.  If your search form has the `Search on All` versions slider, the form correctly does not allow searching on all documents.  However, if the user interacts with the slider, the search button works and runs a search on all documents (tested on edge2 and edge1).

![search-all-versions-invalid](https://user-images.githubusercontent.com/1377228/32297962-e3883eac-bf1e-11e7-98d3-ce447c494529.gif)

**Comment by nwoodbine** [comment]
fixed in HPI revision 19082
