### ISSUE TITLE
Viewing a collection no longer displays anything

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1523]
Something has changed since October 3rd (the last time the Collections STS ran successfully) - Collections now no longer display anything when trying to view the collection.  

The error in the console is:

![image](https://user-images.githubusercontent.com/1377228/32335815-bbd16a4e-bfbb-11e7-860e-97ac1a507998.png)

**Comment by acastor** [comment]
Closed by HPI Revision 19049
