### ISSUE TITLE
Flashing Links in View All Documents and Search Results

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1530]
It appears that there is some kind of race condition/event wiring bug when generating the links in search results. It doesn't happen all the time, but sometimes the links are "unclickable" and the text just flashes until a user mouses out of the search results and goes back over the link.

I was able to capture the issue in the "Performance" tab of Chrome, and it appears that the below anonymous onMouseEnter function in tableview.js is getting fired multiple times per second when the issue occurs, so there must be an issue with this getting wired up wrong in some conditions:

```js
self.grid.onMouseEnter.subscribe(function(e, args) {
```

- [ ] do we need to be executing all of that logic every time a user mouses over a link in the first place?
- [ ] can we ensure that we aren't firing that listener every time a user mouses over the item?
- [ ] could this be done once for the whole table?

![image](https://user-images.githubusercontent.com/4850976/32738978-2cb5277c-c864-11e7-8c4e-b23935af2f54.png)

The above screenshot represents 190ms of time elapsed, in which we are executing that on mouse enter function 8 times.

**Comment by joehof** [comment]
There were some funky timing issues going on during the onMouseEnter function that injected a link to content based on the config. Moved the logic of link creation to the hpiFormatter, which runs on rendering of the table, not real-time in a mouse enter with little noticeable performance drops.

Fixed with revision 19192.
