### ISSUE TITLE
Images shrink after property update

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1531]
After editing properties of a document that appears in the image viewer, the image viewer canvas shrinks really small.  See the screencam below:

![image-edit-props](https://user-images.githubusercontent.com/1377228/32808435-a62012a8-c958-11e7-878d-101aeeb0953c.gif)

**Comment by AubreyZielinski** [comment]
I've seen a similar behavior from the PDF viewer in a client environment as well.

**Comment by acastor** [comment]
Closed by Revision 19200

**Comment by gsteimer** [comment]
Ok, so the image doesn't shrink, but now I'm seeing it get cut off consistently.  After editing properties:

![image](https://user-images.githubusercontent.com/1377228/33033088-de39e0f8-cde8-11e7-9200-c4848e1b6a33.png)

**Comment by acastor** [comment]
Closed by HPI Revision 19244
