### ISSUE TITLE
Cannot start workflow on document in Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1532]
For some reason, you can no longer start a non-AW Activiti Workflow on our Documentum demo environments since the Start Workflow action is failing condition evaluators.  For example:

![image](https://user-images.githubusercontent.com/1377228/32862004-3eb939d6-ca1c-11e7-8a70-eb21ae4a0258.png)

However, this document is actually the latest version:

![image](https://user-images.githubusercontent.com/1377228/32862018-4dc8b1b8-ca1c-11e7-8fa8-5ff0d61685bf.png)

Did something change with the Documentum implementation for `isLatest`?  Could it be because the code is assuming that the version label will have `LATEST` in it?  If so, that functionality is only present for our controlled documents.  Outside of controlled docs, the `CURRENT` version is the "latest" version.

**Comment by CRdouglas** [comment]
UPDATE ISLATEST QUERY: Updated a query to take into account the recent change in isLatest. The change has non-controlled docs using a different status, CURRENT as opposed to LATEST which disqualifies them from starting an AW Activiti workflow. The query takes into consideration this change and pulls back any docs that fit the LATEST tag or, the CURRENT tag and don't have a LATEST tag. 

Location: findLatestVersionId()

ISSUE: #1532

CR - Dan Grumieaux

REV: 18968

**Comment by gsteimer** [comment]
@CRdouglas @nwoodbine - looks like this isn't working on edge1.  Additionally, I'm no longer able to start the Form Creation process from a workflow document using the `createWizardForm-fromSingleWfDoc` action.  It's showing me:

![image](https://user-images.githubusercontent.com/1377228/41561307-2c33104c-730f-11e8-8ce8-284acfbad4c4.png)

Even though the document is `LATEST`:

![image](https://user-images.githubusercontent.com/1377228/41561338-4114bbd2-730f-11e8-90cc-62960ba1432e.png)

**Comment by nwoodbine** [comment]
Fixed query with revision 19079
