### ISSUE TITLE
Weird color bars appear when opening a document

### ISSUE THREAD

**Issue by dsubramanian92394** [tsgrp/HPI#1533]
When you navigate from the dashboard to a document , click on VAD and open it before going back to the dashboard and opening a document under a different trac config you see the three color bars as shown in the image below.

![pasted_image_at_2017_11_15_03_53_pm_720](https://user-images.githubusercontent.com/32146353/32862790-e46a8e8c-ca1e-11e7-8c6d-671f6209fca0.png)

**Comment by alieblich** [comment]
I think this has to do with these divs not being hidden by default and rely on waiting for an event that's not being triggered correctly in this scenario to hide them.

`<div id="rightSideActionHandler-message" class="alert alert-success" />`
`<div id="rightSideActionHandler-info" class="alert alert-info" />`

If you guys have any questions I might be able to help out.

**Comment by dsubramanian92394** [comment]
STAGE - added functionality and code cleanup to fix the weird color bar issue cause by a compute function when pane values get modified.

CR - Nick
Revision - 19211
