### ISSUE TITLE
Navigating to HPI in new Window with Authorized Ticket Causes Error

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1534]
It looks like the issue is that we do an immediate cookie check when launching into the login screen. The cookie is correctly authorized and then we attempt to do some navigation. The navigation fails do to a check for our currentApplicationConfig which doesn't exist at the time. 

Deleting the ticket cookie is a quick workaround. 

![authticket2](https://user-images.githubusercontent.com/13734523/32905871-deee1ce2-cac0-11e7-86f0-e8e0744b4351.gif)

**Comment by gsteimer** [comment]
@nquillin91 - so would the fix be to update the code to try to fetch the app config with the cookie ticket?

**Comment by wrudnickTSGRP** [comment]
HPI Revision #19257
