### ISSUE TITLE
Export Search Results to Excel - document links not formatted properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1536]
The export search results to excel feature has a configuration that adds a column to the spreadsheet with a link to the document:

![image](https://user-images.githubusercontent.com/1377228/32958663-c3a892cc-cb84-11e7-9c21-fb0a455525da.png)

In all cases, the links are not including the `application.root.url` prefix.  Here's an example spreadsheet using the Stage resolver:

![image](https://user-images.githubusercontent.com/1377228/32958807-3562a66e-cb85-11e7-9b7a-8350c556e227.png)

Here's what I'm seeing:

- [x] Stage Resolver - missing the application root URL
- [x] Detail View Resolver - no longer supported, can be removed from the admin
- [x] Wizard Resolver - missing the application root URL
- [x] Stream Resolver - missing the application root URL and link not formatted correctly (see below)
- [x]  Folder Browser Resolver - didn't test this one since we don't support it anymore.  Make sure the application root URL is present
- [x] External Link - This one is working properly, but in the admin, the info icon is not displaying anything.  The tooltip should tell the user how to include the object ID placeholder:

![image](https://user-images.githubusercontent.com/1377228/32959129-373be60c-cb86-11e7-99a3-ee3d8830fd6e.png)

**Stream URL Issue** - here's what the URL looks like:

/alfresco/OpenContent/content/content/**undefined**?id=workspace%3A%2F%2FSpacesStore%2F29bf0da5-c37e-4f65-8269-23212a773738&contentType[]=pdf,txt,.*/**true**

The bolded parts are wrong.  See the "launch in new window" icon in the stage (configured for stream content, not OA) for an example of what this link should look like.

**Comment by wrudnickTSGRP** [comment]
HPI revision: 19295
OC revision: 17836

**Comment by gsteimer** [comment]
@wrudnickTSGRP - so this is working much better than before, but the Stream resolver is still wrong.  It looks like for some reason the URL is seeing the `/hpi//hpi` problem:

![image](https://user-images.githubusercontent.com/1377228/33502972-b87f7e96-d6a7-11e7-866b-be97eecd849f.png)

**Comment by wrudnickTSGRP** [comment]
HPI Revision: 19339
