### ISSUE TITLE
Docviewer doesn't always load the document on first click from VAD and Related Objects

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1539]
I noticed that occasionally when clicking on a document, docviewer opens up but doesn't load the document. Clicking on the document again successfully loads it.

![image](https://user-images.githubusercontent.com/13734523/33134206-b98d1284-cf64-11e7-8b79-03d161e1c06a.png)

**Comment by gsteimer** [comment]
I've noticed this as well.  It sometimes happens from related objects as well, so I don't think it's related to VAD or dual pane.  It's gotta be a timing issue because I can't figure out a way to make it happen consistently, and it always works correctly if you click the doc again.

**Comment by nreiman** [comment]
Also noticed if you minimize browser and maximize it again, the docviewer then loads the document.

**Comment by AubreyZielinski** [comment]
This sounds similar to an issue we ran into with PDFViewer in USF's old branch. I think I've fixed it there for them,  but it might not be the best solution. The issue seems to be that the document is sometimes rendering after the final resize call. I moved that call into the afterRender of PDFViewer to ensure that it executes last.

**Comment by nreiman** [comment]
HPI Revision: 19501
CR: NW 

(**Note: will reopen issue if issue continues to persist after adding this code**)

**Comment by AubreyZielinski** [comment]
It looks like this update was applied only to the OA Viewer, but the code moved from docviewer.js will also have to be applied to the rest of the viewers.

**Comment by nreiman** [comment]
HPI Revison: 19507
CR: RS

**(Note: will reopen issue if it continues to persist after adding this code)**
