### ISSUE TITLE
Enhancement: Scheduled job to delete notifications older than xx days

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/HPI#154]
This is just a nice-to-have, unless a client requests it.

Create a scheduled job - either native in Alfresco or Documentum, or as a quartz scheduled job in OC - that deletes notification objects older than a specified number of days.

The job must account for two scenarios:
- The vanilla Activiti implementation - Activiti tasks that are older than the specified date should be completed (applies to Alfresco and DCTM with Activiti)
- The old DCTM implementation - notification repo objects older than the specified date should be deleted (applies to DCTM only)

I don't know enough about scheduled jobs in both repos to design this, so it should probably be assigned to an analyst first to design, then potentially a developer.

**Comment by gsteimer** [comment]
This was implemented as an OC job in OCMS 3.3
