### ISSUE TITLE
Switching directly from standardized table view to either thumbnail view or table view, hides filtering options

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1543]
When a user has selected the standardized table view and then goes to thumbnail view, the filtering options like the facet dropdown and the role based view dropdown will not appear. This is the case in stage. In search, switching directly from standardized table view to thumbnail view will hide filtering options. If routed through table view it will work as expected.

**Comment by gsteimer** [comment]
@dhruvvora94 @benallenallen - marking this UCR unless your client using the standardized view wants this fixed...

**Comment by acastor** [comment]
@dhruvvora94 I have the fix for this

**Comment by acastor** [comment]
Closed by HPI REV 19582
