### ISSUE TITLE
Cannot add more than one Recent Folders dashlet 

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1548]
Currently, you can only have one Recent Folders dashlet on the dashboard.  For example, if I keep the existing recent folders dashlet (tied to `Folder`) on edge2, but also add a Recent Claims dashlet (tied to the claim folder type), the latter works fine but the original Recent Folders section is blank.

We should ensure that this works for both recent folders as well as recent documents.

**Comment by CRdouglas** [comment]
HPI REV 19397
