### ISSUE TITLE
Chain Versionable compatibility conflict with Autofile Module

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1552]
If a type of document utilizes the Chain Versionable module, its documents will error out if used in conjunction with an autofile configuration. Impacts Controlled Document Solution as it utilizes Chain Versionable.

**Comment by b-k-white** [comment]
The timing of the behaviors is problematic, because Chain Versionable has an onMoveNode trigger, which interacts with the autofile. The solution to get these to work simultaneously will involve management of the timing of these behaviors. I can help whoever ends up working on this task.

**Comment by sambelcher1** [comment]
Fixed in OC commit 24496 and Chain Versionable commit 10311

CR: dgrumieaux, gsteimer
