### ISSUE TITLE
Send Document Email action no longer attaches document

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1553]
Something changed in the send email action recently - if you execute it as a document action, it should automatically attach the document.  However, upon launching the action, this message is displayed:

![image](https://user-images.githubusercontent.com/1377228/33783146-0f97bf30-dc21-11e7-8407-66db28549ac7.png)

And the document is indeed not attached...

**Comment by nreiman** [comment]
Revision: 19467
CR: BW
