### ISSUE TITLE
Why Can't I WhyCan'tI?

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1558]
Some odd behavior with the WhyCan'tI action configuration:

1. Once selected, no label appears for the action configuration (corresponding log in console)
![image](https://user-images.githubusercontent.com/8784125/34184808-57afe1a2-e4e7-11e7-9fce-cffad83685cf.png)

2. After selecting the WhyCan'tI action configuration, and attempting to navigate to other actions, the WhyCan'tI title sticks. The image below is from selecting ViewVersions
![image](https://user-images.githubusercontent.com/8784125/34184861-c7c21b68-e4e7-11e7-8596-f15072a2cd0f.png)

3. After navigating to a doc in docviewer, WhyCan'tI doesn't show up in the stage and attempting to refresh causes the stage to hang

**Comment by gsteimer** [comment]
@nwoodbine - it looks like trying to save after adding a label doesn't actually save any updates as well

**Comment by nreiman** [comment]
19466 CR: Natalia Woodbine

**Comment by nreiman** [comment]
Revision: 19466
CR: Natalia Woodbine

**Comment by gsteimer** [comment]
@nreiman - reopening this.  @joehof and I will fill you in

**Comment by nreiman** [comment]
HPI Revision: 19502 
   CR: BW
OC Revision: 17993
   CR: JH, GS
