### ISSUE TITLE
TracConfig stuck on gray screen after refresh

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1561]
After navigating to the TracConfig on edge environments and refreshing the page, the screen hangs as shown below:
![image](https://user-images.githubusercontent.com/8784125/34276318-848af4e8-e666-11e7-8c34-d37e58736e51.png)

This looks like it could be a timing issue, since the console error shows that this.typesNotUsedInTrac is referenced while not defined on refresh.

**Comment by CRdouglas** [comment]
TRACCONFIG: Deleted unnecessary deferred statements and fixed issues with the scope of some of the variables that caused the gray backdrop to prohibit anyone from using tracConfig on refresh. 

CR - J.Hof and GS

REV. 19476
