### ISSUE TITLE
AW Folder Actions no longer Refresh Folder Action List after execution

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1563]
Something has changed in the stage recently related to refreshing folder actions after an action is complete.  We relied on this extensively with AW folder actions.  For example:

1. Form is in Draft
1. Start the Approval or Review Route
1. After executing, the actions would refresh.  For example, can't start the route anymore (it's already started), but you should be able to view workflow status

See below - notice that stage info refreshes after executing the action and closing the modal, but folder actions do not:

![folder-action-refresh](https://user-images.githubusercontent.com/1377228/34539537-7910cc8e-f096-11e7-914a-0d8a984622ee.gif)

From looking at the actions we have configured, I would think the following should refresh the folder action list after executing:

- start review route
- start approval route
- acquire workflow task
- cancel wizard workflow
- complete review task
- complete approval task
- delegate wizard workflow task

Note that normal non-AW workflow tasks are document actions, which seem to be refreshing properly.

**Comment by CRdouglas** [comment]
"FOLDER ACTIONS: Active wizard folder actions wouldn't update after a change occurred in the workflow. Added a deferred statement to wait for the ajax call before updating the object and container ids. CR - Devin"

HPI REV 19500

**Comment by CRdouglas** [comment]
FOLDER ACTIONS: Updated the folder actions spec file so that a unit test could make a call within the deferred added in REV 19500. CR - Devin/Nick/Rene

HPI REV 19505
