### ISSUE TITLE
Search Results JS Error and Losing the Ability to Filter/Paginate Across Views

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1565]
There appears to be an issue with "Search Results" that is preventing the filters from showing up after a user switches views:

![issuegif3](https://user-images.githubusercontent.com/4850976/34679002-49770b7e-f45a-11e7-9a14-ddcbbf85bd0e.gif)

1. Switching from Table View to Standardized view removes the filters/predefined views (this is good!)
1. Switching back to Table View (or thumbnail view), the filters/predefined views are not displayed again (this is bad!)

The JS error might be a red herring, but we should fix it as a part of this issue as well

**Comment by gsteimer** [comment]
@benallenallen - I'm also seeing issues in search.  If you run a search on edge2 for claims documents, the grid/table/lock/refresh icons aren't there until you hard refresh.

![image](https://user-images.githubusercontent.com/1377228/34679328-3b0f5496-f45b-11e7-8b99-791a3a26f4b7.png)

@dhruvvora94 @joehaynes

**Comment by gsteimer** [comment]
Also, I'm seeing this:

1. Run a search on Claim Doc
1. Hard Refresh
1. Try to run a search on Claim Folder.  Fails with this error:

![image](https://user-images.githubusercontent.com/1377228/34679450-9a71db66-f45b-11e7-811b-4ce1bb52bb6a.png)

**Comment by joehaynes** [comment]
The console error has been happening for a few months now. Here it is outside of the require

![image](https://user-images.githubusercontent.com/22036837/34679572-ff8fce86-f45b-11e7-9088-faca8f8b0a6c.png)

When switching away from the standard view the grid is correctly "opened" back up, allowing the user to change which columns are visible/sort/etc, so it looks like just the search controls need to be fixed

**Comment by acastor** [comment]
Closed by REV 19582
