### ISSUE TITLE
Some searches on Documentum do not display results properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1566]
See below - on edge1 some searches are returning all of their results properly, but the table does not return any rows:

![image](https://user-images.githubusercontent.com/1377228/34687591-d683ddca-f474-11e7-969b-eba986efb8b2.png)

This only happens for some search combinations, but not for all:

- Works:
  - Controlled doc with Document Number `TSG-102` (2 results)
  - Wizard Forms with Name `SCR` (106 results)
  - Policies with policy number `1212` (1 result)
  - Claims with claim number `123` (3 results)
- Does not work:
  - Controlled Doc with Document Number `TSG` (22 results)
  - Policy with policy number `12` (54 results)

The wizard form search is the outlier.  If it wasn't for that search working, I'd think that this has something to do with search results that return more than one page.  However, that search returns over 100 results fine.

**Comment by joehof** [comment]
Closed with OC revision 18079.

The current page was set to 0, so the user saw nothing even though data came back in the search. This is mostly a temp fix, still doesn't explain why some sets of data with more than one page returned, like Wizard form search on SCR. We should continue to do a deep dive in this impl.
