### ISSUE TITLE
form support date picker should allow users to type in dates

### ISSUE THREAD

**Issue by mkolas** [tsgrp/HPI#157]
A client wishes to be able to type in dates as opposed to selecting them through the date picker. From what I hear this has been attempted and deemed fairly troublesome... worth a possible second try?

**Comment by b-k-white** [comment]
@gsteimer I thought we had typeable dates now?

**Comment by gsteimer** [comment]
@b-k-white - yeah, I think we do - it's an option on form config I believe.  We can close this after verifying.

**Comment by b-k-white** [comment]
![screen shot 2017-02-16 at 10 01 28 am](https://cloud.githubusercontent.com/assets/8796489/23029070/f26d1c14-f42e-11e6-8afa-a90db39ad0db.png)


Confirmed.
