### ISSUE TITLE
Folder Actions Duplicated

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1570]
See below.  On edge2, I create a policy folder and it sends me to the folder.  All folder actions are incorrectly duplicated.  Refreshing the screen clears up the issue:

![image](https://user-images.githubusercontent.com/1377228/34845478-954e9832-f6da-11e7-8b85-8f70c234a2fc.png)

**Comment by CRdouglas** [comment]
FOLDER ACTIONS: Folderactions were duplicating on folder creation, but then acting normally after refresh. Took the startListening function out of the initializer and put it into the after render. This was done to make sure that the render had time to fully populate the folderactions without any synchronous listener calls. 

NEEDS UNIT TESTS 

CR - Avi King"
HPI REV19957

**Comment by gsteimer** [comment]
Looks like the root cause of this issue was not fixed.  I'm seeing folder actions duplicated after deleting a document in the stage:

![folder-actions-duplicate](https://user-images.githubusercontent.com/1377228/35873096-5c5c5736-0b2e-11e8-9b5b-3bec29813396.gif)

**Comment by gsteimer** [comment]
I'm also seeing folder actions get duplicated after opening a document and changing doc properties.

**Comment by gsteimer** [comment]
Seeing this again when using Bulk Upload two times in a row.  The first time is fine, but the second time duplicates the actions:

![image](https://user-images.githubusercontent.com/1377228/36163235-614d5206-10ae-11e8-8151-046a65655e53.png)

**Comment by nreiman** [comment]
HPI Revision: 19889
CR: RS, NW
