### ISSUE TITLE
Update Github Wiki with latest build information

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1572]
With the latest dependency updates (see #1529) the current Wiki pages are out-of-date with regards to how to build and deploy HPI. Need to update:

- node version
- build commands
- deployment instructions

**Comment by gsteimer** [comment]
@dgrumieaux - removed the issue tag since this is really documentation related.   Maybe we add a `documentation` label at some point?

**Comment by dgrumieaux** [comment]
Redid the new page, see it here: https://github.com/tsgrp/HPI/wiki/Building-And-Deploying-HPI-2.x-From-Source

**Comment by dgrumieaux** [comment]
@cchau-tsgrp - Should add some nodist commands to make it easier to get going

**Comment by gsteimer** [comment]
@dgrumieaux - can this be closed?

**Comment by dgrumieaux** [comment]
Yes, the documentation has been updated.
