### ISSUE TITLE
Indexer Mode in OpenAnnotate Hook Failing with JS Error

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1575]
Indexer Mode no longer functions when text is highlighted to pull the text that was highlighted into an HPI field:

JS Error below is emitted every time someone jumps from one field to another field in HPI

![image](https://user-images.githubusercontent.com/4850976/34962561-cce36818-fa09-11e7-8ed3-21930788089f.png)

![image](https://user-images.githubusercontent.com/4850976/34962571-d63d262e-fa09-11e7-8862-d40d233f1e39.png)

![image](https://user-images.githubusercontent.com/4850976/34962579-dfb85fac-fa09-11e7-99f6-6f0b50626aca.png)

**Comment by gsteimer** [comment]
@benallenallen - can you try this again on edge2 when you get the chance?  I just tried and it seems to be working fine now.  I was using the Accounts Payable trac.

**Comment by benallenallen** [comment]
don't have a specific revision number that fixed it, but it seems like it is working now... just tried it on the claims trac and it worked perfectly.

Closing...

**Comment by m-brouillette** [comment]
@gsteimer - I just tried the Insurance trac and it worked.  If I had to guess, it was likely fixed by:

OA REV 4514
