### ISSUE TITLE
Bulk Upload does not allow user to navigate past bulk properties page

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1579]
If you have a trac where Bulk Upload is only configured to upload a single document type, it's impossible to move past the bulk properties page when attempting to upload more than one document:

**Next button not enabled**
![image](https://user-images.githubusercontent.com/1377228/35049871-f9284ebc-fb66-11e7-9573-fdf258d63430.png)

If the trac forces to user to pick from a list of document types (Ex: Controlled Docs), then the buttons enable fine.  It seems as if the logic to auto-select the one type is correctly choosing the type, but isn't triggering the logic to enable the next button.

**Comment by renesaladrigas** [comment]
BULK UPLOAD PAGINATION CONTROLS - Now that dependencies have changed, Handlebars will not change context on the model object for {{#if}} statements, only for statements that require a context change like {{#each}} loops.

Fixed with HPI revision: 19620

CR - Avi King
