### ISSUE TITLE
Add file/module filter to build process

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1582]
Not all clients make use of the many modules available in HPI. However, by default, all modules are built into the assembled hpi-require.min.js javascript package. In order to deliver a smaller package to the browser, removing unnecessary files from the build would be good.

Currently this is possible by customizing the `copy:base` target like so, to specifically whitelist a series of modules:

<img width="1276" alt="screen shot 2018-01-18 at 10 50 41 am" src="https://user-images.githubusercontent.com/547941/35111887-fc61025a-fc41-11e7-8d67-fdc01eb0f78a.png">

To incorporate this into the core product, the whitelist should be added as an external configuration file for the build. This whitelist could even aggregate modules so that project configurations could eliminate logical groups of modules.

**Comment by acastor** [comment]
Closed by HPI REV 19762
