### ISSUE TITLE
Collections broken if you don't go to Search first

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1586]
See screen capture below. If you login and go straight to collections, then select a collection it breaks OCMS. The issue is because table view tries to load the "currentSearchConfig" and that hasn't been loaded until a user goes to search.

![brokencollections](https://user-images.githubusercontent.com/2895070/35228509-88e29de4-ff56-11e7-8181-2fe19865eb75.gif)

**Comment by nquillin91** [comment]
Fixed with rev: 19644
