### ISSUE TITLE
Race condition causes error in search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1587]
See below on edge2 in both insurance tracs, if I run a search enough times it will fail:

![search-race-condition](https://user-images.githubusercontent.com/1377228/35233451-d5e5417a-ff63-11e7-8dea-8b0d1476f87f.gif)

Errors in the console:

![image](https://user-images.githubusercontent.com/1377228/35233478-ea37feba-ff63-11e7-88b7-a2da10de907c.png)

**Comment by renesaladrigas** [comment]
SEARCH / TABLEVIEW - Removing a lot of code to clean up the performance of search, based on the listeners triggered. The biggest change in this commit is the change in tableview.js, where we are now listening on the single point of communication between ocquery.js and tableview.js: the listener 'query:complete'. This listener will mark one single completion of a query, thus rendering tableview and the rest of the modules dependent on it correctly.

Closed with HPI revision: 19729

CR: Joe Hof, Dan Grumieaux
