### ISSUE TITLE
Send Email - Inputs not rendering properly on initial load

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1589]
Upon initial load of the Send Email action, the to/cc/bcc inputs are not loading properly:

![image](https://user-images.githubusercontent.com/1377228/35295629-35f8cf24-003f-11e8-8585-163b9b483c3c.png)

As a temporary workaround, if you click the CC or BCC button, the controls pop back to normal:

![image](https://user-images.githubusercontent.com/1377228/35295675-56092c0a-003f-11e8-86e9-9a1b4e169bac.png)

**Comment by renesaladrigas** [comment]
SENDEMAIL - Correcting Handlebars dependency context errors to allow for rendering of the module.

Fixed with HPI revision: 17941

CR - Nick Quillin
