### ISSUE TITLE
Faceted Search for Alfresco 4.2

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#159]
Currently faced search only works for Alfresco 4.1.x. It would appear the issue is that in AbstractAlfrescoEmbQueryImpl#executeQuery line 494 the result set type that is returned is not the correct type to do the faceting, so it is just skipping any faceting. According to Max and Ray, something was changed in the 4.2 API with the way that Solr searches are executed and faceted, so this is probably why the below code is never run.

```java
if( results instanceof SolrJSONResultSet )
```

From quickly looking at how the faceting works, it would appear that as soon as a trac is selected from the search screen, a 'dummy' query is sent to the ocQuery endpoint that doesn't have all of the correct parameters to do an actual search (it only seems to have the facet info) so it errors out and is swallowed. If this how facets were designed to work we need to change it to not execute an invalid search every time someone clicks on the search tab.

We also need to fix the bad exception handling in this entire method. If anything goes wrong, the stack trace that is printed is not at all helpful.

**Comment by b-k-white** [comment]
Fixed the facet search to its previously working state, although it is still not possible to search on multiple facets at a time. This is something that ought to be fixed in the future to have facet functionality work like other websites do.
CR-Dan G

**Comment by gsteimer** [comment]
@b-k-white - let's talk through this.  I'm thinking we can close this one and open a new issue.
