### ISSUE TITLE
Stage Sidebar toggle to expand doesn't work

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1591]
Currently when the sidebar collapses you cannot open it back up using the toggle

![togglenotworking](https://user-images.githubusercontent.com/13734523/35348706-74da0572-00fe-11e8-92f5-94046be1b059.gif)

**Comment by gsteimer** [comment]
Not - the search sidebar toggle _does_ work.  Updating the title to make it clear that the Stage sidebar toggle is failing.

**Comment by joehaynes** [comment]
Fixed with HPI commit 19663

CR- Zach G
