### ISSUE TITLE
If standardized table view is the last view used before navigating out of search/view all documents, re-entering hides filtering options

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1593]
If a user switches to standardized table view and then leaves the context of search/view all documents, then re-entering will cause it to enter standardized table view. The expected behavior in this situation would be to default to table view. 
![stdview](https://user-images.githubusercontent.com/9989329/35364383-804092f6-0134-11e8-9891-2b2b7b0b1c74.gif)

**Comment by acastor** [comment]
Closed by Rev 19925

Needed to add logic to clean up the standard view in searchResultControls.

CR: Bradley White and Joe Haynes
