### ISSUE TITLE
Labels are not translated when different languages are selected in a browser in OCMS

### ISSUE THREAD

**Issue by iwhitingTSG** [tsgrp/HPI#1602]
On Edge, when changing a browser's language, tokens are displaying in the headers and on the stage. Additionally, it appears that many configs are not tokenized. The language json files are present but do not seem to be showing the values.

The main header is partially tokenized - but "Create New Folder" and "Create Wizard Form" are not.

When viewing properties of a folder - nothing is tokenized other than the required *

Release behave differently. Release config labels appear to be hard-coded (at least Claims), but the header nav is translated. Folder Properties are incorrect.

The config files may have hard-coded values and not tokens - but in general all translations seem to be handled inconsistently.

![image](https://user-images.githubusercontent.com/18294569/35646986-c0cfee72-0696-11e8-8432-11253717ee8f.png)

![image](https://user-images.githubusercontent.com/18294569/35646971-b18180fc-0696-11e8-88e0-254824590765.png)

-

**Comment by nquillin91** [comment]
Fixed with Rev 19713
