### ISSUE TITLE
Create Contentless Object  - Description

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#1606]
Copy and pasted from Bulk Upload most likely. Create Contentless Object is not going to be the replacement to Add Documents.

![screen shot 2018-02-02 at 1 33 59 pm](https://user-images.githubusercontent.com/8796489/35751372-da050372-081d-11e8-8ad2-c85200b0206e.png)

**Comment by nreiman** [comment]
OC Revision: 18315
CR: BW
