### ISSUE TITLE
View All Documents - Columns blank out or document names are cut off when table resizes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1610]
See the screencam below:

![vad-dctm](https://user-images.githubusercontent.com/1377228/35869476-bd9b1b54-0b24-11e8-930c-4a10adeeffe3.gif)

I can reproduce this on edge1 when simply viewing a document from VAD.  On edge2, I'm guessing it works because it's a timing issue and edge2 is faster.  However, I can reproduce this as well on edge2 by resizing my browser window:

![vad-alf](https://user-images.githubusercontent.com/1377228/35869613-203481d8-0b25-11e8-8835-7c2b8daadcb7.gif)

**Comment by gsteimer** [comment]
Note - updated the title because I also see this happening:

![image](https://user-images.githubusercontent.com/1377228/35870430-3dbda11a-0b27-11e8-9a9f-dc1250f3b100.png)

**Comment by gsteimer** [comment]
@benallenallen - on the radar for Golden Snitch?

**Comment by nquillin91** [comment]
@gsteimer @renesaladrigas 

The cutoff problem is a result of HPI rev 19729

**Comment by gsteimer** [comment]
@acastor - I'm also seeing this in collections on edge2 today, so be sure to test there as well:

![image](https://user-images.githubusercontent.com/1377228/36032584-19be4e96-0d74-11e8-9ae6-2e76f5a8a861.png)

**Comment by acastor** [comment]
REV 19832

These issues were caused by unnecessary reloadResults calls in tableview.js and invalid logic in the tableview.js columnHeaderResize function. 

CR: Rene and Joe Hof

**Comment by gsteimer** [comment]
@acastor - I still see this on edge2.  It's much better but it still happens if you view a doc in VAD and then close the doc:

![vad-column-blank](https://user-images.githubusercontent.com/1377228/36158163-3c85921a-10a1-11e8-9bb9-fa2d669efd0c.gif)

**Comment by wrudnickTSGRP** [comment]
@gsteimer I believe related to this commit is that now sorting columns will break pagination. 
![sorting](https://user-images.githubusercontent.com/32521696/36398334-34e9a970-158c-11e8-8b53-b7109e0a4a2c.gif)

**Comment by gsteimer** [comment]
@wrudnickTSGRP - that seems like a pretty big issue... I'd think it should be separate.  @benallenallen @acastor - I'm guessing that would be needed as well for Golden Snitch?

**Comment by wrudnickTSGRP** [comment]
@gsteimer I've gone back and reverted to the commit for this issue and that's where it was introduced as far as I can tell

**Comment by gsteimer** [comment]
Haven't seen this in a while, so closing
