### ISSUE TITLE
Repeating tables no longer function in ActiveForm

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1612]
Not sure when this happened (post January 2018 dependency updates or before), but repeating tables are not showing any of the form inputs:

![image](https://user-images.githubusercontent.com/1377228/35886007-4a53d542-0b55-11e8-855c-06e26957f3b3.png)

**Comment by renesaladrigas** [comment]
WIZARD FORM - Correcting html for table questions.

Fixed with HPI revision 19769

CR - Bradley White
