### ISSUE TITLE
Search Result View Controls do not appear in search without hard refresh

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1616]
See the screencam below - after executing a search the view controls on the right of the results header do not appear.  If I hard refresh, they show up:

![search-view-controls](https://user-images.githubusercontent.com/1377228/36033039-715dd148-0d75-11e8-8fd4-79c79ef1a5f5.gif)

**Comment by acastor** [comment]
Closed by REV 19832.

This commit changes SearchResultControls initial view mode logic to be determined in searchresults.js not in a separate child view. This reduces the number of searchresultcontrol views created and total renders while ensuring the view mode buttons are displayed from the first render.

CR:  Joe Hof and Rene
