### ISSUE TITLE
Performing more than one search while interacting with facets will break facets

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1621]
If a user performs a search and then uses facets then the second search will not work as expected. The results that come back from the second search looks like it already been filtered. 
![secondsearchreset](https://user-images.githubusercontent.com/9989329/36232181-5facd946-11a6-11e8-9de8-8b8ea0b8cf11.gif)

If the user resets facets before making the second search, then facets will not work as expected. The results message also seems to be broken.
![secondsearch](https://user-images.githubusercontent.com/9989329/36231847-2fe6a486-11a5-11e8-8023-1237f17d3e20.gif)

Please talk to @acastor or me before fixing this issue since we might have a lead.

**Comment by abrown45** [comment]
Issue still exists as of 2/27/2020

**Comment by abrown45** [comment]
Closed with commit #24920
