### ISSUE TITLE
In View All documents, if user facets before opening documents side by side in dual pane, closing one of the documents breaks view all documents. 

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1623]
If a user applies facets in view all documents and then opens up two documents side by side in dual pane view and then closes the document on the right pane, this will cause View all documents to not display anything. 
![viewalldocumentsfacets](https://user-images.githubusercontent.com/9989329/36280517-1e1a5cd2-1260-11e8-8bdd-c8a2cc9417ce.gif)

This seems to be happening because the applied facets are trying to reloadResults in tableview before it has actually rendered. We also see the following console error. 
![image](https://user-images.githubusercontent.com/9989329/36289230-94cb3300-1284-11e8-87d5-40fbb970ff1b.png)

**Comment by acastor** [comment]
REV 19923 

This issue was caused by calling Backbone Layout Manager's removeView on the View All Documents View before it was reused in the right side action handler. 

CR: Bradley White and Joe Haynes
