### ISSUE TITLE
Moving from thumbnail view (any page that is not the first) to table view causes pagination to reset and start from page 1

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1624]
When the user has thumbnail view set as their default view, then upon entering view all documents the user will not be able to navigate beyond the second page of results. 
![paginationthumbnail](https://user-images.githubusercontent.com/9989329/36281055-ee673918-1261-11e8-80d5-7ab3f9348db0.gif)

**Comment by dhruvvora94** [comment]
Additional slightly related issues: 

Going to std table view and then coming back to thumbnail view breaks pagination.
![paginationthumbnail2](https://user-images.githubusercontent.com/9989329/36287689-fa7f4474-127b-11e8-8741-b474d495342b.gif)

Navigating to a page that is not the first page in table view and then switching to thumbnail view makes the "prev" button stop working. This is because thumbnail view thinks that it is on page 1 despite the message displayed. 
![paginationthumbnail3](https://user-images.githubusercontent.com/9989329/36287773-84b9eeb4-127c-11e8-8c4a-5bbe08543d3f.gif)

Also, switching back to table view from a page(not page 1) in thumbnail view will cause the current page to be reset to 1. This can also be seen in the GIF above. Not sure if this is expected behavior?

**Comment by gsteimer** [comment]
@dhruvvora94 - related to the last point, I think ideally it would send you to the current page whenever switching views (table to grid or grid to table), but if it's causing issues, it's fine to go back to page 1 for now.

**Comment by dhruvvora94** [comment]
UPDATE: the issues above have been fixed with HPI commit #19893

Moving into table view from any page in thumbnail view will cause it to reset and start from page 1. 

Moving from standardized table view to thumbnail view will cause thumbnail view to try to stay on the same page but since standardized table view has different results per page, this should not be the case. Ideally we would want it to reset and start from page 1.

**Comment by benallenallen** [comment]
@dhruvvora94 can this be closed now?

**Comment by dhruvvora94** [comment]
No @benallenallen this is still an issue! When you move to tableview it doesn't care which page you were on and resets to page 1.

**Comment by dhruvvora94** [comment]
Closed with HPI #20586
