### ISSUE TITLE
Open in New Tab Fails in anything but Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1625]
If you execute the open in new tab action in alfresco, the HPI and OC content URLs generated looks great:

HPI URL: `/hpi/View/workspace://SpacesStore/fe63cdfb-e2ec-4b20-a830-ea490d655552/Fake%20Check%201.pdf`

OC URL: `/alfresco/OpenContent/content/content/Fake%20Check%201.pdf?id=workspace%3A%2F%2FSpacesStore%2Ffe63cdfb-e2ec-4b20-a830-ea490d655552&overlay=true&contentType[]=pdf,txt,png,jpg,.*`

However, when executing in Documentum, the HPI URL looks the same, but the OC URL completely misses the document ID, causing the view to fail:

HPI URL: `/hpi/View/090000028002fb0f/2013%20Annual%20Report`

OC URL: `/OpenContent/rest/content/content/090000028002fb0f_2013%20Annual%20Report?id=&overlay=true&contentType[]=pdf,txt,png,jpg,.*`

Notice how the ID of the document is placed in the URL path and not in the `id` param.  There's also a `_` after the ID rather than `/`

From looking at the code with @b-k-white it seems the problem is in this code in `router.js` which is Alfresco specific:

```javascript
        var indexToSplit = nthIndex(idAndName,'/',4);
        var contentId = idAndName.substring(0,indexToSplit);
        var name = idAndName.substring(indexToSplit + 1);
```

Question - why are we including the ID as a path param in the first place?  Wouldn't it be much easier to make it a query param on the URL?  Then we wouldn't need to care that there are slashes in the ID for Alfresco URLs...

**Comment by ZachGerth** [comment]
Resolved with Commit # 19897. IDs are now a query parameter and we encode them when necessary.
CR - bwhite.
