### ISSUE TITLE
Wizard Input jumps to end during typing

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1627]
This doesn't happen _every_ time, but it happens enough to be an issue.

See below:
![cursor_to_end](https://user-images.githubusercontent.com/8784597/36330827-f81ef9b2-1330-11e8-998e-defedcc8411c.gif)

**Comment by mholwey** [comment]
Updated textbox model to override the onDisplayValueChange function. This function should only be calling render for fields that are formattable to avoid excessive/unnecessary rerendering.

Fixed with HPI commit: 19961
