### ISSUE TITLE
Sorting Columns in View All Documents Breaks Pagination

### ISSUE THREAD

**Issue by wrudnickTSGRP** [tsgrp/HPI#1629]
Sorting columns in View all Documents breaks pagination. 

![sorting](https://user-images.githubusercontent.com/32521696/36398656-cf17c8e6-158d-11e8-9064-0cea2b5ece1b.gif)

- It appears  to have something to do with the number of Documents per page when you first load into VAD as shown in the gif below

![25 docs](https://user-images.githubusercontent.com/32521696/36398720-12e9c3d0-158e-11e8-89ee-04573313c4a3.gif)

- When I make it 10 docs per page, 25 docs are returned to be sorted instead of 55, potentially because 25 was the original number of documents per page.

How to recreate this on edge:
- Load into a claim with more than 1 page of documents
- Click on any of the columns to sort the table

potentially has to do with the commit for this: https://github.com/tsgrp/HPI/issues/1610#issuecomment-366810507

**Comment by acastor** [comment]
Closed by Rev 19924

Removed unneeded event listener causing incorrect tableview collection values.

CR: Bradley White and Joe Haynes.
