### ISSUE TITLE
Text filters do not persist when switching between thumbnail view and table view

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1630]
When a user has a text filter and then switches views from table to thumbnail view or vice versa, the text filter is not applied. 
![textfiltering](https://user-images.githubusercontent.com/9989329/36399357-1f57e342-1591-11e8-99b6-f8a284a2f500.gif)

**Comment by gsteimer** [comment]
@dhruvvora94 Marking this one as an enhancement because I think this was a known limitation of the view switching when we implemented it.

Let me know if you disagree @benallenallen

**Comment by dhruvvora94** [comment]
Close with HPI Commit #20136
