### ISSUE TITLE
Thumbnail loading spinner is above the filter dropdown

### ISSUE THREAD

**Issue by wrudnickTSGRP** [tsgrp/HPI#1633]
The spinners that appear when thumbnails are being generated/pulled in from OC are above the filter dropdown on the screen.

![image](https://user-images.githubusercontent.com/32521696/36484915-584e3732-16e0-11e8-8dbb-49db83913441.png)

**Comment by abrown45** [comment]
Closed with commit #24480

**Comment by gsteimer** [comment]
@abrown45 - not sure what changed, but I think there's a timing issue that's causing the Filter By button to stop working (especially right after switching views).  See the screencam below:

![filterby-fail](https://user-images.githubusercontent.com/1377228/71909469-bea91080-3135-11ea-9bd2-bc69b1114f73.gif)

**Comment by abrown45** [comment]
## Update
Offered solution may be causing additional latency with the filter by facet popover. Reverting the commit #24480. Could be beneficial to look into how the popover is being created and how its being taken down.

### Findings
I found the popover is being built and instantly being destroyed in the above scenario. You can see the div flicker on the DOM.

**Comment by abrown45** [comment]
The filter rendering issue is unrelated to commit #24480 since it is still persisting after reverting.

**Comment by abrown45** [comment]
Closes with commit #24519. Opened a new issue for the popover. https://github.com/tsgrp/HPI/issues/2030
