### ISSUE TITLE
Cancel checkout action missing action configurations

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1639]
If you add the Cancel Checkout action, it's missing the action configuration section.  See below:

**New Action**
![image](https://user-images.githubusercontent.com/1377228/36566125-2cedc8ba-17e8-11e8-91d2-cb87a467c6da.png)

**Existing action from edge2**
![image](https://user-images.githubusercontent.com/1377228/36566102-1cf97116-17e8-11e8-949f-049497981007.png)

**Comment by ikaikajcorrea** [comment]
Closed by Rev 19924

Fixed issue where action configuration section was not appearing for Cancel Checkout when trying to configure the action within the admin. Renamed oneDriveChecked attr to cloudModeChecked, which was leftover from the refactor.

CR: Rene S.
