### ISSUE TITLE
Resurrect create related form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1641]
In old HPI 2.0 (the in-between version of old and new HPI), we had an action that let you create a related form, linking two form instances as parent and child.  We should resurrect the functionality in the latest codebase.

Note - this action was Alfresco-only in the past, so this enhancement is simply to get us back to where we were in HPI 2.0.

**Comment by henryerzinger** [comment]
CREATE RELATED FORM - Resurrected Create Related Form action

HPI revision #19980 
OC revision #18365

CR: Bradley
