### ISSUE TITLE
Can't configure Create Wizard Form action in admin

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1644]
Create Wizard Form Action configurations do not show up in the admin, as shown below. 
![image](https://user-images.githubusercontent.com/8784125/36743212-54931026-1baf-11e8-8c37-b1a4763acfde.png)

Dev tools show an error.
![image](https://user-images.githubusercontent.com/8784125/36743282-827378c8-1baf-11e8-9bde-671c589e1b2c.png)

**Comment by henryerzinger** [comment]
CREATE WIZARD FORM - Fixed the issue regarding Create Wizard Form actions not showing up.  Also modified the phrasing in the Create Related Form action to be clear that it will work on Alfresco only.

Fixed with HPI revision: 19989

CR - Bradley
