### ISSUE TITLE
Quick Blur on Wizard Field doesn't trigger Validation

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1646]
See here:
![quick_blur_wizard](https://user-images.githubusercontent.com/8784597/36758431-0a42d4fe-1bda-11e8-9103-5c005690d6e4.gif)

It's worth noting that I am `blur`ing the input multiple times at the end of the gif.  This likely means that even though there is text in the `<input>` the model on the PSI "thinks" it's blank.

**Comment by kgarelli** [comment]
HPI revision: 20000
