### ISSUE TITLE
Filters do not properly load when first entering search

### ISSUE THREAD

**Issue by Kovacinski** [tsgrp/HPI#1647]
See the screen cam below.  On both edge1 and edge2, the first search that occurs when entering search will not properly load the filters.

![predefinedviewsenteringsearch](https://user-images.githubusercontent.com/7279444/36848614-66652b62-1d27-11e8-9a74-9af30f4e945e.gif)

**Comment by gsteimer** [comment]
@Kovacinski - removing the table view label.  Unless you think this is actually related to the table view code?

**Comment by Kovacinski** [comment]
Yeah thats ok.

**Comment by dhruvvora94** [comment]
Closed with HPI #20022

setupFacets was not getting triggered from ocQuery and this caused the facets to not be loaded. Just had to correct the trigger name and make the event listen on the tableview object instead of the app.
