### ISSUE TITLE
View All Documents reset tableview does not display tableview if done in thumbnail view.

### ISSUE THREAD

**Issue by Kovacinski** [tsgrp/HPI#1651]
If we reset tableview while viewing thumbnail view, the view should change to tableview.

This could be related to issue: https://github.com/tsgrp/HPI/issues/1650

![vadresetgototableview](https://user-images.githubusercontent.com/7279444/36858267-4b5028f4-1d40-11e8-8b4c-4302239948f4.gif)

**Comment by benallenallen** [comment]
What are you expecting this to do in thumbnail view?

**Comment by Kovacinski** [comment]
In search it switches the views so that tableview is then displayed. It looks like its trying to do it here as well but is failing

**Comment by gsteimer** [comment]
@benallenallen - I'd say however Golden Snitch wants this to work is fine (switch or don't switch), but it should be consistent across VAD, Search and Collections

**Comment by dhruvvora94** [comment]
This behavior is no longer being seen. Must have gotten fixed as a result of a commit for some other issue/feature.
