### ISSUE TITLE
The check all action does not pop up the select all results option when on the last page

### ISSUE THREAD

**Issue by Kovacinski** [tsgrp/HPI#1654]
![check_all](https://user-images.githubusercontent.com/7279444/36859870-59a95966-1d45-11e8-8e6f-e23a7f1ebec3.gif)

**Comment by gsteimer** [comment]
@Kovacinski - does the same thing happen if you use the checkbox in the table header row?

**Comment by Kovacinski** [comment]
Yes it does.

**Comment by keljopap-tsgrp** [comment]
Oh hey I just fixed this.

**Comment by keljopap-tsgrp** [comment]
![lastpage](https://user-images.githubusercontent.com/37815877/49259822-8696b080-f400-11e8-9a4f-85babe3ccd37.gif)

**Comment by keljopap-tsgrp** [comment]
This'll go in when I commit to trunk for https://github.com/tsgrp/HPI/issues/1778.

**Comment by keljopap-tsgrp** [comment]
Closed with #22114
