### ISSUE TITLE
Results per page selection is always set to default configured in admin.

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1657]
When a user performs a search or enters VAD, the results per page is always set to the value that was configured in the admin. Ideally we would expect the last value selected by the user to be stored in the userPreferences (the same way that predefined views are stored) and that value should be applied. 
![resultsperpageuserpref](https://user-images.githubusercontent.com/9989329/36869739-67914e40-1d62-11e8-8a90-0811d896165c.gif)

**Comment by gsteimer** [comment]
@dhruvvora94 - see #1317

**Comment by dhruvvora94** [comment]
Closed with HPI commit 20027
