### ISSUE TITLE
Message when Documents Can't be Combined Missing Name

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1664]
After the Advanced Combine to PDF revamp that enhanced it to use tableview, the following appears when you select a non-PDFable document to add to the combined PDF:

![image](https://user-images.githubusercontent.com/14186924/37530838-83982a08-2908-11e8-8ab0-5d76bd0db9d0.png)

It correctly identifies documents which can't be added, but it does not list the name, leaving the end user unsure what the issue seems to be.

**Comment by Kovacinski** [comment]
Fixed with Revision: 20577
