### ISSUE TITLE
Stream Resolver no longer works

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1668]
If you set the link stream resolver in search to 'stream', it should launch the document in a new tab in the same way that the "Open In New Tab" link works today.  

![image](https://user-images.githubusercontent.com/1377228/37792722-91bb2a82-2dda-11e8-88cf-d96a761de9bc.png)

However, it looks like due to the fixes implemented in #1625 this no longer works.  The screen just sits there on the loading spinner and the document never streams.  Tested and fails on both edge1 and edge2.

From what I can tell, the problem is that we modified the format of the URL the View route is expecting.  

Open In New Tab produces a URL like this:

`http://edge1.tsgrp.com/hpi/View/TSG-101?id=090000028001cb2c`

while the stream resolver produces this URL:

`http://edge1.tsgrp.com/hpi/View/090000028001cb2c/TSG-101`

... which is the old format that #1625 modified.

When testing this, be sure to test:

- [x] Search Config / Search Results / Link Resolver - link in search results should launch document in new tab
- [x] Group Actions / Export Serach Results / Link generated in Export to Excel (need to enable this in the admin on the action config if it's not already there).  Note that if you're testing alfresco, the link is correct, but Excel may not launch the correct URL if you just click it.  Perhaps this will just work though once we update it to the new URL?

![image](https://user-images.githubusercontent.com/1377228/37793085-a445523a-2ddb-11e8-95d8-a7ffe6e3febe.png)

**Comment by keljopap-tsgrp** [comment]
added linkformatterutil unit tests as well.
