### ISSUE TITLE
Tour styling does not look correct

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1669]
See below as an example from the search tour:

![image](https://user-images.githubusercontent.com/1377228/37794732-62d421a0-2de0-11e8-8db7-9a01aefbb402.png)

We'll want to test both search and stage tour modules:

- [ ] Search Tour
- [ ] Stage Tour

**Comment by nreiman** [comment]
![image](https://user-images.githubusercontent.com/32136774/37798735-9c689c60-2deb-11e8-8e5a-f196cdcf0f16.png)

Styling for Trac Configs also seems to be incorrect.

**Comment by cchau-tsgrp** [comment]
Push the fix. Please see revision #20454. Thanks.

**Comment by cchau-tsgrp** [comment]
Desc of Fix: New module previewCombinedPdfModal overwrote general popover style. Set it to use ID instead of general class.
HPI revision #20454.
CR: Ian
