### ISSUE TITLE
Right click in collections does not provide a context menu

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1670]
Right-clicking on collections results in a console error and the default right click menu pops up. 
![image](https://user-images.githubusercontent.com/9989329/37920173-c404025c-30eb-11e8-8354-97cdc89c854e.png)
![collectionsrightclick](https://user-images.githubusercontent.com/9989329/37920226-e3f657b8-30eb-11e8-83c0-c5e4036a0ba4.gif)

**Comment by Kovacinski** [comment]
isnt this already an issue? https://github.com/tsgrp/HPI/issues/1637

**Comment by dhruvvora94** [comment]
As mentioned above, this is a duplicate!
