### ISSUE TITLE
Advanced combined to PDF does not display input box in IE or Firefox

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1671]
This is what advanced combined to PDF looks like in IE 
![image](https://user-images.githubusercontent.com/9989329/37923778-a8336086-30f5-11e8-8170-88d216394574.png)

This is advanced combined to PDF on chrome
![image](https://user-images.githubusercontent.com/9989329/37923869-dc03c608-30f5-11e8-8d8f-b89a1977b26f.png)

**Comment by gsteimer** [comment]
Looks like this is a problem in Firefox as well:

![image](https://user-images.githubusercontent.com/1377228/38313881-a133da76-37ea-11e8-9fc5-a03cf8ef747c.png)

**Comment by kpelozatsgrp** [comment]
At revision: 20312

CR: Nick and Steve
