### ISSUE TITLE
BulkUpload - Async upload view is blank / doesn't show a progress bar

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1675]
![image](https://user-images.githubusercontent.com/13734523/38266545-9c531456-373e-11e8-9fde-316a964107c9.png)

Asynchronous mode in bulk upload currently does not show a progress bar or anything to notify the user the uploading is being processed. This can be excerbated by a slow environment in which the page will just remain blank for some time.

**Comment by kpelozatsgrp** [comment]
![image](https://user-images.githubusercontent.com/37337985/38388496-fe3013e2-38e0-11e8-853d-89c12e723343.png)

**Comment by kpelozatsgrp** [comment]
Revision: 20472
CR: Avi, Nick, and Steve
