### ISSUE TITLE
After Saving redactions - zooming or navigating around the document causing the original redaction selections to reapper

### ISSUE THREAD

**Issue by iwhitingTSG** [tsgrp/HPI#1678]
It appears that the original selections are not cleaned up after save. Refreshing the page fixes the issue.
![image](https://user-images.githubusercontent.com/18294569/38319523-98e4029e-37f7-11e8-96de-3b8c8beed327.png)

**Comment by m-brouillette** [comment]
Really more of an OA issue; copied to : https://github.com/tsgrp/OpenAnnotate/issues/363 for reference
