### ISSUE TITLE
Export Folder action no longer works

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1681]
The Export Folder action currently just hangs.  When the user executes the action, it _looks_ like it's going to work:

![image](https://user-images.githubusercontent.com/1377228/38427659-750e12fe-397f-11e8-895e-44cbbab4500f.png)

But the network request never fires for the action due to this javascript error:

![image](https://user-images.githubusercontent.com/1377228/38427708-93e9137c-397f-11e8-821e-744e47bc2af5.png)

![image](https://user-images.githubusercontent.com/1377228/38427745-b01e6592-397f-11e8-9557-587c73cb6ac4.png)

@Kovacinski - based on the error message, could the recent Table View updates be causing this?  Odd since Export Folder doesn't use a table, or depend on anything in View All Docs...

**Comment by kpelozatsgrp** [comment]
HPI Revision: 20539
CR: Steve, Rene, and Avi
