### ISSUE TITLE
Check all results provides the wrong number of results in the message when using text filters.

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1683]
![checkallmessage](https://user-images.githubusercontent.com/9989329/38568128-7ffe3406-3cad-11e8-8f7a-463d1cdf0ba8.gif)
When using check all documents action, it provides the user with an option to check all the results including ones that are not currently displayed.  

If text filters are applied, then the number of results in this message seems to be wrong.

**Comment by keljopap-tsgrp** [comment]
This can get covered under https://github.com/tsgrp/HPI/issues/1778 as well.  Have demonstrated a fix that involves just selecting all the filtered items, and still persisting them after removing the filter.

**Comment by keljopap-tsgrp** [comment]
The number isn't "wrong" so long as it's consistent with what we're actually selecting, so I think we should go with the filtered subset there.

**Comment by keljopap-tsgrp** [comment]
Fixed with revision #22267.
