### ISSUE TITLE
Admin Menu container doesn't resize to accommodate the menu

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#1685]
The container that holds the admin menu should resize according to the height of the menu; the menu should not overflow out of the background container.
![image](https://user-images.githubusercontent.com/14186921/38686376-c796539c-3e39-11e8-8b90-b8c4644bcf80.png)

**Comment by gsteimer** [comment]
Note - this didn't happen before #1436 was committed, but we do want the admin menu to always be visible on the left as the user scrolls

**Comment by cchau-tsgrp** [comment]
@renesaladrigas can you go to... `hpiadmin.styl`, at the bottom, you will find "#admin-display-outlet: {...}", besides having padding-left and width, can you also add "min-height: 100vh;" there?

I tested on both Windows and Mac, across all browsers, it seems like it's working.

**Comment by renesaladrigas** [comment]
Closed with HPI revision 20352
