### ISSUE TITLE
Checkin - submit button not clickable when using File Browse on IE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1688]
In IE, if you use the "Choose File" button to select your file to check in:

![image](https://user-images.githubusercontent.com/1377228/38941664-aafe172a-42f2-11e8-9a8b-3b1e618cbbe0.png)

The submit button becomes enabled but is not clickable:

![image](https://user-images.githubusercontent.com/1377228/38941705-c2525ba2-42f2-11e8-9927-18c4dccb9a67.png)

What makes this more odd is that if you drag and drop rather than using the file browse, it works fine.  This issue affects the STS since we use the file browse method to select the file.

**Comment by kpelozatsgrp** [comment]
CR: Joe Hof
At Revision: 20440
