### ISSUE TITLE
Dashlets that should be always visible are never visible

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1690]
Dashlets that do not have any configured groups in the admin:

![image](https://user-images.githubusercontent.com/1377228/39137518-66add336-46e3-11e8-9b1e-e5a6042fea18.png)

should be displayed for all users.  However, it looks like due to a commit last night, these dashlets are never displayed.

**Comment by cchau-tsgrp** [comment]
Fix: For each dashlet, we should show it even if its "allowedGroup" length is equal to 0.
File: dashboard.js
Revision #: 20468
CR: Charles
