### ISSUE TITLE
Admin search tool - No message given if query fails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1696]
The admin query endpoint in OC has this code to check to see if the user is a repository admin:

```java
        if (!CoreContext.getUser().isAuthenticatedUserAdmin(ticket)) {
			throw new OCForbiddenRuntimeException(
					"User is not permitted to execute this action");
		}
```

However, OCMS admin users can be different than repository administrators.  If this is the case, then clicking the search button does nothing.  If you open the network tab, you can see that the request is returning the 403 Forbidden, but no indication is given to the user.

To fix this, we should catch the 403 and display a message to the user saying that this action is limited to repository administrators only.

**Comment by gsteimer** [comment]
Updated the title since no message is given if any error occurs.  We should be smart about displaying different messages if there's a 403 vs a 500 error, of course

**Comment by henryerzinger** [comment]
ADMIN SEARCH TOOL - resolved the issue with no error message showing if a query fails in admin search tool. Error message now shows the error code and error message.  
 
Revision # 20665
CR - Natalia
