### ISSUE TITLE
Admin Search Tool - Not picking up search config for columns

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1698]
In the admin search tool, you can optionally (for now) select a search config as part of the query.  As far as I know, this has two purposes:

1. Allows the user to define which columns are returned in the query and in what order.
1. Allows the user to tell the query to run in Direct SQL mode (Alfresco only)

Ignoring the Direct SQL mode, I tested this on edge2 with FTS queries, but the excel spreadsheet is exactly the same.  See below:

Querying for all wizard forms where name like `SCR`:

**No Search Config Selected**
![image](https://user-images.githubusercontent.com/1377228/39369754-c4fae95c-4a02-11e8-913e-d4fa0890aab6.png)

**Wizard Search Config Selected**
![image](https://user-images.githubusercontent.com/1377228/39369790-d4b12866-4a02-11e8-9903-f8d00145544c.png)

**Wizard Search Config - Search Results Columns**
![image](https://user-images.githubusercontent.com/1377228/39369709-9c999bfc-4a02-11e8-8282-668ac72271dc.png)

**Comment by jharkins2** [comment]
Fix: Actually using search config values in adminsearchtool.js
CR-Ian
Resolved at Revision #20564
