### ISSUE TITLE
Open in New Tab does not work when clicked from action menu

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1701]
Both the `Open in New Tab` and the `Open Each in New Tab` actions seem to work fine with the right click menu:

![image](https://user-images.githubusercontent.com/1377228/39489411-0baa697c-4d4b-11e8-8bb4-61d316365fdd.png)

... but fails when using the Actions dropdown:

![image](https://user-images.githubusercontent.com/1377228/39489436-293cfc16-4d4b-11e8-84cd-4f6df22358a8.png)

When using the actions menu, it opens the correct number of tabs (at least for me, @cadcock is seeing only one tab ever opened), but the tab is `about:blank`:

![image](https://user-images.githubusercontent.com/1377228/39489465-47085a2e-4d4b-11e8-90fa-0e3933de10b3.png)

Note - in IE, instead of a blank page, I see a `undefined` route:

![image](https://user-images.githubusercontent.com/1377228/39489529-789b0b72-4d4b-11e8-818e-ae3b51f9122d.png)

Perhaps this is related to #1689 @joehof?  I'm guessing this is a similar issue (although reversed).

**Comment by renesaladrigas** [comment]
OPEN NEW TAB: Correcting issue where open in new tab action was not opening from the actions menu, only from the search results. The issue was happening due to misshapen if statement structure. Refactored code to accommodate for unit testing.

Fixed with rev: 20682.

CR - Avi King
