### ISSUE TITLE
Related Objects Config - Can't Change Sort Attr

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1702]
In the Related Objects configuration under Stage when you change the sort attribute and click save it doesn't actually get saved on the model. Also, it is expected that when you change the display attribute it will default the sort attribute to that of the display attribute but you should be able to change the sort attribute to something other than the display attribute. Currently if you change the sort attribute it will automatically change the display attribute as well.

It should be noted that it seems that changing the sort direction from Ascending to Descending is reflected in the model and properly saved.

- [x] Sort attribute doesn't save
- [x] Sort attribute currently mirrors display attribute and can't be changed

<img width="459" alt="screen shot 2018-05-07 at 9 42 29 pm" src="https://user-images.githubusercontent.com/13734523/39735223-3e200138-5240-11e8-822c-5aacb803cd0f.png">

**Comment by nquillin91** [comment]
Rev 20584

**Comment by joehof** [comment]
Re-opening, the commit that fixed this was reverted a few days later. We should see if this is still an issue.

**Comment by aviking** [comment]
@joehof I think the only thing that she reverted was variable names, the actual code fix still works.

**Comment by nquillin91** [comment]
There was an issue where the original commit was only working locally. When the commit went in there was an issue in the data-binding of the value due to the new variables being found as undefined. The fix  was to revert 3 of the lines back to their original names. Ie stageConfigDisplayAttr back to displayAttr, but the fix for sortAttr was correct (not reverted), because sortAttr before the initial commit was set to displayAttr. So the fix is valid

Verified to be working on edge environment. 

Fixed with REV: 20602
