### ISSUE TITLE
Stage - folderActionId in URL is ignored, configured autolaunch action opens instead

### ISSUE THREAD

**Issue by Swence32** [tsgrp/HPI#1705]
In Stage, the ID of the last Right Side Action that was launched is stored in the URL. That way if the user tries to load HPI with that URL, the action with the given actionId in the URL will launch automatically. However, this no longer appears to be the case. Below screencapture shows entering Stage, View All Documents auto-launching, opening Add Documents, refreshing the page, and View All Documents loading instead of Add Documents.

![folderactionrsahdirectlaunchissue](https://user-images.githubusercontent.com/5685648/40130172-ddd6da14-58fb-11e8-8154-f9717ad2cc07.gif)

**Comment by CRdouglas** [comment]
FOLDER ACTION ID URL UPDATED: FolderActionId was being ignored when the URI was being built. Causing any action with autolaunch to be fired instead. We changed the URI object to include the query at the end of the url allowing us to pull of the action we were currently in. 

https://github.com/tsgrp/HPI/issues/1705

CR - Natalia, Rene, Alex

Rev: 20706
