### ISSUE TITLE
Uploading Embedded MSGs Fails With Indexing Mode Enabled

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1707]
When adding an MSG that contains attachments and embedded MSGs that may also contain more attachments. The file is sent to OpenContent for parsing to retrieve a flat list of all items being uploaded. When Indexing Mode is disabled, the list of files and attachments for bulk upload is correct. If Indexing Mode is enabled, the call fails entirely.

This looks related to how we normally just retrieve the file names so that a set of OCOs can be crafted representing all the MSGs and attachments, but here with Indexing Mode enabled we are actually attempting to create the email and all of its attachments. Resulting in a null pointer exception in the createMsgOrAttachment method because it attempts to get the corresponding emailAttachmentProperties by fileName but the Map is null.

**Comment by dhruvvora94** [comment]
Closed with OC commit #18920
