### ISSUE TITLE
SearchResultControls - Applying facets in thumbnail mode and navigating to standard view breaks mode switching

### ISSUE THREAD

**Issue by acastor** [tsgrp/HPI#1709]
As seen below, applying facets and then switching the search result view from thumbnail view to standard view causes mode switching to break and hides search result controls. 

![facetbug](https://user-images.githubusercontent.com/6983427/40393214-2996bf18-5de4-11e8-8370-cf9ba0415fb4.gif)

**Comment by gsteimer** [comment]
@acastor is this going to be fixed by Golden Snitch?  As far as I know, that's the only project that uses standard view

**Comment by dhruvvora94** [comment]
Closed with HPI commit #20678
