### ISSUE TITLE
ViewProperties Action Config Doesn't Save "Select Form to Display"

### ISSUE THREAD

**Issue by wrudnickTSGRP** [tsgrp/HPI#1710]
From the viewProperties action config inside search and stage config, users can select a form that the action will display when executed. 

Currently, whenever the action config is reloaded, the previously selected form is ignored and the form at the top of the dropdown is selected.

![viewproperties](https://user-images.githubusercontent.com/32521696/40431398-fa0bfe5a-5e6c-11e8-9a51-cfadda927f66.gif)

From quickly looking at the code, the issue appears to be from this block inside `viewproperties.js`  line ~347

Notes:
- Seems to be related to OCMS revision: 20247

**Comment by CRdouglas** [comment]
VIEWPROPERTIES CONFIG: The issue solved was that we were applying bindings before we were fully completing the initialize. We are making sure the initialize completely resolves using a deferred before applying bindings.

Github #1710

CR - Rene

REV: 20684
