### ISSUE TITLE
Dashboard - Reset Dashlet Order does Nothing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1712]
While testing the fix for #1694 , I also tried resetting dashboard tabs using this button in user prefs:

![image](https://user-images.githubusercontent.com/1377228/40445821-e4206b00-5e92-11e8-85c7-cdf8c6d049c7.png)

It looks like it works (no errors are given), but the dashboard tabs do not update.  It also doesn't fire any network requests, but perhaps that's because it's operating on the local copy of the user prefs and expects the normal save flow to handle saving the updates to the repo.

**Comment by gsteimer** [comment]
May be good to rethink ordering with tabs - see #1756

**Comment by LoganLaFollette** [comment]
Fixed with OCMS revision: 22263.  

- Updated the way dashlet order objects are stored/accessed on the config to match [#1694](https://github.com/tsgrp/HPI/issues/1694) updates.

**Comment by gsteimer** [comment]
It looks like you simply need to add dashlets back to their respective tabs and then it works again:

![image](https://user-images.githubusercontent.com/1377228/50907474-1b6fcf00-13ed-11e9-981a-9bd48bec725c.png)

Update to the upgrade guide forthcoming...
