### ISSUE TITLE
ACTPDF - The selected pages aren't saved when reopening OA Page Select

### ISSUE THREAD

**Issue by mholwey** [tsgrp/HPI#1727]
In ACTPDF, after selecting pages for a document, if OA page select is reopened for this document, all of the document's pages are still selected. On a technical level, tableview's OA page selection logic isn't passing the selected pages to OA.
![hpi_oa_selected_pages_incorrect](https://user-images.githubusercontent.com/22036889/42170564-83e29a56-7ddc-11e8-8b31-10b40ca6e51d.gif)

**Comment by Kovacinski** [comment]
Closed with HPI Revision: 21043
