### ISSUE TITLE
OpenContent picklists always returning a blank item

### ISSUE THREAD

**Issue by mkolas** [tsgrp/hpi#173]
See: picklistconfig.js line ~ 131.

Not sure if OC picklists are being used on the DCTM side, but for Alfresco these are used to get the acceptable values for a constraint as defined on the Alfresco model. 

When originally implemented we inserted a blank value so that DropDowns could be set to blank, but if the picklist is being used for CheckBoxes this adds a blank checkbox which is not desirable.

**Comment by gsteimer** [comment]
@zkeller - You mentioned you thought this was fixed.  Can you verify and close this if that's the case?

**Comment by zkeller** [comment]
Tested on edge2, this is fixed. I couldn't find in the commit logs where, however.
