### ISSUE TITLE
Stage no longer loads after tab title update

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1739]
The Stage no longer loads on edge1 and edge2 after the update to add tab title configurability - see #1738 

The error in the log is:

![image](https://user-images.githubusercontent.com/1377228/43152648-bd0cba46-8f34-11e8-92b1-696b2982dbf7.png)

This must be fixed before release1/2 is rebuilt on 7/31.  Most STS scripts will fail as well pending this fix.

**Comment by renesaladrigas** [comment]
STAGE INFO - If the tabTitle object is undefined (for old configs that haven't been persisted with the new model), we want to be preventing the code from executing and causing javascript errors that break access to the stage. 

Fixed issue with revision: 21002

CR - Graham Singer & Charlie Douglas
