### ISSUE TITLE
Stage Tab Title Issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1740]
In testing the stage tab title enhancement (see #1738), I'm finding a number of issues that prevent us from using this feature in trunk:

- [x] In the admin, I tried to select a single attribute as the tab title.  Instead of putting the token in correctly, it places this String in the textbox: `undefinedNaNap_vendorName$`.  Interestingly, if you try again it puts more of the `undefinedNaN` text in there.  After trying again, I get: `undefinedNaNap_vendorName$NaNap_vendorName$`.  It'll keep appending in there.  Hard refreshing and logging out / in doesn't fix it.

- [x] When navigating to the stage, I do see that it's updating the tab title.  However, if you navigate away from the stage, the tab title sticks around.  After moving to something like search or dashboard, etc, the tab title should not continue to display stage specific information.

- Couple questions / enhancements in the admin
![image](https://user-images.githubusercontent.com/1377228/43269389-5e8fe49a-90b8-11e8-9954-4efbeb973cc3.png)

  - [x] Why are we only displaying a subset of attributes.  What if a client wanted modified date in the tab title?
  - [x] We shouldn't be displaying attribute oc names here.  Display label names instead.

**Comment by CRdouglas** [comment]
STAGEINFO TAB TITLE ISSUES: When changing from stage to another location the tab title would remain unchanged, the abstract router was updated to reset the tab title after leaving stage. Changing stage config to include the full list of attributes for each type, showing the pretty name of each attribute in the dropdown, and creating a default for the tabTitlePattern property.

ADDING abstractRouterSpec.js for Unit Tests 

CR - Rene Saladrigas

Rev 21020
