### ISSUE TITLE
Add White List of Documents to be Allowed for Upload

### ISSUE THREAD

**Issue by henryerzinger** [tsgrp/HPI#1741]
Right now, ocms allows any document type to be added for upload.  In some cases, we may not want that to be case.  We can add a list of document types to config-project.js that could be checked against when adding a document for upload.  For example, if a .exe file is selected in the bulk upload screen and .exe files are not included in the allowed document types, the file would not be added to the list of documents for bulk upload.  And if we do not want to have the whitelist then we simply would not add it to the config-project.js file.

**Comment by dhartman25** [comment]
@henryerzinger @RudraVishweshwar Consider using an HPI picklist for this so that it's possible to add whitelist extensions via config, instead of requiring a rebuild/restart of the HPI server.

**Comment by henryerzinger** [comment]
BULK UPLOAD WHITELIST - Allows a user to create a white list for allowed document types in bulk upload.  User can add file extensions to the bulk upload config and only documents of that type will be uploaded.

CR - Dan & Marc 

Revision: 21113

**Comment by gsteimer** [comment]
Reopening - this update does not account for already existing configs.

**Comment by henryerzinger** [comment]
BULK UPLOAD WHITELIST - Fixing previous commit (2113) to account for already existing configs

CR - Marc 

Rev: 21114
