### ISSUE TITLE
Have ability for Mail Merge Templates to act as Workflow Documents

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1742]
In contrast to the HotDocs solution, the Mail Merge Template solution makes the resulting PDF rendition of the MM document the "wizard form".  The HotDocs solution would keep the Wizard Form (as usual) and instead make the resulting `docx` the workflow document to-be-routed (seen [here](http://www.tsgrp.com/solutions/contract-management-solution/)).

The enhancement would be to have this option available, in addition to the existing functionality.

**Comment by gsteimer** [comment]
@grahamsinger - can you close this one with the OC revs from your updates?

**Comment by grahamsinger** [comment]
Implemented with OC rev19560
