### ISSUE TITLE
Non-editable field becomes editable after cascading query executes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1744]
See the screencam below.  If a field is configured as _not_ editable, when the form loads it's properly read only.  However, if another field is set up to populate that field via a cascading picklist, the field becomes editable after the query executes:

![form-editable](https://user-images.githubusercontent.com/1377228/43340816-2bfea55c-91a3-11e8-94d8-db6f5c56fda4.gif)

Here's the admin:

![image](https://user-images.githubusercontent.com/1377228/43340804-1c70dd76-91a3-11e8-8de8-006701e3a595.png)

Tested on edge2 and release2 in the HR trac

**Comment by LoganLaFollette** [comment]
Closed at revision: 21945
