### ISSUE TITLE
Redacted documents cannot be saved

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#1745]
Redactions are not working for the DCTM environment since HPI is by default looking for the relationship `DM_UNREDACTED`, which is missing from the repository. This relationship should be added to the hpi dar file to be installed by the client, or the default should be changed in the OC configurations. Probably a cleanup combination of both.

Stack trace snippet for reference:
```2018-07-30 09:00:05,007	TP-Processor3	ERROR	DCTMContentImpl	Error occured in DctmContentImpl
com.documentum.fc.common.DfException: [DM_RELATION_E_INVALID_NAME]error:  "Invalid relation_name = DM_UNREDACTED, Must be a valid dm_relation_type name."
```

**Comment by gsteimer** [comment]
Marking this as an enhancement since redaction wasn't targeted for Dctm when developed originally

**Comment by renesaladrigas** [comment]
Aligned default relation names to be "hpi_redacted" for any relation created.

Fixed with HPI rev: 21074 and OC rev: 19426

CR: George Steimer
