### ISSUE TITLE
Clicking on link in ACTPDF table doesn't open file in new tab

### ISSUE THREAD

**Issue by kforbes** [tsgrp/HPI#1747]
Select at least 2 document and choose the Generate Combined PDF action. From the ACTPDF table, clicking on the document name should open the file in a new tab. Currently, the user sees nothing happen on the screen and this JS error is thrown:
![image](https://user-images.githubusercontent.com/10836239/43653327-50ebb3cc-970d-11e8-8894-749921e559f2.png)

The issue occurs when getting the selectedVersion for the document in tableview's `onClickACTPDFNewTabLink`.

**Comment by acastor** [comment]
Closed by Rev 22105
TABLEVIEW: Adding a null check for the versionSelections object accessed in onClickACTPDFNewTabLink. The previous code was assuming the versionSelections object would always be on the grid object, but this is only true if the Advanced Combine to PDF's Select Version config is enabled. Fixed unit tests.

CR: Dhruv and Rene
