### ISSUE TITLE
AW Word Integration - select boxes not supported

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1755]
When using a word document as a mail merge template for an AW form, it looks like select boxes are not supported.  See the screenshot below:

![image](https://user-images.githubusercontent.com/1377228/44275812-52113700-a20b-11e8-948f-dadaa4de7eb8.png)

It looks like normal text boxes and dates seem fine (Date of Injury looks good), but the state is not displaying correctly.  State is a selectbox in the form:

![image](https://user-images.githubusercontent.com/1377228/44275865-8127a880-a20b-11e8-9358-500cb31cfe5a.png)

Based on the above, we should test that all AW form fields work with Mail Merge:

- [x] Textbox
- [x] Date
- [x] Select Box (example above)
- [x] Radio Button
- [x] Checkbox Button
- [x] Multi-text
- [ ] Calculation
- [x] Text Area
- [ ] Wysiwyg (I think it's fine if this one doesn't work 100%)

We don't need to support the File question type.

**Comment by grahamsinger** [comment]
Fixed with committed revision 20682.

**Comment by gsteimer** [comment]
@grahamsinger with the recent commit to #1826 , it looks like this one is back.  The interesting thing is that it only happens when generating a new workflow doc from template.  If you just have the word template be the form PDF, then it's fine.  Here's an example of what I'm seeing:

http://edge2.tsgrp.com/hpi/Stage/wizard/workspace://SpacesStore/160ca876-b9f7-4015-849a-c634ca45e507%7Cworkspace://SpacesStore/160ca876-b9f7-4015-849a-c634ca45e507

![image](https://user-images.githubusercontent.com/1377228/53812688-9ce16a80-3f21-11e9-9880-386215309648.png)

**Comment by grahamsinger** [comment]
Fixed with committed revision 21516.
