### ISSUE TITLE
Dashboard Tabs Usability Enhancements

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#1756]
The admin component of dashboard tabs could use the following enhancements:

- [x] Allow user to rename tabs
- [x] Allow user to change the number of columns for a tab and change the value after the tab is created
- [x] Allow user to reorder tabs
- [ ] Ever since the tabs update went in, getting the dashboard to recognize config changes is more difficult.  Instead of simply a hard refresh, or even a hard refresh with clearing cache, the user needs to logout and log back in to see any changes.  Is this necessary?

**Comment by gsteimer** [comment]
Added items for moving the query config section above the graph config section

**Comment by gsteimer** [comment]
See also - #1693

**Comment by LoganLaFollette** [comment]
Implemented dash tab renaming, reordering, and changing column number.
See OCMS revision: 21833

**Comment by gsteimer** [comment]
@LoganLaFollette @jackjbridge - I think we need some updates based on the latest commit.  here are some things I can see:

- [ ] The tab name update and column update features should either:
  - pre-populate the current name/column number OR
  - update the label text to say "Update tab name" and "update tab columns"

- [ ] When updating the name or the columns, it seems that on blur, the entire dashboard config reloads.  Why is it doing this?  Check out how renaming an individual dashlet works.

*Renaming a tab (notice page refresh)*
![renaming-dashboard-tab](https://user-images.githubusercontent.com/1377228/47579690-4f6d4500-d912-11e8-9e8e-c74449f539ef.gif)

*Renaming a dashlet (no page refresh)*
![renaming-dashlet](https://user-images.githubusercontent.com/1377228/47579703-572ce980-d912-11e8-87e5-8dab4e9b8047.gif)

**Comment by jackjbridge** [comment]
DASHBOARD TABS: Tabs now have a save button, able to modify multiple columns numbers/tab names before hitting save. Done by adding extra variables to each tabs model so it can hold information about the updated name/column number. Potential update could be restoring the update tab name/column number boxes to previous state before save is hit but user has moved tabs.

OCMS Revision: 21913

**Comment by jackjbridge** [comment]
DASHBOARD TABS: Tabs now have a save button, able to modify multiple columns numbers/tab names before hitting save. Done by adding extra variables to each tabs model so it can hold information about the updated name/column number. Potential update could be restoring the update tab name/column number boxes to previous state before save is hit but user has moved tabs.

OCMS Revision: 21913
