### ISSUE TITLE
HTML Viewer Blank In Right Side Action Handler

### ISSUE THREAD

**Issue by keljopap-tsgrp** [tsgrp/HPI#1760]
If the user is in View All Docs and tries to open two html docs side-by-side, the right side one will be blank.

To recreate the issue:
-enable HTML Viewer and disable OA Viewer on the stage config's DocViewer settings
![image](https://user-images.githubusercontent.com/37815877/45054818-b9284b80-b053-11e8-9e26-faa57df0774f.png)

Could be related to the height attribute on the initialization of the HTMLViewer object.

![htmlrsah](https://user-images.githubusercontent.com/37815877/45054946-1fad6980-b054-11e8-8886-46712358b827.gif)

**Comment by abrown45** [comment]
Closed after test on edge.
