### ISSUE TITLE
Moving Chain Versionable documents moves the ACTIVE version instead of the whole version tree

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1761]
When a chain versionable doc is moved (at least through the Share interface), it moves the ACTIVE version to the correct destination, but the other versions and the chain version container stays in the original directory.

The expected behavior would be to move the entire chain version container to the destination.

**Comment by LoganLaFollette** [comment]
After looking in to this problem deeper, we found that calls to `/alfresco/service/slingshot/doclib/action/move-to/node/workspace/SpacesStore/{id}` always executed properly, moving the version chain object, as well as all versions to the new folder. 
Note: the format of every test was as follows: 

Document A (chain versionable content/controlled doc) - created in Folder A
Document A moved to Folder B 
*Check to see if all versions and chain version object moved to Folder B - as well as the corresponding children for Folder A being removed.*
*Documents created in HPI were created as Controlled Docs, and given a minor version before the move call.
*Documents created in share were created as Chain Versionable Content - and also given a minor version before a move call was performed. 

Looking at the network calls made by an Alfresco Share UI move - the only prevalent difference was in the url used. 
Share UI move URL: 
`share/proxy/alfresco/service/slingshot/doclib/action/move-to/node/workspace/SpacesStore/{id}` 

Also, with eclipse debugging, I found that VersionChainPolicy#onMoveNode was not getting hit when the post call went through the share proxy.  (Although I did not have time to test, I did see some erratic behavior as SOME unversioned CVC documents created through share DID move to the destination folder properly) 

Steps to try: 

- set log4j property for BehaviourFilterImpl to DEBUG and see if the filter gets disabled.  

See the following google doc for some resulting data from move calls. 
[]((https://docs.google.com/spreadsheets/d/1O1nGerNQsM_Fkkh7s1YG_vSHk9J4ygaH4TZNhiJbiW4/edit#gid=0))

**Comment by gsteimer** [comment]
When we fix this, we should also re-test #1552

**Comment by gsteimer** [comment]
Given that this hasn't been a priority since last fall, I'm removing the `High Priority` label

**Comment by sambelcher1** [comment]
Alfresco handles moving a node differently if it's parent folder is not the primary parent (seen in FilefolderServiceImpl.java). For chain versionable documents the primary parent is the chain versionable object. In this case, Alfresco just deletes the parent association with the folder and adds a new one, rather than using the move function.

Fixed in OC commit 24496 and Chain Versionable commit 10311

CR: dgrumieaux, gsteimer
