### ISSUE TITLE
Reporting Dashlet - undefined error on date range

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1762]
When enabling a date range on a reporting dashlet, the date range attribute gets automatically selected:

![image](https://user-images.githubusercontent.com/1377228/45367652-5f6dd700-b5a7-11e8-87fa-4a1cb7061adc.png)

If the automatically selected attribute happens to be the attribute you want to select on, the value actually isn't saved to the config even though it appears selected.  Instead, an `undefined` is saved, and the dashlet fails with the following error:

```
2018-09-11 09:33:06,117	ajp-apr-8009-exec-6	ERROR	RESTService	Unable to find property in dictionary: undefined
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unable to find property in dictionary: undefined
	at com.tsgrp.opencontent.alfresco.query.AbstractAlfrescoEmbQueryImpl.buildFTSQuery(AbstractAlfrescoEmbQueryImpl.java:1397) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
```

To fix the problem, the user must choose another attribute and then re-select the desired attribute before saving the config.

There are two ways we can fix this issue - update the html so that the selectbox defaults to a blank option, or we can simply make sure the selected attribute is actually saved to the config vs. `undefined`.  For the former option, we'd want to make sure that we add validation to make sure the user actually selects a date range attribute.

Also - this interface is somewhat confusing since the graph config depends on the query config, yet the query config is below.  While we're in here, we should make the following enhancement:

- [x] Move the Query Config section above the Graph config.  Since the graph config depends on the query config (i.e. - which attribute are available), it's confusing that the query section is below the graph section.

**Comment by joehof** [comment]
Went with the blank dropdown value, since the dropdown value is controlled by knockback and was getting messy to default in the code.

Fixed with OCMS commit 21538.
