### ISSUE TITLE
OCMS Alfresco 6 Compatibility

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1769]
OpenContent needs changes in order to be compatible with Alfresco 6+. This is primarily due to Alfresco upgrading from Spring 3 to Spring 5. Up to this point, OpenContent has been generally proven out to function on Alfresco 6 (Community edition) with changes to the `oc-rest-spring.xml` file. See http://svn.tsgrp.com/repos/tsg/webservices/feature_branches/alf-6-starter for changes made so far.

What still remains to be done is at a minimum the following:

- Add ability to flip between different versions of `oc-rest-spring.xml` file to account for different class file names between Spring 3 and Spring 5
- Update build configuration to allow pointing to correct version of the `repository` dependency.
- Selectively apply the jackson core dep as a runtime dependency (no longer included as part of Alfresco) "group: 'org.codehaus.jackson', name: 'jackson-core-asl', version: '1.9.13'" 
- figure out how to make OpenOverlay work

A full regression test and test of other plugins needs to happen as well (chain versionable, autofile, autonumbering, etc).

**Comment by gsteimer** [comment]
@dgrumieaux @acastor - can we close this one?

**Comment by acastor** [comment]
ALFRESCO 6 COMPATIBILITY: Adding universal-overlay and core-overlay to handle different Alfresco 5 and Alfresco 6 pdfBox dependency versions. Also upgrading Spring to v5 and Jackson to v2. Scheduled quartz jobs are now located in alfresco5xJobs.xml for Alfresco 5 and alfrescoJobs.xml for Alfresco 6. 

When building for Alfresco 5, the pdfBoxVersion property should be set to 1.8.13. If building the hpi-demo-alf project, this property is already set for you in hpi-demo-alf/build.gradle.

When building for Alfresco 6, the alfrescoVersion property should be set to the version number of the alfresco-repository dependency NOT the version of Alfresco you're building for (you can find this in the clean alfresco.war/WEB-INF/lib directory). Additionally if building with the hpi-demo-alf project, springVersion should be set to 5.1.1.RELEASE, pdfBoxVersion should be set to 2.0.12, and the activitiVersion should be set to 5.22.0 (the versions included in Alfresco 6).

CR: gsteimer, mbrouillette, ballen, and dgrumieaux
