### ISSUE TITLE
Bulk Upload - No longer autoselects type when only one available

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1776]
In bulk upload, if there's only one available type, OCMS should auto select it and display the appropriate form (bulk if more than one doc, regular form if one doc).  However, this is no longer happening.

![add-docs-autoselect-fail](https://user-images.githubusercontent.com/1377228/47367019-6f97cc80-d6a4-11e8-8d5c-c300a512985c.gif)

It should auto-select the object type and display it as a label vs. a dropdown:

![image](https://user-images.githubusercontent.com/1377228/47368160-c0a8c000-d6a6-11e8-92f1-69603d2265ba.png)

Note - this is causing STS scripts to fail since the script assumes that the type is auto-selected.

**Comment by ktrinh-tsgrp** [comment]
Issue resolved, revision 21854.
