### ISSUE TITLE
Searching on a single valued attribute with multiple values always returns 0 results

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1779]
On edge1 and edge2 we have this scenario set up for Controlled Docs search on Status.  Status is single valued, but the control is set up to allow multiple.

![image](https://user-images.githubusercontent.com/1377228/47791677-32f15400-dce8-11e8-9284-4b8065cb7391.png)

In the above scenario, documents with status `Approved` or `Effective` should be returned.  However, this query always returns 0 results.  

This behavior was caught by the Search STS and is failing on edge1 and edge2.

From talking to @nquillin91, most likely something in the fix for #1771 accidentally changed this `OR` to an `AND`

**Comment by nquillin91** [comment]
Fixed with REV: 20298
