### ISSUE TITLE
Create Document from Template does not pass Bulk Upload Whitelist

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1781]
If you setup a whitelist for Bulk Upload, creating a document from a template no longer works properly.  On edge1 and edge2, I have the following whitelist set up in the Policy trac:

(note both doc and docx are accepted)
```
pdf,jpeg,jpg,png,gif,doc,docx,docm,msg,potm,potx,ppsm,ppsx,ppt,pptx,pub,xls,xlsx,xlsb,xlsm,xltm,xltx,xltx,xps,html,mp3,mp4,txt,xml,json,eml
```

However, when STS attempts to upload a Word document from a template, the document as caught as invalid by the whitelist:

![image](https://user-images.githubusercontent.com/1377228/48075113-0f2a8400-e1a8-11e8-95f9-b556ec6934cf.png)

This will need to be fixed in order for STS to complete successfully.

**Comment by grahamsinger** [comment]
Closed with r22048
