### ISSUE TITLE
Remove configuration for showing thumbnails in tableview

### ISSUE THREAD

**Issue by keljopap-tsgrp** [tsgrp/HPI#1783]
The `Show Thumbnails in Table View?` config option is lingering from when we were demoing we could display thumbnails before we brought back the grid layout.

![image](https://user-images.githubusercontent.com/37815877/48162871-d2dc4e00-e2a3-11e8-8c15-7c89ce28dcd0.png)

Steps:
1) Remove the localizations and the button.
2) Remove any dependencies in the code.

**Comment by mwojno-tsg** [comment]
This issue was resolved in commit, **25121**. Removed the `showThumbnail` from the results config model and wherever it was used in table view. For this to be reflected on edge the `showThumbnail` needs to be removed from the search configs
