### ISSUE TITLE
Advanced Combine to PDF - Exclude Column Conjures Up Mysterious Rectangles

### ISSUE THREAD

**Issue by keljopap-tsgrp** [tsgrp/HPI#1784]
When the user clicks inside a cell on the "exclude column" within the Advanced Combine to PDF modal but not directly on the glyphicon, a little wingdings-like ascii rectangle squeezes its way into the view and forces them to have to click on the blank space on the right of it to get the desired UI effect for removing a doc.  It's unintuitive.

There must be something off with the onclick behavior for those glyphicons.

![weird-exclude-behavior-actpdf](https://user-images.githubusercontent.com/37815877/48214462-9a8d4c00-e345-11e8-8a3f-05b48b0066eb.gif)

Suggestions:
Perhaps it is already fixed on a branch somewhere - copy that in to trunk.  Isolate all symbol changes to the same location within the cell.

**Comment by Kovacinski** [comment]
Closed with revision 22070
