### ISSUE TITLE
Stage URL garbled when application root is not /hpi

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1785]
When attempting to deploy an OCMS webapp to both edge2 and release2 with an app ID other than `default`, the stage URL is wrong every time the user enters the stage.  For example:

**URL should look like:**
`http://edge2.tsgrp.com/mydemo/Stage/...`

**URL actually looks like:**
`http://edge2.tsgrp.com/mydemo/mo/Stage/...`

From looking at the issue, @joehof thinks that something is hardcoded to 4, which corresponds to the length of `/hpi`... 🤔

**Comment by joehof** [comment]
Pretty straightforward - looks like we hardcoded in a 4 into a substring to account for "/hpi" being a part of the URL. Changed that to look at the length of app.root in case we have set an appId that is not 3 characters long.

Fixed with OCMS commit 21970 and 21972.
