### ISSUE TITLE
Saved Search dashlets cannot be configured on HBase

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1786]
Saved search dashlets cannot be configured when using hbase on the back end.  Setting up the type and columns displayed seems to work fine when you create the dashlet, but after coming back in the columns section disappears:

![image 1](https://user-images.githubusercontent.com/1377228/48731753-6e09e780-ec03-11e8-986a-09214361216a.png)

When setting up the criteria, column values disappear as well.  As seen here, the value disappears when the operator is changed.  This also happens when coming back into an already saved config as well.
 
![hbase-add-criteria](https://user-images.githubusercontent.com/1377228/48731784-7d893080-ec03-11e8-846d-eba9a12e0148.gif)

@aviking - not sure if this is an actual code issue or if something is incorrect in the OTC.  I tried this on edge3 with both `Page Set Instance` and `Document` as the doctype.  Does the same thing either way...

**Comment by jackjbridge** [comment]
In the method **getConfigByType**, the file path is to the indexerConfig, but the indexerConfig has an empty default.json for the Hbase configs. Assuming that is why this problem is occurring

**Comment by jackjbridge** [comment]
It was trying to load in the indexer config, which was empty. Replaced the empty indexer config, with the default indexer config from Alfresco. 

SVN: 22370

CR: Avi King
