### ISSUE TITLE
Versioning above 1.0 results in multiple versions having CURRENT label

### ISSUE THREAD

**Issue by jackjbridge** [tsgrp/HPI#1795]
When a user creates a major version of a form, it correctly publishes and makes the form available to make active. Then if the user goes back to make another major version, the number does not update and the user will end up making two forms with the same version number, throwing everything off. 

Example pictures below:

![image 10](https://user-images.githubusercontent.com/42980355/49256567-f606a300-f3f4-11e8-8aa3-f92e0d605094.png)

What I already have in there.

![image 11](https://user-images.githubusercontent.com/42980355/49256572-facb5700-f3f4-11e8-86e3-dd09f23d7caf.png)

I will be taking a look at this tomorrow, just wanted to keep a log of it being an issue

**Comment by gsteimer** [comment]
@jackjbridge - could it have something to do with you having the `0.1` version active?

**Comment by jackjbridge** [comment]
Potentially. I'm not sure how it is on Alfresco but on HBase that active checkmark stays over the first version no matter which version is selected and made active. Could that be affecting things?

**Comment by gsteimer** [comment]
@jackjbridge yes, for sure.  I think that's the root of the issue

**Comment by jackjbridge** [comment]
Fixed versioning for anything that is not a controlled doc. Before, versioning above 2.0 was not possible, and minor versioning after making a major version did not work. In HBaseContentImpl, a new method called isControlledDoc checks on the object type of a document. This allows us to avoid applying controlled doc logic to documents that aren't controlled docs.

SVN Revision: 20647

CR: George, Natalia, and Dan. G
