### ISSUE TITLE
Active Wizard Leading Pages don't factor in Critera - Lead on query generated answer will not work

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1797]
The WizardAdmin has the ability to conditionally add a page based on a certain value of an input's answer.

Currently, this functionality is not working as expected.  Rather, we seem to only get functionality related to whether the a certain answer has _any_ value vs. not (having one).

Since this isn't top priority right now, I'm creating this and also putting a `TODO` in the module (`pagesetinstanceprovider.js`) where I suspect the fix will be.

To replicate: use `TS Leading Actions` and look at Question 5.

**Comment by gsteimer** [comment]
Marking this as an enhancement since this hasn't been implemented in the HTML5 AW yet.  See https://github.com/tsgrp/ActiveWizard/issues/105

**Comment by renesaladrigas** [comment]
LEADING RULE - Adding support to leading rule criteria values. Configuring a criteria value on a leading rule will take precedence in the equality check to determine if we are going to a new page, then defaulting to checking if the value is equal to the hard coded answer value. Fixes GH issues: https://github.com/tsgrp/HPI/issues/1797 and https://github.com/tsgrp/ActiveWizard/issues/105

CR - nquillin, gsinger
rev - 22571
