### ISSUE TITLE
File Extension Map Has File Extensions In Lowercase - Not All Places In OC Ensure The Extension Being Check Is Lowercased

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1798]
Our file extension map defined in OC is currently all in lowercase, there are several locations in OC that use this map to get the corresponding content formats, but the check doesn't ensure that the extension we are trying to find a match for is lowercase. Ie. Looking for PDF in the extension map, where the map contains pdf, won't result in a match. 

The fix here would be to ensure that file extensions are made lowercase before checking against the map

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-55
