### ISSUE TITLE
Send Email - Typeahead Doesn't Add Email If Fully Typed Out AND Is Available As A Suggestion

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1800]
![typeaheadsuggestionsdontworkwhenpopulated](https://user-images.githubusercontent.com/13734523/49591126-30ab9680-f933-11e8-936b-58671116b7b1.gif)

When sending an email to an email that has already been used, a suggestion appears for the email address. If the user clicks tab / enter prior to typing the whole emaill address out it successfully adds the email. If the user types the full email address out and then hits tab / enter. Nothing happens. The logic for onBlur in typeahead seems to be flawed, not properly accounting for when a suggestion is valid.

**Comment by IanCMcKee66** [comment]
TYPEAHEAD 
resolving an issue where the typeahead for an email doesn't autocomplete and enter the recipient's name when tabbed if the name is an exact match of the email from the address book. Cleaned up functionality for unit testing.

OCMS Revision: 22167

CR- Nick, Steve
