### ISSUE TITLE
Cannot create form that is not autonumbered

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1806]
See the screencam below.  On both edge2 and release2, if a form is not autonumbered, clicking the create form button does nothing.  No errors in the console or network requests are fired.

Edge2 - the `Simple CR` form is autonumbered, the `Master Services Agreement` form is not
![create-form-does-nothing](https://user-images.githubusercontent.com/1377228/50118607-cf7aa180-0215-11e9-867e-30b859ca383f.gif)

Note - I should say that _sometimes_ I can create the form.  Perhaps there's a timing issue going on because it has worked for me today on both edge2 and release2.  It seems to work consistently on edge1 and release1.

**Comment by jackjbridge** [comment]
![selecting wizard forms](https://user-images.githubusercontent.com/42980355/50119699-1f0e9c80-0219-11e9-9715-dba0b902c02d.gif)

To replicate, typing to search for a form causes this error. if you select from the dropdown it works as expected

**Comment by gsteimer** [comment]
Something must've changed - I can't reproduce this anymore on both edge1 and edge2.  I'll bump the priority of this down in case it crops up again.  If it doesn't by the end of the 3.2 release, we can close it.

**Comment by gsteimer** [comment]
Looks like this was fixed with #1809
