### ISSUE TITLE
Tableview - clicking on link from search selects row

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1807]
After searching, clicking the link that should launch the stage for a document or folder selects the row rather than taking the user to the stage.  Clicking the link again when the row is selected works as expected.

![search-tableview-click](https://user-images.githubusercontent.com/1377228/50158260-486f0d00-0299-11e9-819d-84ae2b50cf1f.gif)

Perhaps this is related to #1805 ?

@keljopap-tsgrp @benallenallen @Kovacinski

**Comment by gsteimer** [comment]
Note - this same thing is _not_ happening when clicking a link in View All Docs...

**Comment by CRdouglas** [comment]
REV - 22212, 22215, 22217

EDITABLE SLICK.GRID CELL ENHANCEMENTS: Allows the user to click inside of an editable cell and drag outside of the cell to select everything within that cell. Resets the cells active state to a normal state after leaving the cell.

Fixes previous commit - 22173

UNIT TESTS - Completed.

CR - Steve, Alex
