### ISSUE TITLE
Cannot create form if chosen with mouse

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1809]
When a form is autonumbered, the user should _not_ be able to give the form instance a name.  However, if you select an autonumbered form from the dropdown using the mouse, the user cannot create the form.  Instead, the `New Form Name` field is incorrectly displayed.  The same thing happens when the user clicks the close modal button.  See the screencams below:

![create-form-autonumbered](https://user-images.githubusercontent.com/1377228/50775940-34497a80-125d-11e9-8608-a739472806f8.gif)

![create-form-close-modal](https://user-images.githubusercontent.com/1377228/50775633-470f7f80-125c-11e9-9651-4f89928ce858.gif)

Notes:
- You must select the form in the dropdown with your mouse.  If you use the `Enter` keyboard button, the form is created
- You also need to type some of the form name and _then_ click the item.  If you simply select it in the dropdown, it works fine.
- Using the `Esc` key to close the modal works correctly.
- The user cannot circumvent the autonumbering as typing in a name and clicking the create button does nothing
- Could this potentially be related to #1806?  That issue seems to have been resolved since it was opened however...

**Comment by gsteimer** [comment]
In trying this again on edge2, I'm seeing issues with normal (not autonumbered) forms as well.  For these forms, you must choose the form with the autocomplete dropdown button.  Otherwise, the form cannot be created

**Comment by LoganLaFollette** [comment]
Fixed with OCMS revision: 22301 

@gsteimer not sure if #1806 is from something unrelated or not - but I have a feeling that issue is resolved as well.
