### ISSUE TITLE
Bulk Upload - Heads Up Indexer no longer displays for Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1815]
The Bulk Upload action on both edge1 and release1 is configured to display on the insurance tracs.  At one point, this worked, but something changed and it no longer displays.  I don't see any errors in the console or in the OC logs.  It _does_ look like documents are being added to the indexer temp.  Here's the last one I tried (on the `hpi_demo_alf` internal repo)

![image](https://user-images.githubusercontent.com/1377228/51142661-3047ca80-1812-11e9-8060-9f46078ee73e.png)

**Comment by ktrinh-tsgrp** [comment]
Fixed with OCMS revision 22771:

```
bulkupload: bhudi will trigger based on original (non extension stripped) filenames

CR: gsteimer, skovacinski
```
