### ISSUE TITLE
Notifications do not send in Documentum Environments

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1818]
See the screencam below.  For some reason, notifications do not send on the edge1 and release1 Documentum environments.  There are no errors in the console or in the OC logs, so it must be getting stuck somewhere before the request is fired off. 

![send-notif-edge1](https://user-images.githubusercontent.com/1377228/51262238-98fc8780-1977-11e9-9c02-67d80a257585.gif)

I've attempted in multiple tracs and on edge1 and release1, but no dice.  Notifications are working fine on edge2 and release2 (Alfresco)

**Comment by grahamsinger** [comment]
Fixed with HPI Committed revision 22353.
