### ISSUE TITLE
Saved Search Reset does not work properly with proximity dates

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1819]
When a search contains proximity dates, switching to another saved search does not properly clear out values.  See the screencam below:

![saved-search-reset](https://user-images.githubusercontent.com/1377228/51263082-360bf000-1979-11e9-8d7c-69881f465af9.gif)

- Switching between two saved searches that do not contain proximity dates work fine
- [ ]  Switching to a saved search with proximity dates does not properly clear out criteria left over from a previous search.  Note - the screencam shows bouncing between two saved searches, but the same thing happens if you execute a regular search and then choose a saved search with proximity dates.
- [ ] Switching from a search with proximity dates to a saved search without does not properly clear out the proximity date values
- [ ] In both of the above scenarios, the saved search is actually sending over the desired criteria to OC because the search results are correct.  Notice though, if I click the search button with the criteria as displayed, the search (correctly) returns 0 results.

**Comment by kforbes** [comment]
Closed with HPI revision 22325
FORM SUPPORT - clear out existing values in a form before setting new values for a saved search
CR - Nick, Rene
