### ISSUE TITLE
Faceted Search - Ability to select more than one value in the same attr group

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#182]
From the HPI Advisory Board meeting on 2/20

It would be nice if faceted search worked more like Amazon facets.  For example, if I search for shoes and facet on brand, I should be able to narrow down to 'Nike' and 'New Balance'.  With the way HPI is now, you'd only be able to select one or the other.

**Comment by ladams13** [comment]
Can this be closed?  I am setting up Facets for a client and noticed while testing how they work in edge, was able to select multiple Statuses (Draft and Approved) when searching on the wizard trac.  Forms with both statues returned.

**Comment by gsteimer** [comment]
@ladams13 - yes, I think we can close this one.  @joehof - feel free to comment if you do not agree
