### ISSUE TITLE
Allow "Launch Item In New Window" Button to Open Configured Viewer Instead of OA

### ISSUE THREAD

**Issue by keljopap-tsgrp** [tsgrp/HPI#1822]
![launchinnewtaboaviewer](https://user-images.githubusercontent.com/37815877/51741522-d5597300-205c-11e9-907d-fe073714653f.gif)

Currently the launch in new tab button on the viewer in stage is hardcoded to open up OA, even for docs that aren't suited for it.

This needs to be changed to go through the link resolver module and launch a content viewer, which will take care of selecting the correct viewer.  Step through exactly how the open in new tab action handles this to understand.

**Comment by gsteimer** [comment]
It's actually not hardcoded, but the old configuration options need to be changed.  Currently, the options are:

![image](https://user-images.githubusercontent.com/1377228/51751840-8111bb80-207b-11e9-9bc0-911a94bb6048.png)

Instead, the options should be `Doc Viewer` or `Browser` rather than forcing everything into OA

**Comment by gsteimer** [comment]
Bumping this to 3.2 since I'd like to try to get this into the Spring 2019 release

**Comment by gsteimer** [comment]
When fixing this one, let's make sure that wherever this occurs in the admin, we default the config to `DocViewer`

**Comment by ebrent** [comment]
DOCVIEWER - Changed stage config additional properties to have the options "doc viewer" or "browser" when launched externally. Now, with the Doc Viewer option, when opening a file, it will open with path "hpi/DocViewer".Therefore, the document will open with the configured stage viewer.

Revision #22698
CR: @rsaladrigas @dvora
