### ISSUE TITLE
AW Word Mail Merge isn't Merging Answers

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1826]
When an AW form is tied to a Word Mail merge template, the system is correctly using the template, but none of the data is applied.  See below:

**AW Data**
![image](https://user-images.githubusercontent.com/1377228/51856345-153a8780-22f5-11e9-94af-acd9869a4ccf.png)

**PDF Form**
![image](https://user-images.githubusercontent.com/1377228/51856365-24213a00-22f5-11e9-8a7f-d10f690d7e46.png)

**Comment by grahamsinger** [comment]
Fixed with committed revision 21498.
