### ISSUE TITLE
Add MuPdf support to OpenContent/OpenAnnotate Transformations

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1832]
Ghostscript is currently the primary PDF->PNG transformer of choice for OCMS - this enhancement is to add support for MuPdf, which is a faster and better command line transformer.

- [x] Add support for MuPdf as an OC transformer
- [x] Update OC to use MuPdf as default transformer instead of Ghostscript
- [x] Ensure edge, qa, and release environments utilize MuPdf
- [x] Add wiki page with muPdf info and configuration options

**Comment by egrahamtsg** [comment]
![image](https://user-images.githubusercontent.com/42980322/52297079-89a0a680-2945-11e9-8b9d-6fe7cd1a9004.png)

**Comment by egrahamtsg** [comment]
MuPDF TRANSFORMATION: Adding the 4.transformMuPdf module, which RestOpenAnnotate endpoints 'transform' and 'forThumbnails' utilize to transform pdfs to pngs. MuPDF is replacing Ghostscript for this functionality. Note: mupdf should replace ghostscript in build files and the path to the local muPDF installation must be injected in transformation-mupdf-defaults.properties.
CR: dgrumieaux, jhof

In commit 21162, we replaced Ghostscript with MuPDF for RestOpenAnnotate transformation endpoints. MuPDF runs via command line and is implemented in a structure similar to Ghostscript, but it is better adept to transform pdfs into pngs with higher resolutions. 
Additions/changes:
-1.core-client
	-renamed GhostscriptTransformationOptions to ArtifexTransformationOptions because it is used by both Ghostscript and MuPDF
	-Added MuTransformationRequestContext, which contains the injected variables from transformation-mupdf-bean-config.xml
-1.transformation-utils
	-TransformationUtils#processAndValidateTransformationOptionsForMuPDF validates options inputted via rest endpoint
	-MuPDFTransformThread.java allows for multi-threading
	-MuPdfTransformer.java wraps injectables together, calls the TransformationUtils function to prepare other options, makes the call to the MuPdfTransformer.java in the '4.' module, and cleans up temp files after the process completes
-4.transformMuPdf
	-new module that replaces 4.transformGhostscript in build files
	-MuPdfTransformer.java builds up command line arguments, executes the command via Process Builder, and writes the transformed png's content to the output stream
Notes:
-See documentation: https://mupdf.com/docs/index.html
-Injected path to mupdf installation is required in transformation-mupdf-defaults.properties within the '4.' module or the environment-specific opencontent-override-placeholders.properties file
-To do: implement non-temp files for the output png by reading the png from the stdout of the muPDF process

**Comment by dgrumieaux** [comment]
This has been commit to trunk, but there is currently an issue with thumbnails that needs to be resolved before we can close this enhancement request.

**Comment by egrahamtsg** [comment]
> This has been commit to trunk, but there is currently an issue with thumbnails that needs to be resolved before we can close this enhancement request.

The thumbnail issue is fixed with revision #21191

**Comment by egrahamtsg** [comment]
MuPDF support has been added successfully (revisions 21162-21191)
