### ISSUE TITLE
Form Support - Default values are not longer working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1835]
In the indexer admin trac (edge2 and release2), the index status field is configured to put a default value of `New` in the form:

![image](https://user-images.githubusercontent.com/1377228/52489775-c27c8d80-2b88-11e9-9108-1afa744de8c4.png)

Unfortunately, it looks like form support isn't honoring defaults anymore:

![image](https://user-images.githubusercontent.com/1377228/52489804-d32d0380-2b88-11e9-8235-c1de654d8ddf.png)

**Comment by LoganLaFollette** [comment]
Fixed with OCMS revision: 22473
