### ISSUE TITLE
OC License - Show Expiring Soon Message

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1837]
Currently, only OA shows a 'license expiring soon' message.  We should have the same functionality in OCMS.

Also, while looking into this, let's also make OCMS show the 'add license' page when the license is either Expired or Invalid for too many users.  Currently, if the license is invalid due to the repository being over max users, the OC error page is displayed.

**Comment by LoganLaFollette** [comment]
Added 'expiring soon' banner, as well as new error messages for licenses that are expired or have too many users.  

OC revision: 21810
OCMS revision: 22663
