### ISSUE TITLE
Update Results Message on Standardized Table View when Text Filters are Applied

### ISSUE THREAD

**Issue by keljopap-tsgrp** [tsgrp/HPI#1838]
When switching from table view to standardized table view, the results message has an extra "Showing _x_ results using " trailing after it.  The results are accurate - we just want it to appear the same as the message that shows when you're switching in to standardized table view with predefined filters or facets applied.

![standardized-text-filter-using](https://user-images.githubusercontent.com/37815877/53051284-12006a80-3461-11e9-9de5-7e9eafaf46c6.gif)

**Comment by abrown45** [comment]
Closed with commit 24920
