### ISSUE TITLE
Table view right click broken in IE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1839]
See the screenshot below.  The right click action menu is not appearing in IE11 table view:

![image](https://user-images.githubusercontent.com/1377228/53098348-09537700-34e9-11e9-822a-71d762d0ac44.png)

This is occuring both in search and View All Docs.

Note - this issue is breaking system tests.  The STS machine is also failing using FireFox 30.0.1, but it seems to work on my local FireFox 65.0.1.  No need to fix the older version of Firefox, just including this here for posterity.

**Comment by keljopap-tsgrp** [comment]
See revision #22477.  Should also fix Firefox.
