### ISSUE TITLE
Stage header links not clickable after delegate task

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1845]
See the screencam below.  After executing a delegate task in IE, the non-action header links change the browser URL, but nothing happens.

![stage-header-links](https://user-images.githubusercontent.com/1377228/53432772-bf6f0300-39b8-11e9-8436-baf9ee18ddbf.gif)

Errors in the console:

![image](https://user-images.githubusercontent.com/1377228/53433041-445a1c80-39b9-11e9-9c42-a617ce584f8f.png)

**Comment by gsteimer** [comment]
Could be related to #1684

**Comment by nquillin91** [comment]
Looks to be affecting other actions as well: starting a workflow on a document and then trying to click a header link also causes the issue.

**Comment by nquillin91** [comment]
Fixed by OA rev: 5568
