### ISSUE TITLE
Workshare Compare fails after update to REST

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1847]
After the upgrade to utilize the REST endpoints for Workshare Compare, it's failing to show the comparison document on both edge1 and edge2.  The page comes back with:

![image](https://user-images.githubusercontent.com/1377228/53972508-8b849380-40c4-11e9-9ffa-b97a016a14ce.png)

**Comment by grahamsinger** [comment]
Fixed with committed revision 21548.
