### ISSUE TITLE
Config Archiver - cannot archive configs

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1849]
When attempting to archive configs on any environment, the following javascript error occurs:

![image](https://user-images.githubusercontent.com/1377228/54439254-716f3480-4706-11e9-96b8-81119338769d.png)

**Comment by kforbes** [comment]
CONFIG ARCHIVER - fix config archiver to have an action data object with the action's name. Update to logging in download utils to check for an empty data object
CR - jhof
