### ISSUE TITLE
Active Wizard text fields with currency mask - very difficult to type

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1854]
See the screencam below.  It seems like the cursor is constantly trying to go to the end of the line, making it virtually impossible to type a currency in a textbox:

![aw-currency-textbox](https://user-images.githubusercontent.com/1377228/54835253-c293a100-4c8f-11e9-9e9d-208a0f4e23af.gif)

If you type _really_ fast, it can work - but it's extremely difficult.

**Comment by ebrent** [comment]
ASPECT - Now able to type numbers in "currency" field and have it format only after the last digit is entered. Wrapped function to format in a debounce after one second. Spec file for changes made committed here.

Revision #: 22682
CR: @rsaladrigas @dvora

**Comment by ebrent** [comment]
OnBlur display is now delayed because we delay to format when a user inputs. Therefore, when total is calculated the display of it is also delayed.

**Comment by ebrent** [comment]
ASPECTS - made a new function setDisplayValueNormal that doesn't wait to format (debounce) when clicked out or tab is hit. In order to wait to format everything else, setDisplayValue calls setDisplayValueNormal with a debounce. 

Revision #22712

CR rsaladrigas, nquillin
