### ISSUE TITLE
Add Documents - admin configuration for sanitized object names

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1862]
In the Bulk Upload action, it would be nice to have a configuration that will sanitize the object name field.  This would primarily be needed for Alfresco clients, since Alfresco is much more restrictive object name characters.  Alfresco only allows characters valid in a Windows file name, whereas other repositories allow any character.  We should discuss this in more detail, but here are some items I think this enhancement should have:

- [x] Admin - allow to turn this on or off (default off)
- [x] Admin - if on, provide a default list of restricted chars (base off of Alfresco's list, but allow admin to modify
- [x] Admin - provide an optional "replace" character.  For example, replace invalid chars with `-` or `_`
- [x] When adding a document, sanitize the file name before placing it in the object name field (this would be needed in the case of Box or Gmail integration, or when chars typically allowed in a windows file name are in the restricted char list.
- [x] If a user tries to enter an invalid char, replace the char with the "replace" char, or simply remove it if no replace character is configured

**Comment by FrankSalmick** [comment]
Added in rev 23069
