### ISSUE TITLE
Add Documents - Gmail integration is brittle on Alfresco when using heads up indexer

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1863]
Since the Gmail integration assumes that the subject of the email is the name of the object, it is very easy to end up with an error when the heads up indexer is configured and the back end is Alfresco.  If the subject contains characters such as `/` or `:` (which is _really_ common - `Re:` or `Fwd:`), both the heads up indexer will fail as well as the eventual document upload unless the object name is manually changed by the user.

This is somewhat related to #1862 , but is a little more broad in scope.  Whether or not object name sanitization is configured, we should be filtering out invalid characters when using the heads up indexer.  Even on Documentum or other repos, this wouldn't hurt since the temp document's name is never actually displayed to the user.

**Comment by FrankSalmick** [comment]
Fixed in 23042

**Comment by gsteimer** [comment]
Updates look better, but it seems like some extra characters are pre-pended to the object name.  For example:

Email subject: `Huddle Notes: Monday 6/10/19`

Object Name: `1560262210371-0-Huddle Notes Monday 61019.html`

![image](https://user-images.githubusercontent.com/1377228/59278998-c4cf2100-8c28-11e9-8a68-0943b75819bd.png)

**Comment by nquillin91** [comment]
@gsteimer 

@FrankSalmick is working on fixing that issue where it will account for duplicate names in a more appropriate manner. Ie, uploading two image01s from GMAIL will result in image01.png and image01-1.png

**Comment by nquillin91** [comment]
OCMS REV 23272 / Followup commit 23576
