### ISSUE TITLE
Folder Terms - results are not correct

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1864]
The folder terms object should be generated based on the specific folder's contents.  However, it looks like it's either incorrectly pulling in terms from other folders or duplicating results.  Here's an example:

**Claim on edge2 with no folder terms:**
14 Docs in the folder:
![image](https://user-images.githubusercontent.com/1377228/55486526-138d8880-55f2-11e9-8308-b78b32145bbe.png)

No terms object:
![image](https://user-images.githubusercontent.com/1377228/55486369-d0331a00-55f1-11e9-8714-521f572255d5.png)

**After reindexing folder terms:**
![image](https://user-images.githubusercontent.com/1377228/55486630-4172cd00-55f2-11e9-8227-9216b45421a3.png)

Some of the documents are duplicated.  Other's don't even exist in this folder.  Ex:

![image](https://user-images.githubusercontent.com/1377228/55486673-5b141480-55f2-11e9-9a5b-cbed5cce8f1c.png)

![image](https://user-images.githubusercontent.com/1377228/55486761-7da62d80-55f2-11e9-84d0-5fcc2a22726d.png)

While we're in here, we should also be filtering out the `.oc-info` and `.folder-notes` folders and objects since these should be hidden from OCMS.

**Comment by ebrent** [comment]
FOLDERTERMS - Changed query parameter logic from OR to AND in order to get the correct folder terms in that specific folder. 

Revision #21902

CR: gsteimer rsaladrigas
