### ISSUE TITLE
Word documents are not opening correctly in pdf.js

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#1865]
Opening a word document that should have a PDF rendition on a stage that has configured the viewer to prefer pdf.js (such as in the Engineering trac on edge2), produces an error that the PDF is invalid/corrupted.

There seem to be no errors on the OC side...

![image](https://user-images.githubusercontent.com/14186921/55497884-e4821180-5607-11e9-88ef-f48884c4f2c7.png)

**Comment by jackjbridge** [comment]
Equal sign got left out during commit #22689 in HPI, fixed by putting equal sign back in.

SVN#: 22815

CR: skovacinski, rsaladrigas
