### ISSUE TITLE
Indexer Admin loses saved values

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1866]
A number of issues still persist with the indexer admin:

If you add a new object type to the configured form, everything disappears.  Ex:

Pre-form update:
![image](https://user-images.githubusercontent.com/1377228/55510653-58321780-5624-11e9-8db2-54dd8ed510f0.png)

Post Form update (added a type)
![image](https://user-images.githubusercontent.com/1377228/55510686-641dd980-5624-11e9-825b-cef97da6b563.png)

To get the values back, you can choose a new form and then re-choose the original form (in this case `indexerForm`.  However, all the pre-configured indexer values are blank:

![image](https://user-images.githubusercontent.com/1377228/55510742-87488900-5624-11e9-8f73-f3562d64c6c3.png)

At this point, you have two choices - reconfigure everything, or delete the type you added above from the indexer form.  Interestingly, if you do that, all the saved values come back

I've also seen the "blanking out" happen when editing an indexer config, but I can't make it happen consistently.

**Comment by gsteimer** [comment]
@ebrent - I'm still seeing this happen after adding a type to the form on edge2:

![image](https://user-images.githubusercontent.com/1377228/56060247-ed6f9300-5d2b-11e9-9612-3f1f9df09dfe.png)

I can get it to come back, but I have to expand each section and hard refresh.

**Comment by jackjbridge** [comment]
At least one issue related to this is the changeForm function. Here is what the options passed along to the IndexerConfig.TypeModel looks like when the config is loaded correctly.

![image](https://user-images.githubusercontent.com/42980355/68956800-646f7d00-078e-11ea-97e1-3eca195936a1.png)

Now when I change to another form and come back to the same form: 

![image](https://user-images.githubusercontent.com/42980355/68957046-d9db4d80-078e-11ea-90fb-ebc1206e8a49.png)

This is why the configs are getting initialized with no value. In changeForm in IndexerConfig.js, is one of the spots where we would need to make changes to fix this as the IndexerConfig.TypeModel currently gets instantiated with this:                     

new IndexerConfig.TypeModel({
                        "ocName": type.get("ocName"),
                        "label": type.get("label")
                    });

**Comment by renesaladrigas** [comment]
Fixed with revision 24960.
Committed by cheinz, CR'd by jhof and rsaladrigas
