### ISSUE TITLE
Double Scrollbars are appearing on Stage

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1871]
Double scrollbars are appearing again on the Stage when viewing a document.

![image](https://user-images.githubusercontent.com/547941/55897643-8a90c700-5b86-11e9-829f-7e193a883a51.png)

**Comment by gsteimer** [comment]
@LoganLaFollette is this related to your changes for #1837 ?

**Comment by LoganLaFollette** [comment]
Fixed with OCMS revision: 22813
