### ISSUE TITLE
Combine PDF can leave temp files behind on the server

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1872]
Looking at the temp drive of edge2, it looks like there are a bunch of files called `OverlayFile*.temp`.  From grepping the code, it looks like `AdvancedCombineToPDFActionExecuter` is creating these files (as well as others) in the `executeImpl`.

For all of these files, we should be cleaning them up in a `finally` block.  In the case of the OverlayFiles, there is a line like this:

`overlayFile.delete();`

However, if an error occurs before this line, the file will never be deleted.

Looking at the other files that are created in here, it looks to me like they could suffer from the same issue.  We should clean those up as well.

**Comment by jackjbridge** [comment]
ACTPDF/CONTROLLED PRINT: Cleaning up temp files and streams that weren't getting closed/deleted in AdvancedCombineToPDFActionExecuter and ControlledPrintActionExecuter. This was due to the fact that the delete/close methods were not in a finally block.

SVN: 22128

CR: skovacinski, gsteimer
