### ISSUE TITLE
Alfresco - Attribute Unique in Folder rule uses incorrect logic

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1875]
With the update that changed the default logic operator from `AND` to `OR`, this external form rule is now broken:

![image](https://user-images.githubusercontent.com/1377228/56384798-fb695c00-61e2-11e9-9db1-232463019823.png)

Instead of checking in the folder, it checks the entire repository.  Here's the query that's being generated:

```
(=cm\:name:Fake\ Check\ 3\.pdf OR PARENT:"workspace://SpacesStore/5ad3e69f-ad6f-4231-8bfb-5a6e358fb968") AND TYPE:insuranceDemo\:claimsDocument AND -ASPECT:cm\:workingcopy AND (cvn\:isActiveVersion:true OR -ASPECT:cvn\:chainVersionable)
```

It should be:

```
(=cm\:name:Fake\ Check\ 3\.pdf AND PARENT:"workspace://SpacesStore/5ad3e69f-ad6f-4231-8bfb-5a6e358fb968") AND ...
```

**Comment by grahamsinger** [comment]
Fixed with OC revision 22109.
