### ISSUE TITLE
Form rule to ensure unique document name not working for computed fields

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1876]
It looks like the `Attribute is Unique in Folder` External form rule is not working on computed fields.

![image](https://user-images.githubusercontent.com/1377228/56586634-ab551580-65a5-11e9-87de-9f8d8f41cfa7.png)

This setting is currently working fine for both Claims and Underwriting docs on edge2, but does not work correctly in the Invoice trac.  Invoice names are computed in the form.  Here are some screenshots of what's going on:

**Form Start**
![image](https://user-images.githubusercontent.com/1377228/56586733-d8092d00-65a5-11e9-8d35-6b3e1ee3eefe.png)

**Computed filled out**
![image](https://user-images.githubusercontent.com/1377228/56586797-f8d18280-65a5-11e9-92ff-287e1aa5613c.png)

It looks like the front end is trying to send a `null` type to OC for dictionary lookup.  Here's the error in OC:

```
2019-04-23 08:54:43,108	ajp-apr-8009-exec-7	ERROR	RESTService	Unable to find type in dictionary: null
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unable to find type in dictionary: null
	at com.tsgrp.opencontent.alfresco.query.AbstractAlfrescoEmbQueryImpl.buildFTSQuery(AbstractAlfrescoEmbQueryImpl.java:1468) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.alfresco.query.AbstractAlfrescoEmbQueryImpl.executeQueryAlfrescoAPI(AbstractAlfrescoEmbQueryImpl.java:484) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.alfresco.query.AbstractAlfrescoEmbQueryImpl.executeQuery(AbstractAlfrescoEmbQueryImpl.java:374) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
```

**Comment by jackjbridge** [comment]
FORM SUPPORT: Fixing issues with computed attributes not being able to have external rules applied to them. Putting object type on now in computedFormControl.

SVN: 22822

CR: skovacinski, nquillin

**Comment by gsteimer** [comment]
@jackjbridge - looks like the check is picking up the duplicate name properly, but it's still letting me submit the document

![name-check-computed-fail](https://user-images.githubusercontent.com/1377228/57406358-21609b80-71a6-11e9-8116-5915dfcfce81.gif)

**Comment by jackjbridge** [comment]
EXTERNAL FORM RULE: The finish and upload button was still allowing the user to attempt to upload even though the external rule was invalid. Added a new variable that picks up the return value from the external rule check and uses that to allow/disallow upload.

SVN: 23005

CR: aking, nquillin
