### ISSUE TITLE
Notification for document with no READ access - Message not displaying correctly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1880]
In the scenario where a user sends a notification for a document to another user that does not have `READ` access to the document, the alert correctly does not allow the user to view the document:

![image](https://user-images.githubusercontent.com/1377228/57034632-ab908900-6c15-11e9-837e-8e42e1644e50.png)

However, the user can also click on the link in the email.  In this case, the "Unauthorized" message displays, but the view is way off.  Notice the scrollbar on the stage as well:

![image](https://user-images.githubusercontent.com/1377228/57034687-d1b62900-6c15-11e9-8f41-601e454feaa8.png)

It looks like the view is trying to place it in the normal position, but something is bumping it to the bottom.

One way to replicate this issue is to notify a user in no groups to a Controlled Document in the `Draft` state.  Ex for `jconsumer` user: http://edge2.tsgrp.com/hpi/#Stage/controlleddocs/workspace://SpacesStore/72b9d4da-7463-4fa3-a250-1a8989b5a67f%7Cworkspace://SpacesStore/235f21bf-edfb-43d9-ad19-953fcbd91f51

While in here, take a look at the code.  Was this ever supposed to work in the case of using a stageSimple link?  @aviking was seeing issues with this.

**Comment by jgonzalez-tsg** [comment]
DOCVIEWER- Made unauthorized message appear at the top of the docviewer for users without read permissions, also hid action that they did not have permissions to use. 

Github Issue: https://github.com/tsgrp/HPI/issues/1880

CR: nquillin
    skovacinski
    cdouglas
