### ISSUE TITLE
Alfresco - Controlled Documents with eSig only display first page in OA

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1882]
On release2, as soon as a signature page is added to a controlled document, OA only displays the first page of the document.  See the screenshot below:

Doc in OA:
![image](https://user-images.githubusercontent.com/1377228/57163112-db769280-6db5-11e9-8418-691fc5f8f808.png)

PDF Contents:
![image](https://user-images.githubusercontent.com/1377228/57163132-e9c4ae80-6db5-11e9-86d4-f3644dd0b4f7.png)

When looking at this with marc, we did notice the following flash in the logs when doing a power promote of a document:

```
2019-05-03 14:51:03,232	ajp-apr-8009-exec-8	ERROR	XFDFAnnotationImpl	Unable to get pages from this document.
2019-05-03 14:51:03,232	ajp-apr-8009-exec-8	DEBUG	XFDFAnnotationImpl	COMPLETED Loading PDF document using Apache PDFBox and populating the word maps for pages (0-0)
```

Here's what's really odd - this only happens on Release2.  It works fine on edge2.  I just pushed a release build today, so the two environments are running the exact same code.  This code is also working fine on Release1 and edge1.

One thought that @m-brouillette had - could this be caused by the way we're appending the signature page?  There have been changes recently last month...

**Comment by gsteimer** [comment]
Hmm... this is interesting.  If I turn on PDF.js, it only shows me the _last_ page.

![image](https://user-images.githubusercontent.com/1377228/57248853-102e5800-7009-11e9-9a79-9b8cd6c9c338.png)

**Comment by grahamsinger** [comment]
Have fix for this. To commit tomorrow

**Comment by grahamsinger** [comment]
Fixed with revision 22253 in OC.
