### ISSUE TITLE
Indexer and Add Documents Text Selection no longer working for some documents

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1886]
See the screencam below. It seems as if both the highlight as well as the double click to select functionality is no longer working.   

![indexer-fail](https://user-images.githubusercontent.com/1377228/57394074-23b4fc80-718a-11e9-9a7f-dc2e042182ee.gif)

The above screencam is from Edge2.  The Acme PDF is not selectable, but the FedEx invoice works properly.  Interestingly, on Release2, _neither_ PDF works properly.

**Comment by gsteimer** [comment]
@jharkins2 - can you close this?

**Comment by jharkins2** [comment]
Close at Revision #22283 

OA TEXT SELECT DATA

Fixing issue which would cause text select data to be cached incorrectly, making it possible to get the cached data for a different PDF or wrong version.

CR: ballen, aking
