### ISSUE TITLE
Type dropdown disappears in search if only one Type is expanded in the config

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1895]
The type dropdown will disappear if you only expand one of the types in the search config.  I usually able to get them to show again by expanding them both again as shown in the GIF.  

See GIF below: 
![type_dd](https://user-images.githubusercontent.com/8784597/58912832-990be280-86e0-11e9-9fc2-e7743528665b.gif)

**Comment by gsteimer** [comment]
@grahamsinger - does this only happen on the admin's browser?  I.e. - if you were to do the part in the admin and then login using another machine/browser, would that session see the issue in search?

**Comment by grahamsinger** [comment]
@grahamsinger This seems to affect any user which would point to the config being saved incorrectly rather than something being messed up with a particular user's "application state"

**Comment by gsteimer** [comment]
@grahamsinger - I just tried this again on edge2 and I can't seem to reproduce it.  Can you still get it to fail?

**Comment by gsteimer** [comment]
Closing this issue - I have tried to reproduce this numerous times over the past month or so and have been unable to.  We can re-open this if needed.
