### ISSUE TITLE
Display timing data to the user for search results

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1909]
Currently, OpenAnnotate keeps track of load times through the various high level portions of code loading the document and displays that information to the user:

![image](https://user-images.githubusercontent.com/1377228/59934170-8e578a00-9410-11e9-88d6-cc6be47d598b.png)

It would be nice to do this same thing for Search Results (in search as well as VAD).  We'd have to come up with how to break down the load time.  Some thoughts:

- Request (network)
- Query Time (OC)
- Query Results Processing (OC)
- Response (network)
- Browser JS time to display first page of results (OCMS)

Before starting this effort, we should finalize the above list as well as discuss other information to display (ex: total results).

Note that the OA data is stored in the Elastic Stack as well for later reporting.  We should do that here as well.

**Comment by gsteimer** [comment]
Before starting, talk to @m-brouillette about splitting out some of this code in OA to TsgUtils

**Comment by gsteimer** [comment]
This is currently in trunk, with minor updates upcoming from @grahamsinger

**Comment by grahamsinger** [comment]
Updates in with r24400 and r24402(unit tests)
