### ISSUE TITLE
Filter Service should not include groups when filtering for users

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1914]
When loading the dashboard, the various OCOs are run through the filter service to get pretty names for users (non-Dctm environments).

This causes a bunch of requests like this when the dashboard loads:

`http://release2.tsgrp.com/alfresco/OpenContent/users/user/dhartman/?failQuietly=true&includeGroups=true`

There are two problems with this:

1. There's no reason to include groups.  This just slows down the request
2. These requests are graying out the screen, causing the dashboard to be unclickable while the requests are running, and flashing the screen multiple times based on the timing of when all the requests start and stop.

Currently the entire OCO is run through the filter service, whether or not the attributes are displayed.  A future enhancement could be to only fire these requests when first needed to display the user name on the screen.

**Comment by nquillin91** [comment]
Followup issue is [https://github.com/tsgrp/HPI/issues/1952](https://github.com/tsgrp/HPI/issues/1952)

Include groups fix in OCMS REV: 23438
