### ISSUE TITLE
Cascading picklists no longer load properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1918]
Cascading picklists are no longer loading properly.  The values are correctly being returned by OC.  For example:

![image](https://user-images.githubusercontent.com/1377228/60619361-22750a00-9d9e-11e9-9f1d-cb4b86833dbf.png)

OC returns correct values:
![image](https://user-images.githubusercontent.com/1377228/60619387-31f45300-9d9e-11e9-8ed8-40106717b151.png)

Other cascading queries also return correct values:

![image](https://user-images.githubusercontent.com/1377228/60619421-45072300-9d9e-11e9-9bda-cbe4d9ae2899.png)

![image](https://user-images.githubusercontent.com/1377228/60619437-4c2e3100-9d9e-11e9-9a41-c1c64247588d.png)

**Comment by nquillin91** [comment]
Fixed with OCMS REV: 23179
