### ISSUE TITLE
No Search Parameters Alert Doesn't Show When Quick Search Is Disabled

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1919]
Normally when you click the search button and there are no parameters an alert temporarily pops up to let the user know that they need to enter a search parameter; however, this is not currently working when quick search is disabled because the html element that is used to display the alert is only in the quicksearch template.

In the below screencam you can see that the healthcare trac is an example of where this functionality is failing.

![missingSearchAlert](https://user-images.githubusercontent.com/13734523/60905185-2390b600-a23a-11e9-8d19-d093a6c9394d.gif)

**Comment by egrahamtsg** [comment]
Resolved with revision #23225: moved the search alert div and added a scroll up so the alert is visible both when quick search is disabled, and when the user is at the bottom of the page.
