### ISSUE TITLE
Stage Launch Doc in New Tab Icon has Hardcoded /hpi

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1927]
After the change from `/hpi` to `/ocms` it looks like the icon that launches a document in a new tab has the app name hardcoded.  For example, on edge2 clicking:

![image](https://user-images.githubusercontent.com/1377228/62083593-ead27400-b21c-11e9-9019-2328ebb7af26.png)

Launches this URL: `https://edge2.tsgrp.com/hpi/DocViewer/insuranceClaim/IMG_9078.JPG?id=...`

Which 404's.  Changing `/hpi` to `/ocms` fixes the link.

**Comment by renesaladrigas** [comment]
APP: The value for the docviewer url was hard coded to use "/hpi", now it's using the value for module.config().root or "/" as a fallback.

CR - gsinger, nquillin
Fixed with hpi rev: 23354
