### ISSUE TITLE
Adding Non-Mandatory Aspect to Type adds blank item when using typeahead

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1929]
See the screencam below.  When adding a non-mandatory aspect to a type on both edge2 and release2, often the item that is added is blank:

![add-nmaspect-fail](https://user-images.githubusercontent.com/1377228/62941658-313add80-bd9c-11e9-8f23-ba39036b4b84.gif)

There are no errors in the console when this happens.  I'm guessing this is a timing issue, because one out of 10 times (after hard refreshing each time), it will work.

**Comment by gsteimer** [comment]
Update:  it's not a timing issue.  If you select the non-mandatory aspect using the dropdown arrow it's fine.  But, if you use the typeahead, it fails.  See below:

![add-nmaspect-fails](https://user-images.githubusercontent.com/1377228/62969212-66fab900-bdd2-11e9-9d57-ae4b6bab0747.gif)

**Comment by grahamsinger** [comment]
(Reserving for debugging class)

**Comment by astocks7** [comment]
OBJECT TYPE - adding a non-mandatory aspect to an object type via the typeahead wasn't working. Moved the typeahead listening logic from initialization to beforeRender so the options in the typeahead are correctly updated.
OCMS revision #23720
CR: gsinger, dvora
