### ISSUE TITLE
Document type icons appear at full resolution in the View Renditions modal action

### ISSUE THREAD

**Issue by Swence32** [tsgrp/HPI#1932]
In Stage, when viewing a document that has renditions, clicking the View Renditions action opens the View Renditions modal. The document type icons in the modal appear at their full resolution, causing the user to have to scroll down to view links to any other rendition. 

The icons should be reduced to a more reasonable size.

![View Renditions](https://user-images.githubusercontent.com/5685648/63359754-e5a3a900-c332-11e9-854d-88077fa6fbc5.gif)

**Comment by ebrent** [comment]
VIEW RENDITION mimetypes showed full size. Fixed with class in html and added css in hpi.syl for sizing purposes. 

Revision 23450 ocms 

CR: rsaladrigas
