### ISSUE TITLE
Search - TSGUtils.sterilizeFilename fails when searching on Controlled Docs Folder

### ISSUE THREAD

**Issue by Swence32** [tsgrp/HPI#1933]
In Search, choose the Controlled Docs trac and Folder type. Enter search criteria and click search. The following error appears in the browser console: `Cannot read property 'replace' of undefined at Object.TSGUtils.sterilizeFilename`, preventing any search results from returning See gif below:

![Serialize Error](https://user-images.githubusercontent.com/5685648/63376297-17c50300-c353-11e9-8b9a-435c3ae161f1.gif)

Note: Error does not occur when searching on Claims trac and Folder type, for example, so may be caused by configuration.

**Comment by dgrumieaux** [comment]
From the OCMS meeting: Can we fix this by making the code just a bit more tolerant?

**Comment by joehof** [comment]
In my opinion, this code shouldn't trigger at all during a search - it only makes sense to sterilize the filename when we are adding content to the system, not searching for it.

**Comment by aviking** [comment]
Fixed with Commits:
  - OCMS: 23576
  - TSGUtils: 4fe59adac296d8b6f0521d5fb0981b329daa0744

CR's: @nquillin91 @joehof
