### ISSUE TITLE
Bulk Upload Positional Data Save doesn't work with Multiple Documents

### ISSUE THREAD

**Issue by CRdouglas** [tsgrp/HPI#1934]
When uploading multiple documents in bulk upload, the positional attributes being saved on the oco are not saved correctly to the individual document. It appears that the positional metadata is being saved to the bulk properties and not being set on each individual document.

**Comment by abrown45** [comment]
It appears these two lines in externalEventsModule populate the form data and triggers the oco to pull in the positional data currently set on the properties. This trigger does not work as it seems it was intended in the bulk scenario. 

`this.$("#" + this.inputBoxID).val(childAppModel.selectedText);`
`this.$("#" + this.inputBoxID).trigger('keydown');`

**Comment by abrown45** [comment]
The view passed into the function is the correct view unlike previously thought. The problem is how the oco is being set.

**Comment by abrown45** [comment]
Within `forsupport.html` lines 15 and 25 seem to be the knockout bindings triggered from the keydown event in `externalEventsModule.js`

`<input class="form-control input-sm" type='text' data-bind="value: value, attr: {'id': id, 'name' : id }, enable: !readOnly() && enableDependencyValid(), valueUpdate: 'afterkeydown' " />`

`<input class="form-control input-sm" type='text' data-bind="value: forceNullObservable(repeatingPlaceholder), attr: {'id': id, 'name' : id }, enable: !readOnly() && enableDependencyValid(), event: { blur: addValueOnBlur, keypress: checkForEnter }" />`

**Comment by abrown45** [comment]
Within `bulkupload.js`, `this.options.bulkproperties` has been updated prior to calling `_saveCurrentOcoProperties()` to contain `hpi_metadataPositions` and that bulkproperties update is reflected on the oco only in the single upload scenario.

I think the best solution at this point is to call setValues() within `externalEventsModule.js` with the `hpi_metadataPositions` to properly update the viewPropertiesModel. Then updating `getValues()` to return `hpi_metadataPositions` even if a control is not configured for that attribute as long as it is configured to contain  `hpi_metadataPositions`

**Comment by abrown45** [comment]
Code changes can be found in this svn branch, CRs and unit tests are still needed. Need to confirm if the key for hpi_metadataPositions is really something we want configured or to be just a constant from HPIConstants.

`http://svn.tsgrp.com/repos/hpi/branches/bulk-upload-issue-1934/code`

**Comment by cheinz-tsg** [comment]
Closed with OCMS commit 24319
