### ISSUE TITLE
Search - Results Table and Search Controls "jumping" after scrolling

### ISSUE THREAD

**Issue by Swence32** [tsgrp/HPI#1937]
Steps to reproduce:

- Login to Edge2 and click Search in action header bar
- Switch to Claims Trac and Claim doc type
- Set max search results to 50
- Enter '*' for Claim Number and Search
- Ensure the search results overflow the bottom of the page and cause the scroll bar to appear (if results don't overflow bottom of the screen, resize your screen so they do)
- Scroll down once to see the results table jump once
- Continue to scroll down until you begin to see the search controls begin jumping repeatedly.

Was reproduced on Controlled Docs Trac as well.

![](https://user-images.githubusercontent.com/5685648/63467179-77421200-c42a-11e9-9f74-4a6249e01c9b.gif)

**Comment by gsteimer** [comment]
@ebrent - could this be something to do with the mobile updates that went in recently?

**Comment by astocks7** [comment]
SEARCH RESULT BUG FIX - fixed and wrote unit tests for the function that contained the bug. The else branch in the atTop function in searchresultscontroller.js had a fadeIn animation set on a hidden object causing the jumping issue. Switching this to fadeOut solved the issue.
OCMS revision #23700
CR: dvora, rsaladrigas
