### ISSUE TITLE
Login page no longer displays OCMS version

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1943]
It looks like something has changed on the login page, the OCMS version is no longer displaying in the bottom right corner:

Edge2:
![image](https://user-images.githubusercontent.com/1377228/64798289-6166cf00-d548-11e9-928e-458ef5fdac59.png)

Release2:
![image](https://user-images.githubusercontent.com/1377228/64798355-7a6f8000-d548-11e9-96af-a0ca51eaf7db.png)

It looks like the version number is making it's way into the login template on edge however, since I do see this:

```html
<!--
  OCMS Version: 3.2.0.23613
  SVN URL: http://svn.tsgrp.com/repos/hpi/trunk/code
-->
```

**Comment by ktrinh-tsgrp** [comment]
Fixed in revision 23635
