### ISSUE TITLE
AW Manage Ad Hoc Documents Action - Outstanding Items

### ISSUE THREAD

**Issue by nreiman** [tsgrp/HPI#1946]
The "Manage Ad Hoc Documents" action was recently added to trunk OCMS Wizard, but still has a few outstanding items...

- Alfresco Support - Right now, the action has only been tested for DCTM.

     - [x] Add the "is ad hoc" attribute for supporting documents the awModel.xml and setup the OC name cheater value in `alfrescoEmb-bean-config.xml`
     - [x] Add manageAdHocDocumentsConfig to the hpi-demo-alf (or your project's) config-project.js

- [x] Once ad hoc documents are added to the repo, they aren't showing up in the "Supporting Documents" area under "Related Objects" without a refresh.

- [x] Add a deferred array for each of the newly added items. Once the last item in the array is 
        done being uploaded, call "app.trigger("stage.refresh.bothIds", app.context.container.id, 
        app.context.document.id);"

- [x] Error handling and testing for adding and removing ad hoc documents.

- [x] When clicking on the "Existing Ad Hoc Documents" tab, the "None" pill flashes before loading the existing ad hoc documents table.

- [x] Unit tests for the action.

**Comment by ebrent** [comment]
Error handling and testing for adding and removing ad hoc documents is not an issue - all cases are covered for an error message when adding, removing, existing, etc. Refreshing stage when document added was fixed in revision #23942. 

CR: nwoodbine, skovancinski

Commenting on this issue but not closing it, unit tests still not added and not tested for alfresco.

**Comment by ebrent** [comment]
MANAGE AD HOC DOCUMENTS - adding a spec file to skeleton the manageadhocdocuments.js file. Completed initialize and serialize with spys on other functions. If enough budget, these will be completed eventually. 

CR: skovancinski, dvora

OCMS revision #24080

**Comment by mwojno-tsg** [comment]
MANAGE AD HOC DOCUMENT BASELINE TESTS: this commit adds a few more tests to the manage ad hoc document spec file. 

CR: skovancinski, rsaladrigas

Not closing issue because it still hasn't been tested for alfresco yet.

**Comment by mwojno-tsg** [comment]
Finally resolved this enhancement by completing the first two checkboxes, which were to get this working on Alfresco. **OCMS commit #25210** gets it working and testing on alfresco. Added to `ocms-paas, pnp, and hpi-demo-alf's config-project.js`
