### ISSUE TITLE
Wizard Inbox Issues post Pagination Sorting and Filtering

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1949]
A few issues with the AW inbox I've noticed after the pagination, sorting and filtering functionality was added recently:

![image](https://user-images.githubusercontent.com/1377228/65352561-8abed500-dbb0-11e9-910c-5bc4a81038f7.png)

- [x] Not sure why, but the show docs button used to be a link.  I think we should change it back since the button takes up too much padding / height on the row
- [x] Clicking this button on edge1 (Documentum) returns the list of docs, but only shows the object ID (see below)
- [x] On edge2 (Alfresco), the ajax call fails (see below)

**Edge1**
![image](https://user-images.githubusercontent.com/1377228/65352671-d5405180-dbb0-11e9-9928-916082f7f986.png)

**Edge2 Error**
```
ocms-require.min-be261f481aabc0e348bcb3df1b23bf5d.js:4843 Uncaught Error: Syntax error, unrecognized expression: #workspace://SpacesStore/1f3829c7-9bd9-4ad8-a76c-3d949d857af7
    at Function.Sizzle.error (ocms-require.min-be261f481aabc0e348bcb3df1b23bf5d.js:4843)
    at tokenize (ocms-require.min-be261f481aabc0e348bcb3df1b23bf5d.js:5498)
```

![image](https://user-images.githubusercontent.com/1377228/65352751-002aa580-dbb1-11e9-94d9-8dc1eba5a955.png)

**Comment by nreiman** [comment]
OCMS Revision: 23697
CR: acastor, nwoodbine
