### ISSUE TITLE
When Document Viewer loads, it is cutoff in Stage

### ISSUE THREAD

**Issue by kgarelli** [tsgrp/HPI#1950]
Likely a race condition. When OA viewer is being loaded into stage it is extremely small. Happening consistently and refreshing the page is not helping. Using Chrome currently. 

![image (1)](https://user-images.githubusercontent.com/6698400/65433918-88908c80-dde3-11e9-91f0-a978af5e679f.png)

**Comment by gsteimer** [comment]
@kgarelli - looks like you have a lot of folder actions configured, or at least more than usual.  It also looks like you have no document actions.  Could either of those be related?  I sometimes see this on release/edge, but very rarely.

**Comment by kgarelli** [comment]
@gsteimer I can try removing some folder actions and see if I still see it. I believe it actually has to do with the fact that there are no doc actions configured. Looks like it only happens when there are no actions configured. I'm thinking it is probably because we don't call the throttled resizeHeader function if there are no actions.

**Comment by kgarelli** [comment]
The docviewer was cutoff in stage when no actions were configured or if actions errored while loading. When actions are configured we would end up calling setDocnameNewLine or setDocnameSameLine both of which set the height of the docviewer row. We added that same line to set the height of the docviewer in the afterRender so it will still get called when no actions are available. 

OCMS commit: 23766
