### ISSUE TITLE
Skip Activity - Outstanding Items

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1954]
The following items should be cleaned up to say that the Skip Activity enhancement is complete:

For reference, the UI for the action currently is:

![image](https://user-images.githubusercontent.com/1377228/65908430-0cbab500-e38c-11e9-9cd6-bc3f8c6bfc97.png)

- [x] When configuring the action, the default label should be `Skip Task`.
  - It's currently "Skip Activity".  The screenshot above shows "Skip Task" from edge1 because I changed it manually.
- [x] For the "ok" button, let's change the text to simply "Confirm Skip"
- [x] "Users to review form" should be a label like in the workflow status action (see below) and should say "Users to Skip"
- [x] Entering the correct username and incorrect password causes the action to fail in javascript rather than displaying a message to the user and allowing them to try again.  See the complete task action for an example of how this should work.
- [x] Entering an incorrect user and correct password does nothing.  The action just spins forever, no output to the console.
- [x] The list of users needs to be cleaned up:
  - At a minimum, we should be showing the user display name, not the user id.  Many clients have user ids like `u324234`.
  - It would be much nicer to show the name and role of the user in a table, much like the workflow status action.  See an example below.
- [x] The audit that's being added to the wizard audit trail is incorrect.  In my example, Conan is the CR Approver skipping the Initial QA role.  The audit says that Conan approved as Initial QA.  Instead it should say that Conan Skipped the Initial QA Role.
- [x] After skipping a user's task, when viewing the Wizard Workflow status action, the action shows the skipped user as `Approved`.  Can we change that to `Skipped`?

Here's how the workflow status action shows users and roles.  Can we do something like this?  We'd just need columns for the user and role.

![image](https://user-images.githubusercontent.com/1377228/65908781-c87be480-e38c-11e9-8e3a-fb67b1f924cb.png)

Audit Trail incorrect entry:

![image](https://user-images.githubusercontent.com/1377228/65909783-ef3b1a80-e38e-11e9-8190-591fe6536447.png)

Post skip - View Wizard Workflow Status action - qdadmin2's task was skipped:

![image](https://user-images.githubusercontent.com/1377228/65911097-aafd4980-e391-11e9-8d82-1e82f7ee68a6.png)

**Comment by mwojno-tsg** [comment]
AW WIZARD SKIP TASK ACTION: this is an update to the WIZARD SKIP ACTION commit (23718), which gives the current logged in user the ability to skip over and approve on behalf of another user in a role that is blocking. UI/UX changes were made on OCMS to show the Users to Skip in a nice table. Issues were fixed with the login capability. Finally, the approval detail Signature event was modified to include a status of Skipped and correctly displayed in the audit events as well as workflow status. Fixed in revision OCMS 23784.

Needs OC rev: 23367

CR: nquillin, dgrumieaux
