### ISSUE TITLE
View Properties Display Index Location - scrolls document improperly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1956]
See the screencam below.  When clicking on a metadata location target button in view properties, the document should scroll vertically in the case of the property being on an off-screen page.  However, it looks like the document is incorrectly scrolling horizontally when it doesn't need to.  See below:

![metadata-location-scroll](https://user-images.githubusercontent.com/1377228/66074827-b9796b80-e51f-11e9-90f8-504c9ee8b99a.gif)

When fixing this, make sure that scrolling to a second page still works properly.

**Comment by gsteimer** [comment]
Per @renesaladrigas - this may be fixed in the first commit for Capture 2.0 admin

**Comment by cheinz-tsg** [comment]
This was fixed in the capture template admin OA branch, revision #6142. The fix was merged into OA trunk in revision #6206.
