### ISSUE TITLE
Indexer not working properly with clicked values and repeating attributes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1957]
In the indexer (and potentially Bulk Upload), if you're using the click or highlight to select functionality to pull values from the document over to attributes, it does not work properly when the attribute is repeating.  See the screen cam below:

![indexer-repeating-attr](https://user-images.githubusercontent.com/1377228/66082990-f9951a00-e530-11e9-90af-e876b54daf51.gif)

Ideally, after selecting the value in a repeating field, it would simply add it to the list of selected values rather than just populating the textbox.  In other words, the user shouldn't have to select `Add`.

**Comment by sambelcher1** [comment]
INDEXER REPEATING ATTRIBUTES: Fixed an issue in indexer where using the text select or highlight on repeating attributes would not actually add it to the list of attributes, it just populated the textbox and moved to the next control. Now it keeps focus on that control, and adds it to the list of attributes so you can immediately select a new one

REV: 24378

CR: nquillin, rsaladrigas
