### ISSUE TITLE
Optimus Support for OpenOverlay Overlays

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1968]
Currently Optimus (OAT) does not support any flavor of OpenOverlay. This was a conscious decision to increase performance so as to not have to read the entire PDF into memory and manipulate each page each time the document is being viewed with "view time" overlays. 

Upon Client Request for someone that has a high volume of views AND wants to leverage Optimus for transformations, we would need to enhance Optimus to pass each document through OpenOverlay with the view time transformations.

Tough things to consider:

1) Optimus currently doesn't have access to any of the properties, so this would need to be added
1) Optimus makes heavy use of caching of the PDF, so we would have to make sure that we disable that caching to allow for "view time" overlays to properly reflect the current state of the document.

**Comment by benallenallen** [comment]
@abrown45 - please update this issue, I believe you have commit all updates needed to close this

**Comment by abrown45** [comment]
Finished with two commits. Updates to OAT to accept overlay properties and pass them to OpenOverlay and apply before caching the document. AEV was updated to build up the required overlay properties and pass them on transform and getThumbnail requests.
AEV Commit 6722 and 6723
OAT Commit 1c8afe3b2e61a6a546bbd9845b4cd25cd6ab408f
