### ISSUE TITLE
Submitting View Properties creates a ghost document in VAD

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#1981]
Somehow when clicking on the Submit button in View Properties, there's a document being added to the table of VAD. It's not an object in the repository as it goes away when you refresh the result set.

![viewPropsGhostObject](https://user-images.githubusercontent.com/14186921/68046606-442dc180-fcaa-11e9-8922-9ae5432ff41d.gif)

**Comment by Kovacinski** [comment]
@gsteimer @renesaladrigas . Looks like this issue  was introduced in revision 22557 when we added a listener in tableview for "action:object-modified". This code does not verify if the object-modified was the current folder and will then add the oco onto the collection and re-render the tableview.

**Comment by abrown45** [comment]
Fixed in ocms commit 24104
