### ISSUE TITLE
Email template token replacement does not handle dates properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1983]
The new functionality that was recently added which replaces tokens in email templates is not correctly formatting dates.  See an example screenshot below:

![image](https://user-images.githubusercontent.com/1377228/68225192-ab52bb00-ffb5-11e9-8732-5455a1f99341.png)

Before replacing a date token, we should run it through the formatter, making sure it matches the date format configured in Application Config.

**Comment by abrown45** [comment]
> Another issue I found with testing the above that would be low hanging fruit while we're in here - if a token is included, but the property isn't set, the code simply includes the token. I'd think we'd just skip over that token and display nothing vs. showing the token. For example, if department is not set:
> 
> ![image](https://user-images.githubusercontent.com/1377228/68226260-616ad480-ffb7-11e9-8f1a-1b1852880233.png)

Skipping this for now, waiting for a client to decide which style they prefer for incorrectly configured tokens, leaving them in the template for the user to see or removing them.

**Comment by abrown45** [comment]
Fixed in ocms commit 24103
