### ISSUE TITLE
Email Templates Do Not Handle Special Characters Well

### ISSUE THREAD

**Issue by RudraVishweshwar** [tsgrp/HPI#1985]
When using the email templates in OCMS. If your template has special characters like bullet points or non UTF-8 charachters. When you view the template in the CKEditor it appears wonky. See GIF below. 
![templateIssue](https://user-images.githubusercontent.com/14186904/68311410-2039f980-0077-11ea-96e2-6462e1fef7ee.gif)

**Comment by abrown45** [comment]
Fixed in oc commit 23767
