### ISSUE TITLE
Saved Search Dashlet - Pagination & Search Result Length Issue When User Has 10-20 Forms

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#1993]
Overview
- The issue that is occurring happens when a user has between 10-20 form the pagination and search result length seems to be broken. On the first reload of the page, it can be seen below that there is only 1 form displayed when the user has 11 forms in total. 

![SavedSearchDashletPaginationIssues](https://user-images.githubusercontent.com/54864662/68622065-dc8c2900-0496-11ea-90dd-d01645ec1269.gif)

- However, when clicking on the 25 and then the 10 results, it correctly displays the number of forms (11 in the 25 filter case and 10 in the 10 filter case). 

- This is contrasted when a user has more than 20 forms, then the functionality of the saved search dashlet works perfectly. 

![SavedSearchDashletPaginationNonIssue](https://user-images.githubusercontent.com/54864662/68622144-0e9d8b00-0497-11ea-8be2-8ead24940f91.gif)

Location of Issue
- I was able to trace the issue (thus far) to line 301 of the savedsearchdashlet.js where self.render() is called. 

- At this moment, self.collection will have all of the forms the user has. It is during this self.render() that the collection is someone truncated down (not to the default which should be 10) and then ends up in the beforeRender() function. 

- The collection in the beforeRender() has the wrong amount and thus sets the view to the wrong amount of forms to display. 

- New Insight Into Issue: It appears that only the second page is displayed on the first reload. So, if the case of the first user with 11 forms they are only seeing 1 form. This is because that is what they would see on the second page if it was working correctly.

**Comment by dhruvvora94** [comment]
Closed with OC commit #23874
