### ISSUE TITLE
CKEditor Error handling in Wizard

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1994]
There is an error with WYSIWYG inputs due to an uncaught exception that was thrown in an effort to clean up linting issues.

**Comment by grahamsinger** [comment]
Fixed with OCMS rev24149.

**Comment by gsteimer** [comment]
@grahamsinger - looks like this is broken again

**Comment by nquillin91** [comment]
Fixed with OCMS rev: 24276
