### ISSUE TITLE
Create Form from Folder does not autopopulate answers

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1997]
In the "letters" functioanlity, when launching a form from a folder, the application should pass over folder metadata to automatically populate questions with data.

Currently, this mapping is done in the OCMS `config-project`.  On edge and release2, we have the following config

```
    "modules/wizard/activeformrouter": {
    	folderPropertyToQuestionLabelMap: {
    		"Master Services Agreement": {
	            "tsg_contractVendorName": "Contractor",
	            "con_vendorStreet": "Street",
	            "con_vendorCity": "City",
	            "con_vendorState": "State",
	            "con_vendorZip": "Zip Code",
	            "con_vendorContactName": "What is the name of the Contractor Contact?",
	            "con_vendorContactPhoneNumber": "Phone Number",
	            "con_vendorContactEmail": "Email Address"
        	},
        	"Claimant Contact Letter": {
        		"insuranceDemo_claimantName": "Claimant Full Name",
        		"insuranceDemo_claimNumber": "Claim Number",
        		"insuranceDemo_lossDate": "Date of Injury"
        	}
    	}
    },
```

However, when I create a MSA or CCL form, the form is completely blank.  I know that @nquillin91 and @kpelozatsgrp recently change functionality around auto-populating questions.  Could those changes have borked this?

**Comment by nquillin91** [comment]
Fixed with OCMS rev: 24265
