### ISSUE TITLE
Folder Notes Are Not Created When Updating Properties From View Properties

### ISSUE THREAD

**Issue by engerernoah** [tsgrp/HPI#2002]
If "Integrate with Folder Notes" is turned on in the View Properties configuration folder notes are supposed to be created each time an update is made through View Properties. Currently notes are not being created when this occurs and there is an error in the tomcat logs. 

![foldNotesOn](https://user-images.githubusercontent.com/39744036/68970417-d1920b00-07ac-11ea-90c2-123dc622c816.PNG)

Issue in OCMS: 
![ViewPropsFolderNotesBad](https://user-images.githubusercontent.com/39744036/68971584-731a5c00-07af-11ea-894c-6478cc264668.gif)

Expected Performance: 
![ViewPropsFolderNotesGood](https://user-images.githubusercontent.com/39744036/68971690-b70d6100-07af-11ea-8b9a-cf8b50b223c6.gif)

The issue appears to be that the parameters passed to the FolderNotes.Service in View Properties do not match the parameters OC expects. To fix this issue the properties passed to the Service should be updated to match the properties expected in OC.

**Comment by gsteimer** [comment]
@engerernoah - is this the same root issue as #2000 ?

**Comment by engerernoah** [comment]
Something I found when solving issue #2000 unrelated to the contentless mode updates but view properties was not passing the correct property names to the backend

**Comment by engerernoah** [comment]
VIEW PROPERTIES FOLDER NOTES ISSUE - View properties uses FolderNotes Service to create folder notes when properties are updated. The parameters that were being passed to the FolderNotes Service did not match the parameters expected in OC which created an error and stopped notes from being created. This update ensures the parameters being passed match the expected values on the backend. Updated and cleaned up unit tests for view properties.

Revision: #24288

CR: nqillin, skovacinski
