### ISSUE TITLE
Wizard question validation not displaying properly when using non-repeating groups

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2003]
Question validation does not seem to be working in the expected manner when questions are grouped on a single page. 

It seems that validation is working properly, but the text that should appear below the question is not appearing when the question is grouped.

Zip format check for normal question:

![image](https://user-images.githubusercontent.com/1377228/69094220-95adae80-0a15-11ea-9cf5-20cfb0babfcb.png)

Repeating group showing no validation text (after I had focused on the fields and lost focus) and entered an invalid zip code:

![image](https://user-images.githubusercontent.com/1377228/69094291-b6760400-0a15-11ea-96f2-612878f1d12a.png)

From looking at it, it seems like the validation is actually working (note that in the above screenshot, the page still knows the Zip field is invalid), it's just not displaying the message to the user properly when the question is part of a non-repeating group

**Comment by jlittle-tsg** [comment]
NON-REPEATING GROUPS BUG - Fixing issue https://github.com/tsgrp/HPI/issues/2003 - needed to add in a span for the validation message to appear in nonrepeatingquestion.html. 

CR: dvora, gsigner
Revision Number: 24541
