### ISSUE TITLE
Send Notification Config - Changing default value does not load properly the next time in

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2005]
When setting the email subject, the default value loads properly:

![image](https://user-images.githubusercontent.com/1377228/69257731-25bc3700-0b81-11ea-9c92-516a9e1ba15b.png)

If the admin changes the value to something else and saves, the correct new value is used when sending a notification.  However, when the action is loaded again in the admin, the default value remains in the textbox.

When looking at this issue, we should also verify that updates to the other items are saved and re-loaded properly as well.

**Comment by jlittle-tsg** [comment]
SEND NOTIFICATION BUG FIX -  Fixing issue 2005 that caused default values to persist when the config was saved. Also moved sendnotification view into it's own config folder.

See: https://github.com/tsgrp/HPI/issues/2005

CR: rsaladrigas, skovacinski
