### ISSUE TITLE
Create View Audit Does Not Work From View All Documents

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/HPI#2010]
In the stage DocViewer config, there is an option to create audit event every time an asset is loaded into the DocViewer. Currently, viewing a document from the View All Documents folder action in Stage does not create a view audit - this is because the logic for this is in router.js so it will only work when the docviewer route is hit.

![image](https://user-images.githubusercontent.com/4128978/70471973-e1db9400-1a93-11ea-8d08-aaca0deddce8.png)

Take a look at ocms commit 21648. ktrihn was fixing duplicate audit entries by taking the create audit event logic out of docviewer and foldertree, adding it to router.js. Initial thought is it should be taken out of router.js, keep it out of foldertree, and added back to docviewer.

**Comment by gsteimer** [comment]
Should the audit happen in Doc Viewer as well as the View route only instead?

**Comment by benallenallen** [comment]
The project that we thought was using this is actually not auditing every document view, so this won't be actively worked on until a different project requests it.

**Comment by grahamsinger** [comment]
Fixed with rev 24525 to OCMS.
