### ISSUE TITLE
Stage immediately refreshes after a full pane folder action executes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2011]
See the screencam below.  After running Bulk Upload, Send Email (or any other full pane folder action) the stage immediately refreshes unexpectedly, hiding the success message view.

![stage-add-docs](https://user-images.githubusercontent.com/1377228/70539298-1baaaa00-1b29-11ea-8efb-15e479c99831.gif)

![stage-send-email](https://user-images.githubusercontent.com/1377228/70540932-b6a48380-1b2b-11ea-90ec-12732264a9a2.gif)

**Comment by Kovacinski** [comment]
Fixed with revision 24375
