### ISSUE TITLE
Signature Page Cannot Be Regenerated After Final Approval For Alfresco

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#2014]
Overview
- The signature page cannot be regenerated for alfresco due to a communication issue between the CompleteUserTaskListener and the WizardApprovalWorkflowSuccessServiceTask. This leads to the version label not being able to be updated to the form's version label. 

![2019-12-10 14_05_51-OpenContent Management Suite](https://user-images.githubusercontent.com/54864662/70564684-4101dd00-1b56-11ea-8abc-87dfa4c87388.png)

Steps to recreate
- Route a form for approval with however many approvers you would like to have. You will notice on the final user's approval the signature page can be updated due to a temporary flag switch we implemented, but doesn't update the version label to the form's version label.

Ideas about fix
- This issue is related to: #1617 , #1967 , and #2013 . There is a larger problem going on here between wizard listeners that aren't able to communicate the most up to date approval details. This then leads to numerous issues when tasks are trying to be done according to those approval details.

**Comment by gsteimer** [comment]
Changing this to enhancement since this is new functionality that was built for a Documentum client.  Potential workarounds for Alfresco include:

- Leave the current behavior of marking the actual version being signed on the signature page
- Modify the signature page template to not display the version label

**Comment by mwojno-tsg** [comment]
A temporary fix was put in place in OC commit #25224. The approval details were "fixed" before being passed to the send email. Fixed in the sense that the last signature was changed from "pending" to either "approved" or "rejected" based on what listener it went into/called from. Therefore, it has the correct signatures on the signature page, however, version label was removed in the alfresco environment. The real issue at hand is a much bigger effort as approval details are successfully passed between wizard workflow listeners. See #2107

**Comment by cheinz-tsg** [comment]
Closed with OC Commit #25615. The root cause of this bug is issue #2107, which was fixed in OC Commit #25614. The next commit removed the temporary fix (eSignature template without a version label) from OC Commit #25224.

**Comment by gsteimer** [comment]
Looks like this is working for the form:

![image](https://user-images.githubusercontent.com/1377228/87601758-58d8ab00-c6bb-11ea-9155-ab14de85d508.png)

But the Document still lists the minor version:

![image](https://user-images.githubusercontent.com/1377228/87601788-6726c700-c6bb-11ea-8a35-cebad742c5f5.png)

**Comment by mwojno-tsg** [comment]
## Temporary Fix
- A temporary fix was commit to trunk with OC revision 25650. The temp fix just removes the version label property from the signature .ftl for the time being until the greater issue can be fixed. 

## Discovery for Actual Fix
- What I found while digging more into the root cause of the issue was that there could be alfresco transaction issues again within the listeners of the approval workflow. 

- In the file `WizardApprovalWorkflowSuccessServiceTask`, it will cycle through the workflow documents and promote them. This should then kick off the `onAddAspect` behavior to `onApproval` promote the document, which essentially changes the status and version label attributes.

- However, what I saw while debugging was that the `onAddAspect` behavior was not being hit until after the signature .ftl was being generated. Therefore, the .ftl was using the stale version label not the new major version. 

- Weirdly enough when the form does the exact same thing with its `onAddAspect` behavior, its version label and status properties are correctly updated right away. That is why in the above screenshots you can see the Form's version label is correct in the .ftl. 

- To resolve this we will need to find exactly why the transaction order is screwed up and possibly how to get the document properties to successfully update before generating the e signature page .ftl.

- There are some hacky ways to solve this like passing what that major version needs to be or checking that when we are applying the properties to the signature page, but at this time a good solution hasn't been produced.

**Comment by mwojno-tsg** [comment]
Issue resolved with OC commit: 25947. 

A property variable was created to be a flag on whether we should append the signature pages in the success service task or let the form behavior (in alfresco's case) "onApproval" handle it. Below is the assumed order of transactions now for alfresco: 

1. success service task - approval workflow completes
2. quality doc lifecycle on approval - due to transaction commit behavior this will run next to promote workflow documents
3. form lifecycle on approval - due to transaction commit behavior this will run after (as it is called after ^) to promote form, THEN will append signature pages within the onApproval

CR: gsinger, nwoodbine
