### ISSUE TITLE
Signature Page incorrectly listing user ID twice

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2016]
See the screenshot below.  The signature page is incorrectly displaying user's ID twice:

![image](https://user-images.githubusercontent.com/1377228/70639674-6b0fd980-1c00-11ea-9d45-2e85b5767643.png)

I verified that this is not happening on release, which was rebuilt a couple weeks ago.

**Comment by mwojno-tsg** [comment]
This issue was fixed in at OC revision: 24117. I forgot that the signature event's function "getUserDisplayName()" already formats the display name with the parenthesis. Therefore, I had this trying to format the user id into the parenthesis twice.
