### ISSUE TITLE
Search Results Timing - Provide Reset Defaults Option

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2017]
Currently, in OCMS admin, you can tweak the time ranges from the defaults, however once you make any updates, there's no way to reset the ranges to the default values.  

![image](https://user-images.githubusercontent.com/1377228/70810240-06cc5180-1d89-11ea-8e74-313fdffdbf82.png)

Given that this is a new feature that will likely see some tweaks to the default ranges as we start using the feature at client sites, it would be nice to have a "reset to defaults" button that automatically resets all the ranges.  This would be useful for clients with many tracs (or for me, who would need to make updates manually across all tracs on edge and release).

**Comment by grahamsinger** [comment]
Implemented with rev 24524 to OCMS.
