### ISSUE TITLE
Reporting Dashlet Issues/Enhancements

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#2018]
There are several minor open issues with the reporting dashlet:

- [x] For a particular bar/point/section, the dashlet only displays results up to 25 

- [x] The reports are displayed in UTC, but search uses the browser's time zone, causing potential for different results seen when navigating between the graph and search

- [x] Double bars appearing in graph, when loading up report

- [ ] No results returning gives error and doesn't show an empty graph

- [ ] Special characters can break the "click to search" function (ie, a query value that includes an ampersand)

- [ ] Bar graph labels do not line up with bars. Screenshot attached in comment below.

**Comment by jackjbridge** [comment]
Fixing the first 3 issues with commit below

REPORTING DASHLET FIXES: Merging fixes from client branch for reporting issues with results only displaying up to 25 items, using the browsers time zone, and double bar graphs appearing. Cleaning up linting errors and adding unit tests for reporting as well.

SVN: 24484

CR: dgrumieaux, nwoodbine

**Comment by jackjbridge** [comment]
For the no results issue/enhancement to be made

![image](https://user-images.githubusercontent.com/42980355/71738657-e0945180-2e1c-11ea-8883-9cde5ce769d5.png)

![image](https://user-images.githubusercontent.com/42980355/71738667-e7bb5f80-2e1c-11ea-9a45-0f0da7e09e1b.png)

**Comment by dhartman25** [comment]
Bar graph labels do not line up with bars.
![chrome_2020-02-05_10-30-21](https://user-images.githubusercontent.com/4128978/73866694-e8278b80-480a-11ea-9b54-9e60498fc766.png)

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-54
