### ISSUE TITLE
Allow Group Selection in Route For Review

### ISSUE THREAD

**Issue by henryerzinger** [tsgrp/HPI#2019]
Currently the route for review action only has the ability to select users.  This enhancement will allow a configurable option to select groups for route for review.  There will also be a configurable option for if the task will be a group based task or go out to every user in the group.

**Comment by astocks7** [comment]
WIZARD WORKFLOW GROUP REVIEW ROUTE - added configuration capability to select groups for review routes. Depending on configuration, selecting groups will send the task to members of each group and, depending on configuration, either one member from each group will need to acquire and review the task OR every member in each group will need to review the task.

Requires OC rev 24178, OCMS rev 24446
CR: herzinger, dgrumieaux

**Comment by gsteimer** [comment]
This is not working properly on Alfresco since the `getGroups` method isn't working like we would expect.

**Comment by gsteimer** [comment]
Fixed with OC REV 24218

CR: ballen
