### ISSUE TITLE
Allow Voting Rejection in Complete Review Action

### ISSUE THREAD

**Issue by henryerzinger** [tsgrp/HPI#2020]
This enhancement will use the current voting system that the Complete Wizard Review action uses.  If the user votes the configured rejection value, the review task will be halted and removed from every assigned user's inbox, with the document returning to the draft state.  This enhancement will act very similar to how the Complete Wizard Approval action's rejection behaves.

**Comment by astocks7** [comment]
WIZARD WORKFLOW REVIEW REJECTION - added configuration capability that, when enabled, allows users to halt a review workflow with a configurable rejection vote. Uses a lot of the same logic that an approval workflow abortion does.

Requires OC rev 24177, OCMS rev 24445
CR: herzinger, dgrumieaux
