### ISSUE TITLE
AW Route for Review to Group does not work properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2024]
The functionality introduced in #2019 does not work properly when the route is configured in "group" mode.  That is, only one user in the group needs to acquire and process the task.  After kicking off the route for this form in edge1:

https://edge1.tsgrp.com/ocms/Stage/wizard/0900000280051592%7C0900000280051592

The form is properly `In Review` and is actually on a workflow, but it looks like the group prefix is not removed:

![image](https://user-images.githubusercontent.com/1377228/71293323-a619b780-233a-11ea-8cfb-adf1fcc17dd6.png)

When logging in as a member of `tsg_it_support`, the task does not appear in the user's inbox.

**Comment by dgrumieaux** [comment]
This issue is likely caused by the Wizard Review workflow not being re-deployed with the latest updated BPMN template. This can be fixed by redeploying with the force flag set to true.

**Comment by gsteimer** [comment]
@dgrumieaux was correct - just needed to force redeploy of the templates and that fixed the issue.
