### ISSUE TITLE
OAV Login Fails from Stage

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2026]
The recent ticket handling updates broke OAV.  It looks like it's losing the ticket value somehow and can't login:

![oav-fail](https://user-images.githubusercontent.com/1377228/71738373-0c630780-2e1c-11ea-906c-9aea195580bd.gif)

This is causing OAV STS to fail.

**Comment by gsteimer** [comment]
@Kovacinski - it looks like OAV is loading now, but is showing an error.  

![image](https://user-images.githubusercontent.com/1377228/71825381-5d177200-3061-11ea-99d6-18265fcab329.png)


The error in OC is:

```
2020-01-06 08:37:13,552	1856679	ajp-apr-8009-exec-6	ERROR	RESTService	Unknown user gsteimer&amp;timeStamp=1578321795800
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unknown user gsteimer&timeStamp=1578321795800
	at com.tsgrp.opencontent.core.user.RestUser.getUser(RestUser.java:319)
```

Looks like it thinks that `gsteimer&amp;timeStamp=1578321795800` is my user name.  Guessing the url needs to be `../gsteimer?timeStamp=...`

**Comment by CRdouglas** [comment]
Fixing the url when getting the username for the get user call. Instead of putting the timestamp on with an ambersand, we will check wether a question mark exists in the url already and if not that will be the first parameter.

CR kgarelli & skovacinski
