### ISSUE TITLE
Create New Folder - Submit button is clickable when no form is present

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2027]
See the screenshot below:

![image](https://user-images.githubusercontent.com/1377228/71744196-2278c400-2e2c-11ea-9053-55f00b049254.png)

When no form is present, the `Create Folder` button is still clickable.  This is failing STS since it expects that the button is disabled until the form is present and valid.

If the user clicks the button, the modal changes to:

![image](https://user-images.githubusercontent.com/1377228/71744274-548a2600-2e2c-11ea-9ecd-8f2f593584ac.png)

and never returns.  The user needs to hard refresh to try again.

**Comment by abrown45** [comment]
Closed with commit #24500
