### ISSUE TITLE
Search Results Timing - Icon Appears in Improper Location

### ISSUE THREAD

**Issue by Swence32** [tsgrp/HPI#2033]
In the View All Documents action on edge2, the search results timing appears above the search results table. The icon appears at the end of the result count message "Search returned # results.". When filtering is performed search results, the "name" of the filter being used appears after the search results timing icon. The search results timing icon should appear after all text below the search controls and above the results table.

This occurs when performing:
- Quick Filter
- Predefined Filter
- Facet Filtering

![SearchResultsTimingIconLocation](https://user-images.githubusercontent.com/5685648/72171141-eeefe980-3397-11ea-9531-0fcd391bfa76.gif)

**Comment by jlittle-tsg** [comment]
SEARCH RESULTS ICON BUG - fix for issue https://github.com/tsgrp/HPI/issues/2033 with search results icon not appearing at the end of the returned results text. Needed to move icon span to the end of resultsmessage.html. 

CR: cdouglas, gsinger
Revision Number: 24545
