### ISSUE TITLE
"View all documents" button for Reporting uses fixed offset, causing varied placement on various browser sizes

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#2035]
See below example - 
![image](https://user-images.githubusercontent.com/547941/72378571-44e5c980-36d7-11ea-8cb9-9bb2a7a13c54.png)

The View all documents button should be contained within the dashlet.

**Comment by jackjbridge** [comment]
REPORTING DASHLET VIEW ALL DOCS: Was using manual pixels to move over button before, was causing issues on page resize. Correcting by using float:right as opposed to manually moving over with pixels.

SVN: 24548

CR: dgrumieaux, dvora
