### ISSUE TITLE
Popovers do not close after using Reset table view

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#2038]
Once a user clicks on reset table view - the facet popover will not close on body clicks anymore. 

![popoversvsresettableview](https://user-images.githubusercontent.com/9989329/72749898-ec07ac80-3b80-11ea-9937-bcf6ad5d677f.gif)

**Comment by jlittle-tsg** [comment]
THUMBNAIL VIEW BUG - fix for issue https://github.com/tsgrp/HPI/issues/2039 and https://github.com/tsgrp/HPI/issues/2038. The shared click listener from Revision 24552 was causing these issues. Gave both popovers their own listeners and scoped them to only effect their respective selectors.

CRs: dvora, skovacinski
Revision Number: 24604
