### ISSUE TITLE
VAD does not load properly in thumbnail view

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2039]
If you load VAD in table view and switch to thumbnail view, everything works fine.  However, if thumbnail view is loaded first (OCMS remembers which you were on last), the VAD toolbar does not load properly.  See the screencam below:

![start-thumbnails-vad-fail](https://user-images.githubusercontent.com/1377228/72756519-19f5ec80-3b93-11ea-8d8d-c3d360686aa4.gif)

**Comment by jlittle-tsg** [comment]
THUMBNAIL VIEW BUG - fix for issue https://github.com/tsgrp/HPI/issues/2039 and https://github.com/tsgrp/HPI/issues/2038. The shared click listener from Revision 24552 was causing these issues. Gave both popovers their own listeners and scoped them to only effect their respective selectors.

CRs: dvora, skovacinski
Revision Number: 24604
