### ISSUE TITLE
Combine PDF table view displays search results timing icon

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2041]
See the screenshot below:

![image](https://user-images.githubusercontent.com/1377228/73218152-ff85bb00-411e-11ea-861b-006d2c43180d.png)

When search results timing is turned on, the icon is appearing in the table view utilized by the Combine PDF action.  The icon is always red and clicking it does nothing.  We should just hide the icon since it doesn't make sense here.

**Comment by jlittle-tsg** [comment]
ACTPDF SEARCH STATS FIX - fix for issue https://github.com/tsgrp/HPI/issues/2041. AdvancecdCombineToPDF now sets a boolean in searchresultsviewcontroller.js that will tell searchresultscontrols.js that it does not need to render the search stats.

CR: skovacinski, cdouglas
