### ISSUE TITLE
Using Config Archiver, the Current Edge Configs Import Corrupted/Non-existent Capture Templates 

### ISSUE THREAD

**Issue by kpelozatsgrp** [tsgrp/HPI#2042]
When grabbing the latest Edge2 configurations from the Snapserver and attempting to import them into OCMS using the config archiver, there will be corrupted/non-existent Capture templates for some object types. This causes errors all around because OC will try looking for a template with a noderef that does not exist. If the template is removed, then OCMS will break when it tries looking for existing capture templates. Both of these OC and OCMS issues break indexer mode.

Before importing the configs:
![image](https://user-images.githubusercontent.com/37337985/73300315-6a45fd80-41d6-11ea-92e9-b6e618ccf88d.png)

After importing the Edge 2 configs (notice the `Example Invoice` is selected, but do not see anything corresponding to it):
![image](https://user-images.githubusercontent.com/37337985/73300466-a8dbb800-41d6-11ea-9422-2f4e84c14000.png)

**Comment by cheinz-tsg** [comment]
Closed with OCMS Commit # 25035 and OC Commit # 24947

**Comment by cheinz-tsg** [comment]
OC Commit #24947 incorrectly constructed the repo paths of folder objects, causing DCTM implementation to fail to fetch them.

**Comment by cheinz-tsg** [comment]
DCTM bugs addressed with OC Commit #24967

**Comment by cheinz-tsg** [comment]
OCMS Indexer bugs addressed with OCMS Commit #25049. OCMS commit # 25035 inadvertently broke indexer due to a model change. All known bugs related to this issue should now be fixed.
