### ISSUE TITLE
Dashlet show/hide preferences not working on Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2044]
On edge1 (Documentum), a number of issues are occurring with the new dashlet functionality added recently:

- [ ] Dashlets default to the "hide" option in user prefs:
![image](https://user-images.githubusercontent.com/1377228/73483090-81b2f100-4364-11ea-8621-4dda489f6d4e.png)

- [ ] After changing values to "show", if you navigate away and then back, all the sliders go back to "hide" (no errors in the console or on OC):
![dctm-dashlet-prefs-fail](https://user-images.githubusercontent.com/1377228/73483293-c8a0e680-4364-11ea-87a9-6f5dd305f9b6.gif)

- [ ] Even though dashlets are defaulted to "hide", all of the dashlets appear fine on the dashboard.

**Comment by jackjbridge** [comment]
IOSSWITCH DEFAULT VALUE: Moving isChecked value to after we set the value on the model, so the switch is correctly defaulted.

SVN: 24653

CR: dvora, skovacinski
