### ISSUE TITLE
ViewProperties doesn't load properties on first time action execution

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#2049]
See the gif. Seen on all edge and release environments.

![GHissue_viewProps_no_properties](https://user-images.githubusercontent.com/14186921/73989285-eba23c00-490a-11ea-831a-a9f2b884d6cd.gif)

**Comment by gsteimer** [comment]
@renesaladrigas - is this related to #2045 ?  Can you look into it with @cheinz-tsg?  Wondering if the fix would be the same...

**Comment by cheinz-tsg** [comment]
This is related to OCMS commit #24521. That moved the form support setValues() call to a event handler for something that must trigger before the handler is set up in Search.

**Comment by abrown45** [comment]
Related to #2050

**Comment by abrown45** [comment]
Fixed with OCMS commit 24702
