### ISSUE TITLE
URL broken after back button used

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#2050]
See gif. Seen on all edge and release environments.

![GHissue_url_lost_on_backButton](https://user-images.githubusercontent.com/14186921/73989480-86027f80-490b-11ea-842c-0cb8e32e3035.gif)

**Comment by abrown45** [comment]
Introduced by commit 24449. In search, the url that was being trimmed incorrectly due to the form support update although it was working in stage.

**Comment by abrown45** [comment]
Fixed with OCMS commit 24702
