### ISSUE TITLE
Create Folder Action never validates form when executed in the stage

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2061]
See the screencam below:

![create-folder-validation-fail](https://user-images.githubusercontent.com/1377228/74368463-4fa88280-4d99-11ea-849a-0b4f08873468.gif)

On all environments (edge1/2 and release1/2), the Create Folder action never validates the form properly.  Interestingly, the header action version works fine.

**Comment by abrown45** [comment]
Related to OCMS commits 24448, 24478, 24500

**Comment by abrown45** [comment]
#### The Cause
The current code assumed each form had a trac that needed to be selected immediately when the form was opened. That trac form is populated so form support says the form is complete and can be submitted and the trac check was to ensure the trac was populated before the form was submitted.
#### The Solution
`createfolder.js`: Updated the default value of the `tracSelected` variable to be true when not in header mode (executed from Stage)

**Comment by abrown45** [comment]
Closed with OCMS commit 24756
