### ISSUE TITLE
VAD Popovers not closing after launching modal action

### ISSUE THREAD

**Issue by jlittle-tsg** [tsgrp/HPI#2062]
After combining a pdf, the search result and facet filter popovers will not close when clicked outside of. The popovers have event handlers that are listening for clicks on the body of the html. These handlers are turned off when the ACTPDF view is destroyed, which also causes them to be turned off in the VAD view.

![popover](https://user-images.githubusercontent.com/54864788/74371861-2f7bc200-4d9f-11ea-9895-49bea549827a.gif)

**Comment by gsteimer** [comment]
Note - just tried this with the `Add To Collection` action and the same thing happens.

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-53
