### ISSUE TITLE
Ghost Image If Folder is Empty but Thumbnail is Saved User Preference

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2077]
### Issue
In VAD, ghost document appears when thumbnail view is saved as user preference but folder is empty.

#### Preview
![ghost document when thumbnail VAD](https://user-images.githubusercontent.com/54869173/75471981-7e595800-5958-11ea-8a59-d8c6ded65e72.gif)

**Comment by Kovacinski** [comment]
CLosed with revision: 26543
