### ISSUE TITLE
Split PDF - Trac Button Blank

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2080]
See the screenshot below.  For some reason the trac button in Split PDF is blank.  This doesn't affect functionality, however.

![image](https://user-images.githubusercontent.com/1377228/75921849-80735900-5e27-11ea-967c-8f78448163c9.png)

Clicking the button displays the text (until clicking elsewhere):

![image](https://user-images.githubusercontent.com/1377228/75921877-8ff2a200-5e27-11ea-9348-bbaaef12c741.png)

Some things to look into:

- When testing this, need to test the Prune PDF action as well.
- Why is it showing the trac and type at all here?  If there's only one option, shouldn't it hide the trac button and/or type dropdown?

**Comment by abrown45** [comment]
Fixed with commit #24917
