### ISSUE TITLE
Remove Deprecated Admin Option to Display Annotated PDF

### ISSUE THREAD

**Issue by cheinz-tsg** [tsgrp/HPI#2082]
The PDF Viewer should should display a document's annotated version if the **Annotated Version Configuration** switch in the Admin Config (Stage->Doc Viewer) is enabled and the document is annotated. Currently, the `isAnnotated` check always evaluates to false and the document is displayed without any annotations. I believe this is because the check is against the property `this.isAnnotated`, rather than `this.viewModel.isAnnotated()`. The way of storing the `isAnnotated` flag may have changed at some point without this check being updated.

**Comment by gsteimer** [comment]
@cheinz-tsg - that switch is actually deprecated in the admin.  It's a relic from before OA was integrated into OCMS as a viewer.  The correct way to do this is to just make OA the stage doc viewer.  We should probably remove or hide that switch in the admin.

**Comment by gsteimer** [comment]
Confirmed with OCMS team - we should just remove this option from the Stage / Doc Viewer admin and the associated code in the stage that utilizes it:

![image](https://user-images.githubusercontent.com/1377228/76544325-d4002b00-6455-11ea-9c8d-2fdd6268da2d.png)

The currently methodology is to simply use OA / OAV embedded in the stage.

**Comment by mwojno-tsg** [comment]
This issue was resolved in OCMS commit #25127. The "showAnnotatedVersion" attribute was removed from the docviewerconfig model. Therefore, changes to edge should also be to remove that property from the stage config.
