### ISSUE TITLE
Bulk Redact flips non-pdf mime types to PDF

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2094]
See the screenshots below.  When executing a Bulk Redact across a case folder, any documents that do not have native PDF mimetypes are somehow flipped to PDF:

Prior to executing Bulk Redact:
![image](https://user-images.githubusercontent.com/1377228/78264893-5b771200-74c9-11ea-9ebd-b1e849b1db6f.png)

After Executing Bulk Redact:
![image](https://user-images.githubusercontent.com/1377228/78265157-af81f680-74c9-11ea-9266-8b3ac54f270a.png)

We need to figure out what's going on here.  Is it actually changing the native content to PDF?  Ideally, the code would do the following:

- If the document is not a PDF, but has a PDF rendition, perform the redactions on the PDF rendition (leaving the native content alone)
- If the document is not a PDF and does NOT have a PDF rendition, skip it.

**Comment by henryerzinger** [comment]
Fixed with OC Commit #25175 and HPI Commit #25141

**Comment by gsteimer** [comment]
@henryerzinger - looks like this is working, but we need to ignore any of the 'hidden' items:

![image](https://user-images.githubusercontent.com/1377228/80493639-4906c180-892b-11ea-9ba2-51ed792cdb43.png)

`.oc-info` is actually a subfolder of the case (same with `.folder-notes` if there are any folders notes).

**Comment by henryerzinger** [comment]
Fixed with OC commit #25210 and HPI Commit #25159
