### ISSUE TITLE
Rename HPI Simple workflow

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2095]
We should rename this workflow template so that it no longer has the `HPI` naming.  Perhaps just keeping it as a generic `Simple Workflow`.

![image](https://user-images.githubusercontent.com/1377228/78304439-60a58280-7504-11ea-8949-4dd791a703d9.png)

Talk to me before starting this.

**Comment by gsteimer** [comment]
At a minimum, we should change the user visible name for the workflow, no need to change the actual bpmn file name unless that makes this easier.   If it's just changing this name here, that woudl work.

![image](https://user-images.githubusercontent.com/1377228/80259736-e623da80-864b-11ea-8278-3ef56215b7b5.png)

Also - we need to make sure that the trunk configuration for cleaning up historical workflows is updated and tested as well.

Once we know the direction here, let me know what will need to change (if anything - ideally not) in demo/existing environments.

**Comment by grahamsinger** [comment]
Updated with OC revision 25312.
