### ISSUE TITLE
Refreshing any URL causes 404

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2096]
Something changed recently to cause any URL refresh (other than `/ocms`) to 404.  See below:

![refresh-fail](https://user-images.githubusercontent.com/1377228/78704180-0ffda300-78d1-11ea-94dd-75bb80d5207f.gif)

This does work properly on release, which is at rev 24834.  We need to fix this before I can rebuild the release environments.  Could the recent spring or other dependency upgrades be the culprit?

**Comment by grahamsinger** [comment]
Fixed with revision 25076 in OCMS.
