### ISSUE TITLE
Configurable External Indexes in the OTC for Alfresco with Elasticsearch

### ISSUE THREAD

**Issue by Kovacinski** [tsgrp/HPI#2097]
This enhancement allows for configurable external indexing in alfresco projects via elasticsearch. Configuration can be found in the object type section of OCMS admin. If an object type is configured for indexing, it will have its own index created in the elasticsearch cluster that is setup.

[Wiki page](https://github.com/tsgrp/OpenContent/wiki/Setting-up-Alfresco-with-Elasticsearch) for setup instructions

**Comment by astocks7** [comment]
OC rev 25011
OCMS rev 25075
