### ISSUE TITLE
Doc Info View Section Duplicated after Property Edit

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2102]
See the screencam below.  After editing properties of a document, the section is duplicated.

![doc-info-view](https://user-images.githubusercontent.com/1377228/80012084-64d51800-8492-11ea-8670-72c4518dee77.gif)

Note - I think this must be some sort of timing issue because I've also seen it disappear completely rather than duplicated.

**Comment by henryerzinger** [comment]
Fixed with OCMS revision #25179
