### ISSUE TITLE
Saved Search Dashlets should be able to search all versions to better support Controlled Documents

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2104]
Currently, saved search dashlets do not have the option to search all versions, similar to how the search config works:

![image](https://user-images.githubusercontent.com/1377228/80529678-6a80a100-895d-11ea-8d05-1eddac9025e5.png)

Without this configuration option, this means that saved search dashlets will only be able to display 'active' Chain Versionable Documents

**Comment by astocks7** [comment]
SAVED SEARCH DASHLETS SEARCH ALL VERSIONS - adding a switch in OCMS admin to saved search dashlets which, when enabled, will search for all versions of a document

OCMS rev 25897
CR: jbridge, aking
