### ISSUE TITLE
Cannot Get The Current Approval Details In Wizard Workflow Listeners on Alfresco

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#2107]
Overview 
- There is an overarching issue going on in the Alfresco environment where the approval details are not being correctly passed between listeners within the wizard workflow. It has resulted in a few issues that are listed below. 
- In short, various transactions are probably overlapping resulting in different listeners to access stale or old approval details when performing the next task. This produces wrong behavior as it is not being able to access the current approval details.
- This issue will keep track of the various issues that can be closed once this architectural change is designed and implemented. 

Issue List

- [ ] #1967 
- [ ] #1617 
- [ ] #2014 
- [ ] #2152 

Insights
- In `AlfrescoEmbContentImpl #getContentHelper` line 1233, the content url received is the old content url before the approval details was updated. Therefore, there has to be competing transactions here that are ending in race conditions on getting the correct approval details. This is a prime spot to start for revisions and re-structuring.
  
![image](https://user-images.githubusercontent.com/54864662/80740121-3cc26600-8add-11ea-864e-abfe4f155f5e.png)

**Comment by mwojno-tsg** [comment]
An idea for a fix to this would be to store the approval details on the execution variable that is passed between the wizard workflow listeners. That could alleviate the problem between transactions locking or race conditions, if that is the reason for the issue. We would still have the approval details json file, but this would be our way to easily pass between listeners?

**Comment by cheinz-tsg** [comment]
Closed with OC Commit #25614. A small in-memory cache was added to store AppDetails objects that had been updated in OC (by a workflow listener, etc.) but not yet propagated to Alfresco when another section of code wants to fetch AppDetails.
