### ISSUE TITLE
Link Resolver has broken items

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2109]
The link resolver control in the admin seems to think there's more options available vs. shown.  @Kovacinski - I'm guessing this is due to the removal of the `Folder Browser` option?  

See the screencam below:

![link-resolver-error](https://user-images.githubusercontent.com/1377228/80988465-2c6dfc00-8df9-11ea-9d3f-fb440a3fd465.gif)

**Comment by henryerzinger** [comment]
Fixed with OCMS commit #25181
