### ISSUE TITLE
Reporting dashlet bar graph displays value of 1 when query does not return results

### ISSUE THREAD

**Issue by cheinz-tsg** [tsgrp/HPI#2116]
Here is an example on edge1. At the time of this writing, edge1 does not have any Controlled Documents in the cancelled state ([search](https://edge1.tsgrp.com/ocms/search/ControlledDocs/Controlled%20Document?paramName=aw_status&paramValue%5B%5D=Cancelled&paramType=property&operator=OPERATOR_EQUALS&searchMod=CASE_SENSITIVE&termLogic=OR/paramName=Controlled+Document&paramValue=Controlled+Document&paramType=type&pageNumber=1&sortAttr=objectName&sortOrder=-1)).

However, in a reporting dashlet displaying the number of documents cancelled in each of the last 12 months (querying on tsg_obsoleteDate), each bar has a value of 1.
![image](https://user-images.githubusercontent.com/54864840/82086004-79808680-96b3-11ea-9469-249909877f84.png)

Clicking on the bars in the graph or on the View All Documents button will again take you to the search screen and run a query in which no results are found.

**Comment by mwojno-tsg** [comment]
I didn't see that this issue was related to one I just created. This should be closed by OCMS commit #25313. It is also related to this github issue: https://github.com/tsgrp/HPI/issues/2132
