### ISSUE TITLE
PDF.js fails if object name has invalid characters

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2118]
In non-alfresco environments, objects can have special chars in the object name, ex: `/`.  This causes issues with PDF.js.  In this example, the object name is `Policy / Contract`:

![image](https://user-images.githubusercontent.com/1377228/82493014-dfeb1780-9aac-11ea-9778-1c7f2d17580f.png)

The Request URL is: 

`rest/content/content/Policy%20%2F%20Contract?id=09000002800326a7&overlay=true&contentType%5B%5D=pdf,.*&name=Policy%20/%20Contract.pdf`

Notice the value of the `&name`, which includes an unencoded slash, causing the failure.  Looking at the content/content endpoint however, I don't see that `name` parameter at all.  We should dig a little further, but I think we can just simply remove whatever code is adding that parameter to fix this issue.

**Comment by jackjbridge** [comment]
PDFJS OBJECT NAME: Fixing issue with pdf.js failing when a doc name with a / or \ was being passed in to the /content/content call. Correcting by replacing those characters with an _.

SVN: 25248

CR: gsteimer, dgrumieaux
