### ISSUE TITLE
Folder Notes Launch Externally - Option to Use Doc Viewer

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2124]
## Enhancement
Currently, the launch item externally function in folder notes uses the content/content endpoint and opens the file in a new tab in the browser's doc viewer. Alternatively, if the file is not supported in the browser viewer it will be downloaded. This enhancement is to update that functionality to be configurable based on if the user wants to open in browser or in the doc viewer and if docviewer, use the doc viewer configuration to select which doc viewer to use.

**Comment by nreiman** [comment]
**Note: instead of adding the option to open in Doc Viewer, this update just opens the document in Stage w/ Folder Notes in dual pane mode. 
OCMS Revision: 25515
CR: jhof, skovacinski

**Comment by abrown45** [comment]
An update to the app file is defaulting this configuration to true always causing an issue. See #2249

**Comment by abrown45** [comment]
opening a new issue for the above comment
