### ISSUE TITLE
HPI Setup Script for Alfresco

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/HPI#213]
Create java-backed webscript that will take care of initial HPI setup, including users, groups, and folder structure with proper permissions set. On the FTL, the script will output info to the user about what folders, groups, and users were created. It should be able to be overridden or reused in client projects to create client-specific folders, groups, and users in addition to the HPI defaults.

**Groups to create:**
hpi_administrators

**Folders to create with permissions set:**
hpi - does not inherit permissions, GROUP_EVERYONE with Contributor permissions
hpi/user - inherits permissions from hpi folder
hpi/configs - does not inherit permissions, GROUP_hpi_administrators with Coordinator permissions

**Users to create:**
None by default, but make available for client projects to override.

**Comment by gsteimer** [comment]
This was done long ago as a JS webscript - `hpiSetup.get.js`.  See the HPI Install for Alfresco for more information: https://github.com/tsgrp/hpi/wiki/Installation-guide#alfresco-installation
