### ISSUE TITLE
Folder Notes - Unable to Open Links in Note Content

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2130]
## Issue
Several folder notes contain links telling the user they can route to the documents by clicking. Currently no action occurs when clicking on those links. Depending on the course of action either the text that calls the user to action and the link formatting should be removed or the link should have the appropriate anchor tag allowing the user to route on click.  

![image](https://user-images.githubusercontent.com/54869173/83780027-41d18280-a652-11ea-875f-91c566c8e3cd.png)

**Comment by nreiman** [comment]
**Note: The update only works for NEW notes due to the way the code is setup to create and retrieve notes.
OC Commit: 25691
CR: jhof, skovacinski
