### ISSUE TITLE
Archived Notifications Not Displaying Extra Properties

### ISSUE THREAD

**Issue by josorio-tsg** [tsgrp/HPI#2135]
## Issue
When notifications are configured to have extra properties, they are visible in the dashlet and the modal when clicking the info button and expanding the notification. When you click the Complete button, the notification should become an Archived Notification and display all its properties plus any extra properties that were displayed in the My Notifications view before completing it. However, the archived notifications aren't getting the extra properties. 

### Possible Cause
When debugging in OC through `ActivitiNotificationImpl#getArchivedNotifications`, the TaskQuery object is getting an empty array returned, so our initial thoughts on what could be causing it is that the query isn't grabbing the right data for the archived notifications.

### Recreating The Issue
Configure Notifications View with extra properties. Click the info button to show the extra properties to make sure they are there. Complete the notification and go to the Archived Notifications tab and open the notification again. The extra properties should be missing.

![notifications_archived_extra_properties_issue](https://user-images.githubusercontent.com/54865017/84328137-c175ba80-ab46-11ea-8745-d75202685073.gif)

**Comment by joehof** [comment]
Some extra things to look at to close out Notifications:

- Filter not losing focus after stopping typing
- Possibly hiding the additional details button if no extra props exist AND the display text is all contained in one line

**Comment by nreiman** [comment]
OC Revision: 25729

CR: aking, kgarelli

**Note: The OC commit only fixes the original issue. I have the updates for "filter losing focus after you stop typing" and "hiding the additional details button if no extra props exist AND display text is contained in one line" almost done in OCMS, but need to do a bit more testing and write unit tests.

**Comment by nreiman** [comment]
OCMS: 25550

CR: jhof, skovacinski
