### ISSUE TITLE
Right Click Menu Doesn't Close

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2136]
See the screencam below.  On both edge1/2, but not release2 or qa2 (3.4 tag), when I right click, the menu doesn't disappear if I click away or even click on an action:

![right-click-disappear-fail](https://user-images.githubusercontent.com/1377228/84685715-55a5a000-af00-11ea-8f55-a7e3d29671f2.gif)

**Comment by mwojno-tsg** [comment]
Resolved with OCMS revision #25342. A previous commit messed up the context within the function that does the hiding of the right click menu. That was fixed in the commit by adding `var self = this` and replacing `this` with `self` in the appropriate places. Unit tests added.
