### ISSUE TITLE
Office 365 Edit Online Cancel Checkout on Document With Spaces

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#2139]
If a user attempts to cancel a checkout with a document that has spaces in the name, the following error occurs on the back-end:

Failed to cancel checkout:500 {"status":500,"message":"Illegal character in path at index 67: https://graph.microsoft.com/v1.0/me/drive/root:/OCMS_Working_Copies/Alfresco Master Agreement.docx","error":true}

**Comment by mwojno-tsg** [comment]
Closed with OC commit At revision: 25551. One line added to encode fill name in cancel checkout. This was forgotten during the MS online cloud updates. The Checkin/Checkout from cloud action executers already had encoding in place. Cancel checkout was forgotten.
