### ISSUE TITLE
Related Objects - Add ability to show more than one attribute in the generated link

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#2141]
Currently, we only have the ability to show 1 attribute as the link for related objects.  There is an "Info Block" that allows the user to select additional attributes to show for a given object, but that requires the user to hover over an icon.

There are certain use cases where it would be useful to see more than just 1 piece of metadata at one time for these objects, especially if there is a large number of related objects. (Not having to hover and re-hover to confirm you are clicking on the intended object could save a lot of time).

We should also allow the user to put text in between their selected properties.  E.g `{document_number} Rev: {revision_number}` where `Rev:` is some custom text.

**Comment by cheinz-tsg** [comment]
Closed with OCMS Commit # 25467

**Comment by cheinz-tsg** [comment]
Closed with OCMS Commit # 25467
