### ISSUE TITLE
Deep Linking into a stage link or a specific document doesn't properly direct when going through the login page

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#2142]
When a user has previously been logged into OCMS with a valid ticket and this ticket expires, it seems like the series of routers that we come through when the application thinks it has a valid ticket causes OCMS to lose the URL that it was going to go to. 

Steps to reproduce:

1. In a working browser/session, be in OCMS actively working on a certain page (doesn't matter where)
2. Via Postman, end the ticket that was being used by the browser (stimulates the ticket expiring)
3. In a new browser tab, launch a link that includes context that would take you to the stage to a specific document (simulates a user clicking on an email link to launch into a specific document)
4. User is asked to login (expected, since the ticket that the browser had is expired)
5. Once logging in, the user is taken to dashboard rather than the specific stage link they started with (no bueno)

The error occurs because it seems like OCMS on the client side thinks that it has a valid ticket/ocUser, so it continues into the application. Then it attempts to make a call to OC, and that ticket is rejected when the first call happens (seems to be `/users/user/`). When that call fails, it seems to hit a piece of code that does a hard refresh without preserving the parameters/url.

Want to test this on the /claim router as well.

**Comment by Kovacinski** [comment]
Fixed with Revision 25414
