### ISSUE TITLE
VAD/Search New Timeline View

### ISSUE THREAD

**Issue by engerernoah** [tsgrp/HPI#2146]
### Timeline View
Create a timeline view sorted by year and month to display search results as well as to display contents in view all documents. Add configurable color indicators to represent different values of a configured attribute as colored dots on each thumbnail image in the timeline view. Add the ability to represent that a document has annotations by placing an icon on any thumbnail images in the timeline view that have annotations. Add functionality and UI/UX for timeline view to work in mobile mode. 

### Functionality
- Ability to view search results or to view all documents in a timeline view
- Ability to configure the date attribute used to sort the timeline
- Ability to configure an attribute and its values to have color indicators.
- Enhancing the mobile view to gracefully handle timeline view
- Vertically displaying the timeline view in desktop mode
- Enhancing both stage info and document info to easily display relevant information and efficiently use application space.

### Timeline View Mobile Example
Here is what the timeline should look like in mobile view:
![image (4)](https://user-images.githubusercontent.com/39744036/86834572-9789b800-c060-11ea-9100-3a81e38c45d1.png)

**Comment by engerernoah** [comment]
Closed with revision #25439

**Comment by Kovacinski** [comment]
Reopening unitl unit tests can be committed

**Comment by engerernoah** [comment]
Unit tests and updates for timeline view included in revision #25506 

Issues fixed:
 - Increased CPU usage when in timeline view due to spinners not being properly destroyed
 - Moving code to determine if the actions drop down should show based on what view we are in to the after render. This fixes an issue where if you started in timeline view and switched to table view the actions dropdown would not appear in table view.
 - Determining which no thumbnail available image to show based on mimetype and having specific images for audio files, video files, and dicom images.
 - Cleaning up repeated code and unused code in the timeline view and in the configs as well as breaking things out for easier unit testing
 - Cleaning up inline styling
 - Addressing issues around doc name
 - Adding in better admin text for what the color indicator configs are and how they are used
 - Adding the ability to click on the badges in facets/filters to filter search results
 - Added and updated unit tests for timeline view, the views we created in genericresultsconfig and to areas of stage and docviewer that we updated. 

CR: skovacinski, aking
