### ISSUE TITLE
Change "Pending" Workflow Status to Multiple More Descriptive Statuses

### ISSUE THREAD

**Issue by cheinz-tsg** [tsgrp/HPI#2152]
Currently, the workflow signature status "Pending" is used somewhat vaguely to describe several different scenarios that the signature task could be in. "Pending" could mean that the workflow has not been started, or if it has been started, "Pending" doesn't differentiate between a task that can be completed immediately and a task that is not available until a prior task has been finished. It would be a good idea to split this status into 3 different statuses that each indicate one of these scenarios.

**Comment by cheinz-tsg** [comment]
Added with OC Commit# 25585 and ACA Commit# 25451.

Not Started-Workflow is not routed (review or approval). Default task status when initializing the workflow.
Pending-Workflow is routed, and this particular task can be completed immediately.
Future Task-Workflow is routed, and this particular task cannot be completed until another task is completed and "unlocks" this task.

**Comment by gsteimer** [comment]
When testing this on edge2, I'm not seeing the status values change.  I've sent a form to `qdadmin3` at priority 1, and two other users at priority 2.  When looking at the task for qdadmin3, all of the tasks are still "Not Started"

![image](https://user-images.githubusercontent.com/1377228/87179063-c2178300-c2a3-11ea-8478-46d83881230a.png)

**Comment by cheinz-tsg** [comment]
Closed with OC Commit #25614. The original commit used code that interacted with ApprovalDetails objects in a way that didn't work with Alfresco (issue #2107).
