### ISSUE TITLE
Allow Multiple Properties to be Used when Generating Related Objects Links

### ISSUE THREAD

**Issue by cheinz-tsg** [tsgrp/HPI#2153]
Currently when configuring the related objects section, you can select 1 property to use when generating the link to the related object (usually this is the object name or title). 

![image](https://user-images.githubusercontent.com/54864840/87173043-c7240480-c29a-11ea-8d4a-2a756b5bd124.png)

It would be great to be able to concatenate multiple properties if desired. For example, if 2 different versions of the same document appear in the related objects section, the version label could be displayed in the link so that the user knows which is which without needing to hover over the glyphicon or click the links to open each document's stage view.

**Comment by grahamsinger** [comment]
@cheinz-tsg Thanks for opening, but I already created one for this here: https://github.com/tsgrp/HPI/issues/2141
