### ISSUE TITLE
Remove all iOS style switches

### ISSUE THREAD

**Issue by nreiman** [tsgrp/HPI#2162]
#### All true/false "iOS Switches" will need to be replaced with Google Material Design switches. 
- See the following link for more info on how they should look: [Google Material Design Switches](https://material.io/components/selection-controls#switches)
- See the following link for an example on how to update the CSS/HTML: [Google Material Design Switch CSS/HTML Example](https://codepen.io/finnhvman/pen/pOeyjE)

All other iOS Switches that have >= 3 values will either need to be replaced with Google Material Design radio buttons or converted into dropdowns.

The first pass at the update was done for Folder Notes...see OCMS commit #

### Actions
- [x] Folder Notes

### Admin Config Files
- [ ] Complete Task Custom Config (See https://github.com/tsgrp/HPI/issues/2222)
- [x] Docviewers

**Comment by nreiman** [comment]
OCMS Rev: 25789

CR: aking, dvora

**Comment by gsteimer** [comment]
Other areas of the admin that are left to address:

- [ ] App Config
- [ ] Template Admin - Capture Templates
- [ ] Event Logging
- [ ] Dashboard (Especially Reporting dashlets)
- [ ] Search
- [ ] Collections (Note - may just work with search updates, not sure if this is forked)
- [ ] Stage - All areas except Doc viewer (committed above)
- [ ] Action Configs (default view that shows for all actions)
- [ ] Action Configs (specific views per action)
- [ ] Indexer
- [ ] Active Wizard Forms
- [ ] Admin Search Tool
- [ ] Config Archiver
- [ ] Developer Zone

**Comment by gsteimer** [comment]
Note - going forward, we need to make sure that issues like this do not crop up after switching to the new sliders: #2290

**Comment by nreiman** [comment]
Have App Config and Config Archiver logic complete. Still need to finish up testing all places logic was changed from string to bool vals and then need a CR.

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-51
