### ISSUE TITLE
DocInfo Broken if a user tries to configure just "Associations" without properties enabled

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#2170]
If the UI is configured like the below screenshot, the entire application hangs when a user views a document:

![image](https://user-images.githubusercontent.com/4850976/88197071-9089aa80-cc07-11ea-9744-cb486a0ee5fb.png)

There are use cases that we only want to show the "Associations" without properties, and that is not currently possible. 

The 'workaround" is to configure it like this, but the side effect is that you end up with a bad looking UI blank box for all documents that don't have any associations:

![image](https://user-images.githubusercontent.com/4850976/88197241-cc247480-cc07-11ea-835d-2279b246d168.png)

Looks like this:

![image](https://user-images.githubusercontent.com/4850976/88197297-e0687180-cc07-11ea-9917-cd299c59915e.png)

A part of this update should also be to fix the styling of this feature as it currently takes a ton of vertical UI space and cuts off the attachment name. The UI should allow the hiding/showing of attachments, but with a button that is on the same line as the attachments:

![image](https://user-images.githubusercontent.com/4850976/88197380-04c44e00-cc08-11ea-9441-8a11dc185c31.png)

- [ ] Fix Styling
- [ ] Fix comma separating repeating fields: Tags just throws a comma between the value with no space

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-50
