### ISSUE TITLE
Remove configurations from config-project.js that can change between environments - Phase 1

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2172]
We need to get to a point where the same `ocms.war` can be deployed to any environment.  This is especially important for when OC is configured for Alfresco, so we should start with repo-agnostic items or anything that is used in the Claims and PnP Accelerators. 

When moving items to the admin, we should provide sensible defaults wherever possible.  This should be in the case when creating a new config OR when a value is `undefined` (which will be the case for existing configs).

This may not be an exhaustive list, so we should analyze other areas that may utilize `config-project.js`.

- [x] `manageWFDocSearchConfig` - this should be configurable in the Manage WF Docs action config (Talk to Dan and me before starting this one)
- [x] `manageRelationsConfig` - same as the last one, but different action
- [x] `manageAdHocDocumentsConfig` same as the last one, but different action
- [x] `seteffectivedate` , specifically `setEffectiveDateCtrlDocTypes` to allow for custom doc types

Need to talk through these to see what makes sense.  If we can say that all alfresco environments will never have these changed, then they're likely fine to stay:

- [x] `config:folderPropertyToQuestionLabelMap` - This should be removed and any autopopulation should happen automatically. A question to be autopopulated should have it's short-label (label in WizardAdmin) named to match the property it should populate from.

**Comment by dgrumieaux** [comment]
Related issue - https://github.com/tsgrp/HPI/issues/2181

**Comment by cheinz-tsg** [comment]
Smartcomm URL removed from config-project.js files in OC Commit 25825 and ACA Commit 25584. Going forward the other changes will be made in a feature branch and merged back to trunk at a later date.

**Comment by cheinz-tsg** [comment]
SetEffectiveDate and ManageWorkflowDocuments entries were removed from config-project.js and added to their respective admin action configs in OCMS commit #25664. 

NOTE: These actions must be reconfigured in order to work with this commit. The action handlers no longer read from config-project.js and rely on the action configs for much of their functionality. The actions will error out if attempting to use the actions without the new action configs.

**Comment by cheinz-tsg** [comment]
ManageWorkflowDocuments repository-specific 'set defaults' button added in ACA Commit #25734. A dropdown allows you to select from Alfresco/Documentum/HBase and then pressing the button configures the action for that repository.

**Comment by cheinz-tsg** [comment]
ManageRelations and ManageAdHocDocument action configurations were removed from config-project.js and added to their respective action configs in ACA Commit #25771.

NOTE: These actions must be reconfigured in order to work with this commit.

**Comment by cheinz-tsg** [comment]
folderPropertyToQuestionLabelMap entry used by the active form router was removed in ACA commit#25849. Now in order for a folder property value to be used to auto populate a question on a wizard form, the question's label must have the same name as the property it is matched with. This can be configured in Wizard Admin.

**Comment by mwojno-tsg** [comment]
I am closing this issue as we took in the above commits that are complete into the 3.4.2 release. Opened a phase 2 for the outstanding items on this enhancement: https://github.com/tsgrp/HPI/issues/2271
