### ISSUE TITLE
Folder Notes - consistent link behavior

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2173]
Document links can appear in two places in folder notes - in the "Documents" column as well as "Note Detail":

![image](https://user-images.githubusercontent.com/1377228/88232099-e7f53e00-cc3a-11ea-9276-1ddf319a6070.png)

Currently, the behavior of these links is different - the Note Detail links launch to the document, taking over the loaded action, whereas the "Documents" links open the document in dual pane.  We should be consistent here and also handle the case of a modal Folder Notes action.

- [x] **Folder Notes - Full Pane** - launch documents in side by side mode
- [x] **Folder Notes - Modal** - launch document and close modal

There's also some CSS that needs to be cleaned up in the modal view:

![image](https://user-images.githubusercontent.com/1377228/88232350-51754c80-cc3b-11ea-8e05-e00da51a3cd5.png)

**Comment by abrown45** [comment]
@joehof we need to make sure as we update the links and their click events that they have the ability to be turned off preventing any routing from the action to another part of the application if we are in the `ActionViewer.js` view Nypiua created.

**Comment by nreiman** [comment]
OCMS Rev: 25749
CR: skovacinski, abrown
