### ISSUE TITLE
OCMS unable to load Trac configurations for users not using groups

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#2174]
In the case of OCMS implementations that contain users without groups (as in Solr implementations), the application will fail to load the trac configurations appropriately. The user will be routed to display the error message under "/tracAuthorizationError" because the application isn't saving the Trac configurations appropriately after retrieving them from the server.

![image](https://user-images.githubusercontent.com/14186921/88416561-0a579a80-cda6-11ea-805e-1fd8a67fb4d6.png)

**Comment by grahamsinger** [comment]
This turned out to not be an issue.  I had a local modification that was causing this.
