### ISSUE TITLE
ACA Collaboration Server: Real Time Collaboration in Stage - Phase 1

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2198]
Enhance the stage to utilize the collaboration server (same server that AEV uses) and provide the following functionality:
Phase 1:
- [x] Display an indication of what users are currently viewing the folder in the stage
- [x] Display an icon in table view to indicate what documents are currently being viewed, and by what user(s)
- [x] Allow the user to start a Zoom call with all users currently viewing the folder 
- [x] Navigate from Stage to the Dashboard to Stage without requiring a refresh
- [x] Show to the user that the server has disconnected and collaboration is disabled until the connection resumes

Current issues to be fixed:
- [x] Do not attempt to initialize a socket manager if collaboration is turned off (might need to even add an explicit config for this)  - Causes errors with stage.js for non-collaboration users
- [x] Circular dependency with some actions

**Comment by abrown45** [comment]
Initial commit without unit tests for first demo 25608, 25609

**Comment by abrown45** [comment]
closing off phase 1

**Comment by abrown45** [comment]
Pending AEV collaboration server commit

**Comment by abrown45** [comment]
commit 6966 in AEV for socket server updates

**Comment by abrown45** [comment]
missed underscore replacement from merge, closed on commit 6974 in AEV

SOCKET SERVER FOR ACA ISSUE FIX - missed an '_underscore' changed to '_' after merging changes from branch
GH: https://github.com/tsgrp/HPI/issues/2198

CR: aking, mbrouillette, gsteimer

**Comment by abrown45** [comment]
COLLABORATION UNIT TEST COVERAGE - adding additional test cases to cover functionality from the previous collaboration effort
GH: https://github.com/tsgrp/HPI/issues/2198

CR: dvora, nengerer, jlittle

**Comment by abrown45** [comment]
@gsteimer this did get implemented yes. maybe it needs to be refined or is still lingering on the branch. Ill add it to phase two.
