### ISSUE TITLE
FreeMarker Template Management Admin

### ISSUE THREAD

**Issue by CRdouglas** [tsgrp/HPI#2200]
Create an admin tab under template management to modify properties and version templates within the repo.  This will consist of a list of all the templates that have the tsgTemplate type and will populate with the modifiable properties shown. A button will be added that will show a modal so the user can modify and version the properties.

**Comment by CRdouglas** [comment]
OCMS: 25618, 25619
FREEMARKER TEMPLATE ADMIN: Adds the ftl template management tab to the template management portion of the admin. The admin will query for templates of the tsg template type and return the ability for versioning and modifying of the title and description of the template. creates an interface to modify properties and version templates in the repo only.

CR aking && dgrumieaux

OC: 25849
FREEMARKER TEMPLATE ADMIN: Additions to mask the description property for alfresco and documentum. Also, includes the addition of the ftl mimetype for uploading new ftl files.

CR: aking && dgrumieaux

**Comment by gsteimer** [comment]
@CRdouglas @dgrumieaux - it looks like this isn't working on edge (1 or 2):

![image](https://user-images.githubusercontent.com/1377228/89805264-01cbc780-dafb-11ea-8487-29380b18baa2.png)

There's no way to actually see the template list or make updates

**Comment by CRdouglas** [comment]
Enhancement continued: Rev #2216
