### ISSUE TITLE
Picklist Values are displayed instead of labels when Autocomplete field loads in View Properties

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#2202]
As described in title. If a picklist is configured for an Autocomplete field in View Properties, a user should see the Label value as the field is displayed to the user. Instead, the value is currently being displayed to the user.

**Comment by aviking** [comment]
Fixed with OCMS revision: 25689. 

CR: jhof, skovacinski

**Comment by aviking** [comment]
There is a small issue where if using dependent autocomplete, a null pointer exception is thrown. This can easily be fixed with a null check.

**Comment by aviking** [comment]
Fixed with OCMS revision: 25788
CR: jhof, skovacinski
