### ISSUE TITLE
Manage Workflow Documents action does not allow configuration

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2215]
See the screenshot below.  With the recent commit to move the manage workflow docs config to the admin, it looks like something is causing the configuration to not show up on edge1:

![image](https://user-images.githubusercontent.com/1377228/89797423-8b29cc80-daf0-11ea-9352-42cc393e7e0c.png)

This seems to be working fine on edge2 (Alfresco)

**Comment by cheinz-tsg** [comment]
Closed with ACA Commit #25734. Some default values used when configuring the action for the first time were Alfresco-specific and did not have Documentum equivalents. This caused the view to fail to load. Added some null checks and allowed the view to load with empty selections in the event of a default value not being valid.
