### ISSUE TITLE
Bulk Upload - When uploading from template combined with a normal file, documents are switched in the indexer

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2221]
See the screencam below.  If I try to upload a document from template as well as drag and drop a normal file:

- In the heads up indexer, the normal file is displayed for the template document
- The normal file heads up indexer never displays

Oddly, after finishing the upload, both files look correct.

![bu-template-plus-normal](https://user-images.githubusercontent.com/1377228/89950016-6287fc80-dbee-11ea-939b-89f94a142d91.gif)

**Comment by CRdouglas** [comment]
BULK UPLOAD: Adds the template id to the indexer's showable ids and increments the number of documents so the document won't get overwritten in other arrays.

UNIT TESTS included.

Github issue: https://github.com/tsgrp/HPI/issues/2221

CR: aking & dgrumieaux

REV: #25742
