### ISSUE TITLE
Send Email with chained Folder Note is failing to send

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2223]
Found by STS.  The test failed edge1 (Documentum) but the email sent successfully on edge2 (Alfresco).

The action executer is failing with a NPE on the `setName` line here in `SendFolderEmailActionExecuter`:

```
EnhancedObjectProperty attrSubject = new EnhancedObjectProperty();
		attrSubject.setName(dictionaryService.getPropertyDefinition(EmailConstants.ATTR_EMAIL_SUBJECT).getRepoName());
		attrSubject.setStrings(new String[] { email.getSubject() });
		attrSubject.setType(OCConstants.TYPE_STRING);
        properties.add(attrSubject);
```

**Comment by gsteimer** [comment]
@dgrumieaux @CRdouglas - it looks like this was caused by the FTL commit.  Specifically, we added this cheater to Documentum:

```xml
<entry key="subject" value="desc" />
```

That causes this to fail since we have this in `EmailConstants`:

```java
public static final String ATTR_EMAIL_SUBJECT = "subject";
```

Possible fixes:

- Add a description field to our TSG template custom type (preferred approach)
- Update the ocName of the cheater to be `subject`

**Comment by CRdouglas** [comment]
FREEMARKER TEMPLATE: Changes to the bean configs for alfresco and dctm to fix the subject line issue in send email. Also, changes to allow the title and description to be passed along in the import/export config functionality. 

REV: 25953

Github: https://github.com/tsgrp/HPI/issues/2223
Github: https://github.com/tsgrp/HPI/issues/2228

CR: rsaladrigas & dgrumieaux & gsteimer
