### ISSUE TITLE
Active Wizard - Adobe Form Templates do not check boxes properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2224]
It looks like this the AW / Adobe Form template integration does not properly check boxes anymore.  I'm guessing this happened after the update to use Aspose.PDF for wizard form generation.  See the screenshots below from the CHI Permit Application Form:

![image](https://user-images.githubusercontent.com/1377228/90063117-7eeb6e00-dcae-11ea-8d2d-da5fcae78a6f.png)

Form generated:

![image](https://user-images.githubusercontent.com/1377228/90063250-b22dfd00-dcae-11ea-99ba-5e09dcce5cfa.png)

Note how normal text fields seem fine, but checkboxes are not checked properly.

**Comment by grahamsinger** [comment]
Fixed with OC revision 25942.
