### ISSUE TITLE
Search Results Navigation In Stage Requires Refresh to Re-Sync Collaboration

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2225]
**Creating this issue before the collaboration commit causing this issue is in trunk.**  
When navigating using the search results from within stage the stage view is destroyed and a new one is created. A race condition occurs where the previous stage view is cleaned up after the new stage view is initialized. This causes the stage collaboration socket to be closed until a refresh occurs. Either how stage is cleaned up within the stage router or collaboration needs to change to accommodate this. Linking collab enhancement:  #2198   

![navigate search results from stage](https://user-images.githubusercontent.com/54869173/90068944-210f5400-dcb7-11ea-8208-64a62bee249c.png)

**Comment by gsteimer** [comment]
Guessing that the best way to handle this is to make the navigation _not_ refresh the stage?

**Comment by abrown45** [comment]
Navigation goes through the stageRouter to rebuild stage so that could be the case. Not sure if its captures the case of search results coming from different tracs or if it would be easier to just refresh the VAD pane or whatever the current action is.

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-64
