### ISSUE TITLE
Saved Search Dashlet Show Documents link not working on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2227]
The new "Show Documents" link that can be added to Saved Search Dashlets that return AW forms is not working on Alfresco.  The error in the console is:

![image](https://user-images.githubusercontent.com/1377228/90172748-0f868480-dd69-11ea-92bd-78fc1dbdf82b.png)

**Comment by astocks7** [comment]
SAVED SEARCH DASHLETS ALFRESCO BUG: The enhancement from OCMS rev #25713 was not working for Alfresco. The jquery selector did not like all the characters in alfresco ids, so the fix is to use the form name instead.

OCMS revision 25737
CR: nwoodbine, aking
