### ISSUE TITLE
Facets with Pagination can break when on last page in Thumbnail View

### ISSUE THREAD

**Issue by Kovacinski** [tsgrp/HPI#2235]
If a user is applying Facet filters in Thumbnail view, navigates to the last page, and then removes the facet filter for the documents on the last page, then filtering will not work:
![FacetFilterThumbnailIssue](https://user-images.githubusercontent.com/7279444/90655570-58c25280-e207-11ea-8812-483e422a3388.gif)

The console error thrown is:
![image](https://user-images.githubusercontent.com/7279444/90655659-7099d680-e207-11ea-88ea-68ceee5f1d58.png)

Likely an issue with slick grid pagination

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-48
