### ISSUE TITLE
Zoom creating meeting should continue, even if creating the recording object not working

### ISSUE THREAD

**Issue by sambelcher1** [tsgrp/HPI#2236]
There is an error on some documents when trying to create the related object for the meeting recording. This is causing the zoom meeting to fail, which shouldn't be the case.

If there is an error while creating the meeting recording object then it should log an error for that but not fail the entire zoom call. The call should still be created and put into the chat.

Example doc on edge that it fails on: https://edge2.tsgrp.com/ocms/Stage/controlleddocs/workspace://SpacesStore/50d0a315-89a0-4e86-9457-ab80d4619728%7Cworkspace://SpacesStore/2e2bbe28-4cee-4547-a1a4-9026c0a850f1

Only an issue with Controlled Docs

**Comment by gsteimer** [comment]
Note that this isn't based on trac per se - it's because the trac that's failing is Controlled Docs.  The underlying issue is the restrictive permissions that Controlled / Quality docs contain.

**Comment by sambelcher1** [comment]
ZOOM MEETING RECORDING FIX - Fixed an issue with creating meeting recording object. We were grabbing all of the properties from the document and setting them on the recording object when it was created. This causes issues in controlled docs because there are some system properties that Alfresco will take care of, we don't want to touch them. To solve this, we now filter out any property that begins with "sys_" and let Alfresco set that on the object.

This is a pretty alfresco specific solution. Other repositories might not have properties that have that same sys_ prefix, or they might have them and we don't want to filter them out. Currently the zoom meeting recordings only works on Alfresco so we will have to check this again whenever its implemented in other repos.

OC REV#: 25981
 
CR: aking, mbrouillette
