### ISSUE TITLE
Add the ability for the Admin to Manage Content Templates

### ISSUE THREAD

**Issue by CRdouglas** [tsgrp/HPI#2242]
Add a tab and configuration options for the content templates that mirrors the ftl templates. Combine unnecessary duplicate files.

**Comment by CRdouglas** [comment]
FREEMARKER TEMPLATE: Adding the templatemanagementtabtitle.html to the commit. This wasn't added in the last commit.

- Code consolidation
- additions to make the id more specific

Github: https://github.com/tsgrp/HPI/issues/2242

UNIT TESTS to come.

CR - skovacinski dgrumieaux

Updated to include the templatemanagementtabtitle.html
Revision fixed: 25772

**Comment by gsteimer** [comment]
There are a number of issues with the functionality as is:

- [ ] CSS is slightly off (see images below)
- [ ] Existing Content Templates do not show up properly in the admin.  Seems to be an issue of template type `content` vs. `Content`.  We should be consistent in capitalization.  How do capture templates look?
- [ ] No way to set the name of a template upon import or when versioning
![image](https://user-images.githubusercontent.com/1377228/91181927-243f1280-e6af-11ea-8c37-c1b8ef032888.png)
- [ ] Versioning a template -  It looks like we're using an incorrect view here.  There's no need for the `content` section and there's no modal header
![image](https://user-images.githubusercontent.com/1377228/91182271-931c6b80-e6af-11ea-9788-d9fe0e468026.png)
- [ ] Curious that the title and description fields show up red when there's no text.  These aren't required fields, should they be red?  Perhaps a question for @iwhitingTSG

**Comment by CRdouglas** [comment]
FREEMARKER TEMPLATE: Adding functionality to the template management admin. Changing the functionality of the modals and adding configurations for content and ftl templates.

- Added ability to configure readonly and require props
- Changed Content to content to be consistent
- Changed styling to match other modals
- Fixed Content logic
- Added Tsgtemplatetype drop down for content

Github: https://github.com/tsgrp/HPI/issues/2242

UNIT TESTS to come.

CR - skovacinski dgrumieaux

REV: 25861
