### ISSUE TITLE
Claims API Allow hideHeader=true behaviour

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#2254]
Right now, the claims API/router does not keep the parameter hideHeader=true if it is provided. We should blindly just pass on any parameters in the URL to allow the header to be hidden for customers that want to keep the header off when integrating to their claims OS.

Ex: http://servername.com/ocms/claim?claimNumber=143500&claimantName=Homer%20Simpson&lossDate=2020-05-15&policyYear=2019&policyNumber=A005143&policyHolder=Homer%20Simpson&hideHeader=true

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-46
