### ISSUE TITLE
OpenContent: For REST Claim API, Make Claim Creation Path Configurable

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2258]
## Enhancement
Currently the REST Claim API has a base file path to create new claims as a constant pointing to `/Claims`. We should make this base location configurable although PAAS uses the `/Claims` location. Code is found in `5.insurance`.

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-45
