### ISSUE TITLE
Subscription Lists Refactoring 

### ISSUE THREAD

**Issue by astocks7** [tsgrp/HPI#2261]
Referring to #2252 and #2260. There is some room to refactor the common subscription/notification logic between the two commits tied to these issues.  A good approach would probably be creating a `NotificationUtil` or something that can be extended by both the alfresco class and the hbase class that need the notification logic.

Aside from refactoring there are a couple other minor enhancements that can be made.
- ~~wrapping the subscription action executer in a `runAsAdmin` block~~ (creating separate issue for this #2262)
- adding cheater values for the distribution lists properties into the alfresco dictionary like we did for the subscriptionUsers property

**Comment by gsteimer** [comment]
@aviking - the item around the `runAsAdmin` block should be a separate issue.

**Comment by astocks7** [comment]
Opened #2262 for the `runAsAdmin` issue

**Comment by astocks7** [comment]
NOTIFICATION LISTS ENHANCEMENTS - the recent commits for distribution lists and subscription lists share some common logic; this commit refactors that logic out into util methods. Also added cheater values to the alfrescoEmb dictionary for the distribution lists properties.

OC rev 26101
CR: aking, ballen
