### ISSUE TITLE
Content Templates - No option to change target type after creation

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2264]
When creating a content template, the admin specifies a target type:

![image](https://user-images.githubusercontent.com/1377228/92501821-a60d6080-f1c4-11ea-8bbb-82a6a10e0062.png)

However, after creating the template, there's no way to change the target type:

![image](https://user-images.githubusercontent.com/1377228/92501879-b9203080-f1c4-11ea-8a91-b72347bae8bb.png)

We should add the target type dropdown to the `Version Template` screen to allow this behavior

**Comment by jlittle-tsg** [comment]
Completed in OCMS Revision 25351

------------ Commit Log ------------

CONTENT TEMPLATE ADMIN - making the following UI enhancements to the template admin
1. performing validation on template document, name and target type on upload.
2. changing the order of the form fields for the version and add document templates.
3. allowing a user to change the object type of a template when versioning/editing.

Related Issues:
https://github.com/tsgrp/HPI/issues/2383
https://github.com/tsgrp/HPI/issues/2384

CRs: dvora, aking
