### ISSUE TITLE
Remove configurations from config-project.js that can change between environments - Phase 2 

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#2271]
We need to get to a point where the same `ocms.war` can be deployed to any environment.  This is especially important for when OC is configured for Alfresco, so we should start with repo-agnostic items or anything that is used in the Claims and PnP Accelerators. 

When moving items to the admin, we should provide sensible defaults wherever possible.  This should be in the case when creating a new config OR when a value is `undefined` (which will be the case for existing configs).

See phase 1 GH Enhancement: https://github.com/tsgrp/HPI/issues/2172

This may not be an exhaustive list, so we should analyze other areas that may utilize `config-project.js`.

- [ ] `otcConfig` / `adHocAttrsEnabled` - can this just go in OTC config in the admin?
- [ ] localizations - there are a few places where localization values are stored in the config-project.  These should all be removed and controlled just like any other localization.  If needed, an admin config can be created (not sure why we'd need this though)
- [ ] `documentsPopulatorConfig` - I think this is the same as the last one, but not sure
- [ ] `var config` - we need to analyze what can go in here - what will be static across _every_ deployment and what will need to get pulled out into the admin.  Easy items to say we need to pull out are the action specific configs in here.  For example, there's no need to configure the `sendsmartcomm` server here when it can be in the action config.

Need to talk through these to see what makes sense.  If we can say that all alfresco environments will never have these changed, then they're likely fine to stay:

- [ ] `adminSearchToolConfig`
- [ ] `metadataPositionAttr` - although I'd think this would be easy to factor out into the admin somewhere

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-43
