### ISSUE TITLE
Enable support for SSO and direct login in the same environment

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#2273]
Currently, SSO is an all-or-nothing configuration option for an ACA environment. This enhancement would allow for users to log in either using SSO or direct login. This would make it easier to allow external users to access OCMS (ie a TSG team member logging into a customer's environment) when SSO is enabled.

Related to #2272

**Comment by gsteimer** [comment]
Bumping priority since this should definitely be considered for the 3.5 release

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-42
