### ISSUE TITLE
Stage Collaboration Phase 2 - MS Teams

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2286]
With #2198 finished, it would be great to get MS Teams integration work for phase 2.  Starting a MS teams call would show up as another option here:

![image](https://user-images.githubusercontent.com/1377228/93618565-0fe3f200-f99d-11ea-9fc3-aa9130c2f2be.png)

**Comment by abrown45** [comment]
TEAMS COLLABORATION OPTION IN STAGE - adding teams to join zoom as an option for meeting while in stage viewing the same folder. Updated some zoom functionality to be cleaner. Added some additional changes to stage and socketmanager to assist with unit testing. Unit tests completed for teams collaboration. One following commit will add some missed coverage in files not modified here.
GH: https://github.com/tsgrp/HPI/issues/2286

CR: dvora, nengerer, jlittle
