### ISSUE TITLE
Full Text Searching against Solr Direct Not Working

### ISSUE THREAD

**Issue by CRdouglas** [tsgrp/HPI#2301]
`2020-10-02 08:09:35,530	ajp-nio-8709-exec-10	ERROR	SolrSchemalessQueryImpl	OpenContent Error: Error from server at http://tsgdemosolr2:8983/solr/portal: org.apache.solr.search.SyntaxError: Cannot parse ' AND * AND (objectType_s:("D_aw_qualityDocument")) ': Encountered " <AND> "AND "" at line 1, column 1.`

It looks like the query is malformatted when searching on just a `*`. This is not the case when searching on a `*` and another property. 

![image](https://user-images.githubusercontent.com/11527501/94931337-446fa780-048d-11eb-927e-2565b1421401.png)

**Comment by gsteimer** [comment]
Upping the priority.  On edge4, it seems that _any_ full text search is failing.

**Comment by abrown45** [comment]
@aviking confirm elastic search is still working properly

**Comment by abrown45** [comment]
### Findings
The issue appears to be tied to AbstractLuceneQueryImpl.java. This is used by both elastic search and solr query impls. At least for edge 4, the first search parameter passed is the full text parameter. At line 574 another check needs to be added to check if the query string is empty. If the query string is empty (meaning fulltext is the first parameter parsed) do not append the "AND" from line 575.

**Comment by abrown45** [comment]
Closed with Commit 26286
SOLR FULLTEXT QUERY - adding an additional check to building up the query string when a fulltext parameter is passed. if the query string is empty we do not want to add an AND before out full text logic. Adding check to another area that uses the same logic.

CR: aking, ballen
