### ISSUE TITLE
Boolean False Properties not displayed correctly in Radio Button Form Controls

### ISSUE THREAD

**Issue by cheinz-tsg** [tsgrp/HPI#2304]
![radioButtonFalse](https://user-images.githubusercontent.com/54864840/94970415-3d1abf00-04ca-11eb-8ae2-e6efb80354f8.gif)

As seen above, property values set to ```true``` correctly display as the "Yes" radio button, but ```false``` values do not display at all (should display as "No"). This is likely due to some null/empty value checks in OCMS that don't treat ```false``` as a valid property value.

**Comment by abrown45** [comment]
Check out OCMS commit 25795 as a potential buggy update

**Comment by cheinz-tsg** [comment]
Closed with OCMS Commit #26039

Several ```!control.value()``` checks throughout formsupport were updated to treat boolean ```false``` as a valid value. Also, the version of knockout OCMS uses does not support comparison on booleans, so an additional variable was created as a workaround so that knockout can compare on stringified booleans while the value used/sent to OC remains a regular boolean.

**Comment by cheinz-tsg** [comment]
Boolean values now display correctly in radio buttons, but validation for required fields fails. 
![image](https://user-images.githubusercontent.com/54864840/95589362-4516b980-0a0a-11eb-9fab-866bcd842006.png)

No matter which radio button is selected, the validation failure message appears. This happens because the radio button form control uses an external validation library that expects string input.

**Comment by cheinz-tsg** [comment]
Moving the validation but to its own GH issue.
