### ISSUE TITLE
Radio Button Validation Fails When Property Type is Boolean

### ISSUE THREAD

**Issue by cheinz-tsg** [tsgrp/HPI#2309]
Boolean values now display correctly in radio buttons, but validation for required fields fails. 
![image](https://user-images.githubusercontent.com/54864840/95589362-4516b980-0a0a-11eb-9fab-866bcd842006.png)

No matter which radio button is selected, the validation failure message appears. This happens because the radio button form control uses an external validation library that expects string input. 

Since OCMS Commit #25795, boolean properties have used underlying boolean values (instead of stringified booleans) in the form support module.

_Originally posted by @cheinz-tsg in https://github.com/tsgrp/HPI/issues/2304_

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-40
