### ISSUE TITLE
Some New Admin Sliders Are Not Taking Effect

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2312]
As part of the effort to move from iOS sliders to material design (see #2162), it seems that some of the new sliders are not taking affect when switched on.  For example, when flipping this slider on:

![image](https://user-images.githubusercontent.com/1377228/96472304-ef09f900-11f5-11eb-8532-bb2a42370b13.png)

Doesn't actually cause the left side to be hidden.

We had similar issues with doc viewers (see this issue - #2290) so I'm wondering if the same thing is going on here.

We'll need to check all of the other sliders that were converted as part of #2162 as well to check for similar issues.

**Comment by abrown45** [comment]
The sliders default to boolean true and false which are different than string true false that some ko variables use

**Comment by gsteimer** [comment]
Also - some sliders are defaulting true even though the settings are either undefined or `false`.  For example, here's the stage config for a stage config that hasn't been touched in a long time:

![image](https://user-images.githubusercontent.com/1377228/102387979-b8065880-3f96-11eb-9591-36533c81b69c.png)

This trac (`digitalAssets`) pre-dates the DICOM viewer, so I'd expect that slider to be false.  Same thing for PDF.js since AEV is configured on for this trac.

**Comment by nreiman** [comment]
01/04/2021 - Updated all default slider values to be correct (added in null checks). Still need to test values are translated properly (boolean vs string).

**Comment by nreiman** [comment]
01/04/2021 - Updated all sliders to have default values (booleans), fixed issue where sliders that had values that were strings were causing issues w/ new sliders that were expecting booleans. Still need to do some quick tests to make sure the values set for each slider in admin actually take affect.

**Comment by nreiman** [comment]
OCMS Rev: 26289
CR: dvora, nengerer

**Comment by nreiman** [comment]
Missed a few files in the commit. 
OCMS Rev: 26290
CR: dvora, nengerer
