### ISSUE TITLE
Enhance OCMS to send audio/video files to OpenAnnotate

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#2313]
OpenAnnotate now contains OAV embedded within it by default. Therefore, the integrations should no longer need to send the audio/video files to a separate application.

**Comment by gsteimer** [comment]
@dhruvvora94 - this effort will include changes to the Admin doc viewer config, correct?

**Comment by dhruvvora94** [comment]
Yes, should remove all signs of OpenAnnotateVideo being a separate application - that includes removing it from the docviewer configs.

**Comment by diyarab** [comment]
Completed in OCMS Revision #26085

SEND VIDEO/AUDIO FILES TO OA - this commit allows OCMS to view video and audio files through OA. OA has OAV embedded within it by default, so there is not need to send audio/video file to OAVideo. Unit tests were updated to reflect the changes.

CRs: dvora, aking
