### ISSUE TITLE
Enhancement: Allow Uploading a Document for Complete Review Action

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2320]
## Enhancement
This enhancement is to improve the complete review task. This will allow the user to attach a document to the form as an substitute or in addition to the comments section on the form. The document will receive a relation linking it to the document under review for both alfresco and documentum. The name of the document will be configurable based on properties from the workflow form and the current date. This feature can be configured on or off.

**Comment by nreiman** [comment]
Documentum Relation Name: 
aw_rel_comments_document added to "Active Wizard" project. Not yet committed. Currently only deployed in TSGDEVDCTM4.

**Comment by abrown45** [comment]
Closed with commit 26201
COMPLETE WIZARD REVIEW ROUTE ENHANCEMENT - adding the ability to upload comment documents to the completewizardreviewroute action. This is configurable in the admin defaulting off. The uploaded attached documents will receive a relation linking to the form aw_rel_comments_document/aw:relCommentsDocument. They can then be displayed and viewed in the related object section of stage or searched upon. This commit also introduced two new util files. One UploadAttachedDocWithRelation: this utils out the upload/rollback of those documents and applying the relation. this can be extended by manageadhocdocuments in the future and other actions with attached docs. Second is DragDropToUpload: this is a util file providing a model to hold the files and filenames of the uploaded files as well as two views for the drop-zone area and the file-list area. this can also be used by manageadhocdocuments as well as bulk upload and other actions in OCMS. I tried to make these as dynamic as I could but additional configurations and features can be added. Unit tests were not fully completed for this feature. completewizardreviewroute and dragdroptoupload views still need to be unit tested. 
GH: https://github.com/tsgrp/HPI/issues/2320

CR: nreiman, nwoodbine, rsaladrigas

**Comment by nreiman** [comment]
Small bug fix: 
COMPLETE WIZARD REVIEW ROUTE ENHANCEMENT - Fixing issue where comment "See attached supporting doc(s) w/ additional comments." was not being added to the "Review Review Task Completed" audit comments (when 1 or more comments doc is attached) due to an issue w/ the if statement. 

CR: skovacinski, abrown
