### ISSUE TITLE
Manage Ad Hoc Documents Remove from Upload Not Removing Documents

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2324]
## Issue
The manage ad hoc document action does not allow you to remove items from the upload list although it seems the functionality was intended to do so. If you accidentally select an incorrect file removing that file from the upload list does not remove it from the underlying object sending the upload. Additionally if you add another document after removing one all the previous uploaded files appear. See video detailing this second scenario:

![Alfresco Content Accelerator - Google Chrome 2020-11-10 11-12-14](https://user-images.githubusercontent.com/54869173/98709046-7c4cf300-2347-11eb-976e-d0c0b3584c77.gif)

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-39
