### ISSUE TITLE
Active Wizard Form - Header Padding Missing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2329]
See the screenshots below.  Something has changed in the header or the AW form so that all the padding at the top is missing:

### Edge2:
![image](https://user-images.githubusercontent.com/1377228/99850907-d3bb4200-2b43-11eb-9a35-db834fe56544.png)

### Release2:
![image](https://user-images.githubusercontent.com/1377228/99850876-c736e980-2b43-11eb-946b-fa112532da22.png)

**Comment by renesaladrigas** [comment]
REMOVE HEADER: Correcting the active wizard form styling to apply a margin between the content and the header. This resolution relates to revision 26138 of this repository.

CR: abrown, gsteimer

Revision 26169.
