### ISSUE TITLE
Actions' Use of Delete Objects Endpoint Out of Date

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2331]
### Potential Issue
After testing use the `content/deleteObjects` endpoint with old ACA code, I noticed the functionality was not working as expected. The error for these requests is logged to the console which I feel is often missed. Additionally since this is a rollback function it may not have been tested properly. Below are functions that could always error. An example of the up to date use can be found in `manageadhocdocuments.js#removeAdHocDocuments`

##### Offenders
- [ ] `capturetemplate-new.js#deleteTemplate`
- [ ] `awtemplate-doc.js#deleteTemplateFromBackend`
- [ ] `bulkupload.js#_deleteUnusedTemp`
- [ ] `bulkupload.js#deleteIndexedObjects`

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-38
