### ISSUE TITLE
Content Templates are Deleted After First Use in Bulk Upload if user has DELETE access to template

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2344]
Note - sample quality document templates are in `HPI\trunk\demo-docs\Quality Docs`

Steps to re-create:

1. Create a template in the template admin.  Example - `Policy Template` for type `Quality Document`
1. Use the template to create a new Quality Document from the Add Quality Doc header action on edge2
1. After creating a document, the template is deleted

**Comment by gsteimer** [comment]
It looks like this is an issue with Bulk Upload and the BHUDI.  It deletes the template even if I don't go forward with the actual document creation:

![template-disappear](https://user-images.githubusercontent.com/1377228/102131053-3fc55900-3e17-11eb-816e-66d583854bee.gif)

**Comment by gsteimer** [comment]
Doing a little more digging, I think the problem is only encountered when Bulk Upload is configured as a header action.  Templates seem to work fine when in the stage:

![template-doesnt-disappear](https://user-images.githubusercontent.com/1377228/102131316-a64a7700-3e17-11eb-8433-6078def36383.gif)

**Comment by gsteimer** [comment]
Looking at the dev tools, it seems that a call is being made to `deleteObjects` when the modal is closed.  This is likely trying to delete the "temp" file that is uploaded for the Bhudi, but since Templates do not get that "temp" file, it's deleting the template itself.  @benallenallen mentioned that @dhruvvora94 added this delete call recently.

![image](https://user-images.githubusercontent.com/1377228/102387132-a1133680-3f95-11eb-83e1-3e5c4b70fab8.png)

However, that doesn't explain why this isn't happening in the stage.

To fix this, my guess is that we should somehow flag templates so that the delete does not occur.  We should also test to make sure that nothing breaks with other bulk upload object types:

- [ ] Scanned documents
- [ ] Generated Cover Page
- [ ] Import from Box
- [ ] Import From Gmail
- [ ] Pending Print Documents

**Comment by gsteimer** [comment]
This issue is now breaking STS.  Not sure why this wasn't happening before, but it seems that the templates _are_ being deleted when creating a document from a template while in the Stage.

**Comment by gsteimer** [comment]
@dgrumieaux figured it out - the reason the STS is working most of the time is because the STS user doesn't have permissions to delete the template.  If the user that creates the template attempts to use it, it fails

**Comment by newmanju** [comment]
Closed in OCMS SVN revision 26341:

BULKUPLOAD DELETES CONTENT TEMPLATES: This commit fixes an issue where content templates were being deleted after the bulk upload screen (BHUDI). The fix is to check if the object type for each file being uploaded is of type "tsgTemplate" and if so we add it to an array of content template ids. When deleting temp files after bulk upload, we now make sure the id does not exist in this array of content template ids before calling the delete endpoint.

CR: aking, skovacinski
Unit Tests: jlittle, skovacinski
