### ISSUE TITLE
Bulk properties do not get propagated if a repeating form field is tied to an OpenContent picklist

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#2348]
If the form field is tied to an OpenContent picklist then the values do not get propagated from the bulk properties page. If they are tied to a simple picklist then everything works as expected. 

Bulk properties page with tags set - 
![image](https://user-images.githubusercontent.com/9989329/102558794-dd2cc100-4093-11eb-8172-54cd736195cd.png)

First document with tags empty - 
![image](https://user-images.githubusercontent.com/9989329/102558837-f9306280-4093-11eb-9113-90f84bc4a0af.png)

**Comment by gsteimer** [comment]
@dhruvvora94 - I just tried this on edge2 and it works fine.  Could this be a configuration issue in your setup?  I can't imagine that this would be a back end issue, but perhaps it's an Alfresco vs. another ECM issue in OC?

### Bulk Props
![image](https://user-images.githubusercontent.com/1377228/102623969-f1f76c00-4108-11eb-9e77-89f80272027c.png)

### First Document - all props inherited as expected
![image](https://user-images.githubusercontent.com/1377228/102623988-fa4fa700-4108-11eb-9bd9-1f2e9f9980b8.png)

### Doc Types Picklist is an OC Picklist
![image](https://user-images.githubusercontent.com/1377228/102624439-a2fe0680-4109-11eb-9d35-f55a95019fd1.png)


### Doc Subtype is an OpenContent Picklist (and cascading)
![image](https://user-images.githubusercontent.com/1377228/102624311-70eca480-4109-11eb-8c5e-28fc2c4f88e0.png)

**Comment by dhruvvora94** [comment]
This issue was fixed in the client branch by bringing in the fixes that were made as a part of the commit for https://github.com/tsgrp/HPI/issues/2079
