### ISSUE TITLE
Folder Notes: Creator/Author conflict if non-mandatory aspect author is on HPI Note

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2349]
### Issue
Creator and Author conflict due to their shared label "Author". Proposed fix is to change Creator back to creator and author remains author. The below image shows creator is missing from the picklist if cm:author is on the OTC.

![image](https://user-images.githubusercontent.com/54869173/102900212-93483000-4431-11eb-82b1-61b9ab07104c.png)

**Comment by gsteimer** [comment]
@abrown45 guessing this is only a problem on Alfresco?  Feel free to remove the label if that's not the case

**Comment by abrown45** [comment]
@gsteimer Should be all envs but not sure if author is an Alfresco only property.

**Comment by gsteimer** [comment]
Guessing we'll need to check the "cheaters" in all envs to make sure

**Comment by abrown45** [comment]
since author is not a cheater, use OTC to find user name fields and filter then to display name if configured to do so

**Comment by abrown45** [comment]
FOLDER NOTES TABLE - Author and Creator are not displaying properly ; Document list attribute not sorted properly within the note. This commit fixes an issue with Creator/Author properties in the folder notes table. Previously, the label for creator was Author. These labels have been switched back to their OTC configured labels. Additionally, these fields now rely on the HPI Note OTC to determine their filter for display. To keep everything displaying as it currently is, update the filters on desired attributes in the OTC. To update the label in older configs, remove Author and Creator labels from the toss across, save, and reload. The attributes will be displayed appropriately. Additional, the sorting of the document list attribute for each note was suppose to keep them alphabetical. This commit fixes that sort to make them alphabetically listed.

CR: nwoodbine, mwojno, rsaladrigas, skovacinski, gsteimer 
GH: https://github.com/tsgrp/HPI/issues/2349, https://github.com/tsgrp/HPI/issues/2353

**Comment by abrown45** [comment]
Leaving this open until I configure edge/release @gsteimer

**Comment by gsteimer** [comment]
@abrown45 if Edge looks good, go ahead and close this.  You don't need to wait for a release build.
