### ISSUE TITLE
Chain Versionable Documents Cannot Version Past X.9

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2358]
If you version a document to `0.9` and try to check in a new version, the next version should be `0.10` and be both LATEST and ACTIVE.  However, what actually happens is you get a duplicate `0.1` version and the ACTIVE and LATEST flags are set incorrectly.

You can see this on edge2 by looking at document `TSG-139`

***Version 0.9***
- `workspace://SpacesStore/3f6993d3-b485-480e-be4f-98de41ce504a`
- `isActiveVersion` - true (should be false)
- `isLatestVersion` - false

***Version 0.1 (should be 0.10)***
- `workspace://SpacesStore/abf52a26-7aee-4291-8671-922681b991f4`
- `isActiveVersion` - false (should be true)
- `isLatestVersion` - false (should be true)

Note - I only tested with 0.x versions, but we should also test with 1.x as well since the active flag is handled differently (it sticks on 1.0 until 2.0 is created).  `0.10` should be both active and latest when it is created, whereas `1.10` or `2.10` etc. should be latest, but not active.

**Comment by gsteimer** [comment]
Forgot to attach a gif I took of this happening:

![x-10-issue](https://user-images.githubusercontent.com/1377228/105433063-82503180-5c1e-11eb-90c5-8400a7e38b8f.gif)

**Comment by gsteimer** [comment]
Here are the scenarios we should test:

- [ ] `0.9, active, latest` -> `0.10, active, latest` -> `0.11, active, latest`
- [ ] `1.9, latest` -> `1.10, latest` -> `1.11, latest`
- [ ] `9.0, active, latest` -> `9.1, latest` -> `10.0, active, latest`
- [ ] We don't need to test `100.x`  or `x.100` directly, but we should be reasonably sure this will work by tracing through the code

**Comment by dhruvvora94** [comment]
Closed with trunk OC commit 26751 

UPDATING CHAIN VERSIONABLE - Updating the chain versionable dependency and making sure that we are able to handle documents that have 2 digit minor versions. 

CR - mbrouillette, dgrumieaux

Corresponding CVN amp commit 10463
