### ISSUE TITLE
ACA PaaS PnP: Wizard Admin and Wizard Action's Authentication Fails if User is a Synced Account

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#2368]
## Overview
- Often times customers will have synced user accounts in ACA from their business's active directories. These users are active and valid within ACA.

- However, authentication fails when a synced user (with correct permissions) tries to login to the Wizard Admin or on wizard actions where authentication is enabled.

## Steps to Reproduce
- In a local Alfresco environment, use our own AD to simulate syncing user accounts.
- Next, try to login to Wizard Admin.
- Check the wizard actions that are listed below to see how authentication fails with a synced account. 

## Ideas About Solution
- I would check during authentication if we are just skipping the authentication and returning nothing if a synced user account is encountered. 

- These are the Wizard actions that should be tested to close this issue:
- [ ] Wizard Admin Login
- [ ] Obsolete Document
- [ ] Power Promote
- [ ] Perform Periodic Review
- [ ] Complete Approval

**Comment by gsteimer** [comment]
We've had multiple other customers use synched accounts with Alfresco ACS and ACA / Wizard functionality without issue.  Could something else be going on for PaaS?

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-33
