### ISSUE TITLE
Tableview - On Property Update, Field Formatting is Broken

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2369]
## Issue
When a user submits a property change from table view (VAD and search), the row is updated with the new properties. These properties lose their formatting, easily spotted when other results surround the updated row. See screenshot.
![image](https://user-images.githubusercontent.com/54869173/108724300-cc148c00-74ea-11eb-9dd0-da51f1f65434.png)

**Comment by Kovacinski** [comment]
Fixed with revision: 26531
