### ISSUE TITLE
Content Template Admin Does not validate fields properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2383]
When adding or modifying a content template in the admin, the UI should validate that the following fields are filled in properly:

- Template document provided for upload
- Template Name
- Target Type

In the current UI, all of the above are optional.

**Comment by jlittle-tsg** [comment]
Now performing validation when creating a new template with OCMS Revision 25351. Leaving this open as we are not doing any validation when modifying a template.

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-63
