### ISSUE TITLE
Content Template Admin - UI Improvements

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2384]
The current UI for adding and modifying content templates could use some improvements:

![image](https://user-images.githubusercontent.com/1377228/110965033-70833480-8319-11eb-8645-e09a82c99114.png)

This screen should be ordered from top to bottom to correspond with the user journey through this action.  This should flow in the following order:

1. Specify document to upload (ideally allow drag and drop as well as a browse button)
1. Set Target Type
1. Set Template Name (defaults to the document name that the user is uploading)
1. Set Title and Description (optional) 

The Edit template screen should follow a similar structure:

![image](https://user-images.githubusercontent.com/1377228/110965384-bfc96500-8319-11eb-92d9-cd10969de6b9.png)

**Comment by jlittle-tsg** [comment]
Completed in OCMS Revision 25351

------------ Commit Log ------------

CONTENT TEMPLATE ADMIN - making the following UI enhancements to the template admin
1. performing validation on template document, name and target type on upload.
2. changing the order of the form fields for the version and add document templates.
3. allowing a user to change the object type of a template when versioning/editing.

Related Issues:
https://github.com/tsgrp/HPI/issues/2383
https://github.com/tsgrp/HPI/issues/2264

CRs: dvora, aking

**Comment by gsteimer** [comment]
Re-opening this one.  This is a good start, but I think we could improve the file selection UI:

- [ ] UI cleanup / styling
- [ ] Make Content Template the first tab that loads when the user clicks "Template Management" on the left side
- [ ] Rename the "Version Template" button to something that makes more sense - Perhaps `Manage Template`
- [ ] Make it more clear that drag and drop is supported
  - TODO - I was actually surprised that Drag and Drop worked here.  Is it something we're doing or just Chrome being smart?  If it's the latter, we should make sure it works for other browsers as well.

For reference, here's how the wizard's File input looks:

![image](https://user-images.githubusercontent.com/1377228/111346739-81e77c00-864c-11eb-8c0e-45b4cd1d37fc.png)
