### ISSUE TITLE
Content Template Admin - Download Template button does not work

### ISSUE THREAD

**Issue by jlittle-tsg** [tsgrp/HPI#2389]
When attempting to download an existing template you'll get a server error. The object ID and content type is not being passed through the request correctly. 

![image](https://user-images.githubusercontent.com/54864788/111204851-851f3100-8594-11eb-928d-c47e70d8b199.png)

![image](https://user-images.githubusercontent.com/54864788/111204905-99fbc480-8594-11eb-8551-9002fb5e0b97.png)

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-61
