### ISSUE TITLE
Content Template Admin - Updated properties not reflected in version template form

### ISSUE THREAD

**Issue by jlittle-tsg** [tsgrp/HPI#2390]
Updating the Name, Title or Description of an existing template does not work correctly. The form should be updated with the new properties once saved.

![contenttemplateadmin](https://user-images.githubusercontent.com/54864788/111215032-a9810a80-85a0-11eb-85c3-346a5807e733.gif)

**Comment by gsteimer** [comment]
Interestingly, after a hard refresh, the template target type attr _does_ reflect the new value.  However, the template name, title and description are not saving properly:

![content-template-update](https://user-images.githubusercontent.com/1377228/111347055-d4c13380-864c-11eb-812e-60232aed0209.gif)

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-60
