### ISSUE TITLE
Reset button in search clears out hidden fields as well

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#2393]
Using the reset button in search will clear out the values from all the fields including hidden fields that might have default values. 

Since they are hidden fields - the only way to reset them would be to refresh the page.

**Comment by gsteimer** [comment]
Changing this to a 3.5 issue.  It seems like something that we should fix (and wouldn't be too hard)

**Comment by dhruvvora94** [comment]
Closed with ocms commit #26367

RESET VALUES - Making the "reset" button in search act like a reset instead of a clear. For autocomplete and dropdown fields - we will reset the default values. Enhancement needed in order to get default values working for dates. 

CR - abrown, nreiman
