### ISSUE TITLE
Dashlet User Preferences Appears Broken When Dashlets Do Not Allow Visibility Modification

### ISSUE THREAD

**Issue by abrown45** [tsgrp/hpi#2404]
## ~~Issue~~ Enhancement
Dashlet user preferences is broken for new environments running the 3.4 tag. Thinking the initialization of that view (or user preferences in general) is broken when no user preferences exist to start. Confirm user preference behavior in a new environment. This has been reported in multiple alfresco client environments. Not sure if other backends have the same issue. 
![image (7)](https://user-images.githubusercontent.com/54869173/113308230-958d1680-92cb-11eb-90a5-2d583caa14d6.png)

**Comment by gsteimer** [comment]
@abrown45 - I just checked on QA2 (which runs version 3.4.3) and it looks fine:

![image](https://user-images.githubusercontent.com/1377228/113319526-21f10680-92d7-11eb-9828-a6442e8a2836.png)

Could something be corrupt with the user's preferences json?

Or potentially could this be related to #1816 ?

**Comment by abrown45** [comment]
@gsteimer is QA2 a brand new alfresco for the 3.4 tag? Its possible there is a corruption but I am leaning more towards initialization of the user preferences. I dont think it is related to #1816 because the dashlets are still visible, just the user preference section is not visible.

**Comment by gsteimer** [comment]
@abrown45 hmm... no - qa2 was upgraded from ACA 3.4.2, but the Alfresco remained the same

**Comment by abrown45** [comment]
@gsteimer I can schedule something if you want to dig into it more together. Right now we are seeing this on a PaaS environment and on two separate client alfresco (newly installed 5.1.2). I dont want to limit it to only new alfrescos / no user preferences defined yet but that has been the trend so far.

**Comment by abrown45** [comment]
Relabeling as enhancement. While the feature looks to be broken, it is the case that no dashlets are configured to allow a user to toggle its visibility.  An enhancement is required to better display this scenario.

**Comment by abrown45** [comment]
OCMS Commit 26293
DASHBOARD DASHLET VISIBILITY USER PREFERENCES - update to the user preferences UI for dashlet visibility. if the user does not have any dashlets to modify the visibility on, they should see an message detailing the scenario. this is to improve the UI and fix an issue where the view looks broken in no dashlets allow visibility modification.
GH: https://github.com/tsgrp/HPI/issues/2404

CR: dvora, aking
