### ISSUE TITLE
Send Email Config Tooltip Not Working

### ISSUE THREAD

**Issue by abrown45** [tsgrp/hpi#2406]
## Issue
Cloud send's tooltip is not currently displaying on edge. See image
![image](https://user-images.githubusercontent.com/54869173/113781440-50ffe180-96f6-11eb-809a-82635e0da17f.png)

**Comment by gsteimer** [comment]
![image](https://user-images.githubusercontent.com/1377228/135515601-efa54829-573f-49e9-a007-12ff4e7289ae.png)

@abrown45 ^^^ edge2.  I also checked QA2 and it seems fine there.  Think we can close this one?

**Comment by gsteimer** [comment]
Closing since this seems to be fixed in trunk
