### ISSUE TITLE
Generate Cover Page: Repeated Attrs Breaking Props Table

### ISSUE THREAD

**Issue by abrown45** [tsgrp/hpi#2414]
## Issue
Repeated attributes when applied to a generated cover page in bulk upload break the ftl used to create and style the table. A fix is needed to properly iterate over those repeated attr arrays in OC.

**Comment by gsteimer** [comment]
@abrown45 - will fixing this also fix #2399 ?

**Comment by abrown45** [comment]
OC 26844
GENERIC HTML TEMPLATE - COVER LETTER FIX - the generic html template used to generate a table for a cover letter in ACA is not correctly processing repeating attributes. If a repeating attribute is included in the prop list, the table will fail to render. Adding additional check for a sequence and iterating over that sequence if present with comma separated values.
GH: https://github.com/tsgrp/HPI/issues/2414

CR: kgarelli, rvishweshwar, aking

**Comment by abrown45** [comment]
This does not change #2399
