### ISSUE TITLE
Migration enhancements for Policy and Procedures/CVN content

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#2416]
This enhancement will ensure that major versions can be migrated into Policy and Procedures and that custom version label numbers can be set on incoming migrated content.

Currently when working with chain versionable controlled documents into alfresco, there is not a way to use a custom version label (e.g. 0.001 instead of 0.1). We are also unable to make the initial version of a document a major version - the first version always comes in as 0.1 minor

We can fix this by making some updates to ControlledDocumentVersionPolicy.java to pull the custom version label off of an injectable node property. It is expected that the aspect from which the version label was pulled from is removed from the node after migrating to prevent it from getting continually reset.

**Comment by jlittle-tsg** [comment]
Closed with OC commit 26890

-----------------
CUSTOM VERSION LABELS - Updating ControlledDocumentVersionPolicy.java to pull a custom version label off of an injectable node property. It is expected that the aspect from which the version label was pulled from is removed from the node after upload to prevent it from getting continually reset. Also ensuring that logic to delete previous minor versions in TSGQualityDocumentBehaviors.java is not hit when the tsg:migrating aspect is applied.

CRs: dgrumieaux, aking

**Comment by jlittle-tsg** [comment]
Minor OC update (26920) that changes around the way we default injectables 

---------------
INJECTABLE UPDATES - changing around the way we default injectables in a couple of spots to prevent issues with resolving overridden injectables coming from a client amp. 

ControlledDocumentVersionPolicy.java - no longer defaulting versionAttrName to null (https://github.com/tsgrp/HPI/issues/2428)
AlfrescoEmbInternalRenditionImpl.java - creating a setter for renditionMimetype and injecting attr via bean (https://github.com/tsgrp/HPI/issues/2416)

CRs: aking, dgrumieaux
