### ISSUE TITLE
Make the Action "Edit Form" Open the Summary Page Instead of the First Page

### ISSUE THREAD

**Issue by newmanju** [tsgrp/hpi#2424]
Currently when a user clicks the action "Edit Form", the first page of the wizard form is opened. The change requested is to make the summary page open instead. This will allow for easier navigation and better usability for large, intricate forms with many pages.

**Comment by gsteimer** [comment]
@newmanju - can this be configurable in the action?  I.e. - open on the first page or in the summary?

**Comment by gsteimer** [comment]
Also - we definitely need to test to make sure this works properly for old forms created before the change goes in

**Comment by newmanju** [comment]
Closed with SVN Revision 26458:

Added a config setting to the "Active Wizard Forms" section of the admin settings. The configuration toggles whether the user should navigate to the summary page or not when the user resumes editing a form. The default behavior is to navigate the user to the first page of the form when editing resumes. 

**NOTE: No wizard config for a form will exist if it hasn't been viewed in the "Active Wizard Forms" section of the admin settings. In this case, the default behavior of navigating to the first page of the form is used.**

CR: dgrumieaux, aking
