### ISSUE TITLE
VAD Filter By dropdown showing filters from folder configured facets

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#2427]
See the screenshots below.  When your search config (ex: a case folder and case document) has folder and document types with different facet filters configured, the facets display correctly from search, but not in VAD.

### Folder type - facets correct in search
![image](https://user-images.githubusercontent.com/1377228/125495681-9583d92d-7727-466c-953a-857cd45f62eb.png)

### Doc type - facets correct in search
![image](https://user-images.githubusercontent.com/1377228/125495744-f66f8549-ac97-4e4d-8523-7f69ff473a35.png)

### VAD - facets are a combination of the configured folder and doc facets (should be just doc)
![image](https://user-images.githubusercontent.com/1377228/125495860-51fdfdd7-12a2-4f9d-8d6f-b84a3e777384.png)

It makes sense that VAD would combine filters if multiple document types exist (ex: multiple document types could exist in a single folder), but container types should be excluded from this list.

**Comment by Kovacinski** [comment]
Closed with revision: 26553
