### ISSUE TITLE
Compatibility with ACS 7.0.1

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#2432]
See: https://alfresco.atlassian.net/browse/MNT-22524

@dgrumieaux may have more info on this one as the linked Jira is light on details.  I believe a security update removed some jar files in ACS, causing issues in OpenContent.  The fix should be simply adding in the necessary jar files that OC requires.

**Comment by gsteimer** [comment]
Lets be sure to talk to Alfresco Engineering to make sure we don't add back in a jar that is no longer allowed due to the security updates.  I.e. - we don't want to undo their security update since that won't be allowed on PaaS.

**Comment by gsteimer** [comment]
We can move this one back to 3.4.3.3 if that gets released and we can get this fix in.  It may just need to change to 3.4.4.1 if 3.4.4 is released first.

**Comment by Kovacinski** [comment]
Fixed with OC commit 27007
