### ISSUE TITLE
When private notes are enabled, wrong default is selected when adding a note

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#2442]
When private notes are enabled in Folder Notes, the default note visibility should be public.  Screenshot from QA2 (ignore missing localization):

![image](https://user-images.githubusercontent.com/1377228/134540510-db9ce007-b75d-49de-94ca-be867b447e7f.png)

However, on edge (and release) the slider is turned on so the note default is private:

![image](https://user-images.githubusercontent.com/1377228/134540684-137b38f9-9010-47fa-9a13-79b6ee3b87d5.png)

We should flip that so that a note defaults to public visibility

**Comment by Kovacinski** [comment]
Closed with revision: 26555
