### ISSUE TITLE
ACA Collaboration integration not interfacing correctly with socket server

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/hpi#2453]
The ACA integration for collaboration is no longer interfacing correctly with the socket server after AEV upgrades to the versions of the socket.io packages.

This gif below shows how the calls made to the socket service are unintelligible to the socket server and produce a 400 error:
![aca_collaboration_400](https://user-images.githubusercontent.com/14186921/138465162-02a182f3-a035-4d40-9def-8684a2b25129.gif)

**Comment by gsteimer** [comment]
Moved to Jira: https://alfresco.atlassian.net/browse/SEP-58
