### ISSUE TITLE
Bulk Property Edit Group Action Broken

### ISSUE THREAD

**Issue by joehof** [tsgrp/hpi#273]
So I'm assuming this happened when we moved the Bulk Update buttons from the modal body to the modal footer. That didn't happen for Bulk Property Edit, and the action is now useless. No client is using right now, so not High Priority, but the second a client needs it this should be upgraded to High.

![image](https://cloud.githubusercontent.com/assets/4852255/2989417/ea1b14ca-dc63-11e3-850b-19df88acc494.png)

**Comment by aviking** [comment]
Fixed with Revision: 11488
