### ISSUE TITLE
Recent objects that don't exist still appear in dashlet

### ISSUE THREAD

**Issue by jrubins** [tsgrp/HPI#282]
In the recent objects dashlet, there is no check to make sure the objects that get displayed actually exist in the repository. Since the recent objects are stored in a cookie, if you switch from one repository to another or if a recent object gets deleted, the recent object still shows up in the dashlet even though clicking on it will cause some kind of navigation error (the deleted object is probably more an issue than ones sticking around from different repositories but the concept is the same).

In the below screenshot, the `Automatic Renditioning Test Folder` and `File Extension Test Folder` objects are from a different repository than the other two objects:

![recent_object_stick_around](https://cloud.githubusercontent.com/assets/971647/3067038/ef023138-e27d-11e3-9c2d-48e7347af027.png)

**Comment by gsteimer** [comment]
See #842
