### ISSUE TITLE
Bulk Upload - show more informative error messages

### ISSUE THREAD

**Issue by jrubins** [tsgrp/hpi#296]
When a document fails to upload through bulk upload, all the user sees is that the document failed to upload. It would be nice to get a more informative error message - especially if it's something the user could fix by retrying the upload (such as a document with the same name already exists in the folder [at least for Alfresco]).

In the GIF below (on Alfresco), the "Time Card.msg" document already exists in the folder so the upload fails and displays the error in OC but HPI just says the document failed to upload:

![bulk_upload_informative_error_messages](https://cloud.githubusercontent.com/assets/971647/3233379/8918cfa0-f0bd-11e3-97cc-2c2b556d8883.gif)

**Comment by aviking** [comment]
This issue was fixed. See https://github.com/tsgrp/hpi/issues/653.
