### ISSUE TITLE
Modals should display errors within the modal and not in an extra error modal

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#297]
Some actions use error modals, which end up displaying behind the action modal when fired.

This is how Send Email used to work:
![sendemailerror](https://f.cloud.github.com/assets/4852302/1976773/0a96c1d2-838f-11e3-9911-865bb7249edb.gif)

Instead of using modals for errors in these scenarios, we should instead display errors inside the modal themselves, and disable the submit button (if possible) until the form is fully validated. See how Send Email works now:
![image](https://cloud.githubusercontent.com/assets/4852302/3317704/0aa31c80-f710-11e3-83e6-cd5b0575b8e3.png)

First, an analyst will create a list of actions that should be updated to remove the error modal calls. Then, developer should:
- Create a standardized area in the action modal where errors will be displayed
- Create an event that will get triggered when the error div should show, and pass the error message that should display
- Modify the actions that use the error modal to use the new error div/event

**Comment by gsteimer** [comment]
@cmlewis - I'm thinking we can close this. Do you agree?

**Comment by cmlewis** [comment]
Yeah, haven't noticed any issues with this for a while.
