### ISSUE TITLE
OTC Admin - Hiding attributes does not change settings on attributes

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#306]
This is an issue if an administrator clicks the minus button to hide attributes and expects those attributes to have no effect across the application. This is what I would expect, but is not what happens.

Proposed enhancement would be to default all settings of the attribute to "false" and control type "NONE" upon hiding of an attribute via the minus button in the OTC admin.

**Comment by joehof** [comment]
@gsteimer I'm finally clearing out some old inbox items...I think we can close this with the new OTC that went in for Form Configs.

**Comment by gsteimer** [comment]
Sounds good to me - closed with Form Config updates for HPI 2.3
