### ISSUE TITLE
Ability to configure OC config root path in HPI build

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#308]
Currently, to change the path of the active HPI configs, a user must navigate to /adminClassic and change the OC setting of the base path of the configs. This has three downsides: 
- navigating to a deprecated, obscure page
- configurations are tied to OC's state, thus Jim and Joe cannot access different configs through one OC instance at a time.
- copying configs must happen in the repository's webapp

These downsides make changing the active configs and creating new copies of configs harder and more obscure than it should be.

Possible solutions would be:
- Add configuration options to store the config base path in HPI in the build
- Add ability to easily copy/change active configs

See #309 for an initial enhancement idea.

**Comment by gsteimer** [comment]
@dgrumieaux - guessing this can be closed
