### ISSUE TITLE
Package Management Enhancements and TLC

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#314]
HPI has not had its dependencies updated for many months. Would be worth investigation to see what benefits updating may give us, ie, grunt/karma upgrades.

Additionally, updating HPI Edge and dev builds to automatically update would help us incrementally keep up with updated dependencies. We want to always freeze versions on Release, however.

**Comment by gsteimer** [comment]
@dgrumieaux - can we close this with the recent updates to the build?

**Comment by dgrumieaux** [comment]
Closed as of a while ago. Reference issue: https://github.com/tsgrp/HPI/issues/1529
