### ISSUE TITLE
Document viewer is sometimes duplicated

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#324]
See the screenshot below - after checkin, sometimes the document viewer is duplicated and the doc appears twice.

![image](https://cloud.githubusercontent.com/assets/1377228/3378042/b4416768-fbe5-11e3-8065-666ff2b6a198.png)

**Comment by gsteimer** [comment]
Re-opening this... we definitely see this consistently when using import and then viewing the document before refreshing the page.  This is why the bulk upload confirmation screen refreshes the page rather than just sending the user to the document.


![doc-viewer-dupe](https://cloud.githubusercontent.com/assets/1377228/15946315/f6e811d4-2e5b-11e6-9456-9e918bea8065.gif)

**Comment by gsteimer** [comment]
This was fixed with the updates #1118.  @ZachGerth - can you make the bulk import confirmation links load the doc without refreshing the entire page?  Once that's in, we can close this issue.

**Comment by ZachGerth** [comment]
Finished with HPI Commit #15453.
