### ISSUE TITLE
Alfresco - Search does not do exact matches

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#335]
@zkeller added the proper search parameters for EQUALS, but we do not take advantage of it in the Alfresco query impl. Unfortunately, based on how attributes are tokenized in SOLR affects this.

**Current scenario:**
  1. Search an attribute called status, which is a dropdown. Search on the term "Released."
  2. The Lucene query generated looks like `@tsg\:status:"Released"`
  3. Expected results: Docs only with "Released" status
  4. Current results: Docs with both "Released" and "Released-Transmittal" statuses are returned. This is because the search seems to default to searching on tokenized values.

**Potential solution:**
In Lucene queries, we are supposed to be able to use a specific syntax to search on tokenized vs. non-tokenized values. The '@' sign searches on tokenized, and the '=' is supposed to search on the non-tokenized values, enabling us to get exact matches.

Example: `=tsg\:status:"Released"`

Unfortunately, the '=' syntax only works when using FTS instead of Lucene. We currently use Lucene for all of our searches. Group agreed to try to only use FTS when necessary - i.e. when the query contains an EQUALS parameter or when we want to avoid eventual consistency issues (like in collections).

**Comment by ladams13** [comment]
@dgrumieaux added a fix to this in the AlfrescoEmbQueryImpl for Alfresco 5.  Since we are updating the querying to FTS, if the search parameter has the equals operator (or not equals) on it, then we prepend an '=' prior to the field and value.  If it does not have the equals (or not equals) operator, then we prepend an '@' to the field.

I am working on testing it now.

**Comment by ladams13** [comment]
Fixed and committed, svn revision: 10610  

All searches are now FTS, thus using the '=' syntax for exact match searching
