### ISSUE TITLE
Race condition causes dates to not be formatted in slow environments

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#395]
A call to the "formatPropertiesReadOnly" method assumes it is synchronous, when it is not. In fast environments, this is not a problem, but in slower environments, it is readily apparent.

To replicate, use Fiddler or another network tool to slow network requests, and view a saved search dashlet that has at least one date field configured.

**Comment by gsteimer** [comment]
Calling this one done from @nwoodbine's latest commits
