### ISSUE TITLE
Support HTML5 Plug-in of Dynamsoft ICS

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#396]
By the end of 2014, Chrome is not going to support the Netscape Plug-in API (NPAPI).  See this blog from Google here: http://blog.chromium.org/2013/09/saying-goodbye-to-our-old-friend-npapi.html

Recently, Dynamsoft [introduced](http://www.dynamsoft.com/blog/web-twain-webcam/web-twain-html5-edition/) version 10.0 of the Dynamic Web TWAIN module that is driven by HTML5 so that DWT continues to work in Chrome after support for NPAPI is dropped.

Obviously, we should update OpenCapture to take advantage of the HTML5 version, but first - we need to figure out if the HTML5 version applies to the ImageCapture Suite (ICS) as well.

**Comment by CodyWatson15** [comment]
SCANNER.js Updated to Dynamsoft Version 12 allowing for the DWT object to use HTML 5 to scan in objects. Closed with Revision 16498.
