### ISSUE TITLE
OpenCapture IE Support

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#397]
Currently, the OpenCapture module within HPI is only supported with the Plugin Edition of Dynamsoft's ImageCapture Suite (ICS).  We should also integrate the ActiveX version so that Internet Explorer users can use OpenCapture within HPI.

Perhaps this would be a good enhancement to add while updating the plugin to HTML5? See #396

**Comment by CodyWatson15** [comment]
With the update to Dynamsoft version 12.0, the enhancement to HTML5 to allow for the DWT object to support scanning objects to HPI. Closed with revision 16498.
