### ISSUE TITLE
Advanced search - sort attr on first object type applies to second object type

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#398]
See the screencapture below.  On release1 (DCTM), if I try to sort Controlled Documents by document_number, searching for Folders fails because it's trying to sort on document_number, which doesn't exist on Folder.

Interestingly, this issue doesn't come up on release2 (Alfresco), but my guess is that it's still a problem, but Alfresco just doesn't barf when you try to sort on an invalid attribute. @cmlewis - thoughts?

![search-invalid-attr](https://cloud.githubusercontent.com/assets/1377228/4061941/2653b174-2dfc-11e4-864a-2586d7629f27.gif)

**Comment by gsteimer** [comment]
I'm seeing this issue again on edge1.  Controlled docs are setup to sort on `documentNumber` and Folder is configured to sort on `objectName`:

![image](https://cloud.githubusercontent.com/assets/1377228/7210703/c7e0bada-e519-11e4-9003-1b84d09cb396.png)

![image](https://cloud.githubusercontent.com/assets/1377228/7210707/cdeaf3d2-e519-11e4-8142-d28323c3cb98.png)

However, all searches for folder fail with the following error:

```
DfException:: THREAD: TP-Processor6; MSG: [DM_QUERY_E_NOT_ATTRIBUTE]error:  "You have specified an invalid attribute name (document_number)."; ERRORCODE: 100; NEXT: null
```

The query it's running is (notice the order by): 

```sql
Select object_name, r_object_type, title, subject, authors, keywords, a_application_type, a_status, r_creation_date, r_modify_date, r_modifier, r_access_date, a_is_hidden, i_is_deleted, a_retention_date, a_archive, a_compound_architecture, a_link_resolved, i_reference_cnt, i_has_folder, i_folder_id, r_composite_id, r_composite_label, r_component_label, r_order_no, r_link_cnt, r_link_high_cnt, r_assembled_from_id, r_frzn_assembly_cnt, r_has_frzn_assembly, resolution_label, r_is_virtual_doc, i_contents_id, a_content_type, r_page_cnt, r_content_size, a_full_text, a_storage_type, i_cabinet_id, owner_name, owner_permit, group_name, group_permit, world_permit, i_antecedent_id, i_chronicle_id, i_latest_flag, r_lock_owner, r_lock_date, r_lock_machine, log_entry, r_version_label, i_branch_cnt, i_direct_dsc, r_immutable_flag, r_frozen_flag, r_has_events, acl_domain, acl_name, a_special_app, i_is_reference, r_creator_name, r_is_public, r_policy_id, r_resume_state, r_current_state, r_alias_set_id, a_effective_date, a_expiration_date, a_publish_formats, a_effective_label, a_effective_flag, a_category, language_code, a_is_template, a_controlling_app, r_full_content_size, a_extended_properties, a_is_signed, a_last_review_date, i_retain_until, r_aspect_name, i_retainer_id, i_partition, i_is_replica, i_vstamp, r_folder_path, i_ancestor_id, r_object_id 
FROM dm_folder   
WHERE  UPPER(object_name)  like '%101%' 
ORDER BY document_number ASC ENABLE(NOFTDQL)
```

**Comment by grahamsinger** [comment]
Seems like @JasonKienzle's original fix was removed/taken out at some point.  Added that line back in and removed a duplicate line.

CR: JK
