### ISSUE TITLE
Bulk Upload - many concurrent requests

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#400]
Currently, the modern browser (non-flash) bulk upload fires off all AJAX upload requests concurrently. This could easily cause server load issues. We could take a page out of Share's playbook, where they upload 2 documents at a time and wait for the server to complete those requests before sending additional requests to the server.

**Comment by gsteimer** [comment]
Fixed with new synchronous mode option in Bulk Upload
