### ISSUE TITLE
Folder Tags - display documents with no tags

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#413]
Currently, if a document has no folder tags set on it, it will not display on the Stage unless a Folder Contents Relation Based section is also configured. See image below.

Make a option in the Folder Tags config to display any documents without tags in an Uncategorized tag (also make the tag name configurable)

![image](https://cloud.githubusercontent.com/assets/4852302/4294941/b79737bc-3de4-11e4-8440-9c9944f159a2.png)

**Comment by AubreyZielinski** [comment]
Fixed with OC revision 10596 and HPI revision 11570.
