### ISSUE TITLE
HPI 'Edit Online' Action Configuration

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#415]
Currently the "Edit Online" feature forces an admin to manually add a vtiPath parameter to the path that is running the Sharepoint connector servlet. We need to enhance this action with a custom admin module that forces the user to enter this server info before the action is allowed to be added.

See any of the other actions that require additional configuration for an example of how to do this (Bulk Import and the "license" entry for scanning are a perfect example)

![image](https://cloud.githubusercontent.com/assets/4850976/4341286/93d4f4ea-4037-11e4-9dab-c598c546781d.png)

**Comment by gsteimer** [comment]
This action has been replaced by actions like `CheckoutToCloudService`, etc.
