### ISSUE TITLE
Dashlets that returns AW Forms cannot use stage simple - actions do not display properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#424]
Currently, the saved search dashlet does not include a resolver configuration like search does:

![image](https://cloud.githubusercontent.com/assets/1377228/4460084/171e2382-48b0-11e4-8fa3-b4d1157c5a72.png)

Because of this, if the My Forms dashlet does not configure 'wizard' here:

![image](https://cloud.githubusercontent.com/assets/1377228/4460160/a1fb2144-48b0-11e4-84b8-8131f388df6d.png)

Then the stage processes the form just like any other document, retrieving the parent folder ID and placing it into the URL:

![image](https://cloud.githubusercontent.com/assets/1377228/4460181/c88ccd12-48b0-11e4-9c01-bc42ed265cd8.png)

This doesn't work for AW forms since the folder (or "container") ID should be the form ID, so most of the AW important actions won't appear (like start review route, start approval route, etc.)

This isn't super high priority - for now, we can work around the issue by configuring the trac to link to 'wizard':

![image](https://cloud.githubusercontent.com/assets/1377228/4460227/0d0e34c6-48b1-11e4-999a-cc1ef1ab5cf6.png)

With that in place, the actions process properly.  A better fix would be to give the Saved Search config a resolver option in the admin, similar to the search config.  That way, we can get rid of the logic that says "if the trac is named 'wizard', then set the container ID to the document ID".

**Comment by gsteimer** [comment]
This is also a problem in HPI 2.3 with Recent Objects.  If you click on a form on edge1 in Recent Objects, it goes to the following URL:

![image](https://cloud.githubusercontent.com/assets/1377228/5804063/8aef01b8-9fc8-11e4-9e34-8350f1447756.png)

But it should be:

![image](https://cloud.githubusercontent.com/assets/1377228/5804071/96653a9e-9fc8-11e4-8433-4ec77f85190f.png)

**Comment by gsteimer** [comment]
Another thing to think about here - what about the case where the client has a PSI subtype?  Maybe a better approach would be a configuration on the OTC?  Something that basically says "when this type is encountered in stage simple", set the container ID and document ID to be equal.  Ideally, this would default to true for Page Set Instance.

@joehof - thoughts?

**Comment by m-brouillette** [comment]
Added an 'Wizard' option to the 'isContainer' dropdown in the OTC.  This option will cause that type to use its objectId for BOTH the container & document Id when routing through StageSimple.

For recentObjects, If a documentId is present in the recentObject cookie, it will now navigate to that document within the container stored on the cookie.  With this change, AW PSI's now route properly from recentObjects.

Fixed in HPI REV: 11589
CR: Dan Grumieaux
