### ISSUE TITLE
Bulk Properties Edit clears repeating fields

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#432]
See the screencam below.  I'm bulk editing properties for two documents that each have a folder tag property set.  As you can see, if I don't explicitly reset the tag attribute on each document, the bulk property action clears out the values, causing the documents to disappear from the folder tags view on the left.

![bulk-properties-edit-tag-issue](https://cloud.githubusercontent.com/assets/1377228/4545805/eeb9fa18-4e3d-11e4-859c-f6f9a889605a.gif)

@zkeller @mikeblum @joehof

**Comment by aviking** [comment]
Fixed with Revision: 11488
