### ISSUE TITLE
Bulk properties date formatting not handled correctly and race conditions

### ISSUE THREAD

**Issue by jrubins** [tsgrp/hpi#452]
Bulk properties is expecting the `app.context.dateService.getFormattedDate` call to be synchronous which it no longer is. This code should be refactored to properly use the deferred that `getFormattedDate` returns.

Additionally, the entire `commitPropertyChanges` function is ripe with race condition possibilities. The `getAdminTypeConfig` call is asynchronous, the `getFormattedDate` call is asynchronous, and the `getApplicationConfig` call is asynchronous. The action should not call its `execute` method until all these calls have resolved. We're currently getting lucky because the admin type config and application config are already cached but we should not be relying upon this.

**Comment by aviking** [comment]
Fixed with Revision: 11488
