### ISSUE TITLE
HPI Dictionary Service does not recurse over aspects to get all attributes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#460]
If a type includes an aspect, and that aspect includes other aspects, these "nested" aspects are not displayed in the OTC.  To get around this, we include the aspect twice in the model.  For example, the mandatory aspects for `aw:controlledDocument` looks like this:

```xml
<mandatory-aspects>				
	<aspect>tsg:controlled</aspect>
	<aspect>aw:auditable</aspect>
	<!--  the below aspects are granted by tsg:controlled, but we need these here so that our dictionary service recognizes their properties  -->				
	<aspect>tsg:approvable</aspect>
	<aspect>tsg:effectiveable</aspect>
	<aspect>tsg:renditioned</aspect>
	<aspect>tsg:statusable</aspect>
	<aspect>tsg:periodicReviewable</aspect>
	<aspect>tsg:obsoleteable</aspect>
</mandatory-aspects>
```

We should not need to include any of the aspects below that comment - they are superfluous and most likely bad design from an Alfresco perspective.

This may include OC updates, but at a minimum the code in the admin type config needs to recurse over aspects vs. only assuming one level deep.

**Comment by joehof** [comment]
In HPI, we would not recurse down into aspects and their properties, we would only go one level deep. We are now adding a new "allProperties" set to the OCClassDefinition which recursively grabs all of the type's properties, stripping out duplicates. HPI will now you the "allProperties" set moving forward.

HPI - revision #11698 | OC - revision #10779
