### ISSUE TITLE
Allow Workflow Documents to be managed from the Stage for Active Wizard forms

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#467]
The new HTML5 version of Active Form will not have a "workflow documents" page.  This means that users will need to be able to manage workflow documents from the HPI stage.  

Question - can we just use the new Manage Relations action to do this?  Is there any functionality we would need to add / fork for workflow documents?  If security is setup properly in each of the lifecycle states, this may just work.  For example - users should only be able to manage workflow docs if the form is in the Draft state.

**Comment by gsteimer** [comment]
Testing this on edge1, I see the following issues:

- [ ] Wording - we should use the wording "workflow documents" rather than "relations". @benallenallen - do you think we should instead use the term "Controlled Documents" rather than "Workflow Documents" everywhere?
- [ ] Clicking the "refresh" icon - awkwardly hanging off to the right - actually checks all documents and displays the remove button.  Is it supposed to do that?
- [ ]  See the screencam below - searching for documents to add never comes back on Edge1.  I don't think we should go the route of having this try to be a "live" search.  Client environments are too slow.  If someone is typing slowing, it could easily kick off 5-10 really slow queries which could cripple some client environments.  Would a better approach be to have a search button?
- [ ] There's no indication on the "add" form for what you're searching on.  We should explicitly tell the user they're searching on the document name.  Come to think of it, should we switch this to search on the `document_number` attribute instead?  @benallenallen - thoughts?

![add-wf-docs](https://cloud.githubusercontent.com/assets/1377228/5742174/ddd21394-9bd5-11e4-9370-5270e325f908.gif)

@dgrumieaux @mikeblum @b-k-white

**Comment by gsteimer** [comment]
Another bug here - with the current setup of the query for Documentum, it's never going to find a Draft document past 1.0.  The current query is only searching on `CURRENT` versions.  We'll need to make sure that in the query, it's searching on all versions and one of the version labels is `LATEST`.

Note that this is only an issue for Documentum.  Alfresco queries don't need this extra logic.

@mikeblum @b-k-white - when you're testing workflow documents, **always, always test documents past 1.0**.  If you're only testing documents from 0.x to 1.0, you're only testing the simplest scenario, especially on Documentum.

**Comment by dgrumieaux** [comment]
Assigning myself to scope remaining work

**Comment by dgrumieaux** [comment]
Completed items:

- Updated wording
- Removed refresh button
- configured and tested against edge1

Still TODO:
- configure and test against edge2 (configure search terms)
- implement correct conditions for alfresco (perhaps a inSpacesStore condition)
- remove typeahead and make a manual search button
- show attributes on existing manage relations tab
- potentially remove existing manage relations tab and integrate existing/add into one view

**Comment by gsteimer** [comment]
@dgrumieaux @mikeblum - I tried testing this again with the latest on edge1.  It looks like I cannot find a `1.1, Draft` document, so I'm guessing that the code / config is not properly searching on all versions.  Searching for a `0.x, Draft` works great.  Everything else seems to be working properly with the exception of the refresh issues mentioned here: #624

**Comment by dgrumieaux** [comment]
It looks like the edge1 configuration was not properly updated to search
all versions, unlike the other environments. We can add that in without
issue.

**Comment by gsteimer** [comment]
This functionality is in HPI 2.3.  The only outstanding item is combining the two tabs into one, but that can be a separate issue if a client requests it.
