### ISSUE TITLE
Table View - Can't remove configured types

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/hpi#488]
There is no way to remove a configured object type for Table View.
![tableviewissue](https://cloud.githubusercontent.com/assets/8784125/5252514/14be6752-7964-11e4-8b83-6189cd1e45da.PNG)

Grid View and List View both have close buttons on configured types, as shown below.
![listviewbug](https://cloud.githubusercontent.com/assets/8784125/5252516/1a3efe3a-7964-11e4-9700-c1e910ddf7e3.PNG)

**Comment by aviking** [comment]
Resolved with  revision 11433
