### ISSUE TITLE
Dates not formatting on Saved Search dashlets when going to stage and back

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#493]
See the following screencam from edge2:

![saved-search-stage-nav-dates](https://cloud.githubusercontent.com/assets/1377228/5285697/be16b8b0-7ae3-11e4-833f-d61bde1ba95e.gif)

It's odd that the modified date works, but approved date doesn't.  In the OTC, they're both date fields configured with the DateTime filter.

**Comment by eric-gottschalk** [comment]
Commit #11451

oc.js
Added functionality to allow an otc to pass into property formatting. Removed fetchAndCacheObjectTypeConfig function and used app.context.configService.getAdminTypeConfig in its place to get the otc. Changed formatValues to use a new callback function objectTypeConfigCallback to format values. 

savedsearchdashlet.js
Changed Views.Results to get the otc for the dashlet and pass it into Views.ResultView to limit number of callbacks. 
CR: Zach Keller
