### ISSUE TITLE
Export Form Data action - hardcoded client object type

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#494]
The Export Form Data action does not work because the code is relying on a hardcoded form type:

(object type name changed below)
```js
self.prettyNames = app.context.configService.getLabels('client_object_type', sortFields);
```

This causes the action to fail for any other object type, which is obviously bad.  The code should not assume the object type, but have it passed in and use the actual object type of the form.

**Comment by eschwarzbeck** [comment]
Unit tests written CR'ed by @dgrumieaux in revision #11478
