### ISSUE TITLE
Export Form Data action - correctly limiting based on form template?

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#495]
While I'm not 100%, I'm guessing that this condition will not work with the code in `CommonPropertyValueEvaluator`:

**3.wizard - wizard-condition-bean-config.xml**
```xml
<bean id="condition-commonpagesetname-conditionevaluator" class="com.tsgrp.opencontent.core.action.condition.evaluator.CommonPropertyValueEvaluator" parent="AbstractConditionEvaluator" scope="prototype">
	<property name="propertyName" value="pageSetName" />
	<property name="description" value="Evaluates to true when all selected forms have the same form template." />
</bean>
```

The reason I'm suspicious is that, for the latest client impl, the property was `page_set_name`, which is Documentum specific.  I changed this to the oc-generic `pageSetName`, but I'm betting that the code in `CommonPropertyValueEvaluator` is incorrectly using the repo name vs. the OC bean name.

From talking to @dgrumieaux - it looks like the code in `CommonPropertyValueEvaluator` shuold be updated to use the Data Dictionary service as well (which should clean up the code a bit and fix this issue as well).

@grahamsinger

**Comment by AubreyZielinski** [comment]
Fixed in OC Revision 10693: The OC name is now being used in CommonPropertyValueEvaluator instead of the repo name.

**Comment by gsteimer** [comment]
This does not work on edge1 or edge2.  

On edge1, the action executer is failing:
```
2015-02-03 08:20:00,991	134531	TP-Processor7	ERROR	RESTService	Error parsing JSON
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error parsing JSON
	at com.tsgrp.opencontent.wizard.action.executer.ExportFormsActionExecuter.executeImpl(ExportFormsActionExecuter.java:175)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:303)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:234)
...
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
```

On edge2, I cannot configure the action at all.  The admin is failing initializing the action beans with this error:
```
Unable to get action data. Please contact your administrator: Error creating bean with name 'action-viewAnnotations' defined in class path resource [wizard-alfresco-action-bean-config-overrides.xml]: Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'java.util.ArrayList' to required type 'java.util.List' for property 'groupedConditionEvaluatorList'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.util.ArrayList] to required type [java.lang.String] for property 'groupedConditionEvaluatorList[2][0]': no matching editors or conversion strategy found - Tue Feb 03 2015 08:41:29 GMT-0600 (Central Standard Time)
```

**Comment by gsteimer** [comment]
Update - my bad.  The error on edge1 is what happens when you try to export form data on an old XML form.  This is known behavior - the action only works for JSON forms.

The error on edge2 is unrelated.
