### ISSUE TITLE
Related Objects Does Not Successfully Sort Folders Above Documents

### ISSUE THREAD

**Issue by AubreyZielinski** [tsgrp/HPI#500]
When a related object contains both folders and documents at the same level, the sort does not work correctly because it is dependent on the results of asynchronous calls to isContainer. The logic to alphabetize all the folders above all the documents is there and would execute correctly if not for this race condition with isContainer. Therefore, all the objects in a folder are not seen as containers, even if they are, so the folders and documents are intermixed when alphabetized. This affects both the folder tags and children relations. See the comparator function in foldertree.js.

Talked with @zkeller about this and we were unable to find a way around this issue at the moment, but maybe there will be a straightforward solution once foldertree.js is rewritten without knockout.

**Comment by gsteimer** [comment]
Closing this - I haven't seen this crop up in a long time.
