### ISSUE TITLE
Cascading Queries - Issue with new typeahead?

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#503]
Seems to be an issue now on @joehof's current client.  Assuming that this is also a problem for trunk as well.  Did something in the new typeahead break cascading queries?

@joehof - feel free to add more details here if needed.

**Comment by b-k-white** [comment]
Cascading picklists were functioning correctly, but some unit tests were failing. I have fixed up the unit tests as well as a minor isGrowable change that needed to be added to form support.
https://github.com/tsgrp/hpi/issues/503
CR-ZK

**Comment by b-k-white** [comment]
The color is not changing correctly.

**Comment by b-k-white** [comment]
Fixed the color issue
HPI - 11791
