### ISSUE TITLE
Deprecate Combine PDF group action and make Advanced Combine PDF folder action work as group action

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#508]
Old Combine PDF action hasn't been touched for a long time and doesn't appear to work anymore as a group action in search results. We should update Advanced Combine PDF to also work as a group action, which allows users flexibility to create the cover page, reorder, etc.

**Comment by aviking** [comment]
Fixed with Revision 11456. (Requires an OC update)
