### ISSUE TITLE
Advanced Combine PDF - URLs too long using GET - switch to POST

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#509]
Potential issue with Advanced Combine PDF (was an issue with old Combine PDF group action as well) - when adding many documents, the URL will eventually get too long and reach the URL character limit. This is especially true in IE9, which has a very small character limit.

Current URLs look like this. Every 'ID' is an object id and we also include object names, which generate super long URLs.
http://myserver/alfresco/OpenContent/action/executeAndReturnStream?action={%22name%22:%22advancedCombineToPDF%22,%22parameters%22:{%22objectId%22:%22ID%22,%22objectIds%22:[%22ID%22,%22ID%22,%22ID%22,%22ID%22],%22objectNames%22:[%222013%20OBJECTNAME.pdf%22,%22OBJECTNAME.txt%22,%22OBJECTNAME.msg%22,%22OBJECTNAME.pdf%22],%22indexTitle%22:%22Generated%20Combined%20PDF%20Index%22},%22id%22:%22348ca7a8-98a4-4bd2-818c-d031763fe048%22,%22actionId%22:%22advancedCombineToPDF%22,%22result%22:null,%22conditions%22:[{%22name%22:%22condition-read-conditionevaluator%22,%22parameters%22:{%22objectId%22:%22workspace://SpacesStore/8810a068-0703-4d91-8341-d44b96b819a3%22},%22status%22:%22valid%22,%22message%22:null,%22required%22:true,%22group%22:null}],%22ocActionId%22:%22advancedCombineToPDF%22}&download=false&contentType=application%2Fpdf

We should find a way to switch to a POST to prevent these long URLs.

**Comment by aviking** [comment]
Fixed with revision 11440. There is an issue with the table of contents if more than 40 documents are being combined. I am opening another issue for that.
