### ISSUE TITLE
Create Wizard Form action - Limit forms available for creation

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#515]
In Create Wizard Form, a user may select any form to create, whether the action is launched from the header, or as a doc action, or as a search group action. In scenarios where a client may have some forms with workflow rules and some without, this could be confusing, because some forms will only make sense to be created through a doc actions, and some forms would only make sense to be created through the header.

**Comment by gsteimer** [comment]
I don't think this is an issue.  All forms can have repository documents attached, so whether or not the forms use workflow rules isn't really a problem.  Although calling them "workflow documents" may be confusing, but the label can be changed...

**Comment by dgrumieaux** [comment]
When creating a form in OpenContent, if workflow documents to be related
are provided, we ignore them unless workflow rules are enabled. Should this
be fixed?

**Comment by gsteimer** [comment]
I'd say yes - in the past the two have not been tied together at a technical level.  It just never made sense to attach repo docs unless you have workflow enabled on the form.  But a client could come along and want to attach repo docs to a form that only uses email rules and no workflow.

**Comment by mikeblum** [comment]
**oc update required**

Revision: 10405
Author: mblum
Date: 2015-01-05 12:47:24.690844
quick fix to allow attaching of workflow documents without a backing workflow definition: https://github.com/tsgrp/hpi/issues/515

M	/webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/FinishAndSubmitPSIActionExecutor.java
