### ISSUE TITLE
Saved Search Dashlet - Pagination Controls should not appear if no results

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#516]
Should be an easy one.  Looks like this is working properly for the Recent Objects dashlet, but not saved search:

![image](https://cloud.githubusercontent.com/assets/1377228/5631060/0fe0b208-9589-11e4-9f5e-39790bf2df59.png)

**Comment by nwoodbine** [comment]
Fixed in HPI revision 11453 - added a Handlebars condition to resultcontrols.html that will only allow the pagination controls to be displayed if there are pages. This flag is triggered in the ResultControls view in savedsearchdashlet.js.

**Comment by gsteimer** [comment]
This is not working properly on edge.  See the screencam below:

![no-results-ss](https://cloud.githubusercontent.com/assets/1377228/5669414/e7eb2fde-973c-11e4-9287-5efaa58af70e.gif)

**Comment by eric-gottschalk** [comment]
Commit #11505
In savedsearchdashlet.js, removed collection length check in an if statement in the object type config callback which stopped the spinner from being destroyed if the collection had no results. 
In savedsearchdashlet/results.html, changed no results message from a h2 to a h4. 
CR: Zack Keller
