### ISSUE TITLE
Advanced Combine to PDF - Reorder Not Working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#520]
See the screencapture below - reordering the list of documents seems to be dropping documents out of the list.  Adding a new document seems to reset the list.

![combine-pdf-reordering](https://cloud.githubusercontent.com/assets/1377228/5634731/009968f2-95a8-11e4-8491-bc7534463c69.gif)

**Comment by aviking** [comment]
Fixed with HPI Revision 11458.
