### ISSUE TITLE
Saved Search Dashlet changing object type config in dashboard admin

### ISSUE THREAD

**Issue by eric-gottschalk** [tsgrp/hpi#524]
When there are at least two saved search dashlets with different object type configs in the dashboard admin window, the last dashlet rerendered will override any open saved search dashlets object type config. 

![dashboardadminsavedsearch](https://cloud.githubusercontent.com/assets/8784120/5649632/fd8f4982-965c-11e4-83c2-c962400d4f78.gif)

**Comment by gsteimer** [comment]
@eric-gottschalk @zkeller - can you guys clarify this issue better.  I'm not sure what you mean by "different object type configs".  Don't we only have one OTC now?  Also - how should this be prioritized?  I'm assuming HPI 2.3?

**Comment by zkeller** [comment]
When you have two Saved Search Dashlets in admin with different object types, if you open both of them to edit, when the second one is opened, the first config's object type is changed to the second object type.

Above, the first Saved Search Dashlet has a type of 'Form', the second is 'simple_cr'. When the second dashlet config is opened, the first dashlet's object type is changed to 'simple_cr'.

**Comment by renesaladrigas** [comment]
SAVED SEARCH DASHLET CONFIG - Corrected variable scope to fix issue.

Closed with revision 13657.

CR - MBlum
