### ISSUE TITLE
Facet Search - Error when faceting on already searched item

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/hpi#526]
Currently, if you try to facet on something that you have already searched on in advanced search, you will get a duplicate key error.
![facets](https://cloud.githubusercontent.com/assets/8796489/5671579/ac8f4a9e-974e-11e4-8dab-c2e99428566f.gif)

**Comment by gsteimer** [comment]
@dgrumieaux - will this be an issue with Alfresco 5 facets?  I'm thinking we should try to make sure this isn't an issue since we're redoing facets for 5 anyway...  If that's the case, we can just fix this bug for Alfresco 4.x when needed.

**Comment by dgrumieaux** [comment]
The fix that I am working on right now will account for this issue on both
Alf 4 and 5.

**Comment by joehof** [comment]
Can no longer replicate with the latest facet changes from HPI revision #12737 and OC revision #12113 - closing the issue.

**Comment by gsteimer** [comment]
@joehof - I'm still seeing this same issue on edge2.  Did you commit a fix for it?

**Comment by grahamsinger** [comment]
@gsteimer @joehof @ZachGerth can this be closed with most recent facet updates?

**Comment by gsteimer** [comment]
@grahamsinger - I just tried this on edge2 and it works.  I'm guessing this was fixed with @joehof's client side facet overhaul earlier this year...
