### ISSUE TITLE
ModalActionHandler needs refactoring, cleanup.

### ISSUE THREAD

**Issue by mbowen000** [tsgrp/hpi#527]
ModalActionHandler.js has gotten to a state where it is largely a mess. The bootstrap 3 refactoring effort put it over the edge, in my opinion.

Major problems: 
- Code is highly dirty and unkempt - includes lots of commented out code.
- Rendering is highly UN-reliable. At the time content is injected into the modal for your action, there is no assurance that the modal has actually been rendered to the page.
- Certain events are no longer even firing (likely BS3 changes) See the following:

```javascript
that.$el.find('.modal').bind("show", that.onModalShown);
```

which triggers:

```javascript
that.onModalHidden = function() {
       that.clearModal();
       $("#modalIFrame").attr("src","about:blank");
       that.$el.find('.modal').css({"display":"none"});
       that.$el.addClass("hide");
       $("body").css({ 'overflow': 'auto' });

       app[moduleId].trigger("hide");
            };
```

These are not even firing. The "hide" event is also not firing.  A new ```shown.bs.modal``` has been tested and works.  @aviking has solved some of these problems but additional refactoring is necessary to get this to a sane state.  We can simplify the module w/ a rewrite and I can provide a design.

**Comment by m-brouillette** [comment]
Cleaned up code / removed comments.  Updated MAH to properly pull and use the BootStrap3 Modal properties that are configured.

Fixed in HPI Revision: 11571
CR: MBowen
