### ISSUE TITLE
Advanced Combine to PDF - Do not show available documents list when launching from search or collections

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#528]
See the screencam below.  When using the Advanced Combine to PDF action from search or collections, the user has already selected their documents.  So there's no need to have the available documents list.  When the action launches, it should simply show the "selected documents" table and allow the user to reorder before generating the PDF.

![combine-to-pdf-from-search](https://cloud.githubusercontent.com/assets/1377228/5706665/4fa2c87c-9a48-11e4-81ec-7a4675421d02.gif)

When doing this update, remember that the current interface should *not change* when launching this action from the Stage.

**Comment by aviking** [comment]
Have it fixed locally, awaiting code Review.

**Comment by aviking** [comment]
Fixed with Revision: 11501
