### ISSUE TITLE
Viewer modules don't have config defaults

### ISSUE THREAD

**Issue by jrubins** [tsgrp/hpi#530]
In the `DocViewer.ViewModel` we should be defaulting the different viewers' enabled / disabled toggles to some value (probably `enabled`). Otherwise for existing configs you have to go in and toggle the values to get them to hold a value in the saved config.

**Comment by eschwarzbeck** [comment]
Initial Docviewer config defaults were not getting applied due to a boolean vs. string issue. Updated to ensure that defaults are applied. CR: JR

**Comment by eschwarzbeck** [comment]
Closed at Revision #11506
