### ISSUE TITLE
When adding a type to a search form, advanced search settings should be defaulted

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#534]
See the screencam below.  When a new type is added to a search form, the advanced search config doesn't default the following values:

- [x] Sort Attribute - default to `objectName`
- [x] Sort Order - default to Ascending
- [x] Search on All Versions - default to Disabled

Ideally, these settings should be defaulted _without needing to actually visit the advanced search config_.  In other words, the admin should be able to just add the type to the form and be done with it.

Additionally, I noticed that clicking on the sort order and all versions sliders causes the page to scroll up.  This is only noticeable when there are more than a few types on the form.  The scrolling is super annoying.  While we're in there, can we fix this too?

![search-admin-form-update](https://cloud.githubusercontent.com/assets/1377228/5744278/efe87dd4-9be4-11e4-9129-4f94cef6c3e9.gif)

**Comment by m-brouillette** [comment]
Added aforementioned defaults to the new type's ViewModel in the no configs exist for it yet.

HPI REV - 11594
CR - CMLewis
