### ISSUE TITLE
Docviewer Always sending annotated version to stage

### ISSUE THREAD

**Issue by eschwarzbeck** [tsgrp/hpi#536]
At the moment the Show Annotated Version toggle button is being saved in the config but not being used in `docviewer.js`. The viewer module just passes a `true` or `false` to the view based on whether or not the document is annotated and shows the annotations but doesn't take into account if the show annotations button is toggled to `No` 

![first](https://cloud.githubusercontent.com/assets/6668298/5746987/dd7421e8-9bf9-11e4-8ed4-6d38fd0273d7.gif)

**Comment by eric-gottschalk** [comment]
Commit #11553
docviewer.js
Added check to see if config allows annotations. Will only run an ajax call to get document annotations if config allows annotations. 

docviwerSpec.js
Added unit tests. Unit test to check if annotations appear when document has annotations and config allows annotations. Unit test to check if annotations do not appear when document doesn't have annotations but config allows annotations. Unit test to check if annotations do not appear when document has annotations but config does not allow annotations. 

CR: Zach Keller
