### ISSUE TITLE
Advanced Combine to PDF does not show added documents when no "File to be created" is present

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/hpi#538]
The documents added to the Selected Documents to Combine view do not show up if there is nothing entered in the File to be created text box, as shown below.

![combine to pdf filename](https://cloud.githubusercontent.com/assets/4128978/5762340/1366ae8a-9ca7-11e4-97f6-2698c4124ff3.gif)

**Comment by eric-gottschalk** [comment]
Commit #11521
Removed part of if statement checking if there was a value in the pdf name text box.
CR: Don  Hartman
