### ISSUE TITLE
Ability to play audio files in the Stage

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#546]
It would be nice for us to be able to play audio files in the stage.  We should support:

- [ ] mp3
- [ ] wav
- [ ] anything else supported by html5

**Comment by eschwarzbeck** [comment]
Added the ability for videoJS to play audio files if an audio mimetype is passed in.

**Comment by eschwarzbeck** [comment]
Closed in revision #11647

**Comment by gsteimer** [comment]
I tried an mp3 on edge2 and it works great.  Unfortunately, edge1 not so much:

![image](https://cloud.githubusercontent.com/assets/1377228/6004342/bb2591a8-aac7-11e4-88e0-099d670e94f5.png)

I checked, and the file does look like it is setting the `a_content_type` appropriately, so I'm not sure what's going on...

![image](https://cloud.githubusercontent.com/assets/1377228/6004354/d40813c6-aac7-11e4-9564-32adec91268b.png)

**Comment by gsteimer** [comment]
Looks like there's an error on the server side in OC:

```
2015-02-02 10:35:07,804	2798344	TP-Processor7	ERROR	RESTContent	Failed to retrieve content.
java.lang.NullPointerException
	at com.tsgrp.opencontent.core.content.RESTContent.getContent(RESTContent.java:663)
```

**Comment by gsteimer** [comment]
Audio now works on edge, not sure when this was fixed...
