### ISSUE TITLE
FormConfig/FormSupport Enhancement - TextBox Character Length Limit

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#548]
This feature would enable an administrator in FormConfig to specify a configurable numerical limit on a TextBox. Then when a user would be uploading or updating properties using that form, validation does not allow a user to enter a value greater than the configured number of characters.

**Comment by gsteimer** [comment]
When doing this, we could also implement a min char limit as well.  Seems like it would be easy to do both at the same time.

**Comment by dgrumieaux** [comment]
@b-k-white - I believe this is done - can you comment with the HPI revision # if this is complete?

**Comment by b-k-white** [comment]
Sorry about that. Minimun and maximum characters are now an available validation to put on text boxes. In order to add this more complicated validation, I had to turn back on the old validation for fields. This can be seen in the change to hpi.styl. In order to finish this feature branch, I needed to fix up the appearance of typeahead errors, this should all look good. The trail of this feature branch was committed on my previous commit about promote/demote

CR-Blum
HPI-11661

**Comment by gsteimer** [comment]
@dgrumieaux @b-k-white - I just tried this on edge2 and it didn't work at all.  I setup the viewProperties form for Policy folders to have the following on the Policy Year and Policy Holder limits:

![image](https://cloud.githubusercontent.com/assets/1377228/6394507/87aee60c-bd97-11e4-811c-2012a54bdda6.png)

![image](https://cloud.githubusercontent.com/assets/1377228/6394514/97c814aa-bd97-11e4-95db-d70b001547e1.png)

Then I tested the view properties form for a Policy folder (notice the valid submit button):
![image](https://cloud.githubusercontent.com/assets/1377228/6394526/b36e046c-bd97-11e4-8bb7-ce4a8b92b42a.png)

And save worked:
![image](https://cloud.githubusercontent.com/assets/1377228/6394530/bc9dfab0-bd97-11e4-873b-43fd267a1aa0.png)

**Comment by dgrumieaux** [comment]
This functionality only works if "required" is set to true. Is this
acceptable for trunk? Should we perhaps just add an asterisk saying that
these configurations require "required" to be checked?

**Comment by gsteimer** [comment]
@dgrumieaux - ok, let me try that out.  I think something saying that the field must be required is a good idea.  

It makes sense, although the only complication would be if the user puts 0 as the minimum.  I think that's fine for now though.

**Comment by gsteimer** [comment]
@dgrumieaux - Yep, that works as expected.  Closing.
