### ISSUE TITLE
Bulk Upload - "Next" button is incorrectly disabled when a required field is set in bulk property edit mode

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#551]
Currently on edge2 I cannot upload 2 Controlled Documents at a time when I specify a Document Number property value on the bulk property edit screen. The next button is disabled on the 1st document property edit screen.

**Comment by gsteimer** [comment]
I think this has something to do with the validation.  If you click on the second document and then go back to the first doc, the next button is active

**Comment by dgrumieaux** [comment]
Note this issue only occurs when a user inputs a bulk property value on one or more required fields.

**Comment by dgrumieaux** [comment]
Removing the high priority tag until a client is identified that needs this fix.

**Comment by gsteimer** [comment]
Check out the following screencam.  Basically, even with one document it doesn't work properly, but only when the add documents action is loaded a second time.  @dgrumieaux @AubreyZielinski - if you think this is unrelated, I can create a new issue.

![add-docs-twice](https://cloud.githubusercontent.com/assets/1377228/5877112/c0b9bd48-a2e2-11e4-85e7-90ffa91804f9.gif)

**Comment by dgrumieaux** [comment]
This appears related. I will change the name of this issue to more accurately reflect the bug.

**Comment by AubreyZielinski** [comment]
Fixed with HPI Revision 11602. The properties view for the first document was being rendered before the data that triggers the validation within the afterRender was being set.
