### ISSUE TITLE
Dashboard hangs after refresh

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#552]
See the screencam below.  The dashboard seems to hang consistently after a hard refresh.  At least, that's how I've been able to recreate this.  It may be a timing issue, because I swear I've seen this right after login sometimes.  

Also - notice how, after the dashboard hangs, going to search loads fine, but coming back to the dashboard hangs again, but this time without the gray overlay.

in both cases, the error in the console is: 

![image](https://cloud.githubusercontent.com/assets/1377228/5866020/4dcab0f6-a253-11e4-9b33-ef7229a171d3.png)

I'm guessing this has something to do with the Saved Search dashlet, since in both environments it's the My Forms dashlet that is spinning and never returns.

**Comment by dgrumieaux** [comment]
Clearing cookies has always solved this issue on my computer. This may give a lead to whoever tackles this issue.

**Comment by gsteimer** [comment]
OK, yeah - clearing my cookies fixes this.  I'll lower the priority of this issue since I'm betting it's caused by us logging in to a lot of different environments all the time (localhost, edge1/2, release1/2).

**Comment by gsteimer** [comment]
Nope - bumping the priority of this one back up.  I've only used edge2 today, and I'm seeing the issue again.

**Comment by AubreyZielinski** [comment]
Fixed with HPI revision 11624. The recent objects dashlet was rendering before the handlebars helper subIndex was being registered if the OTC was already cached. Moving the helper registration into the beforeRender corrected this.
