### ISSUE TITLE
Stage - Fix bouncing doc viewer

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#553]
See the screencam below.  Why does the doc viewer bounce like that when a new view is loaded?  Ray calls this the "HPI boing-oing-oing-oing".

![boing-oing-oing-oing](https://cloud.githubusercontent.com/assets/1377228/5876998/942bba16-a2e1-11e4-8990-f9039231be7f.gif)

Whoever looks into this - if this ends up being more than a couple hour thing, let me know.

**Comment by m-brouillette** [comment]
Show() being called multiple times on initialization as Bootstrap css classes were added / removed.  Bootstrap tried to smoothly resize for each .show() call.  Removed the unnecessary show calls. 

HPI REV - 11601 
CR - DGrumieaux
