### ISSUE TITLE
Typeahead overlaying a blank value if clicking vs. typing

### ISSUE THREAD

**Issue by joehof** [tsgrp/hpi#555]
![typeaheadissue](https://cloud.githubusercontent.com/assets/4852255/5910784/99cd069c-a583-11e4-8e49-a151fbcc2c62.gif)

It looks like if you go back to an already populated auto-complete and then do not select anything, the typeahead input (which would be blank) overlays our display label box and shows the field as blank. The value and display label are still actually populated though.

We would need to figure out how to get at the typeahead input box in the setSelectionByLabel function in formsupport.js

**Comment by joehof** [comment]
The formsupport part of this bug is CLOSED with hpi revision #11613 - we still need to go through other areas in the app that use typeahead outside of formsupport and see if this is an issue.

**Comment by gsteimer** [comment]
I've tried

**Comment by gsteimer** [comment]
I've tried the following:

- [x] Active Wizard select box questions
- [x] Wizard Delegate and Reassign actions
- [X] Create PSI Action
- [X] Form support (Search, edit properties)

I'm going to close this - feel free to reopen if anyone finds a typeahead with this issue.
