### ISSUE TITLE
General styling in Add Documents

### ISSUE THREAD

**Issue by joehof** [tsgrp/hpi#556]
![adddocumentsissue](https://cloud.githubusercontent.com/assets/4852255/5910833/14f946c8-a584-11e4-96c1-fe792c5e6dd7.gif)

The add documents for full pane looks pretty bad, especially the dropdowns that add vertical and horizontal scrollbars. This should be prettied up to look better.

**Comment by gsteimer** [comment]
@joehof - can you check this again.  I think Eric's commit yesterday for #497 fixed this.

**Comment by gsteimer** [comment]
This is much better now:

![image](https://cloud.githubusercontent.com/assets/1377228/5925224/9c80cfe6-a627-11e4-9782-54e8e6a34270.png)

One minor thing that would be good - can we make the button the same size as the input?  The way it is now, it's slightly smaller...

**Comment by grahamsinger** [comment]
Fixed styling of button with rev. 12493
