### ISSUE TITLE
Form Config - Remove Extraneous Create Form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#561]
See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/1377228/5943462/d1e73608-a6e4-11e4-9e33-c412d4b49815.png)

The extra create config form below the new button can be removed.  The Add button is the preferred approach to creating a new config (for consistency across HPI admin).

**Comment by gsteimer** [comment]
@joehof - I think you added this - can you close this with the commit log?

**Comment by joehof** [comment]
Fixed with HPI revision #11646 -  removing the Form Config's creation input, since this is handled by the config-switcher.
