### ISSUE TITLE
Bulk Properties lacks tooltips

### ISSUE THREAD

**Issue by m-brouillette** [tsgrp/hpi#564]
I noticed that unlike BulkUpload, BulkProperties doesn't have tooltips when you hover over the breadcrumbs for files with long filenames.  This is a nice feature to have for both modules since it makes the breadcrumbs more usable.

![tooltip](https://cloud.githubusercontent.com/assets/8784115/5966136/607aad36-a7c7-11e4-8e93-9cec4d55720d.gif)

**Comment by bridgetbol** [comment]
HPI commit 13302 - added tooltip functionality to bulk properties
CR - Avi
