### ISSUE TITLE
Export Form Data - Help Text

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#565]
The export form data has the following help text:

![image](https://cloud.githubusercontent.com/assets/1377228/6022684/3ee2d4a8-ab84-11e4-9143-a678cdd5cb71.png)

Let's make it a little more helpful.  Something like this would be good:

`Choose to set the column headers to either the question label or the question display text`

We could also set the label to something better than "Choose Display Type".  I'm thinking this would be better:

`Choose Column Headers`

**Comment by AubreyZielinski** [comment]
Updated in HPI Revision 11666. Also changed text on Export Form button to be Export Forms, and set the default modal size to Large.
