### ISSUE TITLE
Docviewer will not display text/html content

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/hpi#571]
Per the below screen shot, the Docviewer is long longer displaying text/html content, such as the content that is generated by the SendEmail action.

From an initial look, @eschwarzbeck noticed that the div for the viewer is not on the page.

![image](https://cloud.githubusercontent.com/assets/4128978/6069765/b4c7fbac-ad4c-11e4-9c9d-90b86aac846a.png)

**Comment by joehof** [comment]
Viewer was broken due to a copy/paste of the old way of creating HPI spinner. Updated the spinner code and HTML can now be viewed in the docviewer.

Fixed with HPI revision #11736
