### ISSUE TITLE
AutoCAD DWG files do not check in properly

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#572]
Checking in a DWG document... what's supposed to happen:
 1. User checks in doc
 1. TSGRenditionBehaviours.onUpdateProperties fires, cm:content changed = TRUE
 1. Alfresco looks for DWG to PDF transformer and doesn't find one. Removes the existing tsg:rendition.
 1. File gets checked in and versioned.
 1. Success message displayed in HPI. Link to download doc is displayed in stage (because no rendition).

What really happens:
 1. User checks in doc
 1. TSGRenditionBehaviours.onUpdateProperties fires, cm:content changed is FALSE
 1. File gets checked in and versioned.
 1. Success message displayed in HPI, cm:content and tsg:rendition are exactly the same as before the check out.

Here's the weird part... when checking out (Edit offline) in Share, and checking in (Upload new version), the behavior fires appropriately with cm:content changed = true.

**Comment by gsteimer** [comment]
@cmlewis  - is this really high priority?  If a client is requesting it, that's fine, but then someone should be assigned.

**Comment by cmlewis** [comment]
@gsteimer I just went live with an engineering client who can't check in DWG files, it is most definitely high priority and I am looking at it.

**Comment by cmlewis** [comment]
In some cases with more obscure mimetypes (i.e. DWG), DataHandler.getContent() comes back null while DataHandler.getInputStream() does not. What the heck. Anyway, we were doing a null check on DataHandler.getContent() in the checkin method, but then using the input stream anyway. Updating the null check to check the input stream instead so we set content properly when we checkin.

Also updated checkin action to use the standard ByteArrayDataSource instead of the Gautam-created InputStreamDataSource. We might want to get rid of that.

Committed in rev 10778
