### ISSUE TITLE
Export Form Data - Data from Select and Multi-Select not displayed Excel properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#577]
When exporting form data for a form that contains Selectbox and Multi-select values, it seems like the Excel is receiving JSON data in the cell rather than the answer display text.  

![image](https://cloud.githubusercontent.com/assets/1377228/6177521/200444c2-b2cd-11e4-809a-4fadcd93426b.png)

Update - I just tried this again in wizard_d67 with SimpleCR.  It did mostly the same thing, but for some reason didn't pull the CR Approvers answers at all:

![image](https://cloud.githubusercontent.com/assets/1377228/6177529/3ca26398-b2cd-11e4-99e2-e6bf45375b43.png)

Both forms actually do have approvers assigned:

![image](https://cloud.githubusercontent.com/assets/1377228/6177536/48ef5516-b2cd-11e4-8e7a-763738ac0dad.png)

![image](https://cloud.githubusercontent.com/assets/1377228/6177540/5324e01e-b2cd-11e4-94bf-c3064412ff93.png)

**Comment by tconnellytsg** [comment]
Closed with OC revision #10859 and hpi revision #11745
