### ISSUE TITLE
Send notification - Due date should not be required to submit

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#578]
Not sure how this happened, but the due date field should NOT be required when sending a notification.  

From edge2:
![image](https://cloud.githubusercontent.com/assets/1377228/6190889/e06f4796-b36a-11e4-8e77-829fe9f9e719.png)

![image](https://cloud.githubusercontent.com/assets/1377228/6190894/e8704df0-b36a-11e4-8b88-0cf2fc327815.png)

**Comment by gsteimer** [comment]
Also - why is the "Groups:" label orange?  It looks like it somehow got a `.group-slug` class on it.

**Comment by AubreyZielinski** [comment]
@mikeblum suggested we make the group label orange and also the labels for each individual group when added to distinguish between added users and added groups, as they are displayed intermixed.

**Comment by gsteimer** [comment]
I don't think we need to do this.  Let's change it back to the way it was before.  If a client wants to set apart groups in some way, we can do it in the future...

**Comment by AubreyZielinski** [comment]
Fixed with HPI revision 11752. Removed date from validation check and reverted the orange group-specific styling.
