### ISSUE TITLE
Notifications - Due date text is not readable 

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#579]
Looks like the due date is there, but in white text:

![image](https://cloud.githubusercontent.com/assets/1377228/6190970/8b8c0ba0-b36b-11e4-8f29-f8cf3d9b4c3d.png)

![image](https://cloud.githubusercontent.com/assets/1377228/6190973/93eec350-b36b-11e4-860a-2f75c46ce44b.png)

**Comment by jrubins** [comment]
For whoever updates this, pretty sure I re-formatted the due date awhile ago to be a Bootstrap red label (which I think looks nice and we probably want to keep). This is probably invisible due to the Bootstrap 3 upgrade.

**Comment by jrubins** [comment]
In Bootstrap 3 the name for a "red label" got changed from "label-important" to "label-danger". In the Bootstrap 3 upgrade, our notification label class name was not updated.

Fixed in HPI Revision #11737.
