### ISSUE TITLE
Create Form Action - Cannot select form when only one in list

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#581]
This works fine on edge1, but in a client environment, I can't select the form using a mouse.  I can however, use the typeahead.  See below:

![select-one-form](https://cloud.githubusercontent.com/assets/1377228/6219244/8326c7ec-b5ec-11e4-8bfe-db984c7ce84b.gif)

Two things:
- [ ] Obviously, selecting the form with the mouse should be possible
- [ ] When there's only one form in the list, we should auto-select it.  The user shouldn't have to click to select when there's only one option.

@dgrumieaux @benallenallen @mikeblum - will this be an issue for our current client?  I think they have more than one form...

**Comment by tconnellytsg** [comment]
I have this fixed on my machine will commit after code review.

**Comment by tconnellytsg** [comment]
Fixed with hpi commit #11802
