### ISSUE TITLE
Create Form Action - Does not clear out selection properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#582]
See the screencam below.  When I select a form and then clear out my selection, the create button is still enabled and clickable.

![select-unselect](https://cloud.githubusercontent.com/assets/1377228/6219296/0e2b9c32-b5ed-11e4-9fcf-9783930139f7.gif)

@dgrumieaux @benallenallen @mikeblum - I'm guessing this will be an issue for our current client?

**Comment by tconnellytsg** [comment]
I have this fixed locally and will commit after a CR

**Comment by tconnellytsg** [comment]
Fixed with hpi commit #11802
