### ISSUE TITLE
Cascading Picklists trigger reload upon multiple attribute's value change events

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#584]
After implementing https://github.com/tsgrp/hpi/issues/318, the next logical scenario to consider supporting is to allow a picklist to listen to multiple attribute value change events to drive when it fetches its picklist.

For example - if a user changes the value of attribute A OR attribute B, attribute C's picklist would reload.

This enhancement should be carefully designed - restricting requests to the server may need to happen in a smart way in order to avoid overloading a server with queries.

**Comment by zkeller** [comment]
Another scenario to keep in mind:

If attribute A's change fires off a query and attribute B doesn't have a value, the picklist would come back empty. However, if attribute B is updated while waiting for the query to return for the change in attribute A, we would want to make sure a new query is fired (or the old one canceled) so the picklist has values. 

Currently, if a picklist query is getting executed and the code tries to fire off a new request, the new ajax call does not fire.

I think by handling our call logic appropriately (e.g. if attribute A has a value and attribute B does not, we don't fire off a query), this can be avoided.

**Comment by zkeller** [comment]
We would still not be able to handle the scenario where we would want something to come back if attribute A has a value and attribute B does not.

**Comment by zkeller** [comment]
@dgrumieaux did this get implemented? I want to say you can listen to multiple attributes now.

**Comment by dgrumieaux** [comment]
I don't think this is implemented yet. We would have to make an admin update to multiselect dependencies.

**Comment by gsteimer** [comment]
@zkeller @dgrumieaux - this should be there.  Didn't we add it for one of @ellenrtsg's clients a few months ago?

@dgrumieaux - the admin enhancement you're talking about should already be there...

**Comment by dgrumieaux** [comment]
so it is! I didn't realize. Looks like this was implemented.

**Comment by gsteimer** [comment]
I think we can close this since it was implemented for a client a few months ago.  Feel free to comment if you disagree.
