### ISSUE TITLE
Create Wizard Form Action - Does not filter out inactive page sets

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#587]
The Create Wizard Form Action seems to be displaying all AW Page Sets.  If you mark one as inactive in the Wizard Admin, it still appears as a valid form to create.

**Comment by gsteimer** [comment]
I just tried making a form inactive on the Documentum edge environment this morning and it works fine.  Marking this as an Alfresco issue.

**Comment by mikeblum** [comment]
AW Admin:

Revision: 7621
Author: mblum
Date: 2015-04-08 14:07:25.073430
Active Page Set Definitios: active version label is now 'none' when set as such in the activated page set definition list. **OC Update Required**

M	/src/trunk/modules/core/WEB-INF/src/com/tsgrp/wizard/servlets/UpdateActiveVersionServlet.java

Revision: 11337
Author: mblum
Date: 2015-04-08 14:17:17.198430
Active Page Set Definition - not showing page sets set to 'none': https://github.com/tsgrp/hpi/issues/587. ** AW Admin update required ** 
Upgrade: path: toggle all page set definitions to a version number and back to none to update the repo object to use 'none' for the activeVersionLabel as opposed to an empty string/null.

M	/webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/admin/Wizard2AdminImpl.java
M	/webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/Wizard2Impl.java
