### ISSUE TITLE
HPI Admin - Use Attribute labels rather than bean names

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#590]
We have attributes dropdowns and toss across controls in the HPI admin ordering by bean name, which is great, but many of the controls are displaying the OC Bean Name only.  Here's an example:

![image](https://cloud.githubusercontent.com/assets/1377228/6397699/2ab1f466-bdac-11e4-8000-22b36a76b739.png)

This is annoying on Alfresco, and almost unusable on Documentum.  It's a huge pain to find attributes in the list.

All admin attribute controls should have the bean name as the value, but the display should be the attribute label.

This may not be a complete list, but I've seen this issue in the following places:

- [x] Related Objects - Results display and  Sort Options
- [x] Related Objects - Info Block options
- [x] Form Config - Add attributes
- [x] Search config - advance search sort attribute
- [x] Actions that allow the user to configure attributes.  Ex: Adv Combine to PDF, View All Documents, I'm sure there's others...

**Comment by grahamsinger** [comment]
Completed at revision 12478

Replaced ocNames with labels in the config and tested to make sure that the actions were still performing as expected.

CR DG

**Comment by grahamsinger** [comment]
There are still some places where this hasn't been implemented (table view, list view and others).  Also, this update requires some reconfiguration because we are going from strings to objects so taking note/screeenshotting the existing configs is important so that they can be set again.

**Comment by gsteimer** [comment]
@grahamsinger - the filtering is also an issue with the new toss across lists, right?  That should be fixed as well.

**Comment by gsteimer** [comment]
@grahamsinger - Odd... that filtering issue we saw last week doesn't seem to happen anymore.  Not sure what changed...

**Comment by gsteimer** [comment]
Attr labels do not display on stage info:

![image](https://cloud.githubusercontent.com/assets/1377228/8333609/6bbb7946-1a59-11e5-9e23-04dac355c1e6.png)

**Comment by gsteimer** [comment]
Also:

- [ ] Search Config - Table View - Available / Visible / Hidden
- [ ] Search Config - List View - Available / Selected 
- [ ] Search Config - Grid View - Available / Selected
- [ ] Search Config - Facets - Available / Selected
- [ ] Collections Config - Grid View, List View, Table View
- [ ] Folder Browser Config - Table View

**Comment by zkeller** [comment]
I think something is off with Related Objects Query Relations Config -

![image](https://cloud.githubusercontent.com/assets/4852355/8700817/c07ea90a-2ad3-11e5-99a8-def9cb680dc8.png)

**Comment by zkeller** [comment]
Above comment fixed with commit 12690

**Comment by gsteimer** [comment]
Checked off the items from https://github.com/tsgrp/hpi/issues/590#issuecomment-114923602 implemented by @peterkk.  Peter - can you add your commit revs here?

**Comment by peterkk** [comment]
Commit #13986

**Comment by gsteimer** [comment]
@peterkk - I'm assuming that's the HPI commit?  Interestingly both HPI and OC are around the same Rev number right now, so it's tough to tell just from looking at the number...

**Comment by peterkk** [comment]
Facets seem to be fixed already, could have been done in an earlier commit

**Comment by ZachGerth** [comment]
Facets were completed with HPI Revision # 14135 as part of the overall Facet overhaul.
