### ISSUE TITLE
If editing documents in approval is allowed, will eSignatures potentially fail?

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#593]
@dgrumieaux @benallenallen - I thought of a scenario that I'm guessing will fail for Documentum clients:

1.  Client allows the ability to edit documents during the approval route for roles that add an eSignature to documents
1. The approver edits the document, which queues a rendition request
1. Before the rendition engine can process the request, the user approves
1. I'm guessing that the eSig code here will fail since there's no PDF rendition.

I'm thinking that if a client wants to fix this, we'd have to add a condition to the Complete Wizard Approval action.  Basically -  if there are any attached workflow documents AND the approver's role is configured to apply an eSig to workflow documents, then make sure all attached wf docs have PDF renditions.

Also - if we end up doing this, I'm guessing that implementing the "why doesn't X action appear" might be a good idea too.  @dgrumieaux - I thought you added an item for this functionality, but I can' seem to find it...

**Comment by benallenallen** [comment]
The old wizard had a condition that the documents had to have a PDF rendition before the 'complete task' action even showed. We had talked about in the future allowing an action to come back with 'reasons' why the action was disabled that would be very helpful to show to the user for a case like this.

**Comment by dgrumieaux** [comment]
was this fixed with #592?

**Comment by gsteimer** [comment]
@dgrumieaux - Nope - because of the timing issue with queueing renditions.  If you can approve your task faster than DTS can create a PDF rendition, then the eSig will fail.

**Comment by b-k-white** [comment]
Added new condition to check to make sure that pdf renditions exist for all workflow documents. 
CR- Dan G, M Blum 
OC REV - 11083

**Comment by gsteimer** [comment]
Just reviewing this code - I don't think it will work properly if the Role is configured to apply esignatures to the PSI vs. the attached docs differently.  The if statement on line 81 is:

```Java
if(role.getEsigPSI()){
```

So that's checking to see if the role is set to apply signatures to the PSI.  We want to know if it's configured to attach signatures to the _workflow docs_:

```Java
if(role.getEsigWFDoc()){
```

**Comment by b-k-white** [comment]
Fixed and tested this change. 
OC - 11107
CR - Blum
