### ISSUE TITLE
Approval routes do not start properly on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#595]
All active wizard approval routes fail to start on edge2 with the following error:

```console
14:25:55,288 ERROR [com.tsgrp.opencontent.rest.RESTService] [ajp-apr-8009-exec-8] Could not start workflow.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Could not start workflow.
	at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowImpl.startWorkflow(ActivitiWorkflowImpl.java:350)

...

Caused by: java.lang.NullPointerException
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetAndMaintainApprovalDetails(ActivitiClientWizardWorkflowImpl.java:258)
	... 128 more

```

From talking to @dgrumieaux, it seems that this may be because our @Value annotations are not getting processed correctly due to Spring context clashes.

**Comment by gsteimer** [comment]
Also - when this is fixed, we should also test https://github.com/tsgrp/ActiveWizard/issues/75.  I believe group-based workflow routes should work now on Alfresco.

**Comment by aviking** [comment]
I have this issue fixed locally, just waiting for a code review. Becuase of the how the new @Value annotations are being read in, we needed to add some new beans to core-oc-context.xml.

**Comment by aviking** [comment]
Fixed with OC commit 11015
