### ISSUE TITLE
Lifecycle state conditions no longer work on edge2

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#599]
It looks like none of the conditions are working for checking if a controlled document (or form I'm guessing) is in a specific lifecycle state.  For example, the following actions never appear:

- [x] Power Promote
- [x] Perform Periodic Review
- [x] Obsolete Document

Basically, I think we were getting away with an error in the spring config.  Before, I don't think this was overriding properly (using the draft condition as an example):

**wizard-condition-bean-config.xml**
```xml
<bean id="condition-iscontrolleddocdraftlifecyclestate-conditionevaluator" class="com.tsgrp.opencontent.core.action.condition.evaluator.IsLifecycleState" parent="AbstractConditionEvaluator" scope="prototype">
	<property name="stateToCheck" value="${wizard.lifecycle.repoNames.draftControlledDocState}"/>
	<property name="description" value="Checks that the lifecycle state of the object is 'Draft'" />
</bean>
```

**wizard-lifecycle-defaults.properties**
```properties
wizard.lifecycle.repoNames.draftControlledDocState=Draft
```

**wizard-alfresco-defaults.properties**
```properties
wizard.lifecycle.repoNames.draftControlledDocState={http://www.tsgrp.com/model/tsg/1.0}draft
```

The root of the issue is that the `IsLifecycleState` condition evaluator gets the state via this check:

```Java
state = CoreContext.getLifecycle().getCurrentState(ticket, nodeId);
```

The documentum version of this method returns:

```java
obj.getCurrentStateName();
```

BUT, the alfresco version does this:

```java
//lifecycle == status so:
NodeRef nodeRef = new NodeRef(objectId);
QName tsgStatus = QName.createQName("tsg:status", ServiceRegistryProxy.getServiceRegistry(ticket).getNamespaceService());
Serializable status = ServiceRegistryProxy.getServiceRegistry(ticket).getNodeService().getProperty(nodeRef, tsgStatus );
return status == null ? null : (String) status;
```

@dgrumieaux @benallenallen - I have a sneaking suspicion that this is actually an issue that we've been getting away with.  Basically, now it's finally overriding the `Draft` value properly with `{http://www.tsgrp.com/model/tsg/1.0}draft` and since the alfresco version of `getCurrentState` isn't returning the right thing, it's just now starting to fail.

If that is correct, then the fix would be to update that method to return the actual state name.  However, there are a lot of methods that call `ILifecycle#getCurrentState` that we would have to test and potentially update:

![image](https://cloud.githubusercontent.com/assets/1377228/6470143/27c01e78-c1a7-11e4-826f-93f8768e283d.png)

**Comment by tconnellytsg** [comment]
Fixed in OC revision #11028
