### ISSUE TITLE
Obsolete Currently does not record an audit of when the document is obsoleted

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#600]
Currently, the "obsolete" action generates a new signature page and updates in the "Approval Details" object, but there is no "end user" facing way to see the "Reason for Obsoletion." The easiest way to expose this would be to create an audit event when the document is obsoleted, and to expose the "View Audit Events" action on the individual document.

Potential downfalls to this approach are:

1. OOB Alfresco doesn't audit anything in the audit trail, so this action will only display something for "Obsolete" unless we update alfresco to audit more events
2. The IAudit#createAuditEvent method is a new method and not fully implemented for all ECMs.

The code to do this would probably look something like the following and be placed in ObsoleteDocumentActionExecuter.java

```java
                ...
		//audit that this document was obsoleted and the "reason for obsoletion"
		OCAuditEvent auditEventObject = new OCAuditEvent();
		
		//get the username of the current user
		String userLoginName = UserUtil.getCurrentUserLoginName(ticket);
		
		//get the pretty name (ex: "Ben Allen (ballen)" )
		String prettyName = UserUtil.getLabelName(ticket, userLoginName);
		
		auditEventObject.setAuditedObjectID(objectId);
		auditEventObject.setAuditDate(new Date());
		auditEventObject.setDisplayName(prettyName);
		auditEventObject.setEventDescription("TODO");
		auditEventObject.setEventName("TODO");
		auditEventObject.setUsername(prettyName);
		
		CoreContext.getAudit().createAuditEvent(ticket, objectId, auditEventObject);
```

**Comment by gsteimer** [comment]
Fixed in OC Rev 11077
CR - Ben and Dan
