### ISSUE TITLE
Right Click Actions should show available group actions if multiple results are selected

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#602]
![selection_011](https://cloud.githubusercontent.com/assets/547941/6529706/304c20aa-c3f0-11e4-8aa3-fee5f7fa3d14.png)

Currently, if a user selects multiple rows and right clicks, the actions shown and filtered are still only for the single row that was right clicked. A user would more likely expect that the right click action would apply to all rows selected.

**Comment by tconnellytsg** [comment]
I have this mostly done. A few little things are still tripping it up, moving on to some stuff for a client now, talk to me if someone else starts up on this.

**Comment by tconnellytsg** [comment]
Implemented this in hpi revision #11865.
