### ISSUE TITLE
Link on Bulk Upload Confirmation not working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#608]
As seen on edge2, notice the redirect to undefined:

![upload-conf-link](https://cloud.githubusercontent.com/assets/1377228/6621714/353e206c-c8a6-11e4-95e1-6d62bcd47fa1.gif)

Testing needed after fix:

- [x] Test one doc and multi-doc
- [x] Test on Documentum and Alfresco

**Comment by gsteimer** [comment]
Update - I tried this on edge2 with the Insurance trac and it seems to work fine.  Could this be a form config issue?

**Comment by gsteimer** [comment]
From talking to @tconnellytsg and @mikeblum, it seems like this is because the form does not include the object name attribute.  @tconnellytsg is working on a fix.

**Comment by dgrumieaux** [comment]
Note that testing in multiple environments shows inconsistent results. Could point to this being a race condition.

**Comment by b-k-white** [comment]
Whoever ends up fixing this should talk to me first. I have found that at line 338, we might be able to fix this using: 

else{ 
currentProps.objectName = self.options.fileNames[self.options.currentIndex];
}

However, it worked a few times and then I started getting duplicate child errors. Being pulled onto client and another issue right now, but will come back to this if no one gets to it

**Comment by b-k-white** [comment]
If that doesn't work, try passing currentProps.fileName = self.options.fileNames[self.options.currentIndex]; to OC, and then in OC, if the resolvedObjectName doesn't exist, use the fileName as the key.

**Comment by b-k-white** [comment]
Fixed this with unit tests
HPI 11922
CR - Zaq

**Comment by dgrumieaux** [comment]
I see this on edge2 now. Replicated on the Controlled Document trac uploading Controlled Documents.

**Comment by gsteimer** [comment]
I've noticed this too.  It seems to work sometimes with controlled docs that are uploaded.  However, it fails every time if you create a controlled doc from a template.

**Comment by aviking** [comment]
Fixed with HPI Commit: 12392. Code Review: Don H.

**Comment by gsteimer** [comment]
After a little testing on edge1, this doesn't seem to work right now for attachments included with an MSG file.  The email itself is fine, but all attachments always have the 'undefined' URL.

**Comment by aviking** [comment]
Fixed with HPI Commit: 12466.
CR: Dan G.
