### ISSUE TITLE
Attributes set on Bulk Upload not Applying

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#609]
See the screencam below from edge2.  It looks like optional attributes are not applying to the uploaded document properly.

![upload-attributes](https://cloud.githubusercontent.com/assets/1377228/6621812/bfa304c0-c8a6-11e4-89b8-b014eecb06d9.gif)

@dgrumieaux - I know I saw this working during our client functionality review earlier this week.  Could it be something with the Controlled Doc config on edge2?

**Comment by gsteimer** [comment]
Update - I tried this on edge2 with the Insurance trac and it seems to work fine.  Could this be a form config issue?

**Comment by b-k-white** [comment]
Using Joe's new code to call getAllProperties fixes this issue and simplifies the code.
CR- blum
OC - 11105
