### ISSUE TITLE
Computed Admin no longer works

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#615]
See the screencam below - I cannot choose another attribute in the computed in form config:

![computed-fail](https://cloud.githubusercontent.com/assets/1377228/6673418/cce1c93e-cc0a-11e4-8394-d729926c2a46.gif)

We need to make sure that a computed like the following is allowed:

`${attr1} - ${attr2} - ${attr3}`

**Comment by b-k-white** [comment]
An inaccurate event selector was causing a hijack on this dropdown. This has been fixed to correctly manage the control type dropdowns, and not interfere with the one in computed.
CR - JK
HPI 11904
