### ISSUE TITLE
AW Delegate and Reassign - should default role if only one available

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#616]
If there's only one role available in the dropdown, it should be auto selected (the user shouldn't be forced to select from the dropdown).

This used to be there, but must have gotten lost in the BS3 or KO removal efforts:

![image](https://cloud.githubusercontent.com/assets/1377228/6674119/97e472a6-cbe5-11e4-9adc-5dffb650fc6f.png)

![image](https://cloud.githubusercontent.com/assets/1377228/6674116/93d5789a-cbe5-11e4-8d0f-ffff84dcbcde.png)

Implement and Test:

- [x] AW Delegate Task
- [x] AW Reassign Task

**Comment by b-k-white** [comment]
Fixed this to auto-select. Also wrote some unit tests. 
CR - JK
HPI 11911
