### ISSUE TITLE
Set Effective Date - displays in odd format and does not set correctly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#617]
See the screencam below.  The set effective date works (and even sets the proper date when I submit), but the display shows some odd text:

![set-effective-date](https://cloud.githubusercontent.com/assets/1377228/6674359/03a33b20-cbe7-11e4-94c1-73b323db8fd2.gif)

For reference, the text displayed when I select the date is:

`March-Monday-YYYY`

This demo was from edge2.  The application config's date formatting settings are set to:

![image](https://cloud.githubusercontent.com/assets/1377228/6674251/6ad67614-cbe6-11e4-9a1d-3bf3541a84d8.png)

This worked before the #601 update went in.  I'm betting it's a simple date formatting issue.

**Comment by gsteimer** [comment]
On second try - setting the date always sets the date to today, even if I pick a date in the future:

![set-effective-date-prop](https://cloud.githubusercontent.com/assets/1377228/6674373/21f6810e-cbe7-11e4-8254-80f3774ef92d.gif)

**Comment by gsteimer** [comment]
@b-k-white @joehof - after talking to Joe, I was able to get this working on edge1 and edge2 properly.  It's really odd though - I had the timezone set for each to America/Chicago, so the App Config was definitely updated.  TO fix it, I changed the Timezone to empty, verified it was still an issue, then changed it back to America/Chicago, and it magically started working again.

Should we just chalk this one up to cached configs?

**Comment by b-k-white** [comment]
@gsteimer @joehof - There could possibly be something wrong still here after talking to Joe, but I tried clicking around to see if I could recreate the issue but could not.

**Comment by gsteimer** [comment]
@b-k-white - Ok, when you and @joehof think this has been tested enough, I'm fine with closing this.  We can always re-open if it crops up again.

**Comment by gsteimer** [comment]
We definitely need to figure this out.  I saw it again during my demo today.  The date appeared weird and did not actually set to anything but today's date.  

The really weird thing is that if I `ctrl-R` refresh and try again, it works perfectly.  If I then logout, log back in and try again, it goes back to being messed up.  See below:

![set-effective-date-prop](https://cloud.githubusercontent.com/assets/1377228/6712835/b6c44412-cd5c-11e4-8515-8febbd16c868.gif)

@b-k-white @joehof

**Comment by b-k-white** [comment]
Fixed the formatting issue. 
CR - Joe
HPI R - 11903
