### ISSUE TITLE
Set Effective Date Condition on Form Not Appearing Correctly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#619]
See the screenshot below.  On edge2, I created a form and routed two documents on it.  Once the form and docs are approved, I should be able to set effective dates from the doc (doc action) or the form (folder action).  The doc action appears correctly in the controlled documents trac, but the action on the Wizard trac does not appear correctly:

![image](https://cloud.githubusercontent.com/assets/1377228/6695619/9a4c757c-ccb0-11e4-8f0f-058205fe9cce.png)

From looking in chrome, it seems like the iscontrolleddocapprovedlifecyclestate condition is coming back invalid:

![image](https://cloud.githubusercontent.com/assets/1377228/6695633/adc8a4fe-ccb0-11e4-9926-4833d1e379fc.png)

I think that something got messed up with this action when we tried setting it up for documents vs. forms.  It looks like it's checking to see if the _form_ is in the Approved state, not the _attached docs_, Some notes:

- I think the action and conditions are setup correctly for the set effective date from doc action, BUT not when using this action from the form
- When using the action as a form action, the conditions need to be slightly different:
  - The user is a wizard doc editor
  - There's at least one attached document
  - ALL attached document is in the Approved lifecycle state 

I'm thinking this will only be an issue in Alfresco.  In Documentum, the form and controlled doc lifecycle states are the exact same thing.  So even though the code is wrong, the action will appear.

If some docs become effective, and some are still approved, the user will have to go into the individual documents to set the effective dates since the action will no longer show up on the form.

**Comment by gsteimer** [comment]
We definitely need to figure this out.  I saw it again during my demo today.  The date appeared weird and did not actually set to anything but today's date.  

The really weird thing is that if I `ctrl-R` refresh and try again, it works perfectly.  If I then logout, log back in and try again, it goes back to being messed up.  See below:

![set-effective-date-prop](https://cloud.githubusercontent.com/assets/1377228/6712835/b6c44412-cd5c-11e4-8515-8febbd16c868.gif)

@b-k-white @joehof

**Comment by aviking** [comment]
@gsteimer would we have to create another bean for a -Wizard version of the setEffectiveDate action because they have different conditions?

**Comment by aviking** [comment]
After looking into this a little bit, it looks like there are two main issues. One when evaluating the actions for a form the workflow document's objectId's are not beeing added to the url in order to check. The second issue is that the state of the form is aw:formApproved, but the condition on the bean is checking for aw:approved.

**Comment by aviking** [comment]
Created a new action called SetEffectiveDateFromForm, which can be configured as a folder action on the wizard trac.

Fixed with HPI Commit: 12664 and OC Commit: 11980
CR: Don H

**Comment by gsteimer** [comment]
Note for future reference, the fix here is different than my original suggestion since folder actions have no good way to run conditions against related objects.  So, @aviking did this:

1. Create a new action that works against the form
1. The new action appears only when the form is in the `Approved` state
1. When the action runs, any document not in the `Approved` state will disallow setting the Effective Date.  This handles the scenario that some documents are Effective, but some aren't.
