### ISSUE TITLE
Typeahead: clearing user input after options have arrived

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#623]
TODO:

- [x] Wizard
- [x] Form Support (Search & Bulk Upload)
- [x] Queryable Typeahead? (throttle network latency)

Revision: 11897
Author: mblum
Date: 2015-03-18 15:35:42.531298
TYPEAHEAD: adding disabled tag and a spinner when there are no options to display to avoid a user's input being wiped after options have arrived from the server.

M	/trunk/code/app/templates/common/typeahead/typeahead.html
M	/trunk/code/app/modules/common/typeahead.js

**Comment by mikeblum** [comment]
@grahamsinger  can this be closed?

**Comment by grahamsinger** [comment]
I believe so. I think the fixes in #658 should have taken care of these problems.

**Comment by grahamsinger** [comment]
Tested on Edge to confirm; no errors of this kind found.

(Previously fixed with revision #12160.)
