### ISSUE TITLE
Manage Workflow Documents - Refreshes needed when adding/removing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#624]
See the screencam below.  The action is attaching and removing documents properly, but better refreshes are needed on the action itself as well as in related objects:

- [x] Adding - Refresh related objects
- [x] Adding - Should take the user to the 'Controlled Documents' tab after docs are added
- [x] Removing - Refresh related objects
- [x] Removing - List of attached documents in 'Controlled Documents' tab needs refresh.

![attach-wf-doc-refresh-related](https://cloud.githubusercontent.com/assets/1377228/6733708/cd8a8fb0-ce21-11e4-9128-f78714eeffad.gif)

@dgrumieaux @mikeblum - some of these I'm guessing will be needed for our current client (action refreshes), but I'm fine with some of them (related objects refresh) spilling into HPI 2.4 if you think the client will be OK with it.

**Comment by mikeblum** [comment]
Can't seem to reproduce in client environment,

**Comment by gsteimer** [comment]
Tested this again on edge2 and it works fine.  Guessing this was merged in from a client branch a while back...
