### ISSUE TITLE
Notification Bell not displaying in IE9

### ISSUE THREAD

**Issue by ladams13** [tsgrp/hpi#634]
I noticed in IE9 for my client that the notification bell does not appear.  I also tested on edge1 in IE9 and saw the same issue.  I changed the glyphion to another bootstrap image 

Bell:
![image](https://cloud.githubusercontent.com/assets/5861266/6973411/3f20e758-d950-11e4-8211-ea5dc977b81b.png)

exclamation-sign (spacing is off because I updated the image in dev tools):
![image](https://cloud.githubusercontent.com/assets/5861266/6973456/9aacccf4-d950-11e4-9774-98dccd866626.png)

**Comment by ladams13** [comment]
@grahamsinger forwarded me an email of options when setting the glyphicon originally.

Bell and flag seemed to be the final contenders.  The flag does work in IE9 (see below), would that be a suitable replacement?

![image](https://cloud.githubusercontent.com/assets/5861266/6974015/b14ca28c-d954-11e4-91b3-dba951a9d918.png)

Comment was another icon mentioned (I think that is the same as annotate action though, so we may want to stay away from that) -

![image](https://cloud.githubusercontent.com/assets/5861266/6974050/f9e02dc0-d954-11e4-862b-77819b5ae9d5.png)
 
@gsteimer @cmlewis

**Comment by cmlewis** [comment]
I generally like the bell icon... is there some custom CSS on the bell icon that TSG did that is throwing it off? I believe the bell is a normal glyphicon as well.

**Comment by ladams13** [comment]
I think the bell is a good fit as well.  Visibitily, color, opacity, font-size, margin-left, margin-top and padding are assigned to the glyphicon.  But the same styling is applied to the flag and exclamation point above in my screenshots and they work.  Unfortunately, after doing some research online I found that there are some glyphicons that just don't work in IE 8 or 9

**Comment by cmlewis** [comment]
That's really odd. I think the exclamation would be nice if we can make it a little bigger and the same orange color. The flag isn't bad either.

**Comment by jrubins** [comment]
This seems really odd to me as well since the icons should all be in the same file. I suggested that we could look at using the separate, full glyphicon set that we have (we have both the icons that are included for free with Bootstrap and the full glyphicon set we purchased separately). That other set also has a bell icon - the syntax for using it is different though and I'm pretty sure Bowen was the one that introduced the new set into HPI (we originally bought it for OA).

**Comment by gsteimer** [comment]
I definitely think the bell is the best icon to represent notificaitons.  If we can't get the bell to work, would it be hard to make the icon configurable in app config?  I'd hate to have to choose a different icon just for IE9, which clients will hopefully be moving away from.

**Comment by cmlewis** [comment]
@jrubins Do you know if the BS3 icons are images or a web font? I think they're a web font, but I agree that it's odd some would show up and some wouldn't. @ladams13 I can probably help you take a look today if you'd like.

**Comment by ladams13** [comment]
fixed in HPI revision #11993

Updated the bell to pull from the Glyphicons full set rather than the bootstrap free icons
