### ISSUE TITLE
Active Wizard Timing Emails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#636]
The Active Wizard can send out special "timing emails" upon the following actions:

- Submit Timing
  - [x] When the form is submitted for workflow OR 
  - [x] When the form is finished if no workflow is used in the form (normal AW flow)
  - [ ] When the form is finished if no workflow is used in the form (AW streamline mode)
- [x] Approve Timing - When the form is approved
- [x] Reject Timing - When the form is rejected

The timing emails should all be FTL Template emails so once these are all in place, the `email-template-*` files should be removed from the `3.wizard/classes` folder.  The emails should also include the Form and any supporting documents as attachments.

Issue - ensure that Submit Timing still works (should have worked for a previous client, but may have been broken recently)
Enhancement - support Approve and Reject timing.

**Comment by gsteimer** [comment]
I just tested the submit email timing using the `TS Email Action WF` page set on edge1 and it definitely did not send the email properly.

@dgrumieaux @mikeblum - I'm pretty sure that our first HTML5 client uses this, so hopefully it's not an issue on their UAT branch and that something broke the functionality in trunk.

**Comment by mikeblum** [comment]
sendEmailNotifications in pagesetinstanceuploadutils.js will need to be updated to reflect the new contract with OC's sendEmail endpoint.

**Comment by mikeblum** [comment]
This line in pagesetinstanceuplaodutils will now ned to look like this:

    	//configre sending hard-coded email addresses in wizard forms
	var sendEmail = module.config() && module.config().sendEmail ? module.config().sendEmail : true;

Originally, sendEmail flag had to be configured to send timing emails in each config-project. this new line makes it permissible to send timing emails without configuration.

**Comment by gsteimer** [comment]
@mikeblum - is this done?  @RudraVishweshwar was asking me for something new to work on - just wanted to make sure since I didn't see any new activity here...

**Comment by mikeblum** [comment]
I have a few outstanding questions but submit,  reject and approve work.

**Comment by gsteimer** [comment]
Emails are sent out for all timings except for submit timing emails when the form is in streamline mode.  Closing this in favor of https://github.com/tsgrp/ActiveWizard/issues/228
