### ISSUE TITLE
Manage WF Docs on Alfresco - Attached to form 'ABC' displaying wrong name

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#638]
The Manage Workflow Docs action correctly prevents users from attaching a workflow document to more than one form.  However, on alfresco, the error message displays the controlled doc's folder name rather than the form name.  This only happens on Alfresco:

**Alfresco - note the incorrect attached to form**
![image](https://cloud.githubusercontent.com/assets/1377228/7076626/5dc1de12-ded0-11e4-9f2d-5f2a53b81438.png)

**Documentum - displaying the correct Form Name**
![image](https://cloud.githubusercontent.com/assets/1377228/7076647/76517bf4-ded0-11e4-958d-dfb83e5d85d3.png)

**Comment by aviking** [comment]
Fixed with OC commit: 11799. CR Dan G
