### ISSUE TITLE
Workflow tasks with same priority are being created in sequence instead of parallel

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#639]
In the Active Wizard, workflow roles with the same priority are meant to have their tasks created in parallel when both roles are tripped. Right now when multiple priority 1 roles are tripped, the tasks are created in sequence instead of being created in parallel. 

@mikeblum - I think this fix should be simple. We just need to, in the frontend evaluation code, bucket roles by priority into each wizardActivity (a wizardActivity is a collection of tripped roles that have the same priority).

**Comment by mikeblum** [comment]
Revision: 12056
Author: mblum
Date: 2015-04-14 10:00:28.510930
WIZARD WORKFLOW: Parallel and sequential Wizard Aactivites are now supported. Closing: https://github.com/tsgrp/hpi/issues/639 CD dgrumieaux

A	/trunk/code/test/tests/modules/wizard/wizard/workflow/wizardworkflowSpec.js
M	/trunk/code/test/tests/modules/wizard/wizard/questionSpec.js
M	/trunk/code/app/modules/wizard/models/workflow/workflow.js
