### ISSUE TITLE
Set Effective Date not working

### ISSUE THREAD

**Issue by aviking** [tsgrp/hpi#640]
In certain scenarios when a user tries to set the effective date the Knockout bindings that link the datepicker to the actual observable doesn't get set up properly. See gif below.
![alfrescoseteffectivedateissue](https://cloud.githubusercontent.com/assets/2895070/7121331/752c1700-e1d9-11e4-90c6-631206e709f3.gif)

**Comment by aviking** [comment]
A fix for this issue will be going into trunk with the Folder Browser merge.

**Comment by gsteimer** [comment]
@aviking - can you merge this in to trunk separately from the Folder Browser?  That's a better approach from a best practices standpoint and it'll make it much easier for me to merge into the 2.3 tag (which I'll want to do for this one)

**Comment by aviking** [comment]
@gsteimer - Yeah I can do that.

**Comment by aviking** [comment]
Fixed with commit 12049.
