### ISSUE TITLE
Notification Bell not highlighting

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#641]
See the screencam below.  I have a notification, but the bell icon does not light up.  I think this was introduced in the changes for #634.

![bell-icon-light](https://cloud.githubusercontent.com/assets/1377228/7123487/f86bf762-e1e7-11e4-8e59-23a76f516ada.gif)

@ladams13 - not sure if this affects your current client

**Comment by cmlewis** [comment]
Fixed alignment and coloring issue, as well as a bunch of messy CSS in notifications.styl in SVN rev 12116.
