### ISSUE TITLE
Search Running Indicator - Sometimes does not display

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#643]
See the screencams below - I'm guessing this is a timing issue, but sometimes it's possible to run searches where the screen does not dim to let the user know that the search is running:

**Working**
![search-running-indicator-working](https://cloud.githubusercontent.com/assets/1377228/7142002/ce8b353a-e29a-11e4-8c67-968ba0caa173.gif)

**Not working**
![search-running-indicator-fail](https://cloud.githubusercontent.com/assets/1377228/7142008/d41b2460-e29a-11e4-91f3-9d024fc541dc.gif)

Both of the above screencams were taken minutes apart on edge1.

**Comment by gsteimer** [comment]
Note - I've always seen this when a search has already been run.  For example, load the search page and run a search, the running indicator will display.  Then run another search (without refreshing the page) and it will not display.

**Comment by ZachGerth** [comment]
Fixed with Revision # 13933.
