### ISSUE TITLE
Property integrity check on empty folder

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/hpi#647]
Currently if the action property integrity check is ran on an empty folder, and ugly response is shown.
![propinteg](https://cloud.githubusercontent.com/assets/8796489/7206297/7e6913ee-e4f5-11e4-9cae-56ebff4f1700.png)

Two possible solutions for this:
1. Add a condition that checks for child docs. Be careful of the folder notes child.
2. Show a response that explains that no child docs exist.

**Comment by gsteimer** [comment]
Unless a client wants to add this to a project, I'd say we should just do whatever option is easier.  I'm guessing that's No. 2 above.

**Comment by grahamsinger** [comment]
@b-k-white Can this be closed?

**Comment by grahamsinger** [comment]
@b-k-white can this be closed?

**Comment by b-k-white** [comment]
Yes, this was fixed with
HPI -12352
CR - Zaq
