### ISSUE TITLE
Aspect attributes that are not applied to or set on a node show up as "undefined" in Alfresco 5

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#651]
![selection_016](https://cloud.githubusercontent.com/assets/547941/7234537/7817a320-e74d-11e4-9588-543113c7536a.png)

In Alfresco 5, the cm:lockOwner property only exists on a node if that node is checked out (it is granted by the workingCopy aspect). Thus, when a node is not checked out, HPI shows "undefined" for the lockOwner value.

This situation in particular may be easy to handle (just show blank instead of undefined). Keep in mind this shows up in multiple places (check stage info for another confirmed location), so perhaps this would best be handled in oc.js.

This raises the question - how do we want to handle properties in HPI that do not currently exist on the node we are looking at?

**Comment by gsteimer** [comment]
I'd imagine this same thing will happen for any attribute that's not on the node because an aspect isn't applied.  Whatever solution we come up with should handle any attribute, not just `cm:lockOwner`.

**Comment by gsteimer** [comment]
@dgrumieaux - are you sure this is limited to Alfresco 5?  @cmlewis seems to think this would be an issue on 4 as well.

**Comment by cmlewis** [comment]
I confirmed that this is likely only an issue with non-mandatory aspects. We properly handle attributes from mandatory aspects (with dictionary service, I assume), even if they aren't present on the node yet (when you view in node browser).

**Comment by dgrumieaux** [comment]
This could be an issue for 4 or 5, I just noticed it on 5 because the
lockOwner attribute was changed to not be on non-wc node.

**Comment by gsteimer** [comment]
This is really only a problem with the checked out by attribute.  Once we start supporting non-mandatory aspects in HPI (#109), this will become more of an issue.

**Comment by gsteimer** [comment]
@dgrumieaux - does the new NMAC in HPI 2.6 fix this?  Or is it still an issue?

**Comment by dgrumieaux** [comment]
I believe there may still be an open question of how NMAC should display search results and other property displays when nodes do not have property values - but I believe we can track that as part of NMAC enhancements. Closing this issue
