### ISSUE TITLE
Property Integrity Check Action - Handle Blank Values Properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#652]
While configuring this action for the insurance trac on edge, I noticed some issues when properties are blank.  In all cases below, I'm checking the Policy Holder attribute

- [x] When a property is blank on the folder and blank on all of the documents, the property label doesn't show up: 
![image](https://cloud.githubusercontent.com/assets/1377228/7260829/afb3942a-e832-11e4-98ce-e6084540b829.png)
- [x] When the property is populated on the folder, but blank on one or more documents, the documents do not appear in the list.  In this case, the action is correctly finding one document with an inconsistent value.  But a third document with a blank value isn't even in the list: 
![image](https://cloud.githubusercontent.com/assets/1377228/7260921/6b04c8f2-e833-11e4-9198-e1dca5960793.png)
- [x] When the property is populated on the folder, and one document has the same value, but all others are blank, the check incorrectly shows the property as valid.  In this case, there are really two other documents that have a blank value but are not being flagged: 
![image](https://cloud.githubusercontent.com/assets/1377228/7260901/45e07f3a-e833-11e4-87b2-398ca5d460c1.png)

@benallenallen @joehof @b-k-white

**Comment by b-k-white** [comment]
Fixed an if statement that was having empty strings count as not on the sub-document. Wrote two unit tests to back up this fix.
CR- ZK
HPI - 12110

**Comment by gsteimer** [comment]
I think this is minor, but see the screen below.  When the attribute is blank on the folder, it displays "N/A, not on any document" which I believe is the message that should appear when the attribute exists at the folder level, but not on the documents.

![image](https://cloud.githubusercontent.com/assets/1377228/7275799/860039fa-e8cb-11e4-901f-8e6dcad0f422.png)

@benallenallen - what do you think?  At the folder level, should it show nothing, or some message like "Attribute is Blank".

**Comment by b-k-white** [comment]
I noticed this yesterday, I was thinking "N/A, Attribute not configured on
document(s)"

**Comment by b-k-white** [comment]
Fixed this issue along with adding more robust unit tests.
CR - ZK
HPI - 12112
