### ISSUE TITLE
Bubble errors when uploading document fails

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#653]
In Bulk Upload, we don't show to the user why a document upload fails. Sometimes the reason why that a document fails is something as simple as when in Alfresco a duplicate file name already exists in the folder. It would be useful to display to the user a useful error message when errors happen.

**Comment by aviking** [comment]
I have it showing the Text response from the failed action. Is this what you were looking for? See Screen shot below:

![bulkuploaderrorbubbling](https://cloud.githubusercontent.com/assets/2895070/7432429/a983418c-efed-11e4-93aa-29a8ff6790eb.png)

**Comment by gsteimer** [comment]
This is good, but I think the idea was to take it one step further and say *why* each document failed to upload (in a user-friendly way).

@dgrumieaux - correct?

**Comment by dgrumieaux** [comment]
The frontend is now doing what it should be, now the Action Executer should be catching the error and rethrowing with a more user friendly message.

**Comment by aviking** [comment]
So you're saing that when we set the error in OC, it should have a better message like: "Two files in the same folder cannot have the same name" ? But you like the fact that it's displayed in HPI? @dgrumieaux

**Comment by aviking** [comment]
Fixed with HPI Commit: 12193 and OC commit: 11550.
CR by Dan G.
