### ISSUE TITLE
Folder Browser Issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#654]
I'm seeing a number of issues in the folder browser.  See the screencam / screenshots below.  

- [x] The screen looks fine with the 25/Page default, but when I change to 10 per page, the pagination controls do not display.
- [x] The results are not sorted.  I'm guessing this is because in normal HPI Search, the results are sorted based on a configuration in advanced search, which we don't have here.  Should we just say that the results will be sorted based on the first attribute in the table?
- [x] The right click menu is way off to the right

**Sorting and Pagination**
![folder-browser-pagination](https://cloud.githubusercontent.com/assets/1377228/7283010/2b2dcac8-e8f9-11e4-89b0-f42f7adda09b.gif)

**Right Click Menu**
![image](https://cloud.githubusercontent.com/assets/1377228/7283000/2149627e-e8f9-11e4-8b56-5935884d29fc.png)

FYI - @aviking @joehof

**Comment by gsteimer** [comment]
- [ ] Another issue - it seems that the Folder Browser's "Force Actions into Modal" functionality affects the stage as well.  For example, see the insurance trac, where View Properties is configured as a right side action

1. Run view properties on a doc in the stage - correctly displays on the right
1. Load an insurance folder in Folder Browser and run view properties on a doc - correctly displays as a modal
1. Now, go back to the stage and try to view properties again.  It will incorrectly view as a modal until you hard refresh.

**Comment by aviking** [comment]
Fixed these issues, Code reivew by Dan G, HPI commit: 12127
