### ISSUE TITLE
Folder Browser - Allow tracs to be ordered

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#656]
Currently, it looks like the folder browser orders the tracs based on the order they were added to the admin config.  Unfortunately, there's no way to reorder this list.  In order to allow the admin to change the order we should order the tracs based on the trac order in the 'Tracs' tab in the admin.

Folder Browser Admin:
![image](https://cloud.githubusercontent.com/assets/1377228/7283945/c3406f54-e8ff-11e4-8f79-e0cab8074f21.png)

Folder Browser Trac Order:
![image](https://cloud.githubusercontent.com/assets/1377228/7283959/ce987f86-e8ff-11e4-993b-f2cdde91df9e.png)

Trac Config Order:
![image](https://cloud.githubusercontent.com/assets/1377228/7283971/e7ce9904-e8ff-11e4-9157-7e4790a7c63f.png)

**Comment by aviking** [comment]
I have made it so that the order follows the order the tracs are ordered in the Trac Config. (The trac still only shows if it has been configured in Folder Browser). If a Root trac has been configured, it apears at the bottom of the list. 

Fixed locally just waiting a Code Review.

**Comment by aviking** [comment]
Code reivew by Zaq. Fixed with HPI commit 12140
