### ISSUE TITLE
Loading previous version of controlled doc in the stage on Alfresco issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#660]
When loading a previous version in the stage of a Controlled Doc on Alfresco, a couple issues occur:

- [ ] Actions do not load (see stack trace below).
- [ ]  The version number is wrong in the top right corner

![cd-view-previous-version](https://cloud.githubusercontent.com/assets/1377228/7352580/335fa1bc-ecd2-11e4-86d0-6507483884ed.gif)

Here's the stack trace from the server:

```
11:33:18,356 ERROR [com.tsgrp.opencontent.rest.RESTService] [ajp-apr-8009-exec-1] There is no valid lifecycle key for nodeRef + a9d75b7c-9b8d-4f08-bc38-3fbfbb7c2b89
com.tsgrp.opencontent.core.exception.OCRuntimeException: There is no valid lifecycle key for nodeRef + a9d75b7c-9b8d-4f08-bc38-3fbfbb7c2b89
	at com.tsgrp.opencontent.alfresco.lifecycle.AlfrescoEmbLifecycleImpl.getCurrentStateRepoValue(AlfrescoEmbLifecycleImpl.java:112)
	at com.tsgrp.opencontent.alfresco.lifecycle.AlfrescoEmbLifecycleImpl.getCurrentState(AlfrescoEmbLifecycleImpl.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by dgrumieaux** [comment]
An enhancement here that would address the actions failing to load for the
OC Action Service would be to, whenever we throw an error in a condition,
to not throw the error to the client. Instead, just mark that condition as
failed and output the log, then continue processing conditions.

**Comment by ikaikajcorrea** [comment]
Fixed with OC Commit 11946
CR: George
