### ISSUE TITLE
Folder Browser Table doesn't use Cookie to store user visable/hidden columns for search results table

### ISSUE THREAD

**Issue by aviking** [tsgrp/hpi#661]
Currently the Folder Browser table view doesn't store user prefered shown table columns and column ordering on a cookie. In the future we want to store any folder ordering and adjustments to shown/hidden columns on the userPrefernces cookie.

**Comment by aviking** [comment]
Fixed with HPI Commit: 12658. CR: Zaq

**Comment by gsteimer** [comment]
@aviking - I'm not seeing this work on edge2 - can you reconfirm your fix?

**Comment by aviking** [comment]
Fixed with HPI Commit: 12665
CR: Don H
