### ISSUE TITLE
Search All Versions - Broken in IE9

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#662]
See the screencam below - the search on all versions feature in advanced search seems to be broken on IE9.  It defaults to checked (should be unchecked), and never actually searches on all versions:

![search-all-versions-ie9](https://cloud.githubusercontent.com/assets/1377228/7377891/e3f3e268-edae-11e4-8f5c-31b675cbf665.gif)

For reference, here's the results in chrome:

![image](https://cloud.githubusercontent.com/assets/1377228/7377909/0f3cdd9e-edaf-11e4-8b4f-437bedcdffdf.png)

@dgrumieaux @mikeblum

**Comment by mikeblum** [comment]
Got a fix - waiting for a merge into trunk.

**Comment by mikeblum** [comment]
Revision: 12153
Author: mblum
Date: 2015-04-30 10:00:07.568684
SEARCH ALL VERIONS: support for IE9 and modern browsers

M	/trunk/code/test/tests/modules/search/advancedsearchSpec.js
M	/trunk/code/app
M	/trunk/code
M	/trunk/code/app/modules/search/advancedsearch.js

**Comment by mikeblum** [comment]
Reset not working on edge1 in modern browsers. Have a fix on a client branch.

**Comment by mikeblum** [comment]
r12313 | mblum | 2015-05-22 15:56:54 -0500 (Fri, 22 May 2015) | 1 line

RESET SEARCH: search all versions now correctly blanks out on clicking reset in advanced search.
