### ISSUE TITLE
Folder Browser - Only Displays Content of Top Folder

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#663]
See the screencam below.  If you click on a subfolder, the top folder in the tree is loaded.

![folder-browser-open-wrong-folder](https://cloud.githubusercontent.com/assets/1377228/7396474/e1ffbbc2-ee66-11e4-930f-db52805e421a.gif)

FYI - @aviking

**Comment by aviking** [comment]
Have it fixed locally, awaiting Code Review. It was caused by the click event propogating up to the top level from. All that was needed was an event.stopPropogation() call.

**Comment by aviking** [comment]
Fixed with HPI commit 12154
