### ISSUE TITLE
Actions don't work in the stage after coming from Folder Browser

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#664]
If you load a folder in the folder browser and then go back to the stage, modal actions do not load and fail with this error:

![image](https://cloud.githubusercontent.com/assets/1377228/7396996/ef414130-ee6a-11e4-83fd-5f60f1e46ef4.png)

Additionally, add documents seems to not load properly:

![image](https://cloud.githubusercontent.com/assets/1377228/7397065/87e2687e-ee6b-11e4-8b09-b4fd9635e1a1.png)

Refreshing the page clears something out and it starts working again.

See the screencam below:

![folder-browser-jacks-up-actions](https://cloud.githubusercontent.com/assets/1377228/7397123/ecf107e8-ee6b-11e4-8f34-e9714d3fa31f.gif)

**Comment by aviking** [comment]
Have this fixed locally, wating for a Code Review. It was an issue with how the folderbrowser view was being created and destroyed.

**Comment by aviking** [comment]
Fixed with HPI Commit 12169
