### ISSUE TITLE
Print Fails in pdf.js

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#665]
The print icon in pdf.js throws a couple of javascript errors rather than printing:

![image](https://cloud.githubusercontent.com/assets/1377228/7397253/c1aeae18-ee6c-11e4-8e2a-48f93e1532d3.png)

![image](https://cloud.githubusercontent.com/assets/1377228/7397268/d66e8332-ee6c-11e4-82e4-d65c8f763cfe.png)

**Comment by mikeblum** [comment]
As a note going forward, we are not using the viewer.,js project but rather the pdf.js project. These are two separate projects:

https://github.com/mozilla/pdf.js

vs

https://github.com/kogmbh/ViewerJS

**Comment by mikeblum** [comment]
r12205 | mblum | 2015-05-12 10:27:58 -0500 (Tue, 12 May 2015)

PDFJS: updated pdf.js build to the latest release from https://github.com/mozilla/pdf.js and this resolves #665

**Comment by gsteimer** [comment]
Great - thanks!  

As for which project we're using - it is my understanding that we are using viewer.js which wraps pdf.js.  Is that correct?  @eschwarzbeck @benallenallen
