### ISSUE TITLE
Make Search Sidebar Minimize Upon Search on Smaller Browsers

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#668]
Currently in the Search interface on smaller browsers where users have many search columns configured, the search criteria sidebar takes up a lot of valuable screen real estate. This enhancement would target hiding the sidebar whenever a search is executed, and having a button available to showing the sidebar when the user needs to tune their criteria.

**Comment by gsteimer** [comment]
This could be a good candidate to put in a user preferences file - some users may want this, others won't...

**Comment by dgrumieaux** [comment]
@grahamsinger was this merged into trunk?

**Comment by grahamsinger** [comment]
Yep, sorry.  Forgot this existed.  Implemented with rev13011.

**Comment by gsteimer** [comment]
I dont't this this is working on edge - see below.  Is there anything I need to do in the admin to get this to work?

![image](https://cloud.githubusercontent.com/assets/1377228/9736053/9b2eeea6-5604-11e5-907b-481e85931119.png)

@dgrumieaux @grahamsinger

**Comment by grahamsinger** [comment]
Yeah, try checking the checkbox in the User Preferences tab.

**Comment by gsteimer** [comment]
Ah, I didn't know that was there.  I think we need to reorganize and reword a little bit.  Here's how it looks now:

![image](https://cloud.githubusercontent.com/assets/1377228/9737319/ac019cae-560b-11e5-9127-4814e25ea6ad.png)

Some small stuff we should change:

1. The order of the sections across the top is confusing.  There's a bigger enhancement here (see #807), but for now I think we just swap the dashboard settings with the search sidebar (make dashlet reset the last one).
1. This could be reworded to be a little more user friendly:
  - Title: `Search Side Bar`
  - Label: `Automatically hide the Side Bar upon Search Execution?:`
1. I think the div for this section is missing the `col-md-3` class, causing this section to look a little messed up in small browsers/mobile.
1. The checkbox works, but a yes/no slider would be better, and would fit more with the look of HPI.

**Comment by grahamsinger** [comment]
Fixed with rev.13055.

4 changes listed above were made.

CR: MB

**Comment by dgrumieaux** [comment]
This also should minimize when a saved search is selected for execution.

**Comment by gsteimer** [comment]
@dgrumieaux - I just tested executing a saved search on edge2 with my user prefs set to hide the search sidebar and it seemed to work fine.  I'm closing this, but let me know if I'm missing something...
