### ISSUE TITLE
Form Support: Repeating date controls are not showing the typed-in/selected dates

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#670]
![fs-repeating-dates-bug](https://cloud.githubusercontent.com/assets/3905463/7431632/071d5290-efe6-11e4-8372-0bcc28145737.gif)

But the control is updating correctly in the background. This appears to just be a rendering issue.

**Comment by b-k-white** [comment]
Fixed with unit tests, the display array wasn't being changed on add/remove events.
CR - ZK
HPI - 12325
