### ISSUE TITLE
Wizard + WYSWIG: more than five CKEDITORs at a time causes severe performance issues

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#675]
Currently, to support both mobile and desktops views of a Wizard form, we maintain two separate versions of the form that live on the DOM at the same time. To solve this issue, we'll only want to render a CKEDITOR instance on the textarea that currently has focus, otherwise fallback to a rendered textarea or div if raw HTML was added by the CKEDITOR instance.

**Comment by gsteimer** [comment]
Would another option be to say that you only get the WYSIWYG in the desktop view?

Marking this as 2.x - I'm also fine with saying that the wysiwyg is not yet supported for the repeating table.

**Comment by mikeblum** [comment]
r12271 | mblum | 2015-05-19 16:56:59 -0500 (Tue, 19 May 2015) | 1 line

MERGE from wizard_wyswig: wyswig controls in the wizard now toggle on ands off based on the focus of the user. CR jhof
