### ISSUE TITLE
Spacing for Related Objects Icons

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#676]
See the screenshot below - what happened to cause the odd spacing in the related objects icons?

**Edge2 from today**
![image](https://cloud.githubusercontent.com/assets/1377228/7613024/d7e3675e-f953-11e4-8e4b-4700f59f7692.png)

**Release2**
![image](https://cloud.githubusercontent.com/assets/1377228/7613032/dfade130-f953-11e4-81cd-bedf6249fd7b.png)

**Comment by b-k-white** [comment]
Fixed using custom css instead of non-breaking spaces.
CR - Christy
HPI - 12210
