### ISSUE TITLE
Sign Out button - Undefined Text

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#677]
The Sign Out button currently says 'undefined' on edge:

![image](https://cloud.githubusercontent.com/assets/1377228/7613346/c7041864-f955-11e4-99f1-f6ab449f35b5.png)

@dgrumieaux - we talked about this before (it's an issue with L10N), but I thought you fixed it.  Did you fix not yet make it into trunk?  Edge1/2 both still have the undefined text.

**Comment by dgrumieaux** [comment]
I thought I fixed it, but instead I believe it is an issue with
localization on Tomcat builds. I will roll back the changes and test on
Tomcat before recommitting.

**Comment by gsteimer** [comment]
Fixed by @dgrumieaux in HPI Revs 12217 & 12238
