### ISSUE TITLE
Loading a picklist clears out first character in autocomplete 

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#678]
![licecap-001](https://cloud.githubusercontent.com/assets/547941/7614333/ba76854a-f95b-11e4-80ee-13fa83b1eafd.gif)

See the gif. The first time that I type in "1", the 1 is deleted and no values are dropped down. It should behave like it does the second time I type in "1".

**Comment by grahamsinger** [comment]
Fixed with revision 12354.

If the defaultItem of the config was blank, it would replace the typeahead input with that blank value on the valueHasMutated() call on the picklistItemsArr.

CR: ZK
