### ISSUE TITLE
DocuSign - Should not list users in the system

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#681]
See the screencam below.  There are a few issues:

1.  The user should be able to type in *any* email address.  More than likely, this will be used to send docs out to 3rd parties for signature, not users in the system
1. I'm thinking we should remove the typahead all together.  I worry about putting this into client environments where there are thousands of users.

![send-to-ds](https://cloud.githubusercontent.com/assets/1377228/7640270/de6ee928-fa47-11e4-8e69-542f251f198a.gif)

@aviking - It looks like the tab does work, but only if the typeahead comes back with no results.  Moot point though, because I think we should just remove the typeahead.

**Comment by grahamsinger** [comment]
Fixed with revision #12285

CR: ZK

**Comment by gsteimer** [comment]
Just tested on edge - it looks like email addresses are only added to the list when the user hits the enter key.  User's aren't going to know to (or want to have to) do this.  Instead, the address should be added (if it's a valid email address) on blur.

The instructions text needs some updating as well.  It should say:

    Type in an email address to add it to the list of users that require signatures via DocuSign.

If it's not hard, an "add" button would be great to have here as well for users that are more mouse-focused.  I'm thinking of something like what the Manage Workflow Documents action has:

![image](https://cloud.githubusercontent.com/assets/1377228/7816886/94b0b1b0-0396-11e5-9986-45d414c154a5.png)

**Comment by grahamsinger** [comment]
Made the changes listen above with revision 12326

**Comment by grahamsinger** [comment]
FYI: Unit test added for previous "enhancement" with commit 12339.
