### ISSUE TITLE
Cloud Send Issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#684]
It looks like the send email fixes for #497 have messed up the Cloud Send functionality.  Here's what I can see:

1. The user should have to choose between attaching OR sending via ShareFile.  Currently, the interface allows you to do both, causing issues
1. Items added while the slider is on 'Attach' vs.'Share' don't seem to line up
1. The alignment of the attachment names is way off to the right.  Perhaps because I have this setup as a full pane action vs a modal?

![send-email-cloud-attach-issues](https://cloud.githubusercontent.com/assets/1377228/7713104/2c78e4ec-fe3b-11e4-8eed-56f1642ce643.gif)

FYI @dhartman25

**Comment by grahamsinger** [comment]
Fixed with revision #12324.

**Comment by grahamsinger** [comment]
Removed the 4th tab resulting in only one tab for better performance and clarity.  Also, changed the styling so that there isn't that unsightly gap between the checkbox and the object name.

CR: DH
