### ISSUE TITLE
Does HPI use Viewer.js or PDF.js?

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#685]
I've always thought that we used Viewer.js (ex: see Rubins' comments here: https://github.com/tsgrp/hpi/issues/529#issuecomment-74341977), but I've heard @mikeblum say that we really use PDF.js.  Which is it?

If it actually is PDF.js, we should change the text in the admin here:

![image](https://cloud.githubusercontent.com/assets/1377228/7748689/4ec898f6-ff8c-11e4-8fcf-04fe64df59b3.png)

**Comment by gsteimer** [comment]
From looking at the Viewer.js download, it includes an ODF viewer called webodf.js.  This file does not exist within HPI, so I'm guessing we actually do use PDF.js directly and not Viewer.js.

Thoughts? @mikeblum @benallenallen @eschwarzbeck

**Comment by mikeblum** [comment]
When I filed that print issue against viewer js their people said it was a
pdf. Js issue.  Based on the builds of the two projects,  we definitely use
pdf. JS

**Comment by gsteimer** [comment]
Thanks Mike.  @eschwarzbeck - you added this in to HPI.  Do you agree?

**Comment by eschwarzbeck** [comment]
Sorry, don't check this much. After talking with @mikeblum he is correct we use PDF.js it had a viewer.js file but not the actual project.

**Comment by gsteimer** [comment]
Admin updated in HPI Rev 12497
