### ISSUE TITLE
Image Viewer - Loads in whatever viewer was previously in the stage

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#686]
The image viewer works great, if it's the first viewer loaded in the stage.  However, if you load a document into PDF.js or Video.js first, and then click on an image, the image tries to load into the previous viewer rather than the image viewer.  See the screencap below:

![image-viewer](https://cloud.githubusercontent.com/assets/1377228/7749125/64fc7fc6-ff90-11e4-9939-84fefb668163.gif)

Notice that when I refresh the stage, the image viewer displays as normal.

**Comment by aviking** [comment]
Fixed with HPI revision: 12334
CR: Zaq
