### ISSUE TITLE
Allow async picklists to be completely loaded via dropdown button

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#692]

**Comment by gsteimer** [comment]
Note - the goal of this is to allow clients with large picklists to have the user friendliness of the dropdown arrow combined with the performance of an async picklist.

**Comment by grahamsinger** [comment]
Merged with revision #12415

**Comment by mikeblum** [comment]
@grahamsinger Dependent picklists are not updating when the parent picklist's value is changed a second time. Reproduce by changing a cascading picklist property in View Properties or in Advanced Search.

**Comment by grahamsinger** [comment]
Fixed at 12455.
