### ISSUE TITLE
Allow HPI to Use Data List Picklists

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#695]
We should update HPI to utilize @parzgnat's awesome Alfresco Data List picklists.  Main question to start - is this a new picklist type, or can we use the existing web service picklist?

![image](https://cloud.githubusercontent.com/assets/1377228/7961391/ef81d8ee-09cc-11e5-9378-efd00e3d79a2.png)

In any case, once this works, we should get the following working:

- [ ] Normal Picklist
- [ ] Cascading Picklist

I see two AMPs in SVN that could be what we want - valueAssistance and cascadingValueAssistance.  @parzgnat - given that we want to do cascading picklists, I'm guessing we'll only need the cascadingValueAssistance AMP?  Or is that wrong and we need both?

**Comment by gsteimer** [comment]
After talking to the HPI team, it sounds like we can use @parzgnat's data list picklists in HPI.  So perhaps this is more of an enhancement to make it more apparent in the HPI admin.  Perhaps give users a way to acutally pick the data list in the admin, vs. having to use an OC picklist?  A couple of things to think about though:

1. How would we make this not Alfresco specific on the front end?  Documentum does not have a data list concept
1. How would cascading picklists work?
1. However this ends up shaking out, we need to have a something on the HPI wiki describing how to setup HPI picklists to be backed with Alfresco Data Lists.

**Comment by dgrumieaux** [comment]
A consideration would be to have an OC picklist creation/add/remove
interface that would use the Alfresco data lists as the Alfresco
implementation and a Documentum picklist schema as the Dctm impl.

**Comment by aviking** [comment]
The abiltity to use datalists exists already. However the ability has be enhanced to now support cascading datalists via a lucene query picklists. See https://github.com/tsgrp/hpi/wiki/Picklists for instructions on how to set it up.
