### ISSUE TITLE
Picklist Config Async/Cache dropdown info icon

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#696]
Info icon should be beside/inline with the dropdown
![image](https://cloud.githubusercontent.com/assets/4852355/8163956/b76e1c5a-134b-11e5-9495-532fd7c907b8.png)

**Comment by gsteimer** [comment]
Whoever ends up doing this - we also need more information on this page.  Some things I've noticed:

1. There's no label for that dropdown.  What should it be?  Picklist Type?
1. 'None' doesn't really make sense as a picklist type.  What's a better name for it.  Something like Normal? Refetch?
1. The info icon for Cache picklists should indicate for how long the picklist information will be cached.  Is it cached until the server is restarted or when the user logs out?

**Comment by aviking** [comment]
Fixed with HPI Commit 12457
CR: George S.
