### ISSUE TITLE
Grid View and List View Collections do not handle Subtypes

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#698]
Currently if you Try to use GridView or ListView to view collections the properties do not show up. Additionally for list view there is no link to resolve to the stage (link is present for gridView). This is because collections can be with multipul object types and the only type that can be configured in the admin is "Document". Because of the way the GridView and ListView work if they are displaying the "Document" ObjectType, but not if it is any other ObjectType.

See screen shots:
![gridviewnoprops](https://cloud.githubusercontent.com/assets/2895070/8187984/a6c4159e-1418-11e5-8755-b10596c508f9.png)
![listviewnoprops](https://cloud.githubusercontent.com/assets/2895070/8187985/a6c60a48-1418-11e5-92c3-7b837e6982e6.png)

**Comment by gsteimer** [comment]
@aviking - is this only for when you try to configure a Document subtype?  If that's the case, then I think making this an enhancement is fine.  Basically - it works, as long as you only configure the root Document type.

However, if you're saying grid view and list view are always messed up in collections, we probably want to call this an issue and up the priority to 2.4.

**Comment by aviking** [comment]
This is an issue with GridView and ListView not displaying document properties for anything except base Document Type.

**Comment by grahamsinger** [comment]
So, after digging into this one, it seems this can be fixed with the right configuration.  You can, in fact, configure more than one type in collection config, it was just not obvious (to me at least) how to do so at first.  I'm not sure if this means we can close this, because it will still show the errors above if configured improperly.

**Comment by gsteimer** [comment]
I'm fine with leaving this one and marking it as an HPI 2.x issue as long as it works if HPI is configured properly.  @grahamsinger - can you describe what the 'wrong' configuration is vs. the 'right' configuration?  That will help when someone is trying to configure this 6 months from now...

**Comment by grahamsinger** [comment]
In order for this to be configured correctly, you need to have type configurations for all object types you want/will want to have in collections.  

For those who haven't done this previously, at the top of collection config, you need to make sure all potential object types you want to configure are showing under 'Selected Object Types:'.  If they aren't all there, you need to first click remove, then Ctrl+Click on all the object type you want in the list then click 'add'.

In the future, designing and implementing a more intuitive way of doing this might be good.

**Comment by gsteimer** [comment]
Unless anyone has any other thoughts, I think we would treat this one like #360 - basically you have to configure all known types and subtypes.

Note that table view does work properly for subtypes.

**Comment by gsteimer** [comment]
Closing since we've redesigned grid view and dropped list view.  See #1422
