### ISSUE TITLE
Property Integrity Check - Not ignoring folders that start with a dot (hidden folder)

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#699]
See the image below - the Integrity Check action is incorrectly flagging the .oc-info folder as invalid:

![image](https://cloud.githubusercontent.com/assets/1377228/8188429/8fba872c-141b-11e5-9c50-c1dfc94804a8.png)

In HPI, all folders that start with dot are considered hidden folders.  So the code here should be checking for any folder that starts with a dot (not just .oc-info).

The weird thing with this one is that, for some reason, the .folder-notes folder is not flagged, even though it exists in the repo:

![image](https://cloud.githubusercontent.com/assets/1377228/8188482/e652be06-141b-11e5-89b1-64132ca33b3f.png)

@b-k-white - not sure if this is an issue for your current client...

**Comment by grahamsinger** [comment]
Fixed at revision #12472

Made sure that all hidden folders are ignored.  Unit tested.
