### ISSUE TITLE
Allow Cascading Picklists to depend on more than one value

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#701]
According to @zkeller, this should work on the back end, we will just have to update the admin (See below) and make sure the HPI front end processes the data properly (it may already).

Admin Screen now:
![image](https://cloud.githubusercontent.com/assets/1377228/8210373/47772c06-14d7-11e5-833a-cad27c6e80c6.png)

Update to have a plus sign to allow admins to add another value.  Additional values should have another plus sign to add another row, as well as an X to delete an attribute dependency.

**Comment by aviking** [comment]
Fixed with HPI Commit 12503
CR: Zaq
