### ISSUE TITLE
Allow HPI to be able to utilize Glyphicon Pro icon set

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#703]
TSG purchased the Pro Glyphicon set for OpenAnnotate, but it has yet to be integrated into HPI.  

When doing this, hopefully just using the icon styles in the current admin will just work.  I'm thinking that we would simply remove the old icon set since all of those icons are included in the pro set.  If not, we'll have to come up with a way to separate the icon sets.  Perhaps make the pro icons use a prefix like `pro:`?

We should also change the modal here to point to the right page so that HPI admins have the full list of available icons:

![image](https://cloud.githubusercontent.com/assets/1377228/8213550/2c9a40ce-14e8-11e5-9948-db7935a308e3.png)

**Comment by cmlewis** [comment]
Note, the pro set is integrated HPI and sometimes they work, but I think they're an old set. glyphicons.css has the full set, but they don't seem to match the current docs. I wonder if we could upgrade to the latest set.

**Comment by peterkk** [comment]
commit #14111

Glyphicons - Incorporated PRO set of glyphicons - picking specific glyphs for stage & folder actions now from pro set.

CR-Jason
