### ISSUE TITLE
Dashboard - Persist dashlet ordering per user

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#704]
Currently, users can drag dashlets around if dashlet dragability is allowed per the admin config.  However, the dashlet order is not persisted.  This enhancement would make it so that HPI remembers the order of the dashlets per user.

Some notes that will need to be addressed before we can start this:

* Where should we store the user preferences?  We probably don't want to use a cookie in this case since some clients use Citrix to access HPI.  This clears out cookies each time the user loads a new Citrix session.  Dashboard order (similar to saved searches) should probably persist across machines as well (ex: the user signs in from a different laptop).
* The design for this will have to handle all of the different dashboard layouts - 1, 2, 3, and 4, column layouts.  Note that only the 1 and 2 column layouts have ever been used.

**Comment by dgrumieaux** [comment]
Note: #724 should probably be finished before work starts on this issue.

**Comment by gsteimer** [comment]
This was added in HPI 2.4.
