### ISSUE TITLE
Cascading Picklists - Not populating all fields from bulk properties

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#706]
See the following issue where the first property should be set from bulk properties, but is being lost:
![licecap-002](https://cloud.githubusercontent.com/assets/547941/8239940/b244ca8c-15c4-11e5-89a3-eacd6c24f1a5.gif)

**Comment by grahamsinger** [comment]
Fixed at revision 12522.

Made sure that the picklist values would be triggered to load if there were existing ones (and it isn't loading/loaded).  Also added the that.loaded flag to the other that.value.subscribes as it was added in one, but not all, necessary places when it was implemented.

Unit tested.

CR: Zaq Keller
