### ISSUE TITLE
Picklists - Default Value Configuration - Search and/or View/Edit Properties

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#71]
Some clients want the ability to default a picklist value if no value is set.  Before doing this, we need to decide:
1. Is this everywhere?
2. Just in advanced search?
3. Just in edit proeprties?
4. Configurable?

**Comment by b-k-white** [comment]
@gsteimer I believe this is implemented for anything that uses form support? Advanced Search appears to still not default, but all of these other spots do.

**Comment by gsteimer** [comment]
Agreed - This has been finished in most places.  Sounds like advanced search would need to be implemented for any clients that use both it and a defaulted picklist

**Comment by b-k-white** [comment]
I am currently working on this.

**Comment by b-k-white** [comment]
Fixed Advanced Search with revision 18051. CR - Erich
