### ISSUE TITLE
View All Documents - Filter clearing out value after first character typed

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#710]
When typing in the filter box, the first character is cleared out. The filter itself seems to work with the one character, but obviously starts over when you being typing again.

![view all documents - filter issue](https://cloud.githubusercontent.com/assets/4852302/8263363/6c3b2a6e-169f-11e5-81a6-f9dcadf8fa4c.gif)

(Sorry for messed up image, licecap was doing something weird, but you get the idea)

**Comment by grahamsinger** [comment]
Fixed at Rev #12633

CR: ZK
