### ISSUE TITLE
View All Documents: Add indicators that the document is annotated/checked out/has document notes

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#711]
To make View All Documents more comprehensive, add indicator icons near the Export icon similar to the icons on the Stage when viewing one document, and an icon if the document has associated folder notes.

Icons to include:
- [x] Checked out
- [x] Annotated
- [x] Has document notes

![image](https://cloud.githubusercontent.com/assets/4852302/8264116/0f36d6b6-16a8-11e5-94af-722065770faf.png)

**Comment by cmlewis** [comment]
@stinachen Please update with your HPI and OC revs, thanks!

**Comment by stinachen** [comment]
HPI revision #13026
OC revision #12503 (main updates here) / 12504 (minor code fix)
