### ISSUE TITLE
Right Click Add To Collection on Multiple Results Only Adds One Document

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#712]
See the screencam below.  If I choose more than one document and then right click and select add to collection, only one document is added, not both.  When you have multiple documents selected, the right click menu should do the same thing as the Actions menu at the top.

Note that the following items do work properly:

- Bulk Actions -> Add to Collection (adds both docs to the collection)
- Right Click -> Download as Zip (adds both docs to the zip)

Based on the above, my bet is that the right click menu is incorrectly pulling the single 'addToCollection-docViewer' action.  Side note - this action should really be renamed since it's not just used in the doc viewer anymore...  My thoughts:

- addToCollection-docViewer should become addObjectToCollection
- addToCollection should become addObjectsToCollection

![add-multiple-to-collection](https://cloud.githubusercontent.com/assets/1377228/8331932/9836a15c-1a50-11e5-9084-2828c42233ba.gif)

**Comment by dgrumieaux** [comment]
It is possible that this is misconfiguration. When multiple objects are
selected, the Search config should look at the configured group actions. If
there are single object actions configured in the group actions section, I
would expect this error to occur.

**Comment by gsteimer** [comment]
Yeah, I thought the same thing at first too.  But it's impossible to configure the single version in the Group Actions since it only shows group actions.  Here's the config on edge2 Controlled Docs search config:

![image](https://cloud.githubusercontent.com/assets/1377228/8332093/994c7048-1a51-11e5-99f3-c02c3f3e2d8c.png)

**Comment by grahamsinger** [comment]
Fixed at Revision 12634

CR: ZK

**Comment by grahamsinger** [comment]
The `objectId` of the action was being populated even when `multipleSelected` was true.  This essentially made the action not able to behave as a group action.

CR:ZK
