### ISSUE TITLE
Table View - Right Click Menu Location

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#713]
See the screencam below.  The table view right click menu appears fine, until you start right clicking documents towards the bottom of the screen.  After that, the menu appears noticeably off...

![right-click-menu-location](https://cloud.githubusercontent.com/assets/1377228/8331975/dcc96c46-1a50-11e5-88a3-80ad06d57ae3.gif)

**Comment by gsteimer** [comment]
Update - this happens when you have to scroll down to see the items lower in the list..

**Comment by grahamsinger** [comment]
Fixed with revision 12635.

Used clientX/Y instead of pageX/Y when adjusting the css of the tableviewActionMenu.

CR: ZK
