### ISSUE TITLE
Advanced Combined to PDF - Admin Does not Work

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#714]
After updates to #590, the Advanced Combine to PDF action does not seem to work in the admin.  See the screencam below - when I choose an attribute, a blank value is saved.  Trying to use the action saved like this does not work .

![adv-combine-pdf-admin](https://cloud.githubusercontent.com/assets/1377228/8332481/b73f0f5a-1a53-11e5-9005-afba0a0949d2.gif)

**Comment by grahamsinger** [comment]
Fixed at revision 12564

--Forgot to change the template when I changed from variable name 'text' to 'label'.
--Made sure that when executing the action, the 'docProps' that we are getting the ocName because we are using objects now instead of strings.
