### ISSUE TITLE
Dashlet Admin - Group Names on Alfresco Do Not Display Properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#715]
See the screenshot below - seems like the group names that try to use the display name are not displaying properly:

![image](https://cloud.githubusercontent.com/assets/1377228/8333161/5b0d533c-1a57-11e5-97ac-7708ece3e91f.png)

**Comment by gsteimer** [comment]
@grahamsinger - is this related to #590?

**Comment by grahamsinger** [comment]
Yeah it seems like this is the same basic idea.

**Comment by grahamsinger** [comment]
Fixed with rev 12644.

We now show the actual display name (not just the group without the `GROUP_`).  This was done by hitting `/groups` instead of the deprecated `/users/allGroups`.

CR MB
