### ISSUE TITLE
Developer - HPI

### ISSUE THREAD

**Issue by dshivnani** [tsgrp/hpi#717]
Hi 
We are trying to evaluate interfaces for Documentum like HPI, D2 and CARA. I downloaded HPI and have seen few videos in which its configurable to have few widget/dashlets but I am not able to login with any user on http://localhost:8080/hpi/ and only to http://localhost:8080/hpi/admin in which configured ApplicationConfig etc. But I am not getting any documentation in which I can have normal user login to HPI interface and see then how it works.

![image](https://cloud.githubusercontent.com/assets/12757338/8351850/dd61a152-1b4d-11e5-9c53-c4336a01e864.png)

Please help or guide in this.

Regards
Deepak

**Comment by gsteimer** [comment]
Deepak,

First - TSG uses the GitHub issues list to track issues and enhancements to the main line of HPI code, not for HPI support.  You can contact us here if you're interested in support from TSG: http://www.tsgrp.com/about/contact.jsp

Second, the communication with the repository is all handled with OpenContent.  You should check the OC logs and check to see the actual reason why users cannot log in to HPI.
