### ISSUE TITLE
Hitting Enter on the Create Wizard Form Action should submit action if it's valid

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#718]
When the user hits enter, we should attempt to submit to create the form.  

- [ ] No form selected (either blank, or something entered, but no form selected) - do nothing
- [ ] Autonumbered Form - valid selection - create form
- [ ] Non-autonumbered Form - valid selection and form name filled out - create form
- [ ] Non-autonumbered Form - valid selection and *no* form name filled out - do not create form

**Comment by grahamsinger** [comment]
Fixed with rev12636.

Added helper function to handle the scenarios so that when the enter key is hit, it either creates a new form or doesn't to ensure the user puts in all info required based on if it's autonumbered or not.

Unit Tested to cover scenarios.

CR: ZK
