### ISSUE TITLE
Drag and Drop MSG with attachments, drop area disappears

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#719]
See the GIF below.  The drop area disappears after dragging in a MSG file with attachments.  Note - dragging in a regular file works fine.  Seems to only occur when there are attachments.

@zkeller - could this be caused by the Gmail updates that went in recently?

![bu-dand-disappear](https://cloud.githubusercontent.com/assets/1377228/8462177/8812bec6-1ff7-11e5-899f-c2fd8887a38e.gif)

**Comment by zkeller** [comment]
This is coming from the Add from Template update. It uses a 'keepWellHidden' property, that is getting set to true when the 'Processing Attachments' screen is shown. When this is set to true, the dropZone is hidden. Without a good understanding of what that code is accomplishing, I don't know the best solution. @aviking should have a better idea

**Comment by zkeller** [comment]
Fixed with commit 12648 - needed an additional check for the 'Processing Attachments' div.
