### ISSUE TITLE
Bulk Upload File Select Next Button Disabled Incorrectly

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#720]
See gif below. When you click the File Select button to go back to the File Upload screen and you have a document already selected, you can't click the Next button, even though a document has been selected.

![bulkuploadnextbtn](https://cloud.githubusercontent.com/assets/4852355/8527399/09b4a75e-23d2-11e5-96b1-cd1576379b9d.gif)

**Comment by aviking** [comment]
Fixed with HPI Commit: 12657. CR: Zaq
