### ISSUE TITLE
Power Promote - Sign Off Enhancement

### ISSUE THREAD

**Issue by bradleywhite2014** [tsgrp/hpi#721]
Creating a record of the Power Promote enhancement to allow for users to sign off when promoting, which in turn creates a signature event as well as an audit event.

**Comment by b-k-white** [comment]
Sorry I accidentally opened this enhancement with my personal GitHub account.

HPI REV - 12654

Unfortunately I did my HPI commit prior to double checking that someone was present to give me OC commit power. Will get the OC part in asap in the morning

**Comment by b-k-white** [comment]
OC REV -- 11961
