### ISSUE TITLE
Picklist Admin Enhancements

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#723]
From looking at #694 on edge today, here are some things I think we should also implement in the picklist admin:

- [x] In the Main configuration section, it would be nice if the picklists were in alpha order.  RIght now, they're in creation order, so looking through a long list of picklists is tough.
- [x] When looking at the Picklist details after clicking on a picklist, there's no way to see the type of picklist (Simple, OC, etc).
- [x] After adding a picklist, it just drops to the end of the list in the selectbox.  This could be confusing to users, especially when there's a long list - there's no indication on what to do next (have to know to click on item at the bottom of the list).  I think the simplest way to fix this would be to open the picklist details as soon as it's created.  I'd be open to other ideas though...

![new-picklist](https://cloud.githubusercontent.com/assets/1377228/8582751/6870c6b6-258e-11e5-9161-f08fcaacf5b1.gif)

**Comment by tbrandstatter** [comment]
Added the first two enhancements so picklists are sorted alphabetically and in picklist details it shows the picklist type. The last enhancement will be added when phase 2 of implementing simple picklists (#694) is completed (factoring out ko/kb for backbone).

Completed at revision: 12703

**Comment by zkeller** [comment]
First two parts fixed with commit 13885

**Comment by gsteimer** [comment]
Third part seems to have been committed with all the picklist updates recently.  It's working on edge.
