### ISSUE TITLE
HPI User Preferences Enhancements

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#724]
It would be great if HPI had a dedicated spot for users to manage their preferences / profile.  Additionally, a lot of the things we've been using for cookies would be better stored in the repository.

**Initial Scope**
- User preferences architectural changes:
  - [x] upon login, pull user preferences model for the user
  - [x] HPI features (ex: saved search) look at the local model to read prefs, not the repo
  - [x] When something changes (ex: user adds a saved search), change the local pref model
  - [x] Upon app exit, save the model to the repo
  - [x] Every x minutes, if the model has changed, save the model to the repo
  - [x] When saving the model, save as same version
- [x] Update search column preferences (columns visibility, order, etc.) to be stored in user preferences and not a cookie (Client request - start here first when porting HPI cookie functionality to user prefs)
- [x] New section in HPI where a user can see their preferences.  I'm thinking this should be a new route / page and not a modal.  I can envision a lot ending up in here.
- Within this new page, give the user a place to:
  - [x] Reset their search column preferences (question - per trac, or just reset all)
  - [x] Delete saved searches (Low priority for this first phase)

**Phase 2 (in priority order)**
- [x] Save the user's dashboard order to user preferences (see #704)
- [x] Give the user a way to reset dashboard order
- [x] Question: should Recent Objects be stored in user preferences or is it better in a cookie?
- [x] If we end up allowing users to manage saved searches from the user preferences page, should we remove or clean up this functionality from the search page?

**Future Scope**
Some ideas:
- Give the user the ability to set an inbox proxy
- Give the user the ability to change their user information in the repo.  We'd need to think through this one given differences between Alfresco, Dctm, and Hadoop/Solr.

**Comment by aviking** [comment]
Phase 1 is compldete and merged back into trunk. 
OC revision: 12046, HPI revision: 12706
CR: Dan G.

**Comment by gsteimer** [comment]
Closing since all items in the original checklist have been implemented.
