### ISSUE TITLE
Power Promote fails on Documentum when eSigs are enabled

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#726]
After updates to #722 power promote is not working on edge1 or edge2.  Here's what I'm seeing:

**Edge2**
Power promote with eSigs on works, but does not add sig page.  eSigs are enabled in the admin and I see the username/pwd UI.

**Edge1**
Power promote fails (eSigs are enabled in the admin - I did not test with eSigs not enabled).  Error in OC is:

```
DfPathNotFoundException:: THREAD: TP-Processor7; MSG: [DM_API_E_EXIST]error:  "Folder specified by /Wizard/docApprovalDetails does not exist."; ERRORCODE: 100; NEXT: null
	at com.documentum.fc.client.impl.session.Session.getFolderBySpecification(Session.java:1294)
	at com.documentum.fc.client.impl.session.SessionHandle.getFolderBySpecification(SessionHandle.java:835)
	at com.documentum.fc.client.DfSysObject.doLink(DfSysObject.java:1222)
	at com.documentum.fc.client.DfSysObject.link(DfSysObject.java:1206)
	at com.tsgrp.wizard.dctm.tbo.AWDocImpl___PROXY.link(AWDocImpl___PROXY.java)
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.enhancedCreateObject(DCTMContentImpl.java:1261)
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.setApprovalDetailsHelper(ActivitiClientWizardWorkflowImpl.java:452)
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.setApprovalDetails(ActivitiClientWizardWorkflowImpl.java:336)
	at com.tsgrp.opencontent.wizard.action.executer.PowerPromoteActionExecuter.executeImpl(PowerPromoteActionExecuter.java:177)
```

@b-k-white @stinachen - please look into the edge2 issue.  I'm guessing the edge1 issue is because the functionality hasn't been tested on Documentum.  Unless it's an easy fix, I'm fine with holding off on the edge1 fix.  I can just turn off eSigs on edge1.

**Comment by gsteimer** [comment]
Weird - It looks like edge2 was a caching issue.  Refreshing my cache seems to have fixed the issue.  Didn't we fix this with the Cache Buster?  @dgrumieaux, @joehof - any ideas why the cache buster wouldn't be working anymore?

Looking more at edge1, that folder definitely doesn't exist.  I think we store things differently in Documentum, so we'll either have to update the Power Promote action to work properly for Documentum, or update Documentum to include this folder for Power Promoted docs with eSigs.  Talk to me before doing the latter option because we'll have to update the Controlled Docs DAR as well.

**Comment by joehof** [comment]
Cache Buster still should be active - unless something screwy happened with the build we should not have to be clearing cache to get things to work. I wonder if you could have had a different require-*.js loaded up from a local instance of HPI - and if so - if that would cause the error.

**Comment by gsteimer** [comment]
Yeah, not sure.  I haven't run HPI locally in a while, so I don't think that's the issue.  I've noticed Cache Busting issues for other things as well.  Could it be that the hash isn't getting updated properly between builds?

For reference, the require.js on edge2 is this right now: `require-105c23281aa2b8123e378e26b9613393.js`.

I guess we can check this against the next version that's deployed tonight and over the weekend...

**Comment by joehof** [comment]
That was going to be the next thing I suggested - there are a few moving parts with Cache Busting and looking at if the hash is indeed updated is the place to start.

**Comment by gsteimer** [comment]
@joehof - something is definitely not working with the cache buster.  HPI has successfully rebuilt on edge2 nightly, but the require.js is still: `assets/require-105c23281aa2b8123e378e26b9613393.js`.  I'll open a new issue.

**Comment by dgrumieaux** [comment]
Discussing this with Bradley - looks like Documentum Wizard doesn't yet have the /Wizard/docApprovalDetails folder. Adding this folder should fix the issue.

**Comment by gsteimer** [comment]
Sounds good - let me know the details so I can make sure the DAR is updated appropriately (or let me know if you end up updating the DAR)

**Comment by b-k-white** [comment]
Fixed this by adding the folder and a new acl to the dar and to wizard_67. 
HPI revision 12697
CR - George
