### ISSUE TITLE
Cache Buster not Working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#727]
HPI has a "cache buster" that is supposed to compile the require.js using a hash on the file name so that every deployment has a different require.js and the browser is forced to recognize the changes.

However, for the last few weeks or so, I've noticed that I need to refresh to see changes on edge.  As mentioned on #726, I noticed that the require.js file name on edge2 hasn't changed in at least 3 builds.  It's stuck on:

`assets/require-105c23281aa2b8123e378e26b9613393.js`

**Comment by gsteimer** [comment]
For reference, the require.js on edge1 is currently:

`assets/require-577fcab879fba18f1bd57cb4163ab577.js`

**Comment by joehof** [comment]
Hmmmm - ok, I can take a look at this.

**Comment by gsteimer** [comment]
edge1 today is:

`assets/require-1931406c7549ce2ba04af82a94f4dbf5.js`

Which is different from yesterday.  Not sure what's happening...

**Comment by joehof** [comment]
Also, there will only be a hash change on the require if code has changed. If no commits have gone in since the last build, the hash will be the exact same.

**Comment by joehof** [comment]
Currently, I cannot seem to replicate the cache buster not working. The hash does seem to update every time code changes, and I am able to match the hash from the edge environments locally using the same code.

**Comment by gsteimer** [comment]
let's keep an eye on this one and make sure that when changes are made, the new require.js request is a 200 OK vs a 304 Not Modified

**Comment by gsteimer** [comment]
I think it's safe to close this one at this point
