### ISSUE TITLE
Grunt: modernize our build process

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#729]
After looking into #728, it appears that our Gruntfile needs some attention when it comes to things like the node server and other build processes. After building a quick yeoman project (http://yeoman.io/learning/index.html), it looks like window.reload works in the more modern Gruntfile. 

Let's take a page out of their book. Starting with a generated Gruntfile off of a yeoman build (using configuration options for require.js, LESS, jasmine, etc)

The goal of this enhancement is the following:
- make our Gruntfile more legible
- don't re-invent the wheel. If there is a canonical way of doing a build task (minification, reload, concatenation, etc), we should go that route unless we have a compelling reason not to.
- trust our build process - right now there are several tasks in the Gruntfile that either fail out right or otherwise don't work as expected (looking at you distDebug and serverDebug).

@dgrumieaux

**Comment by dgrumieaux** [comment]
related: #540

**Comment by dgrumieaux** [comment]
Can close this issue as many problems were addressed in this commit

https://github.com/tsgrp/HPI/issues/1529
