### ISSUE TITLE
Bulk Import defaulting picklist to a value when it shouldn't

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#731]
I noticed this today on the Incident trac on edge2.  I have a picklist for folder tags using the new static picklists:

![image](https://cloud.githubusercontent.com/assets/1377228/8749517/b3451f0e-2c67-11e5-80d9-cefea1dc5373.png)

Notice that the blank value is the default.  However, when I use bulk import, the first option "ID'd Photos" is defaulted on the bulk properties page:

![bulk-prop-default](https://cloud.githubusercontent.com/assets/1377228/8749562/ed6866a0-2c67-11e5-97d8-0298f3ce1a2b.gif)

@tbrandstatter @zkeller - any ideas why this would be happening?

**Comment by gsteimer** [comment]
Actually - this is a bigger deal than I originally thought.  No matter what I set the individual documents to, they both default to "ID'd Photos".  

@zkeller - @aviking is going to try to fix this quick for my demo this afternoon at 1PM.  Can you help him out if he needs anything?

**Comment by zkeller** [comment]
Yeah, I can help with this

**Comment by gsteimer** [comment]
See the screencam below - this happens with one doc too:

![default-folder-tag](https://cloud.githubusercontent.com/assets/1377228/8749775/57c412dc-2c69-11e5-8570-fe473d6cc495.gif)

**Comment by gsteimer** [comment]
Thanks @zkeller - the main issue was that someone setup a rule on the folder in Share that always set the attribute to that "ID'd Photos" value.  Removing those cleared up the issue. 

However, I still can't figure out why it would default the value on the bulk properties page.  @zkeller was not seeing this...

**Comment by gsteimer** [comment]
Ok - figured this out, again thanks to @zkeller.  It turns out that whoever set this up put the folder tags property on the incident folder type, when it really shouldn't be there.  So, the rule was setting "ID'd Photos" on the parent folder and then Bulk Upload was correctly inheriting it down.

Closing this - edge2 should be correctly configured shortly...
