### ISSUE TITLE
Form Config - Picklists default to cascading

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#732]
See the screencam below.  When I create (or edit) a picklist in form config, the picklist defaults to cascading.  This happens whether the control type is Autocomplete or DropDown.

![picklist-default-cascading](https://cloud.githubusercontent.com/assets/1377228/8752107/a63081b8-2c77-11e5-960c-261bfd4e5a47.gif)

**Comment by gsteimer** [comment]
@joehof - is this an easy fix?

**Comment by cmlewis** [comment]
Bumping this - would love to have a new hire fix soonish. Been a pain setting up new client configs.

**Comment by grahamsinger** [comment]
Fixed with rev12914.

Old forms had dependsOn configred as a blank string, and new ones are defaults to a blank array.  The ternary was only accounting for the blank string, making the new attributes default to cascading.  We now account for both.
