### ISSUE TITLE
User Preferences - Assumes Node Server

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#734]
On Edge2, clicking the gear icon sends the user to `/userpreferences` instead of `/hpi/userpreferences`:

![image](https://cloud.githubusercontent.com/assets/1377228/8782068/9d1cd8c0-2ed8-11e5-85d3-a66e09fcc648.png)

@aviking

**Comment by aviking** [comment]
I can fix that

**Comment by aviking** [comment]
Fixed with HPI Revision: 12712
CR: Zaq
