### ISSUE TITLE
User Preferences - Search Fails when user does not have a prefs file

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#735]
When doing a search logged in as a user without a user prefs file, searches do not display anything:

![image](https://cloud.githubusercontent.com/assets/1377228/8785980/16585904-2ef1-11e5-9190-6a99bbd24902.png)

It looks like it's failing because the fetch for the user prefs 404's:

![image](https://cloud.githubusercontent.com/assets/1377228/8786006/2f63224e-2ef1-11e5-9dad-63338753e571.png)

We should be defaulting the model to a new blank user prefs object when the call 404's.

**Comment by aviking** [comment]
Fixed with HPI Revision: 12713
CR: Zaq
