### ISSUE TITLE
User Preferences - Fails loading in dashboard

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#738]
This doesn't happen all the time, but I have seen the dashboard fail to load with this error:

![image](https://cloud.githubusercontent.com/assets/1377228/8786350/356848b6-2ef3-11e5-925d-30627884cf4f.png)

However it is inconsistent.  @zkeller has seen this as well.

**Comment by aviking** [comment]
Fixed with HPI Revision: 12713
CR: Zaq
