### ISSUE TITLE
User Preferences - Small Resolution / Mobile Enhancements

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#741]
With small resolutions or on a mobile device, some sections of the user preferences need cleanup:

![image](https://cloud.githubusercontent.com/assets/1377228/8803550/0840aa5a-2f8d-11e5-949f-e7b231294316.png)

![image](https://cloud.githubusercontent.com/assets/1377228/8803558/106aa104-2f8d-11e5-9e8b-9d6c3e9b32a3.png)

![image](https://cloud.githubusercontent.com/assets/1377228/8803562/19a792fe-2f8d-11e5-9bfb-904263113eeb.png)

Perhaps using some wells and maybe even a tabbed layout like the HPI admin would help on the user preferences page as well.

**Comment by dgrumieaux** [comment]
+1

**Comment by b-k-white** [comment]
Using the out of the box bootstrap classes should solve this issue. They are designed to work dynamically. I think George is correct that wells with container-fluid inside of them will look good.

Currently each row is pushed to the next line by maximizing the columns used to 12. By doing 
``<div class="col-md-12">```
on each input option, a new row isn't being declared, it is just being pushed down because there is no space left in the bootstrap grid system.

I'm happy to fix this up if I am still free after my AW Admin fixes.

**Comment by b-k-white** [comment]
Fixed locally, will get a CR to commit tomorrow

**Comment by b-k-white** [comment]
Fixed styling to work on small devices
HPI- 12784
CR - Dan G.
