### ISSUE TITLE
Folder Browser - Routes to object ID's 404

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#743]
See the screencam below.  Only the `/hpi/folderbrowser` route works directly.

![folder-browser-404](https://cloud.githubusercontent.com/assets/1377228/8852980/f939e566-311d-11e5-98bb-f6d77f6d616d.gif)

**Comment by dgrumieaux** [comment]
This looks like an Apache issue - I'd be interested to see if this works on
node

**Comment by gsteimer** [comment]
Fixed using Apache parameter.  See https://github.com/tsgrp/hpi/wiki/HPI-Installation-Requirements#apache-configuration-updates-for-alfresco for details.

No code updates.
