### ISSUE TITLE
Folder Browser - not formatting dates properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#744]
See the screenshot below.  Modified Date is correctly setup in OTC as a date, but it's displaying as an ISO string in folder browser:

![image](https://cloud.githubusercontent.com/assets/1377228/8853165/11e589de-311f-11e5-8043-846db83b3166.png)

**Comment by peterkk** [comment]
filtered instances of collections versus folderbrowsers. 

CR-Joe

forgot to put that in the commit log

**Comment by peterkk** [comment]
commit #13202
