### ISSUE TITLE
Editing a form fails with 404

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#745]
Potentially related to #743 - it looks like the same thing is happening whenever you try to edit a form.  See the screencam below.

![edit-form-404](https://cloud.githubusercontent.com/assets/1377228/8859160/24bf0572-3141-11e5-84be-1f4d66abcab0.gif)

Obviously this one is much higher priority.  Currently, editing forms on edge2 is impossible.

@mikeblum @dgrumieaux @grahamsinger - we turned off the edge2 build last night because of a slew of demos today and tomorrow.  Editing a form seems fine on edge1.  Could there be something in the trunk codebase that was committed yesterday that would fix this?

**Comment by gsteimer** [comment]
Looks like this could be the problem:  http://www.leakon.com/archives/865

It's apache rejecting the URL encoded forward slashes in the Alfresco ID...

@dgrumieaux @parzgnat - thoughts?

**Comment by mikeblum** [comment]
We probably need to implement the same url encoding we do for alfresco on
the stage.

**Comment by gsteimer** [comment]
The stage works as is though.  Let's work through these issues first...

**Comment by gsteimer** [comment]
@mikeblum - also note that your suggestion is already an issue here: https://github.com/tsgrp/hpi/issues/153

**Comment by mikeblum** [comment]
I was able to replicate this issue with my local apache2 proxy configured like this:

<VirtualHost *:80>
#    AllowEncodedSlashes On
    ProxyPassMatch ^/(.*) http://10.1.1.14:1337/$1
    ProxyPassReverse ^/(.*) http://10.1.1.14:1337/$1
    ServerName 10.1.1.14
</VirtualHost>

browsing to a url like this with ***AllowEncodedSlashes*** disabled caused the 404:

http://10.1.1.14/hpi/activeform/workspace%3A%2F%2FSpacesStore%2F58a6fc7d-db1c-4a33-bb52-eca1685bc55e/edit/0

note the troublesome %2F. The reason we're not seeing this in the Stage is that we're not yet url-encoding Alfresco assets:

http://edge2.tsgrp.com/hpi/Stage/wizard/workspace://SpacesStore/34d5fbaa-6a05-4f3c-8401-9f97a944834d%2BCURRENT%7Cworkspace://SpacesStore/34d5fbaa-6a05-4f3c-8401-9f97a944834d%2BCURRENT

Apparantly just the Wizard router is encoding the urls right now.

When I re-enabled the ***AllowEncodedSlashes*** option the 404 went away.

Is this an acceptable fix to deploy to edge2?

**Comment by gsteimer** [comment]
I'm guessing that if we go this route, it'll fix #743 too.

**Comment by gsteimer** [comment]
Fixed using Apache parameter.  See https://github.com/tsgrp/hpi/wiki/HPI-Installation-Requirements#apache-configuration-updates-for-alfresco for details.

No code updates.
