### ISSUE TITLE
Setting a "Default" for a picklist breaks Advanced Search

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#746]
See GIF below, but setting a default seems to break all of advanced search. Tried hard refreshing, clearing cache, and clearing the OTC cache too after saving, and still didn't do anything.

![scroll2](https://cloud.githubusercontent.com/assets/4850976/8878766/85b5ef6a-31f2-11e5-9436-55a753ccf274.gif)

**Comment by joehof** [comment]
This looks like a ko.computed() is firing something that needs typeahead before it is completely setup. Normally, an if() block waiting for this.typeahead has fixed issues like this in the past.

**Comment by ikaikajcorrea** [comment]
Fixed locally, awaiting CR.

**Comment by grahamsinger** [comment]
Fixed with rev12894.

Defaults now populate the autocomplete correctly.

CR: ZK
