### ISSUE TITLE
Workflow Reporting Dashlet - Route to Stage Simple

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#749]
See the screencam below - notice how it's sending the user to `/hpi`.  I'm guessing that the dashlet needs to be updated to use StageSimple.

![workflow-reporting-login](https://cloud.githubusercontent.com/assets/1377228/8884348/b9353886-321b-11e5-8992-b35d73fdc0f1.gif)

Also, when doing this, remember #632

**Comment by grahamsinger** [comment]
@gsteimer is this still an issue, I wasn't able to recreate on edge1

**Comment by gsteimer** [comment]
hmmm - yeah I tied this on edge1 and it worked.  I tried starting a worklfow on edge2, and the workflow isn't showing up at all in the dashlet.

I'll close this one and open a new issue...
