### ISSUE TITLE
Stage Doc Info - Should not display lock and key at the same time

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#753]
See the screenshots below.  When an object is checked out to the logged in user, both the key and padlock icons display. 

**Key icon - lock owner**
 ![image](https://cloud.githubusercontent.com/assets/1377228/8961466/fce501ca-35da-11e5-8ec5-9be285809fd5.png)

**Padlock icon - lock owner**
![image](https://cloud.githubusercontent.com/assets/1377228/8961468/03a41ce4-35db-11e5-8a9a-1c6c0dc475af.png)

If you login as another user, the icon looks correct (lit up padlock).  However, the tooltip isn't large enough to see the whole user name.  We should either make it long enough dynamically, or allow the text to wrap.

**Padlock icon - another user**
![image](https://cloud.githubusercontent.com/assets/1377228/8961490/237e6bf0-35db-11e5-89b7-da349599bffd.png)

**Comment by renesaladrigas** [comment]
DOCVIEWER - Fixed styling of lock and unlock icon to hide the lock icon when lockOwner is viewing the file to just display key icon.

CR - BWhite

Fixed with revision #13278
