### ISSUE TITLE
Bulk Upload: Make disabled fields disabled on bulk page

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#754]
During bulk upload, the bulk property page shows all fields as enabled even when the configured form has some disabled fields. We should disable on the bulk page as well.

Check Bulk Property Edit to see what the bulk page does there - we probably just need to replicate in Bulk Upload.

**Comment by zkeller** [comment]
Nabbing for training as well

**Comment by zkeller** [comment]
Fixed with Rev #13140

**Comment by gsteimer** [comment]
@zkeller - is this an issue with bulk properties too?

**Comment by zkeller** [comment]
@gsteimer No, bulk properties was handling this correctly. It set a flag for form support to disable the read only fields, and now we set that flag for bulk upload as well.
