### ISSUE TITLE
Related Objects - Link Resolver - add "Trac Resolver" option

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#765]
When an object's link is clicked in related objects, we pass through the link resolver configuration to determine how to route the user's link. For the "Stage" link resolver option, we should be able to use the Trac Resolver/StageSimple feature to decide where to route the link. This enhancement encompasses adding a new dropdown selection to the Resolver Trac dropdown called "Trac Resolver" and implementing the behavior to route the user to StageSimple when clicked.

This enhancement should also include having some help text added to the admin to explain what "trac resolver" does.

**Comment by zkeller** [comment]
Do we even still want to use/need the trac chooser? I would say that the stage should just route to stage simple always, wizard goes to stage in wizard (since that url has to be special), and detail goes to the detail view. It would be more consistent with how we do trac resolving in other places in the app.

**Comment by dgrumieaux** [comment]
I would argue yes - if a document is used in multiple tracs, but we want to direct the user to a specific trac for one reason or another. I can see this being useful.

**Comment by zkeller** [comment]
I think setting up a scenario intentionally where a user couldn't go to the trac they want if they have access to more than one wouldn't be ideal. Especially because we don't impose this restriction in other parts of the app.

**Comment by b-k-white** [comment]
@dgrumieaux @zkeller What was the resolution in your debate? I am going to be solving this issue soon.

**Comment by dgrumieaux** [comment]
We'll open a new issue if we want to remove the functionality like @zkeller suggested. For now, just implement the addition of trac resolver option.

**Comment by b-k-white** [comment]
Fixed so that Trac Resolver is now an option. This uses stage simple.
CR - Dan
HPI - 12772

**Comment by gsteimer** [comment]
@b-k-white - when I use the trac resolver option, a URL like this is put into the browser history:

```
http://edge2.tsgrp.com/hpi/Stage/Trac%20Resolver/%7Cworkspace://SpacesStore/c3f5139a-ec40-4c1c-aaf0-ea999e75afc9
```

This causes a similar issue as #632 .  Can we do anything at a higher level vs. just point fixing every break for these?

@zkeller @dgrumieaux

**Comment by b-k-white** [comment]
From what I read when solving this the first time, the higher level fix would require a rework of the routers so that there is one instead of the multitude that we have.

**Comment by dgrumieaux** [comment]
Why does this not just direct us to stage simple?

**Comment by b-k-white** [comment]
Not sure, the code calls stage simple like the other issues in #632 do.

**Comment by zkeller** [comment]
Fixed this with commit 13081

@gsteimer can this be closed?

**Comment by gsteimer** [comment]
@zkeller - I assume you fixed the back issue with Stage Simple for recent objects?  That looks to no longer be an issue on edge2, so I think we can close this issue. 

I think there's a bigger issue though that Stage Simple is going to keep having these issues unless they're accounted for each time calling code uses it.  It would be great if we can have a more generic way to handle it so calling code doesn't have to worry about it...

**Comment by zkeller** [comment]
Yeah, until we overhaul our routers to work correctly, there isn't really a way around the larger issue of having to tweak wherever we call stage simple. If there isn't already an enhancement out for that, we should create one
