### ISSUE TITLE
Attach Workflow Doc with Stage Action Not Working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#766]
See the screencam below.  When I use the stage action to create an AW form, the document loaded in the stage should be attached as a workflow document.  This is not happening on edge1 or edge2.

![attach-wf-doc-from-stage](https://cloud.githubusercontent.com/assets/1377228/9071856/44c66a06-3abd-11e5-96d7-8b2847677254.gif)

**Comment by gsteimer** [comment]
From @dgrumieaux - we're thinking that the fix to refresh the browser that went in a couple weeks ago is the root cause for this issue.

@mikeblum - any other things that could be affected?  Streamline mode maybe?

**Comment by mikeblum** [comment]
Yeah, anything we're passing into the wizardContext object. This affects:

- Contract Scenario - going from a folder or document action
- Starting a Wizard Form from Search
- Streamline Mode

**Comment by mikeblum** [comment]
------------------------------------------------------------------------
r12790 | mblum | 2015-08-05 15:43:09 -0500 (Wed, 05 Aug 2015) | 1 line

Fix for #776 - Workflow documents are now attached even after a page reload when creating a new form. Adding URI.js lib to make url generation easier and less error prone: http://medialize.github.io/URI.js/ CR dgrumieaux
