### ISSUE TITLE
User Preferences Page - Not displaying

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#767]
See the screencam below (from edge1):

![user-prefs-not-working](https://cloud.githubusercontent.com/assets/1377228/9086810/6691493c-3b4c-11e5-8fa2-9ccd702c2808.gif)

@b-k-white - not sure what happened here, but the last user prefs update that went in was for #741

**Comment by gsteimer** [comment]
Update - this works on edge2, so it seems to only be an issue for Documentum

**Comment by b-k-white** [comment]
Fixed just waiting on CR

**Comment by b-k-white** [comment]
Fixed to not show tracs that don't exist
CR - Dan G.
HPI - 12789
