### ISSUE TITLE
User Preferences functionality does not work on Solr (Ex: Saving Column Visibility and Order)

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#771]
As mentioned in #770, our updates to move certain functionality to use the User Preferences service does not work for Solr implementations.

At a minimum, we need to make sure the following functionality works with a Solr back-end:

- [x] Saved Searches - added for HPI/Solr in late 2014
- [x] Search Column preferences (order / visibility) - broken by change to user preferences
- [x] Recent Objects - still a cookie

Recent objects is cookie-based now, so that should just work.  Saved Searches used to work for Solr, we'll just have to make sure the updates for user preferences haven't broken the functionality, or our updates for #770 don't break it.

For the column preferences, I'm wondering if we could do it one of the following ways:

1. Somehow come up with a way to tie a "user" to a user preferences config.  Perhaps with a cookie that looks at the request machine name.
1. Give HPI a configuration to read and save user preferences to a cookie rather than the repository.
1. Make HPI code smart enough to check to see if user preferences are available.  If so, use it.  If not, fall back to using a cookie.

@dgrumieaux @benallenallen - thoughts?

**Comment by dgrumieaux** [comment]
1) seems overkill - if we are saving a cookie, might as well store the config in the cookie. no use to have that repository/filesystem object tied to a cookie uuid that a user cleared out ages ago...
2) not ideal
3) this should be very straightforward, though it might be easier to just have a config-project.js setting to disable repository user preferences instead of a "smart detect".

**Comment by gsteimer** [comment]
I was thinking that 1 would be the most straightforward solution.  Basically, the only gotcha for using user preferences on Solr would be that there is no concept of a user (except when using an SSO).  So, store a cookie that basically says:

```
user = ${machine-name}
```

And then the HPI code can just do the same thing it does now (read and write user prefs rather than pulling data from a cookie).  Of course, this assumes that we have a way to actually read and save user preferences JSON objects with a Solr back end.

**Comment by gsteimer** [comment]
Also, I thought 2 was what you were suggesting here: https://github.com/tsgrp/hpi/issues/770#issuecomment-128402690

**Comment by gsteimer** [comment]
Ah, nevermind - I get it now.  I'll update the checklist item.

**Comment by gsteimer** [comment]
After the discussion above, I think we agree that option 2 is the easiest way to solve this issue.  

@dgrumieaux - feel free to reply if you have other ideas.

**Comment by nwoodbine** [comment]
Implemented with Local Storage, HPI Revision 13881.

See https://github.com/tsgrp/hpi/issues/911 for enhancement.
