### ISSUE TITLE
Start Workflow - admin "selected workflows" tossacross does not show selected workflows properly

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#772]
To reproduce:

- Drag an "available workflow" into the "selected workflows" side of the tossacross.
- Save config
- Refresh page and open up the edit action again

Result is that the selected workflow does not appear under the selected workflows tossacross.

**Comment by grahamsinger** [comment]
Fixed with revision 12830.

In the initialize both `availableWorkflows` and `selectedWorkflows` were being set to a blank array, then the `availableWorkflows` were being populated.  This made it so the user could never save a different config.

CR: MB
