### ISSUE TITLE
View All Documents - Admin UI improvements

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/HPI#774]
View All Documents needs to have all possible object types configured in the admin in order to display correctly. It is possible to do this in the admin by selecting a type from the dropdown, then dragging all attributes that should display across. You can configure an additional type by selecting a different document type from the dropdown and dragging attributes as well. Saving the config saves all configured types.

![image](https://cloud.githubusercontent.com/assets/4852302/9182563/a4752ec6-3f70-11e5-8487-4e07e586396a.png)

Even though the backbone model is updated properly, the UI does not show currently configured types, so it's hard to tell what's been configured unless you click on every type in the dropdown to check. This enhancement should show all configured types in a list, which should be clickable and editable in the toss across.

Related issue: #360

**Comment by gsteimer** [comment]
This admin was replaced when we moved VAD to table view
