### ISSUE TITLE
Grunt "tomcatRelease" target

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#776]
In order to better support our clients running HPI on Java web applications, this enhancement will create a new target option in the build process to create an uglified and minified require.min.js file to deliver to the client. This will ease network requirements as the minified require.js is approximately 60% the size of the unminified.

**Comment by gsteimer** [comment]
See also: #659

**Comment by dgrumieaux** [comment]
Note this is now enabled now that #1529 is closed. Use the `grunt tomcat --project=myproject --release` command to uglify and minify the require.
