### ISSUE TITLE
Quick Search Styling on FireFox

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#779]
See below - for some reason the quick search doesn't fill the width of the search sidebar on FireFox:

![image](https://cloud.githubusercontent.com/assets/1377228/9282233/85fa5b38-4290-11e5-86af-e82316bb4183.png)

Here's how it looks on Chrome:

![image](https://cloud.githubusercontent.com/assets/1377228/9282243/9dce24e2-4290-11e5-9717-567590612e47.png)

**Comment by peterkk** [comment]
Needed to make quick search and saved search bars line up

CR-JASON
