### ISSUE TITLE
Search Small Resolution Display

### ISSUE THREAD

**Issue by maxwellmstein** [tsgrp/HPI#78]
![cssstageissue](https://f.cloud.github.com/assets/3271912/1758111/65a2b76a-668a-11e3-9482-72280f4604ec.png)

See the search controls does not degrade nicely

**Comment by gsteimer** [comment]
This seems resolved to me as of HPI 2.5 / 2.6:

Full View:
![image](https://user-images.githubusercontent.com/1377228/27607185-a44f0372-5b48-11e7-904d-f270ad6ffe66.png)

Small View:
![image](https://user-images.githubusercontent.com/1377228/27607200-b2678c0e-5b48-11e7-942a-86967627ff69.png)
