### ISSUE TITLE
Related Objects - header shows when no Related Objects configured

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#780]
![image](https://cloud.githubusercontent.com/assets/4852302/9309023/d48d1108-44cc-11e5-8323-5b6de73bb074.png)

We should hide the header if no Related Objects relations are configured.

**Comment by renesaladrigas** [comment]
RELATED OBJECTS -- The related objects box is hidden in the stage viewer if no related objects are configured.

Fixed with revision #13199

**Comment by gsteimer** [comment]
This is not working correctly for related objects that are configured to display even if no documents are present.  This is typically how we have AW forms setup on the wizard trac.  There are two related objects sections, both configured to display even if no documents are present.  However, with this update, the section is still hidden:

![image](https://cloud.githubusercontent.com/assets/1377228/10320550/9c428816-6c39-11e5-8fe1-e1adba532481.png)

@renesaladrigas @m-brouillette

**Comment by renesaladrigas** [comment]
RELATED OBJECTS && FOLDERTREE -- Modified the previous fix to this issue by including the config hideEmptyRelations in the conditional statement that triggers an event to hide the related objects panel.

CR - MBrouillette
Fixed with revision #13328

**Comment by renesaladrigas** [comment]
Added pending unit tests for this issue in revision 13869.
CR - ZKeller
