### ISSUE TITLE
Stage Info - Config not saving properly

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#781]
Changing Stage Info to display document properties does not currently work because the "Show Properties for Current" dropdown is not persisted on save. It automatically switches back to Folder.

![image](https://cloud.githubusercontent.com/assets/4852302/9309625/9a6f2110-44d0-11e5-9ba5-7b0b409205d8.png)

**Comment by grahamsinger** [comment]
Fixed with rev12882

Made sure dropdown option would save correctly on config.

CR: Zaq
