### ISSUE TITLE
Default Typeahead Values Lose Value on First Load

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/hpi#783]
When loading a form with a default value in a typeahead, clicking on and off the field causes the typeahead to lose its value. This is only on first load - navigating to a different page and then back will perform as expected.

![wizard_typeahead_loses_value](https://cloud.githubusercontent.com/assets/4128978/9392070/1ba68ab8-4740-11e5-9e6d-902dd97598ed.gif)

**Comment by mikeblum** [comment]
r12911 | mblum | 2015-08-21 10:18:32 -0500 (Fri, 21 Aug 2015) | 1 line
Changed paths:
   M /trunk/code/app/modules/common/typeahead.js
   M /trunk/code/app/modules/wizard/views/controltypes.js

TYPEAHEAD - #783. Typeahead on blur behaves correctly for defaults and on initial page load. CR dgrumieaux.
