### ISSUE TITLE
Quality Docs - cannot attach using Manage Workflow Documents Action

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#787]
With the update from Controlled Docs to Quality Docs, I can no longer attach a quality document to a form on edge2:

![image](https://cloud.githubusercontent.com/assets/1377228/9450384/edb73b8a-4a6d-11e5-8b0c-74d8777c2c7d.png)

@dgrumieaux @b-k-white - can this be fixed quickly?

**Comment by dgrumieaux** [comment]
Sort of - it will be easy to fix this for Quality documents. But if we want to support both Quality documents and Contracts to use this action it may be a bit more configuration.

**Comment by gsteimer** [comment]
Hmm not sure.  @dhartman25 - does the contracts demo use the manage workflow documents action?

**Comment by dgrumieaux** [comment]
The correct condition to check for (the quick fix for just Quality documents) is condition-isqualitydraftlifecyclestate-conditionevaluator. Since either way we need to support at least Quality documents, I will replace the condition.

**Comment by gsteimer** [comment]
actually - that question is moot since we only have one Wizard trac.  If we update it to use Quality Documents, then the action will always appear, but won't work for contracts.

**Comment by dgrumieaux** [comment]
In order to support both, we'd need to enhance the condition evaluation logic to behave one way for a type and another way for the other type.

**Comment by gsteimer** [comment]
Unless @dhartman25 disagrees, I think just updating it for Quality Docs is fine.  I think this is one of those things that will only be a problem if Quality Docs and Contracts are combined in the same system.  To date, that's just been edge2...

**Comment by dgrumieaux** [comment]
Agreed.

**Comment by dhartman25** [comment]
@gsteimer Yes I agree. Contract management will have workflow docs but those will be automatically attached from the "Create Contract" document action.

**Comment by dgrumieaux** [comment]
Tested and working on edge2 with form SCR-115 after HPI commit 12931. Closing.
