### ISSUE TITLE
User Preferences - Not correctly saved upon logout

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#789]
The search results column order/visibility and dashlet ordering does not save properly if you logout right away after making changes.  See screencams below:

*Dashlet Reorder*

![save-dashlet-order-fail](https://cloud.githubusercontent.com/assets/1377228/9475917/479b2424-4b2f-11e5-8e05-6e9747657f5c.gif)

*Search Column Preferences*
![save-column-order-visibility-fail](https://cloud.githubusercontent.com/assets/1377228/9475927/50d88f22-4b2f-11e5-8e72-2509f0b78bac.gif)

User preferences should save with the following rules:

- Save within a certain amount of time of being in the app, _if anything on the model has changed_
- Save upon logout, _if anything on the model has changed_

So it must be that the save is not working properly, or the model doesn't think it has changed.

**Comment by grahamsinger** [comment]
Fixed with rev12966

Put the logoff code in the done() of the `UserPreferences.Config.saveNow()` so we know it gets saved before logging out.  Previously the call would just end up as cancelled/not found because `app.context` would get blown away as the `logoff()` code ran.

Unit tested.

CR: ZK
