### ISSUE TITLE
Collection Controls Small Resolution

### ISSUE THREAD

**Issue by maxwellmstein** [tsgrp/hpi#79]
Similar to #78 but for collections
![cssdefect2](https://f.cloud.github.com/assets/3271912/1758159/379b57ea-668b-11e3-925c-2a7e3e3e864a.JPG)

**Comment by m-brouillette** [comment]
Now actually fixed this problem in Collections and not just in search, using the same fix as above.  Also had to move the view-controls so that they don't overlap with everything. 

HPI REV - 11593
CR - CMLewis
