### ISSUE TITLE
Create Folder Header Action - Submit button incorrectly enabled when only one trac configured

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#790]
Found from HPI system tests.  When the Create New Folder is configured as a header action with only one trac configured (this is the current situation on edge1), the Create Folder Button is incorrectly enabled:

![image](https://cloud.githubusercontent.com/assets/1377228/9477038/af3f4bb8-4b35-11e5-977a-34abf170d0dd.png)

The create folder button should only be enabled when a Trac and Object Type have been selected, and all required properties on the form are present.

**Comment by vachanta93** [comment]
Fixed with revision #13182

Added a data-bind in createfolder.html to check if object type is selected before enabling Create Folder button
