### ISSUE TITLE
Search Config - Tableview - Configure force fit columns at top level

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#792]
Currently when configure table view in Search Config, you have to configure force fit columns for every type you configure. There's no reason to have this on every type - let's set it on the top level for the table view instead.

**Comment by gsteimer** [comment]
Agreed... however, maybe let's make it override-able at the type level?  For example, a client may search for a type that brings back 5 visible attributes and another type that brings back 15 visible attributes.  The former would definitely need force fit on, but more that likely the latter type would have it off.

**Comment by cmlewis** [comment]
Yeah, that makes sense, sounds good.



*From:* George Steimer [mailto:notifications@github.com]
*Sent:* Tuesday, August 25, 2015 4:04 PM
*To:* tsgrp/hpi <hpi@noreply.github.com>
*Cc:* Christy Lewis <clewis@tsgrp.com>
*Subject:* Re: [hpi] Search Config - Tableview - Configure force fit
columns at top level (#792)



Agreed... however, maybe let's make it override-able at the type level? For
example, a client may search for a type that brings back 5 visible
attributes and another type that brings back 15 visible attributes. The
former would definitely need force fit on, but more that likely the latter
type would have it off.

—
Reply to this email directly or view it on GitHub
<https://github.com/tsgrp/hpi/issues/792#issuecomment-134741467>.

**Comment by cmlewis** [comment]
@gsteimer Maybe we should just leave as is based on your reason above instead of complicating things. Lmk what you think.

**Comment by gsteimer** [comment]
Is Force Fit `true` the default when you add a type to the table view config?  If it's `false`, we should definitely change it.  If it's already `true`, then I think we should leave the admin as is.

**Comment by cmlewis** [comment]
It is true by default, which is annoying for me because I had to change them all to false because I have fewer attributes in my tables :) I think we can close.

**Comment by gsteimer** [comment]
Wait - but if you have fewer attributes, wouldn't you want Force Fit to be on?  I thought having it off is only useful for clients that want a ton of visible attributes...

**Comment by cmlewis** [comment]
That's what I thought, but it seems to be the opposite. When set to 'Yes' in the admin, columns don't fill up the full width of the page (if you have few columns). When set to 'No' in the admin, columns are evenly distributed the width of the page.

**Comment by gsteimer** [comment]
I think something must be going wrong in the code then.  Force fit yes turn force fit on in SlickGrid, which should make all the columns fill up the full width.

@grahamsinger - you just fixed the bug around force fit... Is my description how it should work?

**Comment by grahamsinger** [comment]
@gsteimer yeah that was my impression
