### ISSUE TITLE
Picklists - show which forms are currently using picklist

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#797]
HPI allows you to delete picklists even if they are currently in use by various form configs. It would be nice to add a section to the picklist config that shows "Picklist used by forms:" when you click to view the picklist, so a user knows what to update before they delete a list, something like this:

![image](https://cloud.githubusercontent.com/assets/4852302/9505356/8036fd3e-4c07-11e5-8edb-e9803f07b775.png)

**Comment by vachanta93** [comment]
Committed what I have now in picklist_config_remove_knockout feature branch of HPI (Rev #13617). It's mostly done, but still need to:
* Add unit tests in `picklistConfigSpec.js` to check if `PicklistUsedOnFormsView` is created in the `RepositoryPicklistItemsView` and `SimplePicklistItemsView`
* Change existing unit test `picks out the forms that the selected picklist is used on` to make it test that the returned form config equals `"mockForm"`
* Modify when the `Spinner` is displayed (we want it to be showing while the forms list is loading)

Please let me know if there are any problems! I will try to finish this ASAP.

**Comment by zkeller** [comment]
Fixed with commit 13885
