### ISSUE TITLE
Bulk Props broken

### ISSUE THREAD

**Issue by joehof** [tsgrp/hpi#800]
When trying to use bulk props in edge2 and edge1, a mapping error occurs trying to get the mimetype:

![bulkprops](https://cloud.githubusercontent.com/assets/4852255/9606789/177491d4-508b-11e5-8b26-8765f9b9c9c0.gif)

**Comment by alieblich** [comment]
BULK PROPERTIES ACTION EXECUTER - add check to see if the mimetype is null on objects passed in, if the mimetype is null don't try to add or remove the file extension that way folders will work in bulk properties update.

OC rev 13224

cr - George
