### ISSUE TITLE
Cascading Questions: textboxes are disabled when they shouldn't be

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#802]
![selection_057](https://cloud.githubusercontent.com/assets/3905463/9635435/159fc7da-515c-11e5-874a-e9cc36d7ebe0.png)

On edge1, TS Cascasing Queries the first textbox that starts the chain of cascading queries is disabled. Removed the disabled class from the markup seems to work.

**Comment by mikeblum** [comment]
moving to AW issue tracker

**Comment by gsteimer** [comment]
Is this related to https://github.com/tsgrp/ActiveWizard/issues/260 ?

**Comment by grahamsinger** [comment]
Yep, that fix is in now.
