### ISSUE TITLE
Form Micro-States

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#803]
This enhancement covers the ability to configure attributes being updated to a preconfigured value before each Active Wizard Priority's tasks are completed. For instance, when Simple CR's first priority is arrived at in a workflow, a configured micro state attribute could be updated to read "Waiting on Initial QA".

**Comment by dgrumieaux** [comment]
Additionally, upon approval of a form, the micro state attribute is set to "Approved".

**Comment by grahamsinger** [comment]
Implemented with OC revision 12484.

CR: ZK / DG
