### ISSUE TITLE
Timeout Error - Re-Login Instead

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#804]
Currently if a login ticket times out, an ugly error appears and we're taken to the login screen. It would be nice if when the ticket timed out, a pop-up modal appeared asking you to enter in your password again, and this would fetch a new ticket. This way, users aren't taken back to the login screen and can remain doing the work they were currently doing.

**Comment by gsteimer** [comment]
Fixed with OCMS timeout setting in admin
