### ISSUE TITLE
OpenAnnotate Embedded Viewer AutoSave

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#805]
When using OpenAnnotate as an embedded viewer in HPI, the autosave functionality does not fire when a user navigates away from the stage or goes to view another document in the stage. This is probably due to the embedded iframe not calling the .close() method to cleanly exit OpenAnnotate, thus we aren't triggering OA's close behaviour.

@dgrumieaux suggested some kind of registering mechanism for being able to register events to run when the stage view gets de-constructed. I would hope there isn't anything OpenAnnotate specific we have to write to deal with this, so hopefully it can just be a cleaner cleanup of the iframe from the DOM that will cause the onclose events to be fired? Seems too easy to be possible...

![save](https://cloud.githubusercontent.com/assets/4850976/9692049/1992a1a8-530c-11e5-80f2-e2256e390b48.gif)

**Comment by dgrumieaux** [comment]
Note that this issue is related to the intended behavior that this enhancement would allow: https://github.com/tsgrp/hpi/issues/784

**Comment by joehaynes** [comment]
@acastor closed with HPI commit 18780 and OA commit 4196

CR- Marc
