### ISSUE TITLE
Folder Browser Table view shows folders

### ISSUE THREAD

**Issue by aviking** [tsgrp/hpi#806]
When you click on a folder in folder browser it shows all contents including folders. It should only show the non-container objects within the folder. See screen shot below:

![folderbrowser issue pic](https://cloud.githubusercontent.com/assets/2895070/9695142/89c9805a-5324-11e5-8843-83ba3ad0e401.png)

Talk to @aviking before starting this fix.

**Comment by aviking** [comment]
Using this issue for Training. Please don't fix yet.

**Comment by peterkk** [comment]
Filtered out other folders in Document list

Fixed with revision #13175
