### ISSUE TITLE
User Preferences - Better sections to prevent clutter

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#807]
The user preferences screen in the admin is getting a little cluttered.  I think we need to section off the areas of HPI and use tabs, similar to the HPI admin.  

![image](https://cloud.githubusercontent.com/assets/1377228/9737588/f99d7914-560c-11e5-86f1-182951074114.png)

Here are some thoughts:

1. For the current user preferences screen, I think we need two tabs:
  - Search
  - Dashboard
1. In the future I could see tabs for:
  - Stage
  - My User

**Comment by renesaladrigas** [comment]
Fixed with HPI commit #13158

**Comment by gsteimer** [comment]
@renesaladrigas - I noticed that the screen was updated, but the confirmation message always appears on the search tab.  See below:

![user-prefs-conf](https://cloud.githubusercontent.com/assets/1377228/10148923/fa6625d6-65fb-11e5-8778-9fc10d296d0a.gif)

Can you update that - I'm thinking we either need to target the correct div in the tab, or move the whole thing above the tabs.

**Comment by renesaladrigas** [comment]
USER PREFERENCES - Reset table view and reset dashlet order confirmation messages re-targeted to proper divs.

CR - GSinger

Fixed with revision #13174
