### ISSUE TITLE
Export Search Results - OC Error

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#809]
Executing the export search results action fails on both edge1 and edge2 with this error:

```
13:09:06,727 ERROR [com.tsgrp.opencontent.rest.RESTService] [ajp-apr-8009-exec-4] 
java.lang.NullPointerException
	at com.tsgrp.opencontent.universal.action.executer.ExportSearchResultsActionExecuter.executeImpl(ExportSearchResultsActionExecuter.java:87)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:316)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

```

**Comment by gsteimer** [comment]
@aviking - did you test export search results in your testing of https://github.com/tsgrp/OpenContent/issues/68 ?

**Comment by gsteimer** [comment]
Line 87 is blank in trunk, so it's odd that's where the error is thrown.  I tried debugging this on edge2, and something is definitely going on - looks like it's running old code:

![export-debug](https://cloud.githubusercontent.com/assets/1377228/9797259/d29f28da-57bf-11e5-910d-ab199d8ff069.gif)

@benallenallen - I know you were talking about edge3 running old code... could the same thing be happening with edge1/2?  Not sure how we wouldn't have noticed that though...

**Comment by benallenallen** [comment]
If you take a look at the jar on the deployed instance and check the modify date, and/or decompile it to look at that line you will be able to tell for sure...

**Comment by gsteimer** [comment]
Decompiled, the code looks like this... Obviously different than trunk:

![image](https://cloud.githubusercontent.com/assets/1377228/9797492/09aa7da6-57c1-11e5-873e-ea0b4423c436.png)

Which is an issue, for sure, but not the root cause of this issue...

**Comment by gsteimer** [comment]
Ugh - my bad.  I didn't update my OC since @aviking's big commit.  Edge2 is running the correct trunk code.  Looks like Jenkins is smarter than I am!

**Comment by gsteimer** [comment]
OK, after updating and debugging, it looks like this is being caused by the 'content type' update.  It looks like the problem is that the code blows up on the new `mimeType` attribute.

![image](https://cloud.githubusercontent.com/assets/1377228/9798713/63c28a02-57c8-11e5-9d8a-dfee53ac9347.png)

The above property fails on this line:

```Java
String ocPropName = CoreContext.getDictionaryService().getPropertyDefinitionByRepoName( prop.getName()).getOcName();
```

@aviking @benallenallen - is there a way to fix this without needing this attribute in OTC?  It's not available in the admin anyway (I'm guessing because it's not actually in the Data Dictionary).

This brings up more testing scenarios though, since there are tons of places in OC that loop over the available attributes in an EOP

**Comment by aviking** [comment]
Fixed with OC Commit: 12570
