### ISSUE TITLE
Full Pane Actions: actions not refreshing after creating a folder/other actions?

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#811]
When the 'View All Documents' action is configured as a full pane action and a user creates a folder (configured as a modal action), the View All Documents action shows the documents from another folder.
***Steps to reproduce:***
1. Browse to an existing folder
2. Populate with some documents
3. Select the 'View all documents' action
4. Create a new folder

Issue will be once the create folder action has concluded, we're not properly refreshing the full pane action.

**Comment by RudraVishweshwar** [comment]
Fixed with revison #13480. The viewAllDocuments now loads the documents of new folder when create new folder is called. Also cleaned up the spec file with better variable names and added waitsFor and runs for all tests.
