### ISSUE TITLE
View in Dual Pane doesn't work when there isn't an active document

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#813]
An error is thrown when you try to open a document in dual pane view and there is no active document. The error is coming from docviewer.js line 290 when it tries to get the properties of self.activeDocument(), and self.activeDocument() is undefined. See gif below
![dualpaneissue](https://cloud.githubusercontent.com/assets/4852355/9856288/5374aebe-5ad9-11e5-8b4a-5aa34de2e3b3.gif)

**Comment by vachanta93** [comment]
Fixed with revision #13171
