### ISSUE TITLE
Wizard Workflow Dashlet: showing the wrong task names for parallel tasks

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#820]
The root of the cause appears to be in the OC endpoint:

    http://localhost:9080/OpenContent/rest/aw-workflow/getAllWizardUserAndGroupTasks

Here is what Approval Details should be displayed vs the dashlet:

![selection_069](https://cloud.githubusercontent.com/assets/3905463/9910495/e95c3f52-5c62-11e5-99c8-d7d3ec5702f8.png)
![selection_070](https://cloud.githubusercontent.com/assets/3905463/9910494/e95a737a-5c62-11e5-907e-23ec08971a87.png)

Perhaps since the root cause is coming from the OC endpoint this is largly an OC issue I think.

**Comment by gsteimer** [comment]
Note from @mikeblum - this is fixed on a client UAT branch, waiting to be merged back to trunk

**Comment by ZachGerth** [comment]
Fixed with Revision # 13358.
