### ISSUE TITLE
View All Documents - Make Link Attr configurable

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#831]
Right now, the attribute that has the link is hardcoded to be object name. This should be configurable for clients that don't want to use object name in View All Documents

**Comment by gsteimer** [comment]
@zkeller - is this going to be assigned to a developer soon?  If not, then this should be Upon Client Request and not HPI 2.4...

**Comment by zkeller** [comment]
@gsteimer Yes, our current client has requested this. Just wanted to document it here.

**Comment by RudraVishweshwar** [comment]
Closed with revision #13209. Merged from client branch into trunk

CR- GS, JH
