### ISSUE TITLE
Recent Objects - Store data in User Preferences

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#834]
Recent Objects should store it's data (recent object ID's) in user preferences rather than a cookie.  This is beneficial for a number of reasons:

- Users that login to HPI via Citrix will be able to utilize recent objects
- It will fix #690 (which can be closed once this item is closed)

**Comment by bridgetbol** [comment]
Fixed with HPI commit 13293
CR - Avi
Made it so all recent object cookies are now user preferences
