### ISSUE TITLE
Async Picklists Not Re-Running with new value

### ISSUE THREAD

**Issue by ladams13** [tsgrp/hpi#837]
When I type "CR-" in a configured async picklist, all values that start with "CR-" are returned.  However, if I change "CR-" after that search to "WT-" the picklist is not reloaded unless the user refreshes the page and enters the new value in the search field.

Update:
Below is a gif of the above mentioned scenario.

![picklist search 2](https://cloud.githubusercontent.com/assets/5861266/10319465/072bab54-6c34-11e5-8f32-cbced0fd634f.gif)

I have the picklist (FormName) configured as Form Load Type: Async
In forms: the Form Name search field is an Autocomplete with Allow Dropdown checked.

If Allow Dropdown is not checked, then the query executes on initial load of the search page (for the Change Request type) and brings back all available results since the user has not submitted any value yet.

**Comment by gsteimer** [comment]
@ladams13 - please add labels and a milestone as well too.  Thanks!

**Comment by zkeller** [comment]
@ladams13 Did you check the 'async' box in the form config? This is a different 'async' than what we discussed. That checkbox keeps the picklist from loading until the user interacts with the input, but only pulls it once. This is for very large picklists that we want all values - no filtering, but only want to load if a user types in the box or clicks the dropdown. 

The 'async' we talked about is set in the picklist config. For the picklist you want, from the Picklist Load Type dropdown, select 'async'. The box in the form config should not be checked. It is very confusing and we should rename one of them.

**Comment by gsteimer** [comment]
@benallenallen - should this be fixed as part of your current project with @ladams13 ?

**Comment by benallenallen** [comment]
Decision - in form support, need to check if it is an async picklist, and if it is, re-execute the query when it changes.

**Comment by m-brouillette** [comment]
Fixed in HPI REV - 13476
We can once again re-query for Autocomplete Picklists, whenever the box is cleared and 3 or more characters are typed again.  If 'allowDropdown' is configured, we still only query once when the arrow is still clicked on Dropdown enabled Picklists.
