### ISSUE TITLE
AW Approval Complete Email - Blank when attached document is past 0.1

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#838]
When one of the approvers has an apostrophe in his/her name user, the email approval complete email (for attached workflow documents) fails with the following error:

```
[2015-10-05 11:11:18,759|ERROR|FreeMarkerTemplateImpl|applyTemplate|53] Error processing Template

Expression approvalDetails.workflowDocumentsInfo[key] is undefined on line 45, column 11 in approval-complete-notification.ftl.
The problematic instruction:
----------
==> ${approvalDetails.workflowDocumentsInfo[key].additionalProps.docName} [on line 45, column 9 in approval-complete-notification.ftl]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression approvalDetails.workflowDocumentsInfo[key] is undefined on line 45, column 11 in approval-complete-notific
ation.ftl.
```
No errors are presented to the user, but the email is blank:

![image](https://cloud.githubusercontent.com/assets/1377228/10286719/d54a6aba-6b54-11e5-807c-d058eea32b78.png)

I'm betting this is caused by a faulty query that isn't properly escaping single quotes in a DQL statement.  Something like this is dangerous:

```java
select * from dm_user where user_name = ' + userName + "'";
```

If the `userName` variable contains something like `Conan O'Brien`, the query will fail.  Instead, the code should be:

```java
select * from dm_user where user_name = ' + userName.replace("'", "''") + "'";
```

Essentially - replace single quotes with double single, which will process correctly in DQL.

Note that for this email to show up, you must have at least one attached workflow document.

**Comment by gsteimer** [comment]
Trying this again - it looks like the problem doesn't have anything do do with the approver user name, it's the attached document.  On edge1, if I send an approval through with `TSG-101`, I get the error.  However, using a different doc produces the correct email and no error:

![image](https://cloud.githubusercontent.com/assets/1377228/10437224/43f357a0-70f1-11e5-9bb3-fc77c7a0f299.png)

This could be a case of bad data, but we should look into it to make sure.

**Comment by gsteimer** [comment]
Update - @dgrumieaux and I looked into this a little bit more and figured out that the issue is actually with documents that are past 1.0.  It seems that the problem is in the approval details json.  Here's the sections of note:

```json
    "workflowDocumentsInfo": {
        "090000028000cfb0": {
            "additionalProps": {
                "docName": "TSG-109",
                "docTitle": "Disaster Recovery"
            },
            "version": "0.1"
        }
    },
    "docSignatures": {
        "090000028000cfb0": [
            {
                "disciplines": null,
                "userId": "gsteimer",
                "userDisplayName": null,
                "status": "reject",
                "comments": "asdf",
                "informationRole": false,
                "date": 1448912155676,
                "object": {
                    "additionalProps": {
                        "docName": "TSG-109",
                        "docTitle": "Disaster Recovery"
                    },
                    "version": "0.1"
                },
                "role": "CR Approval",
                "originalUserId": null,
                "originalUserDisplayName": null
            }
        ]
    },
```

From our discussion, it seems that the problem is due to how we are keying the `workflowDocumentsInfo` list and the `docSignatures` list.  The doc signatures list is keyed by chronicle id (a relatively recent update), whereas the workflow documents info list is keyed by object id.  The thought is that if we start keying the workflow doc info section by chron id as well, this will start working properly.

@dgrumieaux @mikeblum 

@benallenallen @nwoodbine - Can you guys confirm if this is an issue on HBase?

**Comment by dgrumieaux** [comment]
It might even be on anything beyond a 0.1 - needs verification on Dctm

**Comment by gsteimer** [comment]
@dgrumieaux - yep, you're right.  If I attach a 0.2, it fails with the same error.

**Comment by ZachGerth** [comment]
Fixed with commit # 13475. CR - mikeblum.
