### ISSUE TITLE
AW Inbox - Shows wrong description for parallel tasks

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#839]
When using parallel tasks, the task "Description" is not displaying correctly based on the user's current role.  I should have two tasks here - one for my assigned task, and one for the group-based task.

![image](https://cloud.githubusercontent.com/assets/1377228/10292715/6af5b5c6-6b76-11e5-8092-0643df36f2d1.png)

![image](https://cloud.githubusercontent.com/assets/1377228/10292729/82e94c38-6b76-11e5-856f-60bc91a599d8.png)

Also, even after I acquire the group-based task, logging in as one of the other approvers (that didn't acquire the task) still shows the wrong task description:

![image](https://cloud.githubusercontent.com/assets/1377228/10292828/f678eeec-6b76-11e5-81cf-f5f6567315ac.png)

@mikeblum has a fix on a client branch ready to merge in soon

**Comment by gsteimer** [comment]
For reference, I'm using the `TS Wizard Workflows` page set on edge1

**Comment by grahamsinger** [comment]
Fixed with revision13249

We were displaying the `description` instead of the `roleName`.  So, I added the `roleName` to the model, then made sure to display that.
