### ISSUE TITLE
Lock Icon - tooltip in stage cuts off user names

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#841]
This was mentioned on #753, but I'll split it out here.  When viewing the lock icon in the stage, the lock owner text (in white) runs outside the black tooltip bounds, making it look like the user name is cut off:

![image](https://cloud.githubusercontent.com/assets/1377228/10397937/df26fa94-6e6f-11e5-83f1-705ba195d97d.png)

We should either make the text wrap, make the tooltip larger, or better - a combination of both.

**Comment by gsteimer** [comment]
For reference, Bulk Properties and Bulk Import have tooltips that wrap:

![image](https://cloud.githubusercontent.com/assets/1377228/10398613/b4b91c20-6e73-11e5-9064-1f0d61105c54.png)

**Comment by RudraVishweshwar** [comment]
DOCVIEWER - tooltip lock icon does not cut off the text anymore. Added custom config to docviewer.styl.

CR-AK

**Comment by RudraVishweshwar** [comment]
Fixed with revision #13341
