### ISSUE TITLE
Stage - Better handling of deleted objects

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#842]
If an object is deleted, but a user still has a link to the object the stage fails with the following error:

![image](https://cloud.githubusercontent.com/assets/1377228/10398224/7801a48e-6e71-11e5-8789-e0683659acc6.png)

This can happen if the user has an old notification link, or in the case of #282, recent objects.  Once this issue is implemented, we can close #282.

There's no way to prevent this error from happening, but we should present a nicer error message to the user.  One thing to note - the code won't be able to tell if the object is actually deleted or if the user simply doesn't have access to it.  We'll need to reflect that in the error message - something like: "The document or folder you are trying to view either does not exist or you do not have access to it." 

Here's what I'm thinking we need to account for:

- Navigating to a stage link directly with both a container ID and a doc ID
  - [ ] Folder does not exist
  - [ ] Folder exists, but the document doesn't
- Navigating to a stage link directly with both a container ID only
  - [ ] Folder does not exist
- Navigating through stage simple with a doc ID only:
  - [ ] Folder does not exist
  - [ ] Folder exists, but the document doesn't

**Comment by mikeblum** [comment]
In a client branch, we modified delete document to take the user to the new latest version in the version tree.

**Comment by gsteimer** [comment]
@mikeblum - this issue doesn't have anything to do with deleting an object.  It's around the scenario of attempting to go to the stage to a folder or document that is already deleted.  For example - an old link in a notification email.

**Comment by dgrumieaux** [comment]
@JasonKienzle - any update on this? Are you working on this still?

**Comment by dgrumieaux** [comment]
Can we use a runAsAdmin block in OC to tell if the user has no access on this document/folder if it is deleted? Would that make sense in order to display a better error message?

**Comment by JasonKienzle** [comment]
Last time I worked on this, I was able to get the 404 error messages showing at the proper times for Alfresco and almost Documentum. Basically, from what I have already, we'd need to make sure the various repo Impl's throw the proper exception for HPI to pick up and display the 404 message.

**Comment by gsteimer** [comment]
Can this one be closed with the work from our current client? @dgrumieaux @nwoodbine

**Comment by nwoodbine** [comment]
Fixed (and updated) in HPI Revisions 14737, 14673, 14624, 14640 + OpenContent Revisions 14162, 14099, 14095.
