### ISSUE TITLE
Saved Search Filter Changes Input Text to Lowercase 

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/hpi#844]
When typing into the Saved Search filter, the "debounced" filter function converts the displayed filter input text to lowercase. My guess is that while we want to do a case insensitive filter, we should store the filter text in a new var so we can convert to lowercase without impacting the user's entered text.

Below is an example of typing "SCR" into the filter. 

![saved-search-lowercase-bug](https://cloud.githubusercontent.com/assets/8784125/10431471/d948a958-70ca-11e5-997c-3be31a1e6a91.PNG)

**Comment by RudraVishweshwar** [comment]
Fixed with revision no. 13575.Saved Search the filter input is not automatically converted to lowercase.

CR-NW
