### ISSUE TITLE
Inbox Proxy - Set Proxy and Process Proxy

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#845]
Inbox proxy is the ability for a user to temporarily set their workflow inbox to another user.  The typical use case is - "I'm going on vacation, while I'm out, User A should get my tasks".  To make this work, there are two parts - the ability to set the proxy user, and the actual workflow proxy and audit.  Inbox proxy actually already works on Documentum, but users have no way to set their proxy user.  As a workaround, users set their inbox proxy in Webtop.  

Here's what we need to do:

- Documentum
  - [x] Set inbox proxy user in HPI User Preferences.  The Documentum side of this should be easy.  Simply set the user's `workflow_disabled` attribute to `true` and set the `user_delegation` attribute to the proxy user's `user_name`.
  - [x] Process proxy in workflow
  - [x] Audit entry
- Alfresco
  - [ ] Set inbox proxy user in HPI User Preferences.  Unlike Documentum, we need to come up with a good way to actually set the proxy user.  I could be wrong, but I don't think alfresco has anything native for this.
  - [ ] Process proxy in workflow.  This may just work, given that we use Activiti.  The main point here may just be writing the code that retrieves the proxy user given however we implement the previous item.
  - [ ] Audit entry
- Hadoop
  - [x] Set inbox proxy user in HPI User Preferences. 
  - [x] Process proxy in workflow.
  - [x] Audit entry

For reference, here's how Webtop allows users to set their inbox proxy:

![image](https://cloud.githubusercontent.com/assets/1377228/10433056/cfd34202-70d4-11e5-83b2-56916a928998.png)

**Comment by gsteimer** [comment]
Just tested this again with @aviking and it looks like this is no longer working on edge1.  This is an issue.  Once this is fixed, we can remove the issue label.

**Comment by ZachGerth** [comment]
This has been implemented for Documentum in Revision #13526 . Right now, for Documentum, it correctly forwards tasks assigned to a user with a proxy setup to the proxy, following chains of proxies if necessary, and throws an error if a "loop" is somehow created and would loop back to the user setting a proxy. For other ECMs this currently indicates that it has not yet been implemented for them.

**Comment by nwoodbine** [comment]
HBase supported by OC revision 13480 (HPI configs revision 14056). Implemented ActivitiWorkflowImpl#getInboxProxyUser so the User Preferences proxy is the default.

**Comment by dgrumieaux** [comment]
What is level of effort for Alfresco implementation, if we know?

**Comment by gsteimer** [comment]
@nwoodbine - correct me if I'm wrong, but I think the alfresco implementation will jsut work, since we did this in a generic way.  

Which reminds me - I think we can get rid of this in project-config now:

```
	'modules/hpiadmin/userpreferences/userpreferencesconfig': {
		inboxProxyEnabled: true
	},
```

Is that true?

**Comment by gsteimer** [comment]
@nwoodbine - if what I mentioned above is true, can you remove that code from any project-config's that use it, and also remove the backing code in userPreferences?

**Comment by gsteimer** [comment]
Bumping this to HPI 2.5 - we should be able to test this on Alfresco.  It may just work now that the generically coded HBase implementation is in place.

**Comment by gsteimer** [comment]
@nwoodbine @dgrumieaux - I just tested this on edge2 and it seems like it's not working.  Sounds like your current client is going to need this...

**Comment by ZachGerth** [comment]
Fixed for Alfresco in OC Revision # 14303. Removed separate configuration for enabling proxy in HPI Revision # 14990.
