### ISSUE TITLE
Picklist default value not set in search on page load

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#848]
Steps to reproduce:

- Configure a picklist value to be a default (ie Draft for status)
- Confirm picklist is used by a search form as an autocomplete control
- Navigate to search page. Attribute is not defaulted as would be expected.

If I switch between object types and back, it sets the default as expected.

**Comment by gsteimer** [comment]
@dgrumieaux - I'm assuming this is related to #746.  Should that issue be re-opened, or does it make sense for this to be a new issue?

**Comment by zkeller** [comment]
Form support is designed to not show default values in search ever. You shouldn't ever be getting default values to show up in search. I don't remember exactly why we decided to do it that way.

Is this behavior that we want to change? Issue #746 was fixed to not bomb if an autocomplete picklist did have a default value set, it didn't actually show the default value.

**Comment by gsteimer** [comment]
@zkeller - according to @grahamsinger's (https://github.com/tsgrp/hpi/issues/746#issuecomment-132652416) it sounds like he did change search to process defaults in autocompletes.

**Comment by zkeller** [comment]
Looked at the code update, it doesn't touch the code that says not to use the default value. It fixed a race condition between the typeahead instantiation and the control value getting populated. And it keeps the default value from clobbering the actual value in some scenarios.

**Comment by gsteimer** [comment]
@grahamsinger - can you comment?  was your comment on #746 misleading or did you actually get it to default a value in advanced search?

**Comment by grahamsinger** [comment]
Yeah, my comment was misleading.  As @zkeller said, the fix was to not have a picklist with a default value break the form  (the spinner indicating it was querying was constantly spinning).  However, I feel like I have had scenarios where default values would populate a dropdown, even in search.  I could be wrong though.

**Comment by dgrumieaux** [comment]
@gsteimer tracking here may make more sense now that we have established in comments what is going on.

The use case is to always search on Effective docs in controlled docs by default. This simplifies search for users of Alfresco Controlled Docs so that they don't have multiple versions showing up in search unless they explicitly change the status search term.

**Comment by dgrumieaux** [comment]
Interesting note - if there is only one value and one blank in the list, the defaulting works.

**Comment by gsteimer** [comment]
I thought we fixed this in the latest HPI codebase.  Can this item be closed? @dgrumieaux

**Comment by dgrumieaux** [comment]
I'll have to test on latest. It doesn't work on my demo branch

**Comment by dgrumieaux** [comment]
Confirmed still an issue on edge2 1/20/2016

**Comment by ZachGerth** [comment]
Fixed with Revision # 14220.

**Comment by dgrumieaux** [comment]
If a user changes the selected dropdown value to a blank value on a field that has a default, then runs a search, the correct search is performed, BUT the field switches back immediately to the default. This is not the desired behavior. After a search is performed, the field should stay at the value that was set as the search was performed.

**Comment by ZachGerth** [comment]
Fixed with Commit # 14277.
