### ISSUE TITLE
View All Documents - Can't Filter or Sort if values are blank

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#849]
In View All Documents, if you try to sort or filter and a column value has a blank value, an error is thrown. This is due to the toLowerCase() method not being allowed on an empty string or null value. See gif:

![viewalldocsissue](https://cloud.githubusercontent.com/assets/4852355/10518379/bcb80406-7326-11e5-86e0-179b6fdd48ac.gif)

**Comment by RudraVishweshwar** [comment]
Fixed at revision #13399. handles null and gets value based on new object model.
