### ISSUE TITLE
View All Documents - Cannot sort using date column

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#853]
While testing #849, I noticed that clicking to sort a date column does nothing:

![vad-sort](https://cloud.githubusercontent.com/assets/1377228/10544815/22abbc02-73eb-11e5-9dc9-35a1b814b7e2.gif)

Not sure if this is going to be an issue for any of the current client projects...

@cmlewis @zkeller @joehof @dhartman25

**Comment by dhartman25** [comment]
I know this was previously working. @zkeller - would the updates for redaction have broken this?

**Comment by zkeller** [comment]
Issue comes from the update to make link attribute configurable. Having @RudraVishweshwar fix this

**Comment by RudraVishweshwar** [comment]
Closed with revision #13439. You can now sort by date,
