### ISSUE TITLE
View renditions - link to document doesn't work when running node server

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#854]
To replicate:

- Build a node HPI server
- Configure view renditions
- Open view renditions and click a rendition link

Note that the URL is updated to an invalid address, but nothing else happens. What should happen is that the rendition type is downloaded.

**Comment by mikeblum** [comment]
at line 74 of viewrenditions.js here's how the download url is built up:

```javascript
"link" : new URI().path(app.serviceUrlRoot + "/content/content")
                                                  .addSearch("id", self.documentId)
                                                  .addSearch("download", true)
                                                  .addSearch("contentType[]", _.findWhere(self.extensions, {"mimeType" : type}).fileExtension)

**Comment by ZachGerth** [comment]
Fixed with Revision# 14015.
CR - mikeblum
