### ISSUE TITLE
Search page refresh problems

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#855]
To replicate:

- Configure both advanced search and facets
- Run an advanced search
- Refresh the page

The page never reloads, spins with a greyed out screen.

Would be good to fix in order to support URL search state continuity.

**Comment by RudraVishweshwar** [comment]
Went through steps to recreate. Unable to recreate. Attaching GIF to show the same. @dgrumieaux  can you please try to replicate this again and provide screen capture?

![facetsearch 855](https://cloud.githubusercontent.com/assets/14186904/10769913/8e04914e-7cb6-11e5-9497-b13b1b0b4705.gif)

**Comment by dgrumieaux** [comment]
@RudraVishweshwar - what version of Alfresco are you testing against?

I was able to replicate my error with alfresco-5.0.1.10 and with a custom client object model.

**Comment by RudraVishweshwar** [comment]
@dgrumieaux  I am using alfresco 5.0.1 too. I was testing it against NYPIUA so I think they have their own custom content model too.

**Comment by dgrumieaux** [comment]
I am running the node server. Are you on node or tomcat?

**Comment by RudraVishweshwar** [comment]
Tomcat

**Comment by dgrumieaux** [comment]
OK after clearing my cache and retesting this I can't replicate the issue on Chrome or on Firefox. Unsure of what caused original issue, but closing.
