### ISSUE TITLE
Audit Trail views as UTC and is not Configurable

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#856]
Currently, the "View Audit Trail", and the "View Wizard Audit Events" actions show the date/time in UTC time. This is not configurable. This enhancement would be to make it configurable so that the main HPI admin control can be used. @gsteimer: does this need to be configurable, or would it always just use what is in the admin? I'm leaning towards whatever is defined in the admin for the date/time format/zone should be used everywhere to keep things simple, but not sure if a client would want audits to be in one time zone whereas other dates be in their local timezone.

![image](https://cloud.githubusercontent.com/assets/4850976/10586997/c2760d7a-7664-11e5-838e-7881579670ee.png)

![image](https://cloud.githubusercontent.com/assets/4850976/10587020/e9b66286-7664-11e5-9e57-10aef73a7b74.png)

**Comment by gsteimer** [comment]
@benallenallen - hm... not sure.  I could see this going either way, especially for heavily regulated clients.  I would lean towards just always using the HPI application config, but you never know with heavily regulated clients.  We should meet with the TSG Controlled Docs brain trust to decide before deciding one way or the other.

**Comment by dgrumieaux** [comment]
It would be easy to allow per-action or per-module overrides if we desire that to be configurable.

**Comment by mwojno-tsg** [comment]
This issue/ehancement was fixed by utilizing the `app.context.dateService.getFormattedDatetime()` to have the date format in the view wizard audit events action to be what the user configures in the admin. Closed with OCMS commit: 24679
