### ISSUE TITLE
Note visibility - only works from document note

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#859]
I created a document note with private visibility as my user.  I logged in as another user and I correctly cannot see the note from document notes:

![image](https://cloud.githubusercontent.com/assets/1377228/10610447/6e1c18c4-770d-11e5-8b30-422281daac56.png)

However, if I go to folder notes, I can see the private note (still logged in as the other user):

![image](https://cloud.githubusercontent.com/assets/1377228/10610454/80ab9866-770d-11e5-962c-bb7844437a9c.png)

@joehof @b-k-white - I'm assuming this will be an issue for your current client project.

**Comment by b-k-white** [comment]
Fixed, configurable for both now.

HPI - 13484
CR - Zaq
