### ISSUE TITLE
Display original approver name on signature page after delegate/reassign

### ISSUE THREAD

**Issue by aviking** [tsgrp/hpi#860]
If a task was delegated or reassigned and a user who wasn't the original assignee completes the task we want it to show the original assignee's name on the signature page. For example if User A was assigned a task and delegated it to User B and User B completes the task the signature should read "User B on behalf of User A"

Design:
Keep track of the original assignee on the SignatureEvent itself.
Set the original assignee on a SignatureEvent if the assignee is ever changed.
Update how the TSGAbstractAppendSignaturePage replaces tokens.

**Comment by ZachGerth** [comment]
Closed with revision #12891. The original approver's name now appears after the delegate's signature and a configurable wording. 
CR: aviking
