### ISSUE TITLE
Create Folder in same trac - folder not getting added to recent objects

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#864]
Because of how we navigate to new folders when they are created in the same trac - we do a stage.refresh, not a Backbone.navigate, the folder isn't getting captured in recent objects. If we switch to do a Backbone.navigate, this will fix https://github.com/tsgrp/hpi/issues/863 as well.

**Comment by RudraVishweshwar** [comment]
Fixed with revision #13829. 

CR-ZK
