### ISSUE TITLE
Document Notes - Search Notifier

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/hpi#872]
Some clients would like the ability to see if their search results have a document note attached to them or not. This enhances the ability of the document notes action from search, as the user is able to tell when there are some to check.

**Comment by alieblich** [comment]
DOCUMENT NOTES NOTIFIER - Documents can now have notifier icons show in tableview search when they have notes on them. In order for a document type to show the notifier, they need to have a string meta-data field configured in their object model. This field must then be used in BOTH the tableview config as well as the document notes config. If the document attribute is not configured, everything will continue as normal.

CR Bradley, Zaq

HPI revision 13532

**Comment by alieblich** [comment]
fixed issue in link hover when attribute does not exist.

revision 13542
