### ISSUE TITLE
Saved Search Dashlet - Filtering causes column headers to disappear

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#877]
While testing #844, I noticed a new issue - when filtering, the column headers of the saved search dashlet disappear:

![saved-search-column-disappear](https://cloud.githubusercontent.com/assets/1377228/10791614/23f137ac-7d57-11e5-8aa2-e0be579d1c13.gif)

**Comment by RudraVishweshwar** [comment]
Fixed with revision 13587. When we type in filter the header does not disappear.

CR-AK
