### ISSUE TITLE
AW Reassign Task fails after delegate

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#880]
**Route started**
![image](https://cloud.githubusercontent.com/assets/1377228/10851331/95111590-7ef8-11e5-95b3-069a09b29952.png)

**1st approver delegates - works**
![image](https://cloud.githubusercontent.com/assets/1377228/10851369/bc3bdb50-7ef8-11e5-84bc-2f04206cf983.png)

**2nd approver delegates - works**
![image](https://cloud.githubusercontent.com/assets/1377228/10851434/0d746bfe-7ef9-11e5-9634-b428154b4732.png)

**Admin reassigns 2nd approver - fail**
This fails with the following error:

```
2015-10-30 11:22:41,789	40256172	TP-Processor3	ERROR	RESTService	-1
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.set(Unknown Source)
	at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowImpl.setTaskAssignee(ActivitiWorkflowImpl.java:314)
	at com.tsgrp.opencontent.wizard.action.executer.ReassignWizardWorkflowTaskActionExecuter.executeImpl(ReassignWizardWorkflowTaskActionExecuter.java:57)
```

From looking at the code and debugging, it seems that the code is not updating the assignees properly after the initial delegate.  Right before the failure, the assignees var looks like this:

![image](https://cloud.githubusercontent.com/assets/1377228/10851530/984b72f4-7ef9-11e5-9b48-e424cc9ee3ab.png)

The assignees should actually be cobrien and gsteimer.

@nwoodbine - I can only get this to happen on Documentum, although I'm not sure why that matters.  Alfresco seems to work just fine.  Can you try HBase?  If it fails on HBase, I'm guessing you'll want to fix this for your current client and bump this up to a 2.4 enhancement.

FYI - @benallenallen @dgrumieaux @mikeblum

**Comment by nwoodbine** [comment]
@gsteimer - I was able to recreate this issue on edge3.

**Comment by gsteimer** [comment]
@nwoodbine @benallenallen - I'll bump this up to HPI 2.4 since I'm guessing you'll want reassign / delegate scenarios to work for your current HBase client

**Comment by nwoodbine** [comment]
Fixed in OC Revision 13077.

**Comment by gsteimer** [comment]
@mikeblum - can you give more context?  I'm betting that @nwoodbine and @aviking will need this fixed for their respective clients...

FYI - @benallenallen

**Comment by mikeblum** [comment]
We're seeing an issue when with parallel tasks - setting the assignees is propagating to the other parallel tasks - clobbering other other task's assignees. Seeing if removing the line setting the bpm_assignees resolves it...

**Comment by mikeblum** [comment]
For the wizard, the fix was to remove this line from ActivitiWorkflowImpl ln 317:
```
		// Reset the assignees variable and set the task assignee
		// pe.getTaskService().setVariable(taskId, WorkflowConstants.ASSIGNEES_KEY, assignees);
```

as it was clobbering task assignees for parallel tasks. Going forward, we'll want to support multiple assignees ```bpm_assignees`` but for the time-being, since wizard tasks always have one assignee per task, this fix works for Wizard clients. Simple Workflow/trunk needs more discussion. @dgrumieux, @gsteimer

**Comment by gsteimer** [comment]
@mikeblum are you sure this change doesn't affect any other types of workflows?  I'm thinking of HPI Simple Workflow or other AW workflow scenarios

**Comment by gsteimer** [comment]
@mikeblum - I just tried this out on edge1 (with two approvers in two roles, same priority) and it worked perfectly fine:

![image](https://cloud.githubusercontent.com/assets/1377228/11352040/aa945836-91ff-11e5-838b-c92364dd623b.png)

![image](https://cloud.githubusercontent.com/assets/1377228/11352046/b1052952-91ff-11e5-8ad6-f2fe550b8312.png)

Am I missing something?

**Comment by gsteimer** [comment]
Closing this in favor of a new issue: #902
