### ISSUE TITLE
Search - Tracs are not ordering properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#882]
The search page is not ordering tracs in the dropdown properly.  It should be based on the order of the tracs in TracConfig:

![image](https://cloud.githubusercontent.com/assets/1377228/10894474/7f11e26e-8174-11e5-9db3-4b0f4263d2f2.png)

![image](https://cloud.githubusercontent.com/assets/1377228/10894488/85d28cac-8174-11e5-8281-40945685db8d.png)

We have seen this before - #323 - but that was with the old admin, so I'm opening a new issue.

**Comment by renesaladrigas** [comment]
Tracs are displayed correctly on the search page based on the order configured by the user.

CR - ZKeller
Revision 13707
