### ISSUE TITLE
When finishing a Wizard Approval route no email is sent

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#884]
By default, the initiator should get an email when a form approval is completed in Active Wizard.  However, this email is no longer coming through.

@dgrumieaux @mikeblum - I did a quick call hierarchy on the `WizardConfig#getWizardSendToInitiator`.  I only see this being utilized in the Abort and WizardReview listeners:

![image](https://cloud.githubusercontent.com/assets/1377228/10895961/98096c44-817c-11e5-83ae-95caf4b8e5d0.png)

The review complete email sends perfectly fine.  Did some code in the Approve/Reject listener get deleted recently?

**Comment by mikeblum** [comment]
r13045 | mblum | 2015-11-03 09:01:28 -0600 (Tue, 03 Nov 2015) | 1 line

WORKFLOW EMAILS TO INIATGOR/OWNER: upon approving or rejecting a workflow, either the form owner or the iniator gets a workflow email. Reinstating code here so nothing new to see.


** OC Update Required **
