### ISSUE TITLE
After Bulk Upload the confirmation page gets overwritten immediately

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#888]
See the screencam below - if you have a folder with an action configured to load upon stage load (typically View All Documents), the Bulk Upload confirmation screen is immediately replaced after documents are uploaded.  This is an issue because if any documents fail to upload, the user never has the chance to see what went wrong.

![bu-confirmation-replaced](https://cloud.githubusercontent.com/assets/1377228/10947871/46bb955e-82f0-11e5-8e80-6bb9866b965a.gif)

**Comment by renesaladrigas** [comment]
After bulk upload the confirmation message stays on the screen until dismissed by the user; the stage refreshes itself after dismissing this message.

CR - ZKeller
Revision 13709
