### ISSUE TITLE
If form is in a workflow route, loading previous version allows user to attempt to start another route

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#889]
See screenshots below - we should be restricting the following actions to only execute on the most recent version of the form:

- [x] Start Review Route
- [x] Start Approval Route
- [x] Manage Controlled Documents

**Latest Version - in a workflow**
![image](https://cloud.githubusercontent.com/assets/1377228/10975841/7219baf0-83ae-11e5-90cf-1ae77bb8539e.png)

**Old version**
![image](https://cloud.githubusercontent.com/assets/1377228/10975857/850e01c0-83ae-11e5-814a-0ce0395b7d67.png)

One note here for Documentum, the `LATEST` flag is _not_ applied to forms - only to documents.  If we can have the condition look for `CURRENT`, it should work properly.  We'll have to ensure that the Alfresco and HBase impls work properly as well.

**Comment by gsteimer** [comment]
Update - this seems to work properly on alfresco:

**Old Version - latest version in a workflow route**
![image](https://cloud.githubusercontent.com/assets/1377228/10975998/4f52dd70-83af-11e5-8270-4ef06e30ec17.png)

**Comment by dgrumieaux** [comment]
Can use the in spaces store condition for alfresco.

**Comment by gsteimer** [comment]
@dgrumieaux - it's actually pretty odd - this works fine on Alfresco.  So it's just Documentum and possibly HBase that are not working properly.

**Comment by ZachGerth** [comment]
Fixed with OC Revision # 13451. CR - dgrumieaux

**Comment by ZachGerth** [comment]
Leaving open so that it can be tested with HBase.

**Comment by gsteimer** [comment]
Just tested this on hbase, seems to be working
