### ISSUE TITLE
Date Search Enhancement

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#890]
We currently allow users to input a specific to/from date when searching. A useful enhancement (or new control) would be for users to be able to enter a generic range instead, like in the next 30 days or in the past 12 months. This would be great for saved searches, where a user might want to see contracts that are expiring in the next 90 days, or docs made effective in the past week.

**Comment by gsteimer** [comment]
When we do this, it would also be good to include this functionality in the Saved Search dashlet.

**Comment by alieblich** [comment]
PROXIMITY DATE SEARCH - Add new control type to allow for proximity date searching. Users will be able to search on fields that have a date within X number of days/weeks/months either in the past or the future. Proximity date search also works with saved search dashlet and can be configured to search with the same parameters as listed.

Also, alphabetized the control list in formattributemodel.html

cr - Zaq, Graham


HPI rev - 13821
