### ISSUE TITLE
Bulk Properties Cascading Auto-Select

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/hpi#893]
When auto-select is enabled in form support so that options are automatically selected when its dependent attribute is selected. It currently incorrectly handles the new selection and the old one that propagated from bulk properties. See gif below, after changing to Resume, the category should only have one value, but it has two.
![bulkpropcascadeissue](https://cloud.githubusercontent.com/assets/8796489/11040291/1db1556a-86d1-11e5-9875-53edd24080c5.gif)

**Comment by alieblich** [comment]
Fixed
hpi revision 13747
