### ISSUE TITLE
Inbox Proxy Indicator

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#894]
We have Inbox proxy configurable (and working for Documentum - see #845), however it would be nice to have some sort of proxy indicator on the dashboard.  This way, users have a visual reminder that their inbox is proxied to another user.  With no indicator, it's entirely likely that users will forget to remove their inbox proxy.

Notes:

* Should the indicator be on the inbox dashlet or in the Dashboard header?  I'm leaning towards the header at this point, since we have multiple inbox dashlets.
* Somewhere in the wording there should be a link to the user preferences Workflow tab.
* Wording should be something like this: `Your inbox is currently proxied to User Name.`

**Comment by gsteimer** [comment]
While doing this, I think we should change the wording on the Inbox Proxy config page.  It's confusing to use "inbox proxy", "enabled", and "disabled".  

![image](https://cloud.githubusercontent.com/assets/1377228/11282429/f2dda0a4-8ec4-11e5-80c9-c7d49ffd0f10.png)

We should put this in more user friendly terms:

- Title: Are you available to receive workflow tasks?
- Options:
  - Yes
  - No - choosing this will bring up the typeahead to select a proxy user.

**Comment by renesaladrigas** [comment]
DASHBOARD & USER PREFERENCES -- Added a message on the dashboard that reminds the user their inbox is still proxied to the specified user. Changed wording in user preferences workflow tab to be more user friendly. Appropriate unit tests are also included in this commit.

Closed with revision 13870.

CR- ZKeller
