### ISSUE TITLE
Bulk Upload Form Reseting

### ISSUE THREAD

**Issue by alieblich** [tsgrp/hpi#896]
When re-entering the bulk upload folder action configs, the form to display is being reset

![bulkuploadformbug2](https://cloud.githubusercontent.com/assets/14186936/11224940/0c2ee196-8d3d-11e5-96f9-2cc924889da0.gif)

**Comment by gsteimer** [comment]
@alieblich - can you post a gif to give more context?

**Comment by alieblich** [comment]
Yup, updated the original comment just now

**Comment by gsteimer** [comment]
@benallenallen - you mentioned this is happening in at least 3 other places?  Can you add a checklist?

**Comment by benallenallen** [comment]
Can't reproduce the other places I was seeing it, but the "Bulk Upload" is def happening.

**Comment by alieblich** [comment]
BULK UPLOAD CONFIG - After the dropdown options are loaded, made sure to set the form value to the value that was saved previously.

Fixed with hpi rev 13787

cr - Zaq
