### ISSUE TITLE
Bulk Upload - No longer refreshes related objects

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#900]
This one is breaking the HPI automated system tests.  After bulk upload completes uploading documents, the Folder Contents related objects section should refresh to show the added documents in the tree.  However, this is no longer happening:

![bu-refresh-folder-contents](https://cloud.githubusercontent.com/assets/1377228/11351669/ab9bb262-91fd-11e5-8c0b-c26f12ebd528.gif)

Question - I'm not sure if the code was previously refreshing _all_ related objects sections, or only the related objects 'children' section.

**Comment by zkeller** [comment]
It should be refreshing the related objects section when the add documents action is closed. The code that was reloading related objects is the same code that forced the view all docs to show up after the upload.

If we need both to happen, we'll need to refactor how that code gets called, which could be difficult.

**Comment by gsteimer** [comment]
@zkeller since bulk upload is configured as a full pane action in most cases, (as in my screencam) there's really no "close" that's apparent to the user.  Let's talk in the weekly meeting about our options.

**Comment by gsteimer** [comment]
Decision from the HPI/OC meeting on 11/24:

- Add documents should fire a new event after documents are added
- Related objects should listen for this new event and refresh when the event is fired

**Comment by dgrumieaux** [comment]
What should the new event name be? Leaning towards "stage.container.childrenChanged" unless anyone else has any ideas.

**Comment by dgrumieaux** [comment]
This should be tested on IE9 and modern browsers before being called finished

**Comment by gsteimer** [comment]
I like the childrenChanged event name.  That way we can scope it to only 'children' related objects, and not force all related sections to update.

**Comment by alieblich** [comment]
RELATED OBJECTS - BULK UPLOAD - add listener in Related Objects that listens to when Bulk Upload is done uploading docs that then refreshes the list of related objects.

CR - Dan

HPI Rev - 13888
