### ISSUE TITLE
After running search with a proximity search, it's impossible to remove the criteria

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#901]
See the screencam below:

![prox-date-reset](https://cloud.githubusercontent.com/assets/1377228/11372110/51bd32fe-9291-11e5-9ed4-e0ef937834ac.gif)

@alieblich

**Comment by alieblich** [comment]
PROXIMITY SEARCH - Fix bug where the proximity search criteria was not getting removed when a proximity search value was being reset.

HPI rev - 13859

CR - Zaq
