### ISSUE TITLE
Info Block no longer displaying

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#904]
Something seems to be wrong with the Info Block functionality for related objects sections configured recently.  For the Controlled Docs trac on edge2, info blocks appear fine:

![image](https://cloud.githubusercontent.com/assets/1377228/11380720/6b541828-92bd-11e5-9c2a-56584bd569e9.png)

But in the admin, something looks off:

![image](https://cloud.githubusercontent.com/assets/1377228/11380725/743566c2-92bd-11e5-9feb-e5dea2b50e6e.png)

If I change it to what it should be and save:

![image](https://cloud.githubusercontent.com/assets/1377228/11380740/8e7e517e-92bd-11e5-91d0-2b4f11c53060.png)

Now the info block doesn't appear at all:

![image](https://cloud.githubusercontent.com/assets/1377228/11380749/9b29118e-92bd-11e5-9d81-c9e9fc037db5.png)

**Comment by gsteimer** [comment]
could this be due to admin updates from #590?

**Comment by alieblich** [comment]
RELATED OBJECT INFO BLOCK - Fix an issue where info blocks in related objects were not showing up after updating admin configs due to the configs saving the attributes to be displayed in the info block as objects instead of their oc string names.

HPI rev - 13899

Cr - Graham
