### ISSUE TITLE
DatetimeBox broken on Search

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#905]
The DatetimeBox control type seems to have broken on Advanced Search (haven't tested it from edit properties). See the below gif, but what I'm seeing that needs to be fixed:

- [ ] there is a random ` character, that is probably just a symptom of the main problem
- [ ] clicking on an actual date doesn't seem to select the date at all
- [ ] dragging on the hour slider seems to lose focus as soon as you move the mouse one hour

![vers](https://cloud.githubusercontent.com/assets/4850976/11382926/5c9fb640-92ca-11e5-9c47-af9bbd5fc222.gif)

**Comment by nwoodbine** [comment]
Fixed in HPI revision 13898
