### ISSUE TITLE
Creating Folder Notes does not work in HBase

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#910]
Currently on edge3, if you go to add a folder note, you are allowed to enter it in as expected. However, once you add the folder note, it does not show up as a folder note.

I have verified that the folder note object is being created in the repository.

Based on discussion with @benallenallen , next step is to determine if the relationship logic is being created correctly.

@nwoodbine - thoughts?

**Comment by dgrumieaux** [comment]
@nwoodbine status?

**Comment by nwoodbine** [comment]
Fixed in OC revision 13485
