### ISSUE TITLE
Simple Workflow - Complete Task action does not work on Edge1

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#913]
For some reason, the complete task action does not fully load on edge1.  This works fine (viewing the action and completing a task) on edge2.

*Action never fully loads*
![image](https://cloud.githubusercontent.com/assets/1377228/11660358/759c6bfc-9d92-11e5-89ff-2e03fd6b8c07.png)

*Console*
![image](https://cloud.githubusercontent.com/assets/1377228/11660386/91dbaabc-9d92-11e5-8545-a5389de65418.png)

I'm guessing that this is most likely a configuration problem with edge1 and not actually a Documentum specific issue since the code is never calling OC...

**Comment by ZachGerth** [comment]
This was a configuration problem in edge1 - for some reason, it was set to "completetask" instead of "completeTask" for this action, and not able to resolve what that was, it would just crash. Removing completetask and adding completeTask resolved the issue.
