### ISSUE TITLE
FormSupport - Dates in non-editable fields are blank

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#914]
It seems like dates are not displaying properly when the field is non-editable.

On edge2 (Alfresco), all dates are not displaying when the field is non-editable.  See below - the two editable fields are fine, but the creation date and modified date are not:

![image](https://cloud.githubusercontent.com/assets/1377228/11662096/b0f6ec6a-9d9a-11e5-88a7-7a6aba2a21b4.png)

This happens across multiple tracs with OOTB properties (like created and modified) as well as custom properties (like Quality Doc's effective date and approved date)

However, on edge1 (Documentum) it's a little different.  In the screenshot below, all the custom properties are displaying, but the OOTB properites are not:

![image](https://cloud.githubusercontent.com/assets/1377228/11662164/fb5281ac-9d9a-11e5-9477-cbad1972f5df.png)

**Comment by gsteimer** [comment]
Update from @grahamsinger - this may actually be an issue of datetime fields vs. dates (not editable vs. disabled)

**Comment by alieblich** [comment]
FORM SUPPORT - Add date validation to markup that was causing an issue with Datetime fields from showing on formsupport.html

HPI rev - 13926

cr - Graham
