### ISSUE TITLE
"object-modified" event not reloading search results

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#915]
![bug](https://cloud.githubusercontent.com/assets/547941/11662458/50a6bdb6-9d9c-11e5-8ee5-0271379a5dfd.gif)

@gsteimer @eschwarzbeck what milestone should this issue be marked at?

**Comment by gsteimer** [comment]
@dgrumieaux It's not high priority unless someone is assigned and actively working on it.  I'd say 2.5 unless a client needs it in the next month or so (I'm hoping to cut 2.4 by mid-January at the latest).

**Comment by dgrumieaux** [comment]
OK - @eschwarzbeck let's confirm if your client needs this fix

**Comment by eschwarzbeck** [comment]
Issue has been resolved. However we still need to write a unit test.

**Comment by gsteimer** [comment]
@eschwarzbeck - status on this?  Has the unit test been written?

**Comment by eschwarzbeck** [comment]
@gsteimer  - No, if someone has time to write I could fill them in.

**Comment by RudraVishweshwar** [comment]
Fixed with revision no. 14352. 

CR-DG
