### ISSUE TITLE
View All Documents - Inconsistent Links When Filtering

### ISSUE THREAD

**Issue by JasonKienzle** [tsgrp/hpi#916]
This issue involves the "View All Documents" action in stage (see gif below). Basically, when you try to click the "View Properties" or "Export" links with the unfiltered view, everything works fine. As soon as you type into the filter and pare down your table rows, the first 2 columns of the table (the aforementioned links) don't match the rest of the information and appear to reference the first X documents from the unfiltered table.

Also, this appears on my client's branch and trunk, so this issue goes back to at least June 2015 (for anyone else who has branched code)

![viewalldocuments](https://cloud.githubusercontent.com/assets/4266516/11668548/645a3cc2-9dbd-11e5-83fb-c6cadd989e2e.gif)

**Comment by grahamsinger** [comment]
Fixing this for our current client.

**Comment by grahamsinger** [comment]
Fixed at revision 13925.  We were going off of `recentDocuments`
