### ISSUE TITLE
Full Text Search - bringing back invalid results

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#921]
See the screencapture below - on edge2, when I do an attribute search, it's working properly.  However, if I do a full text search or combine the attribute search with a full text search, the search is bringing back invalid results and not correctly ANDing the parameters.  See below:

**Full Text Search**
When I do a full text search only, the search results are correctly reading full text, BUT some of the results are from totally different tracs.  In my example, I'm doing a search for Underwriting Documents, but I'm getting results from the contract management trac (the MSAs and DocuSign test docs) and in Incident trac (the sentencing documents) as well.

![full-text-alf-search](https://cloud.githubusercontent.com/assets/1377228/11745562/abeaee42-9fde-11e5-948e-1b11da00be0d.gif)

**Full Text + Attribute Search**
When I combine full text and attribute search, it doesn't seem like the search criteria are ANDed properly.  I also get values back from other tracs, but even documents within the correct trac are coming back when they shouldn't:

![full-text-alf-search-w-attrs](https://cloud.githubusercontent.com/assets/1377228/11745612/0af91b20-9fdf-11e5-90e1-3482f8e648eb.gif)

**Comment by alieblich** [comment]
Just committed a fix for the above two bugs for Alfresco 4 (added quotes around full text search terms)
in OC rev 13402 .

Looking into the issue with full text search in Alfresco 5 where multiple search terms are being OR'ed now.

**Comment by alieblich** [comment]
Fixed full text search in Alfresco 5.x implementation to wrap the search terms in quotes.

OC rev 13404

CR - Dan
