### ISSUE TITLE
New Advanced Search should not be the default when Attribute Search configured

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#926]
When both advanced search and attribute search are configured for a type, we should be defaulting to Attribute Search.  See the screencam below:

![attr-search-default](https://cloud.githubusercontent.com/assets/1377228/11817851/7cf0ced6-a31c-11e5-9329-b3afec4d7177.gif)

**Comment by alieblich** [comment]
update search side bar to store the last search type in user preferences instead of a cookie

HPI rev - 13987

CR - Graham
