### ISSUE TITLE
After creating a folder note, the stage is refreshed.  Should send user back to folder notes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#927]
See below:

![folder-notes-refresh](https://cloud.githubusercontent.com/assets/1377228/11853517/20bb30f0-a404-11e5-8367-857ffd76e7db.gif)

Perhaps related to #888?  Is there something deeper going on here that we need to address so that we don't have to keep doing spot fixes for every full pane action?

**Comment by alieblich** [comment]
Remove code that enabled auto launching actions after a folder was already opened in stage. Updated unit test to reflect change

hpi rev 13992

CR - Graham
