### ISSUE TITLE
Bulk Upload - Bulk Properties not correctly applied to documents when property is inherited from folder

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#928]
See the screencam below.  The Policy Holder property is correctly inherited from the folder properties to the bulk property page.  However, if that property is changed, the update is not correctly reflected on the individual document pages.  

It seems that this is only happening with properties that are inherited from the folder.  Non-inherited properties seem to be set properly (Folder Tags in the example below).

![bulk-upload-bulk-props](https://cloud.githubusercontent.com/assets/1377228/11854124/6ddf35c2-a407-11e5-9b44-0dabbc8f7a44.gif)

**Comment by alieblich** [comment]
Add back in code to copy properties to docs being uploaded in bulk upload that was removed in rev 13573

hpi rev - 13989

CR - Bradley
