### ISSUE TITLE
Advanced Search (old complex search) - AND/OR doesn't seem to work properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#929]
I was testing out advanced search (used to be called complex search) on edge today and I'm seeing some incorrect behavior with AND / OR functionality.  See below:

These searches are all from edge2 on the Contract Management trac

*Searching for state like IL and 'ALL of these values - looks good*
![image](https://cloud.githubusercontent.com/assets/1377228/11871516/b2908e30-a495-11e5-8f33-0d19615c7af0.png)

*Searching for state like IL, creator like 'George', and 'ANY of these values - looks good*
![image](https://cloud.githubusercontent.com/assets/1377228/11871554/f38671d4-a495-11e5-87ea-734492ffb6d1.png)

*Searching for state like IL, creator like 'George', and 'ALL of these values - not correct*
![image](https://cloud.githubusercontent.com/assets/1377228/11871571/10f5e3d0-a496-11e5-8864-d0fe1ecf8fbd.png)

The above query brings back zero results, but I would think that it should return 2 results (where state = IL and Creator like 'George'.  Changing the creator to 'George Steimer' or 'Ray' still returns zero results.

I also tested this on edge1 with similar results:

*Status like Effective, Doc Number like Security, ANY of these values - incorrect results*
![image](https://cloud.githubusercontent.com/assets/1377228/11871707/d6190642-a496-11e5-968e-3a1ef6a5d0da.png)

*Status like Effective, Doc Number like Security, ALL of these values - incorrect results*
![image](https://cloud.githubusercontent.com/assets/1377228/11871720/ebbeb42e-a496-11e5-915d-01da0e1d4ea6.png)

**Comment by gsteimer** [comment]
Update - turns out that this is not an issue, at least on Alfresco.  I was seeing the problems above because I'm using creator, which isn't tokenized properly for LIKE searches.

However, I'm leaving this issue open since I still was seeing problems on Documentum

**Comment by gsteimer** [comment]
Marking this as HBase - not because I think there's issues, but because I don't think we've tested Advanced Search at all on it...

**Comment by ZachGerth** [comment]
I was unable to replicate this in wizard-dctm on hpi_dev_71; it appeared that the various combinations George recommended and others would search fine, and apply the AND/ORs properly.
I can't test on edge1 right now while some config changes are pending.

**Comment by gsteimer** [comment]
I tried this out again on edge1 and edge2 and it seems to be working now.  Not sure what Rev fixed it, but it's definitely working...
