### ISSUE TITLE
Advanced Search (old Complex Search) - Does not properly work with Full Text Search button

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#931]
The search buttons on the search criteria pane should all work in the same way.  That is, user's aren't going to know that clicking the search button here:

![image](https://cloud.githubusercontent.com/assets/1377228/11872017/cb3ecc50-a498-11e5-99c3-d771833f393f.png)

Works differently than the button here:

![image](https://cloud.githubusercontent.com/assets/1377228/11872021/d4a02d7a-a498-11e5-8ef8-0b78f413b846.png)

So, with Attribute searches, users can click either button and get the same results.  For example:

1. Only entering attributes and then clicking the full text search button will execute the attribute search in the same way as clicking the attr search button (Users do this *all* the time...)
1. If the user enters *both* full text and attributes, either button does the same thing.  The full text results should be `AND`ed with the attribute results.

I'm seeing some odd behavior when trying these scenarios with the new Advanced Search pane.  For example:

*Enter Advanced Attribute, click full text search button - tells me to enter params*
![image](https://cloud.githubusercontent.com/assets/1377228/11872109/3ebbbf62-a499-11e5-8b32-182686b97de6.png)

Due to #930, i wasn't able to test a scenario where we combine advanced search and a full text search.  We should definitely test that, and ensure the correct results are returned.

**Comment by gsteimer** [comment]
Note - the same thing happens on edge1, which doesn't have the problem mentioned in #930, so I'm guessing this issue isn't caused by #930...

**Comment by ZachGerth** [comment]
Closed with revision # 13997.

CR - gsinger
