### ISSUE TITLE
Approval Details object does not "clean" input of non UTF-8 characters

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#932]
A client experienced an error where a workflow could not be cancelled due to non UTF-8 characters breaking Jackson parsing of the Approval Details object. The signature comments should be cleaned of non UTF-8 characters and replaced with their safe UTF-8 encoded counterpart.

The offending character was  , which is a Windows specific encoding for hyphens (-) in some systems. This can potentially occur when copying and pasting from a Microsoft Word document.

**Comment by ZachGerth** [comment]
Fixed with revision # 13569. CR - dgrumieaux
