### ISSUE TITLE
Advance Combine PDF config - adding ONE attribute broken

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/hpi#935]
Saving 1 attribute doesn't work.  However, for some reason, saving 2 (and I'm assuming more) works.  

See GIF below:
![advancecombineconfigonce](https://cloud.githubusercontent.com/assets/8784597/12053949/b7f375e2-aee3-11e5-8a6c-3120ec271707.gif)

**Comment by b-k-white** [comment]
Fixed, will get a CR tomorrow.

**Comment by b-k-white** [comment]
Fixed.

HPI - 14181
CR - Joe
