### ISSUE TITLE
Folder Browser - Folder Contents do not load until page is refreshed

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#942]
See the screencam below (from edge2).  Clicking on a folder does nothing upon entering the folder browser.  However, after I refresh the page, it magically starts working.

![folder-browser-load-fail](https://cloud.githubusercontent.com/assets/1377228/12126624/e7a5e53a-b3b7-11e5-892a-949f45bb529f.gif)

An error is coming up in the JS console:

![image](https://cloud.githubusercontent.com/assets/1377228/12126644/064a63ee-b3b8-11e5-8ca1-5334c045a972.png)

**Comment by gsteimer** [comment]
Looking at this with @ZachGerth - I still do see the problem, but now only when there's an Audio file (MP3) in the folder.  The error is:

![image](https://cloud.githubusercontent.com/assets/1377228/12128261/b560d616-b3c1-11e5-839c-5f5bee14b633.png)

**Comment by ZachGerth** [comment]
Right now on Edge2, even with the audio file this isn't happening consistently for me - selecting folder browser and navigating to the folder with the audio file, then selecting it, it correctly loads the tableview results. I got it to occur once earlier today before looking into it, but not since then.

**Comment by gsteimer** [comment]
Closing this - there must be something going on with my browser.  I can't get the error to happen at all using Chrome in incognito mode.

**Comment by gsteimer** [comment]
Ok - I think I finally figured out a way to consistently get this to happen:

![folder-browser-weirdness](https://cloud.githubusercontent.com/assets/1377228/12128962/444da9fe-b3c6-11e5-9d9d-3e1cd3dfeca1.gif)

Also - notice that simply hovering over the document link clicks it.  We should definitely fix that as well.

@ZachGerth

**Comment by ZachGerth** [comment]
Fixed with revision # 14046; the issue was that folderbrowser would automatically redirect on hover, and it was incorrectly trying to find the mimeType of audio or video documents. CR - aviking
