### ISSUE TITLE
Collections - fails to load using browser history

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#943]
Clicking on a collection in edge2 fails with the following:

![image](https://cloud.githubusercontent.com/assets/1377228/12126679/447902ba-b3b8-11e5-9c1c-995a80cf17e0.png)

Admin updates in #590 haven't been implemented yet for collections, so I'm not sure why this is no longer working

**Comment by gsteimer** [comment]
Note - this is also making it impossible to delete a collection.  When you try to delete a collection, the same error occurs and the Remove Collection dialog is stuck behind the gray overlay (can't click on anything):

![image](https://cloud.githubusercontent.com/assets/1377228/12126757/b4661400-b3b8-11e5-96d4-386aeefcdee1.png)

**Comment by gsteimer** [comment]
From talking to @ZachGerth - this is because the Collections admin config has not been updated in #590.  Once we implement the collection admin, this should start working again.

**Comment by gsteimer** [comment]
On second glance - this was just a collections config issue.  However, after fixing the issue, I'm still seeing issues trying to get the collection item to load.

![image](https://cloud.githubusercontent.com/assets/1377228/12128134/119c3f16-b3c1-11e5-9d49-064160950539.png)

**Comment by gsteimer** [comment]
Closing this - there must be something going on with my browser.  I can't get the error to happen at all using Chrome in incognito mode.

**Comment by gsteimer** [comment]
Similar to #942, I can now get this to consistently happen:

![collections-load-fail](https://cloud.githubusercontent.com/assets/1377228/12129001/8591e3bc-b3c6-11e5-9b23-c32f7cd31971.gif)

Note - because of #632, you cannot just click the back button - you have to go back two steps.

**Comment by ZachGerth** [comment]
Fixed with revision # 14046. Similar to the initial cause of #942, this was due to code incorrectly trying to find the mimeType of an object to determine if it was an audio file.
