### ISSUE TITLE
Advanced Combine to PDF - Sorting Attribute is hardcoded to object name

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/hpi#944]
Currently, the Advanced Combine to PDF action is hardcoded to sort by `objectName`.  This presents a problem when `objectName` is not chosen as one of the **Attributes to Show**.  The action will crash when trying to remove a document that has been inadvertently selected to be combined.

The problem stems from the fact that when a document is selected to "be combined", we are only passing along the **Attributes to Show** on that JS object.  So, when it is passed back to the **Available Docs**  (without an objectId) the following line crashes: 

    model1.get("properties").objectName.toLowerCase().localeCompare(model2.get("properties").objectName.toLowerCase());`

The enhancement would be to:
* Add a dropdown to the config to allow the sortable attribute to be selected. (See View All Documents action for an example)
* Pass the entire OCO to and from when selecting/deselecting documents.

**Comment by b-k-white** [comment]
Fixed.

HPI - 14181
CR - Joe
