### ISSUE TITLE
Advanced Search - Typeahead fields do nothing on the search form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#945]
See the screencam below.  Issues:

1. Searching for only a Typeahead field - HPI thinks the form isn't filled out
2. Searching for a Text field and typeahead field - only text field is sent as search criteria

![adv-searc-fail](https://cloud.githubusercontent.com/assets/1377228/12128486/3f2abc26-b3c3-11e5-8db5-0b343aaded3f.gif)

**Comment by ZachGerth** [comment]
This appears to be fixed with revision #14042.

**Comment by ZachGerth** [comment]
This is still happening on Edge 1 - to specify, typing in the value and hitting "Enter", it does not think the field has a value, but if selecting it from the form, it does.

**Comment by ZachGerth** [comment]
Fixed with Revision # 14050. CR - grahamsinger
