### ISSUE TITLE
User Preferences Workflow Allows Empty Proxy

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/hpi#948]
Typically the Save button is disabled in order to prevent this. However, I noticed that if I refresh the page before selecting a proxy, the Save button is enabled, allowing for an blank proxy user to be assigned. See the image below:

 ![blank-proxy](https://cloud.githubusercontent.com/assets/8784125/12151773/70b6a454-b476-11e5-940a-de64f8278d4e.png)

**Comment by ZachGerth** [comment]
Fixed with Revision # 14055. Also added unit tests. CR - aviking
