### ISSUE TITLE
Enhance FormConfig DependsOn Rule to Support Conditionals

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#949]
Current state of FormConfig dependsOn allows an admin to configure if a field has a value selected, then another field will show up. This enhancement would allow a conditional test to determine if the dependent field should show up. For instance, if the field matches a value, or a value in a picklist, or matches a regex field... simplest/most flexible to start with would be a regex match.

Current state:
![dependsonss](https://cloud.githubusercontent.com/assets/547941/12158570/f5746bc2-b48f-11e5-8526-53552ad40d3c.png)

**Comment by dgrumieaux** [comment]
@aviking @joehof thoughts on difficulty?

**Comment by nwoodbine** [comment]
Merged to trunk in HPI revision 14385

**Comment by nwoodbine** [comment]
HPI REV 14483 For regex comparison
