### ISSUE TITLE
AW Overlay - 

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#957]
See below - it looks like the Draft status overlay is being burned in on Edge2:

**Draft**
![image](https://cloud.githubusercontent.com/assets/1377228/12337263/99f36fce-bace-11e5-893e-e4016a367e9a.png)

**In Review**
![image](https://cloud.githubusercontent.com/assets/1377228/12337268/a2c9984e-bace-11e5-880c-b43ece08c54e.png)

**Pending Approval**
![image](https://cloud.githubusercontent.com/assets/1377228/12337296/c3ec49cc-bace-11e5-8d8a-f57681969585.png)

Note that the In Review overlay doesn't seem to be sticking around - so it's only the Draft overlay that's being burned in.

**Comment by gsteimer** [comment]
Update - same thing is happening on edge1:

![image](https://cloud.githubusercontent.com/assets/1377228/12337358/2eedcb74-bacf-11e5-80d1-84f79221f031.png)

**Comment by mikeblum** [comment]
Made an update to the OpenOverlay code to make an explicit object type check before loading the document in to iText for further checks against orientation, page number, etc. You should now see open-overlay-1.4.1.jar in the `WEB-INF/lib` directory of your exploded Tomcat. The test case is to take a Wizard form and start an Approval/Review route then cancel the route - the status should be updating properly and not burning-in.

Note: if your openoverlay config lacks an object type it just passes through this check as valid so the following config is valid even though it lacks a type:
```html
<!-- 
		Footer overlay - applied when the Combined PDF is viewed.
		This overlay displays the page x of y text.
	-->
	<overlay id="footerPageNumOnView">
		<configuration pageOrientation="portrait" pageSize="letter" />
		<restrictions>
			<restriction key="ocCombinedPDFRequest" value="true"/>
		</restrictions>
		<actions />
		<block id="0" x="535" y="30" alignment="right" rotation="0">
			<text template="default" font-size="10">Page ${currentPage} of ${totalPages}</text>
		</block>
    </overlay>
```
