### ISSUE TITLE
Bulk Upload with .msg -- Attachments with identical names cause upload to fail

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/hpi#960]
Trying to upload an .msg will fail if there are attachments that have identical names.  The underlying reason that this happens is because there is a map created of the attachments and their properties, so there will only be one object in the map for the attachments with identical names, instead of the actual number of attachments.  When the second of an identical attachment is queued to upload, it grabs the same properties from the first one (that has been previously uploaded) which causes a duplicate node error.

**Comment by gsteimer** [comment]
@grahamsinger - Documentum (and I believe HBase) do allow documents in the same folder with the same name.  Is our code failing, or is the only problem the eventual duplicate node error?  If it's only the duplicate node error, then we should mark this as an Alfresco specific issue.

**Comment by grahamsinger** [comment]
@gsteimer Right, but the properties map that is created for the attachments is wrong, so even though the upload might be "allowed" in DCTM and HBase, the properties will be incorrect (i.e. all identical attachments will pull map to the same properties object in that map).

**Comment by gsteimer** [comment]
@grahamsinger  - Ok, sounds good.  I just wanted to make sure.  We typically recommend against naming documents the same thing anyway in Dctm/Hbase even though it's allowed.

I'm guessing the fix here would be to automatically do something to change the name of the document after it's pulled off the email?  Something like `My Doc.pdf` and `My Doc (1).pdf`?

**Comment by grahamsinger** [comment]
@gsteimer Yeah exactly.  It's a interesting scenario for sure to have attachments with the same name.  But, even if you change the names in bulk props, the actual file name is what end up being used in the map created in OC.  So, unfortunately that can't be used as a solution.  The proper fix will involve making sure that this map correct.

**Comment by grahamsinger** [comment]
Have this fixed. Waiting on a CR.

**Comment by grahamsinger** [comment]
Fixed with OC revision 13631.

CR - George
