### ISSUE TITLE
Searching on repeating attributes is broken

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/hpi#965]
See below (edge2):

![searchrepattr](https://cloud.githubusercontent.com/assets/8784597/12459298/a6e0bbca-bf73-11e5-9870-7a3527c4a824.gif)

This is causing an invalid query in OC because the params don't get separated from their `2010~|~2011` form.  @gsteimer have you noticed this issue recently, because we are seeing a similar with our client.  Seems like a high priority, too.

**Comment by gsteimer** [comment]
I haven't tried this recently.  Is this an issue on edge1?  Just wondering if this issue is Alfresco specific...

**Comment by grahamsinger** [comment]
I think it is alfresco specific... Something must not be working correctly with this line in OC:

    listNewParams = ((String)sp.getParamValue()).split("~\\|~");

**Comment by gsteimer** [comment]
@grahamsinger Wait - Policy Year is a single valued attribute.  Based on the notes from #486, I don't think this is a bug.  It's an enhancement that hasn't been added yet.  I think we can close this in favor of implementing #486 on Alfresco.

**Comment by grahamsinger** [comment]
@gsteimer Ahhh, ok that makes sense.  Need to see for sure if we can do this for our current client.

**Comment by gsteimer** [comment]
I just tried a repeating attribute on edge2 and it worked fine.  Closing this out, since it looks like #486 is what you want.
