### ISSUE TITLE
Alfresco - View Versions not displaying correctly for Effective document with later Drafts

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#966]
Note - this issue is Alfresco specific.  See here: https://github.com/tsgrp/hpi/wiki/TSG-Compliance-Solution background on how quality document versions are handled in Alfresco.

When we implemented #277, the idea was that the view versions action would show ALL document versions when viewing any version of a controlled document.  However, it looks like this is only happening correctly with the latest version.

In the example below, I've taken a 1.0 document (prior minor versions are correctly deleted), and checked in 1.1 and 1.2.

When viewing versions from the 1.2 document, everything looks correct:
![image](https://cloud.githubusercontent.com/assets/1377228/12486248/69eeff74-c027-11e5-816f-ed606cebbf29.png)

However, when viewing versions from the 1.0 document, it is not displaying the 1.1 version:
![image](https://cloud.githubusercontent.com/assets/1377228/12486278/85fb6680-c027-11e5-83ec-79bdea2d0805.png)

When fixing this, we should also test that all versions appear when loading any version in the stage for a document with a tree like this:

1.0 -> 2.0 -> 3.0 -> 3.1, -> 3.2 -> 3.3

@dgrumieaux - not sure if this is a potential issue for your current project.

**Comment by dgrumieaux** [comment]
Yep it will be. Good catch

**Comment by dgrumieaux** [comment]
@ZachGerth and I identified fix. He is implementing now.

**Comment by gsteimer** [comment]
@ZachGerth @nwoodbine - did this go into trunk yet?

**Comment by ZachGerth** [comment]
Fixed with Revision #13805 .
