### ISSUE TITLE
Export Search Results - Fails due to Admin Label update

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#968]
Export search results fail after the updates made for #590.  See below:

![image](https://cloud.githubusercontent.com/assets/1377228/12491600/a20e4936-c041-11e5-8a30-5663f08f7979.png)

From discussion on Slack, it sounds like @aviking knows what the fix should be

**Comment by gsteimer** [comment]
Note to self - this will have to be merged into the 2.4 tag and the tsg-prod branche

**Comment by ZachGerth** [comment]
Fixed with revision #14197. CR - aviking
