### ISSUE TITLE
Notification Bell Icon no longer appears

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#969]
Not sure when this happened, but even though notifications are enabled in the application config, the bell icon is no longer displaying:

Admin:
![image](https://cloud.githubusercontent.com/assets/1377228/12495450/5ea1f472-c055-11e5-97ec-9e0a3110e991.png)

Header (seeing this on edge1/2/3 and release1/2)
![image](https://cloud.githubusercontent.com/assets/1377228/12495459/6dea2d78-c055-11e5-8a44-0e27723610c9.png)

**Comment by gsteimer** [comment]
Note to self - double check to see if this needs to be included in the 2.4 tag and tsg-prod branch

**Comment by peterkk** [comment]
Fixed With revision #14221
