### ISSUE TITLE
Search Grid and List Views do not show link attribute properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#970]
See the screenshots below from edge2.  I think this is not working due to the admin label updates made as part of #590 

Admin - define "Object title to display" as Document Number
![image](https://cloud.githubusercontent.com/assets/1377228/12494521/44c94c12-c050-11e5-8e85-20f0270591f1.png)

Also - not sure why, but the layout in this admin screen is off.

Grid View - Document number is not correctly displayed
![image](https://cloud.githubusercontent.com/assets/1377228/12494538/62af9b3c-c050-11e5-9110-1ad5adcfd5d2.png)

I don't have list view configured, but I'd imagine the same problem occurs there as well.

**Comment by grahamsinger** [comment]
@peterkk Can this be closed with HPI rev. 14304?

**Comment by peterkk** [comment]
Closed with hpi revision #14304

**Comment by gsteimer** [comment]
@peterkk - reopening this one.  it looks fine on search results, but does not work in collections view:

![image](https://cloud.githubusercontent.com/assets/1377228/13061742/8080b7f0-d3ff-11e5-8832-113a681efd37.png)

**Comment by aviking** [comment]
Fixed with Commit: 14822
CR: Dan G.
