### ISSUE TITLE
Advanced Combine to PDF - Save to Repo Form should process folder attribute inheritance

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#971]
If you're using the save to repo option for Advanced combine to PDF, the form used to set attributes for the new document does not process folder inherited attributes.  For the insurance trac on edge2, you end up with a form that can't be populated since `Policy Number` is a disabled field (since it should be inherited and not changed):

![image](https://cloud.githubusercontent.com/assets/1377228/12513077/74eef22a-c0e1-11e5-8499-da187be47e0b.png)

In the above case, it's impossible to create the document since Policy Number is a required field.

@b-k-white

**Comment by RudraVishweshwar** [comment]
Fixed with revisioon #14470.

CR-BW
