### ISSUE TITLE
Search - Repeating text field, should not force user to click 'add'

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#972]
See the screencam below:

![search-repeating-text](https://cloud.githubusercontent.com/assets/1377228/12516455/1e234bd2-c0f3-11e5-8acc-197efeccdbf3.gif)

I've seen users get confused by this multiple times.  What should happen is that the form should not only use the fields added, but also anything in the text field as well.

We should test to make sure this works with other repeating types too.

**Comment by joehof** [comment]
We need to keep in mind while implementing this that form support is used in Add Docs and View/Edit Properties. I would assume that we would NOT want this logic in those places, so we should make sure this is only implemented for search. Do you agree George?

**Comment by gsteimer** [comment]
@joehof - yeah, good point.  I think this would be a search only thing.  Unless we want to make it configurable on form config - maybe as an option on repeating text fields?

**Comment by peterkk** [comment]
Closed with commit #14226

**Comment by gsteimer** [comment]
This needs a bit more work.  Basically, if you just put in some text and then hit enter, it tries to run the search, but doesn't take into account the value you placed in the textbox.  In other words, executing the search by hitting enter should do the same thing as pushing the search button.

The same thing happens if you do this:

- Select some other criteria (ex: set Status to effective)
- type in the repeating text field
- hit enter (without bluring from the text field)
- The search runs, but ignores the value you placed in the field, returning incorrect (to the user) results.

In the above scenario, once you blur from the repeating field, the field is added to the list of repeating fields.  It'll look like OC is returning incorrect results.

**Comment by renesaladrigas** [comment]
Tested this issue across modern browsers: IEv11, Firefoxv43 and Chromev55 and this issue seems to be working for the last comment raised by @gsteimer.

See screencam below for a demonstration of it working on IE 11.
![searchrepeatingtextfieldsearchesonenter](https://cloud.githubusercontent.com/assets/14186921/18973733/a81a8eae-8664-11e6-923e-825b2f981ba5.gif)
