### ISSUE TITLE
Cannot Create wizard form on Alfresco 5.0.1 - forms not found

### ISSUE THREAD

**Issue by alieblich** [tsgrp/hpi#974]
Given the following query:

```solr
 (TYPE:aw\:page_set  AND NOT(@aw\:activeVersionLabel:"none")) AND NOT ASPECT:\{http\://www\.alfresco\.org/model/content/1\.0\}workingcopy
```

This returns the active Wizard forms in Alfresco 4.2.1 but returns no results in 5.0.1. Trying other strings like 1.0 and test also failed. Here's the schema from the awModel.xml:

```xml
<property name="aw:activeVersionLabel">
	<title>Active Version Label</title>
	<type>d:text</type>
	<mandatory>true</mandatory>
	<multiple>false</multiple>
	<index enabled="true">
	<atomic>true</atomic>
		<stored>false</stored> 
		<tokenised>false</tokenised>
	</index>
</property>
```

other attributes that are ```<stored>false</stored> ``` and ```<tokenised>false</tokenised>``` can be searched on, such as pageSetInstanceType. A possible workaround is to make the "none" string "" instead, which will return all page set definitions regardless of their activeness.

paging @mikeblum

**Comment by cmlewis** [comment]
Hi all - Solr4 gets finicky with content model updates (not sure if awModel.xml was changed, but I've seen this happen quite a bit). Two things to try:

1. Shutdown Alfresco
2. Force a full reindex by deleting the folder `ALFRESCO_HOME\alf_data\solr4\index`
3. Delete the cached content models (this is a new thing with Solr4) by deleting the folder `ALFRESCO_HOME\alf_data\solr4\model`

If that does not work, there may be additional issues with Solr indexing. Let me know if it continues, and I'll send you some steps to run some Solr commands (RETRY and FIX).

**Comment by cmlewis** [comment]
In Chrome, try the following Solr commands and retest your query (no restart required):

1. `https://localhost:8443/solr4/admin/cores?action=RETRY`
2. `https://localhost:8443/solr4/admin/cores?action=FIX`

In Chrome, select the Alfresco certificate (a modal should pop up) and ignore any security warnings.
