### ISSUE TITLE
Get Doc Permanent Link Action

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#977]
This new HPI action should give users a PERMANENT link to a document that always links to the PUBLISHED version in the chain. If there is no PUBLISHED version in the chain, should direct to the LATEST version. Will be harder in Alfresco due to virtual version chain. Should support both Quality and non-quality documents... if there is no CURRENT version, just return the LATEST version.

This link should bring back the PDF version of the document directly by default. Could consider linking to the Stage version as a configurable option, but that is a secondary requirement.

@gsteimer @benallenallen - thoughts?
@b-k-white - heard there was a related enhancement for your client?

**Comment by benallenallen** [comment]
@dgrumieaux - There is already a legacy action called "openContentUrl" that we would want to implement to do what you are asking about. One of our Life Sciences clients developed this on HPI 2.0, so we would want to make sure we can support that behaviour as well.

It acted like the following:

```
http://server/OpenContent/rest/OCURL?documentNumber=S6114_0010&status=Effective&site=xxx
```
All this did was execute a search for the conditions passed in and streamed back the PDF of the document that fit the criteria.

The HPI Interface allowed for users to select if they wanted a link to the:

* Current Version (always follows the "CURRENT" label, whatever that may be)
* Exact version (pick an exact version, ex 1.4, and don't ever go anywhere else)
* Status (pick a "status" like Effective or Approved and it will always resolve to that version)

It then listed the URL that they would copy/paste wherever they wanted to use the link

**Comment by ZachGerth** [comment]
Implemented with Revision # 13992. The generated permanent link will always give the user the latest document (for documents that have no effective version), or the latest version which is effective.

For example, if a document has a 0.1 version, the link will lead to this version.
If a document has a 0.1 and 0.2 version, the link will lead to the 0.2 version.
If a document has a 0.1, 0.2, and 1.0 Effective version, the link will lead to the 1.0 Effective version.
If a document has a 0.1, 0.2, 1.0 Effective, and 1.1 version, the link will lead to the 1.0 Effective version.

**Comment by dgrumieaux** [comment]
Additional cases:

If a document has a 1.0 Effective, a 1.1 version, and a 2.0 Approved the link will lead to the 1.0 Effective version.
If a document has a 1.0 Superseded, a 1.1 version, and a 2.0 Effective the link will lead to the 2.0 Effective version.

**Comment by ladams13** [comment]
@ZachGerth @dgrumieaux This can be closed, correct?  I'm creating a new enhancement to note the config updates that Rene worked on.

**Comment by ZachGerth** [comment]
@ladams13 Yes, I'll close it now.
