### ISSUE TITLE
Visibility Dependent Form Values Break Bulk Upload when Hidden

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/hpi#983]
When these values remain hidden through the completion of the Bulk Upload form, they are never actually loaded and therefore are passed to OC as null. This causes the upload to fail in OCUtil#openContentObjectToEnhancedCompleteObject for all types except dates (which are null-protected).

**Comment by nwoodbine** [comment]
Fixed for non-repeating String types in OC revision 13754

**Comment by ZachGerth** [comment]
Fixed with Revision # 13819.
