### ISSUE TITLE
AW Cancelled Email blank when Workflow Document attached.

### ISSUE THREAD

**Issue by aviking** [tsgrp/hpi#985]
Steps to replicate:

1. Create a form and attach a document
2. Route for approval
3. Cancel the workflow

The email that you receive has a subject and a blank body.

The error that is thrown looks like:
```
Expression signature.comments is undefined on line 31, column 82 in abort-notification.ftl.
The problematic instruction:

${signature.comments} [on line 31, column 80 in abort-notification.ftl]

Java backtrace for programmers:

freemarker.core.InvalidReferenceException: Expression signature.comments is undefined on line 31, column 82 in abort-notification.ftl.
	at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
```

**Comment by gsteimer** [comment]
Note - the fix will likely be similar to what was done for #838

**Comment by aviking** [comment]
Looks more like the issue is that the ${signature.comments} variable is blank because we never set the "comment"s anywhere unless a user rejects the workflow. I think the easiest and cleanest fix is to create a default constructor for the SignatureEvent object that just sets the "comments" variable to an empty string. @gsteimer thoughts?

**Comment by gsteimer** [comment]
@aviking - yeah, sounds good to me.

**Comment by aviking** [comment]
Fixed with OC Commit: 13913
Code Review: George S.
