### ISSUE TITLE
Type to Path Security - Types not Displaying for Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#998]
With the addition of the new "Type to Path" security feature - types are not displaying at all in search on edge1 and edge2, even though the feature is disabled in the admin.  From edge1:

Admin:
![image](https://cloud.githubusercontent.com/assets/1377228/12920037/80d316a0-cf0c-11e5-9023-5c2fddd47a9e.png)

Search (Controlled Docs trac should have 2 types):
![image](https://cloud.githubusercontent.com/assets/1377228/12920047/8ed76e54-cf0c-11e5-982b-2d3c28eff68f.png)

**Comment by b-k-white** [comment]
Fixed.
HPI - 14292
